# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(blank=True, upload_to='signatures/profiles/', verbose_name='صورة التوقيع')),
                ('signature_data', models.TextField(blank=True, verbose_name='بيانات التوقيع (Base64)')),
                ('stamp_image', models.ImageField(blank=True, upload_to='signatures/stamps/', verbose_name='صورة الختم')),
                ('initials_image', models.ImageField(blank=True, upload_to='signatures/initials/', verbose_name='صورة الأحرف الأولى')),
                ('initials_data', models.TextField(blank=True, verbose_name='بيانات الأحرف الأولى (Base64)')),
                ('default_font', models.CharField(default='Tajawal', max_length=100, verbose_name='الخط الافتراضي')),
                ('default_color', models.CharField(default='#000000', max_length=20, verbose_name='اللون الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف توقيع',
                'verbose_name_plural': 'ملفات التوقيعات',
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('document', models.FileField(upload_to='signatures/documents/', verbose_name='المستند')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('signed', 'تم التوقيع'), ('rejected', 'مرفوض'), ('expired', 'منتهي الصلاحية'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('document_hash', models.CharField(blank=True, max_length=64, verbose_name='تجزئة المستند')),
                ('message', models.TextField(blank=True, verbose_name='رسالة للموقعين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signature_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب توقيع',
                'verbose_name_plural': 'طلبات التوقيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'تم الإنشاء'), ('sent', 'تم الإرسال'), ('viewed', 'تم العرض'), ('signed', 'تم التوقيع'), ('rejected', 'تم الرفض'), ('reminder_sent', 'تم إرسال تذكير'), ('completed', 'اكتمل'), ('cancelled', 'تم الإلغاء'), ('downloaded', 'تم التحميل')], max_length=20, verbose_name='الإجراء')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='digital_signatures.signaturerequest', verbose_name='طلب التوقيع')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('document', models.FileField(upload_to='signatures/templates/', verbose_name='المستند')),
                ('fields_config', models.JSONField(default=list, verbose_name='تكوين الحقول')),
                ('default_message', models.TextField(blank=True, verbose_name='الرسالة الافتراضية')),
                ('default_expiry_days', models.IntegerField(default=7, verbose_name='أيام الانتهاء الافتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_templates', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب توقيع',
                'verbose_name_plural': 'قوالب التوقيع',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('role', models.CharField(choices=[('signer', 'موقّع'), ('approver', 'موافق'), ('viewer', 'مشاهد'), ('cc', 'نسخة')], default='signer', max_length=20, verbose_name='الدور')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_signed', models.BooleanField(default=False, verbose_name='تم التوقيع')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوقيع')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='تم الرفض')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='تم إرسال الإشعار')),
                ('reminder_count', models.IntegerField(default=0, verbose_name='عدد التذكيرات')),
                ('access_token', models.CharField(blank=True, max_length=100, verbose_name='رمز الوصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='digital_signatures.signaturerequest', verbose_name='طلب التوقيع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موقّع',
                'verbose_name_plural': 'الموقّعون',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'توقيع'), ('initials', 'أحرف أولى'), ('date', 'تاريخ'), ('text', 'نص'), ('checkbox', 'خانة اختيار'), ('stamp', 'ختم')], max_length=20, verbose_name='نوع الحقل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الحقل')),
                ('page', models.IntegerField(default=1, verbose_name='رقم الصفحة')),
                ('x', models.FloatField(default=0, verbose_name='الموقع X')),
                ('y', models.FloatField(default=0, verbose_name='الموقع Y')),
                ('width', models.FloatField(default=200, verbose_name='العرض')),
                ('height', models.FloatField(default=50, verbose_name='الارتفاع')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
                ('is_required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('is_filled', models.BooleanField(default=False, verbose_name='تم الملء')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الملء')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='digital_signatures.signaturerequest', verbose_name='طلب التوقيع')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='digital_signatures.signer', verbose_name='الموقّع')),
            ],
            options={
                'verbose_name': 'حقل توقيع',
                'verbose_name_plural': 'حقول التوقيع',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(verbose_name='بيانات التوقيع (Base64)')),
                ('signature_image', models.ImageField(blank=True, upload_to='signatures/signed/', verbose_name='صورة التوقيع')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('geolocation', models.JSONField(default=dict, verbose_name='الموقع الجغرافي')),
                ('signature_hash', models.CharField(max_length=64, verbose_name='تجزئة التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوقيع')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='digital_signatures.signaturefield', verbose_name='الحقل')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='digital_signatures.signer', verbose_name='الموقّع')),
            ],
            options={
                'verbose_name': 'توقيع',
                'verbose_name_plural': 'التوقيعات',
            },
        ),
    ]
