# Generated by Django 5.2.9 on 2026-01-04 16:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        ('inventory', '0025_add_ecommerce_fields'),
        ('production', '0008_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعدة')),
                ('product_category', models.CharField(blank=True, max_length=100, verbose_name='فئة المنتج')),
                ('method', models.CharField(choices=[('fixed', 'سعر ثابت'), ('cost_plus', 'التكلفة + الهامش'), ('market_based', 'حسب السوق'), ('ai_dynamic', 'ذكاء اصطناعي ديناميكي')], default='cost_plus', max_length=20, verbose_name='طريقة التسعير')),
                ('base_cost_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='معامل التكلفة الأساسية')),
                ('quantity_discount_threshold', models.IntegerField(default=100, verbose_name='حد الخصم الكمي')),
                ('quantity_discount_rate', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5, verbose_name='نسبة الخصم الكمي %')),
                ('min_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('15.0'), max_digits=5, verbose_name='هامش الربح الأدنى %')),
                ('target_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('25.0'), max_digits=5, verbose_name='هامش الربح المستهدف %')),
                ('max_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('50.0'), max_digits=5, verbose_name='هامش الربح الأقصى %')),
                ('size_multiplier_small', models.DecimalField(decimal_places=2, default=Decimal('0.8'), max_digits=5, verbose_name='معامل المقاس الصغير')),
                ('size_multiplier_medium', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='معامل المقاس المتوسط')),
                ('size_multiplier_large', models.DecimalField(decimal_places=2, default=Decimal('1.3'), max_digits=5, verbose_name='معامل المقاس الكبير')),
                ('size_multiplier_xlarge', models.DecimalField(decimal_places=2, default=Decimal('1.6'), max_digits=5, verbose_name='معامل المقاس الضخم')),
                ('complexity_simple', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='معامل التصميم البسيط')),
                ('complexity_medium', models.DecimalField(decimal_places=2, default=Decimal('1.2'), max_digits=5, verbose_name='معامل التصميم المتوسط')),
                ('complexity_complex', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5, verbose_name='معامل التصميم المعقد')),
                ('use_ai_pricing', models.BooleanField(default=False, verbose_name='استخدام الذكاء الاصطناعي')),
                ('ai_model_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار نموذج AI')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير',
                'verbose_name_plural': 'قواعد التسعير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoMaterialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=50, unique=True, verbose_name='رقم أمر الصرف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('released', 'تم الصرف'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='تم الإنشاء تلقائياً')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_materials', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع/المستودع')),
            ],
            options={
                'verbose_name': 'أمر صرف مواد آلي',
                'verbose_name_plural': 'أوامر صرف المواد الآلية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المطلوبة')),
                ('released_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية المصروفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='التكلفة الإجمالية')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المادة')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smart_pricing.automaterialrelease')),
            ],
            options={
                'verbose_name': 'مادة أمر صرف',
                'verbose_name_plural': 'مواد أوامر الصرف',
            },
        ),
        migrations.CreateModel(
            name='SmartQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العرض')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('size', models.CharField(choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير'), ('xlarge', 'ضخم')], max_length=20, verbose_name='المقاس')),
                ('complexity', models.CharField(choices=[('simple', 'بسيط'), ('medium', 'متوسط'), ('complex', 'معقد')], max_length=20, verbose_name='التعقيد')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الطول (سم)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='العمق (سم)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (كجم)')),
                ('raw_material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة المواد الخام')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة العمالة')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='التكاليف الإضافية')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='التكلفة الإجمالية')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('25.0'), max_digits=5, verbose_name='هامش الربح %')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='السعر الإجمالي')),
                ('quantity_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='خصم الكمية %')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='السعر النهائي')),
                ('ai_calculated', models.BooleanField(default=False, verbose_name='محسوب بالذكاء الاصطناعي')),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الثقة AI')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('calculating', 'جاري الحساب'), ('ready', 'جاهز'), ('sent', 'مرسل'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='العميل')),
                ('pricing_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_pricing.pricingrule', verbose_name='قاعدة التسعير')),
            ],
            options={
                'verbose_name': 'عرض سعر ذكي',
                'verbose_name_plural': 'عروض أسعار ذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة المتوقعة')),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الوقت المتوقع (ساعات)')),
                ('capacity_match', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مطابقة السعة %')),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الجودة')),
                ('recommendation_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الترشيح')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='مُرشح')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionworkcenter', verbose_name='خط الإنتاج')),
                ('smart_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='smart_pricing.smartquote')),
            ],
            options={
                'verbose_name': 'ترشيح خط إنتاج',
                'verbose_name_plural': 'ترشيحات خطوط الإنتاج',
                'ordering': ['-recommendation_score'],
            },
        ),
    ]
