# Generated by Django 5.2.5 on 2026-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_pricing', '0003_price_list_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistsettings',
            name='use_company_data',
            field=models.BooleanField(default=True, help_text='عند التفعيل، يتم استخدام بيانات الشركة من الإعدادات الرئيسية', verbose_name='استخدام بيانات الشركة'),
        ),
        migrations.AlterField(
            model_name='pricelistsettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='pricelistsettings',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='pricelistsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='price_list_settings/', verbose_name='الشعار'),
        ),
    ]
