# Generated by Django 5.2.5 on 2026-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_pricing', '0004_price_list_use_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='default_height',
            field=models.PositiveIntegerField(default=30, help_text='ارتفاع المنتج بالسنتيمتر - يظهر في رأس الجدول', verbose_name='الارتفاع الافتراضي (سم)'),
        ),
    ]
