# Generated by Django 5.2.5 on 2026-01-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_height_product_length_product_width'),
        ('smart_pricing', '0005_add_default_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='المنتج المرتبط في نظام المخزون (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_families', to='inventory.product', verbose_name='المنتج الأساسي في المخزون'),
        ),
    ]
