# Generated by Django 5.2.5 on 2026-01-11 19:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_product_unit_warranty'),
        ('smart_pricing', '0006_productfamily_base_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('version_name', models.CharField(blank=True, help_text='مثال: أسعار يناير 2026', max_length=100, verbose_name='اسم الإصدار')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='تاريخ بدء تطبيق هذا الإصدار', verbose_name='ساري من')),
                ('effective_until', models.DateTimeField(blank=True, help_text='يُملأ تلقائياً عند إنشاء إصدار جديد', null=True, verbose_name='ساري حتى')),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='عدد الأيام التي يمكن فيها استخدام السعر القديم بعد تاريخ البدء', verbose_name='فترة السماح (أيام)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في انتظار التفعيل'), ('active', 'نشط'), ('expired', 'منتهي'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('change_reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_price_versions', to=settings.AUTH_USER_MODEL, verbose_name='اعتُمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_versions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='smart_pricing.pricelist', verbose_name='قائمة الأسعار')),
            ],
            options={
                'verbose_name': 'إصدار قائمة أسعار',
                'verbose_name_plural': 'إصدارات قوائم الأسعار',
                'ordering': ['-version_number'],
                'unique_together': {('price_list', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الجديد')),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار التغيير')),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='نسبة التغيير %')),
                ('change_type', models.CharField(choices=[('increase', 'زيادة'), ('decrease', 'تخفيض'), ('new', 'سعر جديد')], max_length=20, verbose_name='نوع التغيير')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productfamily', verbose_name='عائلة المنتج')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='smart_pricing.pricelist', verbose_name='قائمة الأسعار')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productsize', verbose_name='المقاس')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_pricing.pricelistversion', verbose_name='الإصدار')),
            ],
            options={
                'verbose_name': 'سجل تغيير سعر',
                'verbose_name_plural': 'سجل تغييرات الأسعار',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LockedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_type', models.CharField(choices=[('order', 'أمر بيع'), ('quotation', 'عرض سعر'), ('contract', 'عقد'), ('manual', 'تثبيت يدوي')], max_length=20, verbose_name='نوع التثبيت')),
                ('locked_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المثبت')),
                ('locked_price_with_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر شامل الضريبة')),
                ('locked_quantity', models.PositiveIntegerField(blank=True, help_text='اتركه فارغاً لتثبيت السعر لأي كمية', null=True, verbose_name='الكمية المثبتة')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المستند')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(blank=True, help_text='اتركه فارغاً للصلاحية الدائمة', null=True, verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_prices', to='partners.customer', verbose_name='العميل')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productfamily', verbose_name='عائلة المنتج')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.pricelist', verbose_name='قائمة الأسعار')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productsize', verbose_name='المقاس')),
                ('price_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_pricing.pricelistversion', verbose_name='إصدار القائمة')),
            ],
            options={
                'verbose_name': 'سعر مثبت',
                'verbose_name_plural': 'الأسعار المثبتة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='smart_prici_custome_b3dc94_idx'), models.Index(fields=['family', 'size', 'is_active'], name='smart_prici_family__07ddbf_idx'), models.Index(fields=['reference_type', 'reference_id'], name='smart_prici_referen_b5b4c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VersionedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأساسي')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر بعد الخصم')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر النهائي (شامل الضريبة)')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='التكلفة')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='هامش الربح %')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productfamily', verbose_name='عائلة المنتج')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_pricing.productsize', verbose_name='المقاس')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='smart_pricing.pricelistversion', verbose_name='الإصدار')),
            ],
            options={
                'verbose_name': 'سعر إصدار',
                'verbose_name_plural': 'أسعار الإصدارات',
                'unique_together': {('version', 'family', 'size')},
            },
        ),
    ]
