# Generated by Django 5.2.5 on 2026-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_pricing', '0007_pricelistversion_pricechangelog_lockedprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfamily',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='الكود'),
        ),
    ]
