# Generated by Django 5.2.5 on 2026-02-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_add_is_active_to_supplier'),
        ('smart_pricing', '0009_update_currency_default_to_egp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartquote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.customer', verbose_name='العميل'),
        ),
    ]
