# Generated by Django 5.2.9 on 2026-03-01 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=255, verbose_name='المنطقة')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='توصيل مجاني فوق')),
                ('estimated_days', models.IntegerField(default=1, verbose_name='أيام التوصيل المتوقعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'منطقة توصيل',
                'verbose_name_plural': 'مناطق التوصيل',
                'ordering': ['governorate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التوصيل')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('assigned', 'تم التعيين'), ('in_transit', 'جاري التوصيل'), ('delivered', 'تم التسليم'), ('returned', 'مرتجع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوصيل')),
                ('delivery_address', models.TextField(verbose_name='عنوان التوصيل')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='sales.salesinvoice', verbose_name='الفاتورة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryzone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'أمر توصيل',
                'verbose_name_plural': 'أوامر التوصيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
