# Generated by Django 5.2.5 on 2025-08-13 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('type', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'حوالة بنكية'), ('check', 'شيك'), ('credit_card', 'كارت ائتماني'), ('installment', 'قسط')], max_length=20, verbose_name='نوع الدفع')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True, verbose_name='رقم القرض')),
                ('loan_type', models.CharField(choices=[('personal', 'شخصي'), ('business', 'تجاري'), ('vehicle', 'سيارة'), ('property', 'عقار')], max_length=20, verbose_name='نوع القرض')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ القرض الأساسي')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='معدل الفائدة %')),
                ('duration_months', models.IntegerField(verbose_name='مدة القرض بالشهور')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القسط الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية القرض')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية القرض')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='حالة القرض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='المقترض')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_loans', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='رقم القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ القسط')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('partially_paid', 'مدفوع جزئياً')], default='pending', max_length=20, verbose_name='حالة القسط')),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='رسوم التأخير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.loan', verbose_name='القرض')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['due_date'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(verbose_name='تاريخ التذكير')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة التذكير')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('delivery_attempts', models.IntegerField(default=0, verbose_name='محاولات التسليم')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.loaninstallment', verbose_name='القسط')),
            ],
            options={
                'verbose_name': 'تذكير دفع',
                'verbose_name_plural': 'تذكيرات الدفع',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='رقم المعاملة')),
                ('transaction_type', models.CharField(choices=[('payment', 'دفع'), ('refund', 'استرداد'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.loaninstallment', verbose_name='القسط')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم المعالجة بواسطة')),
            ],
            options={
                'verbose_name': 'معاملة دفع',
                'verbose_name_plural': 'معاملات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
