# Generated by Django 5.2.5 on 2025-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'حوالة بنكية'), ('check', 'شيك'), ('credit_card', 'كارت ائتماني'), ('instapay', 'إنستا باي'), ('wallet', 'محفظة إلكترونية'), ('installment', 'قسط')], max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
