# Generated by Django 5.2.5 on 2025-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentmethod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'حوالة بنكية'), ('check', 'شيك'), ('credit_card', 'كارت ائتماني'), ('instapay', 'إنستا باي'), ('wallet', 'محفظة إلكترونية عامة'), ('vodafone_cash', 'فودافون كاش'), ('orange_cash', 'أورنج كاش'), ('etisalat_cash', 'اتصالات كاش'), ('stc_pay', 'STC Pay'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('paypal', 'PayPal'), ('mada', 'مدى'), ('installment', 'قسط')], max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
