# Generated by Django 5.2.5 on 2025-08-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cashflowaccountmapping'),
        ('payments', '0003_alter_paymentmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم لإنشاء قيد استلام آلي (مدين نقدية/بنك) مقابل عميل عند تسجيل دفعة.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account', verbose_name='الحساب المحاسبي المرتبط'),
        ),
    ]
