# Generated by Django 5.2.5 on 2025-09-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='رقم أصغر = يظهر أولاً', verbose_name='ترتيب العرض'),
        ),
    ]
