# Generated by Django 5.2.11 on 2026-03-01 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=300, verbose_name='الاسم')),
                ('supplier_type', models.CharField(choices=[('local', 'محلي'), ('international', 'دولي')], default='local', max_length=20, verbose_name='نوع المورد')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='هاتف 2')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='خاضع للضريبة')),
                ('payment_terms', models.PositiveIntegerField(default=0, verbose_name='شروط الدفع (أيام)')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='جهة الاتصال')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب البنكي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='accounts.account', verbose_name='الحساب المحاسبي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['code'],
            },
        ),
    ]
