# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0011_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('open', 'مفتوح'), ('pending', 'قيد الانتظار'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='اسم جهة الاتصال')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('assigned_team', models.CharField(blank=True, max_length=100, verbose_name='الفريق المعين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='معين إلى')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='helpdesk/attachments/', verbose_name='الملف')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('sla_hours', models.IntegerField(default=24, verbose_name='وقت SLA بالساعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='helpdesk.ticketcategory')),
            ],
            options={
                'verbose_name': 'فئة التذاكر',
                'verbose_name_plural': 'فئات التذاكر',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.ticketcategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_kb_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.ticketcategory')),
            ],
            options={
                'verbose_name': 'مقال قاعدة المعرفة',
                'verbose_name_plural': 'مقالات قاعدة المعرفة',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_internal', models.BooleanField(default=False, help_text='التعليقات الداخلية لا تظهر للعميل', verbose_name='داخلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
    ]
