# Generated by Django 5.2.5 on 2025-08-11 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'مدير عام'), ('accounting_manager', 'مدير محاسبة'), ('inventory_manager', 'مدير مخزون'), ('sales_manager', 'مدير مبيعات'), ('production_manager', 'مدير إنتاج'), ('hr_manager', 'مدير موارد بشرية'), ('accounting_staff', 'موظف محاسبة'), ('inventory_staff', 'موظف مخزون'), ('sales_staff', 'موظف مبيعات'), ('production_staff', 'موظف إنتاج'), ('hr_staff', 'موظف موارد بشرية'), ('viewer', 'مستخدم عرض فقط')], max_length=50, unique=True, verbose_name='نوع الدور')),
                ('display_name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('can_approve', models.BooleanField(default=False, verbose_name='يمكنه الموافقة')),
                ('approval_level', models.IntegerField(default=1, verbose_name='مستوى الموافقة')),
                ('max_approval_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='أقصى مبلغ للموافقة')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'db_table': 'users_role',
                'ordering': ['approval_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('failed_login', 'فشل تسجيل دخول'), ('multiple_sessions', 'جلسات متعددة'), ('suspicious_ip', 'IP مشكوك فيه'), ('permission_violation', 'انتهاك صلاحيات'), ('password_expired', 'انتهاء صلاحية كلمة المرور')], max_length=50, verbose_name='نوع التنبيه')),
                ('description', models.TextField(verbose_name='وصف التنبيه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم حله')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='حُل بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تنبيه أمني',
                'verbose_name_plural': 'التنبيهات الأمنية',
                'db_table': 'users_securityalert',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='العملية')),
                ('module', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='وصف العملية')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('success', models.BooleanField(default=True, verbose_name='نجحت العملية')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط مستخدم',
                'verbose_name_plural': 'أنشطة المستخدمين',
                'db_table': 'users_useractivity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='المنصب')),
                ('allowed_ips', models.TextField(blank=True, help_text='عناوين IP مسموحة (واحد في كل سطر)', verbose_name='عناوين IP المسموحة')),
                ('max_concurrent_sessions', models.IntegerField(default=2, verbose_name='أقصى عدد جلسات متزامنة')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='يجب تغيير كلمة المرور')),
                ('password_last_changed', models.DateTimeField(auto_now_add=True, verbose_name='آخر تغيير كلمة مرور')),
                ('account_expires', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='موافق من قبل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole', verbose_name='الدور الرئيسي')),
                ('secondary_roles', models.ManyToManyField(blank=True, related_name='secondary_users', to='users.userrole', verbose_name='أدوار إضافية')),
            ],
            options={
                'verbose_name': 'ملف تعريف مستخدم',
                'verbose_name_plural': 'ملفات تعريف المستخدمين',
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='معلومات المتصفح')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت تسجيل الدخول')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مستخدم',
                'verbose_name_plural': 'جلسات المستخدمين',
                'db_table': 'users_usersession',
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('core', 'الإعدادات الأساسية')], max_length=50, verbose_name='الوحدة')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('approve', 'موافقة'), ('print', 'طباعة'), ('export', 'تصدير')], max_length=20, verbose_name='العملية')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مسموح')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية وحدة',
                'verbose_name_plural': 'صلاحيات الوحدات',
                'db_table': 'users_modulepermission',
                'unique_together': {('role', 'module', 'action')},
            },
        ),
    ]
