# Generated by Django 5.2.5 on 2025-08-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250811_0312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modulepermission',
            table=None,
        ),
        migrations.AlterModelTable(
            name='securityalert',
            table=None,
        ),
        migrations.AlterModelTable(
            name='useractivity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userrole',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usersession',
            table=None,
        ),
    ]
