# Generated by Django 5.2.5 on 2025-08-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_modulepermission_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('core', 'الإعدادات الأساسية')], max_length=50, verbose_name='الوحدة'),
        ),
    ]
