# Generated by Django 5.2.5 on 2025-08-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_modulepermission_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('fleet', 'الأسطول'), ('core', 'الإعدادات الأساسية')], max_length=50, verbose_name='الوحدة')),
                ('resource', models.CharField(max_length=100, verbose_name='المورد / الشاشة')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('approve', 'موافقة'), ('print', 'طباعة'), ('export', 'تصدير')], max_length=20, verbose_name='العملية')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مسموح')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية مورد',
                'verbose_name_plural': 'صلاحيات الموارد',
                'unique_together': {('role', 'module', 'resource', 'action')},
            },
        ),
    ]
