# Generated by Django 5.2.5 on 2025-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resourcepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('fleet', 'الأسطول'), ('core', 'الإعدادات الأساسية'), ('pos', 'نقطة البيع')], max_length=50, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='resourcepermission',
            name='module',
            field=models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('fleet', 'الأسطول'), ('core', 'الإعدادات الأساسية'), ('pos', 'نقطة البيع')], max_length=50, verbose_name='الوحدة'),
        ),
    ]
