# Generated by Django 5.2.5 on 2025-12-15 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_seed_expanded_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('super_admin', 'صاحب الشركة / رئيس مجلس الإدارة'), ('general_manager', 'المدير العام'), ('system_admin', 'مشرف نظام'), ('branches_manager', 'مدير إدارة الفروع'), ('branch_supervisor', 'مشرف فروع'), ('branch_manager', 'مدير فرع'), ('branch_vice_manager', 'نائب مدير فرع'), ('accounting_manager', 'المدير المالي'), ('senior_accountant', 'كبير محاسبين'), ('accounting_staff', 'محاسب عام'), ('cost_accountant', 'محاسب تكاليف'), ('treasury_officer', 'محاسب خزنة'), ('branch_accountant', 'محاسب فروع'), ('internal_auditor', 'مراجع داخلي'), ('hr_manager', 'مدير الموارد البشرية'), ('hr_recruiter', 'مسؤول توظيف'), ('hr_payroll', 'مسؤول رواتب'), ('hr_attendance', 'مسؤول حضور وانصراف'), ('hr_training', 'مسؤول تدريب وتطوير'), ('hr_gov_relations', 'علاقات حكومية'), ('hr_staff', 'موظف موارد بشرية'), ('procurement_manager', 'مدير مشتريات'), ('procurement_lead', 'مشتري رئيسي'), ('procurement_officer', 'مشتري فرعي'), ('po_officer', 'مسؤول أوامر شراء'), ('supplier_followup', 'متابعة الموردين'), ('warehouse_manager', 'مدير المخازن'), ('store_supervisor', 'مشرف مخازن'), ('inventory_staff', 'أمين مخزن رئيسي'), ('branch_store_keeper', 'أمين مخزن فرع'), ('inventory_controller', 'مسؤول جرد'), ('warehouse_worker', 'عامل مخزن / شيال'), ('it_manager', 'مدير تقنية المعلومات'), ('it_developer', 'مبرمج'), ('it_network', 'مسؤول شبكات'), ('it_support', 'فني صيانة أجهزة'), ('sales_marketing_manager', 'مدير التسويق والمبيعات'), ('marketing_manager', 'مدير التسويق'), ('campaign_team', 'فريق الحملات الإعلانية'), ('graphic_designer', 'مصمم جرافيك'), ('content_creator', 'صانع محتوى'), ('social_media_specialist', 'مسؤول سوشيال ميديا'), ('sales_manager', 'مدير المبيعات'), ('sales_supervisor', 'مشرف مبيعات'), ('sales_rep_internal', 'مندوب مبيعات داخلي'), ('sales_rep_external', 'مندوب مبيعات خارجي'), ('cashier', 'كاشير / نقطة بيع'), ('pricing_officer', 'مسؤول تسعير'), ('quality_manager', 'مدير الجودة'), ('quality_inspector', 'مفتش جودة'), ('customer_care_lead', 'مسؤول شكاوى ورضا العملاء'), ('customer_service_lead', 'مسؤول خدمة العملاء'), ('cs_agent', 'موظف خدمة عملاء'), ('cs_order_followup', 'متابعة الأوردرات'), ('cs_complaints', 'حل الشكاوى'), ('operations_manager', 'مدير التشغيل/الإنتاج'), ('factory_manager', 'مدير المصنع'), ('factory_vice_manager', 'نائب مدير المصنع'), ('production_manager', 'مدير الإنتاج'), ('production_supervisor', 'مشرف إنتاج'), ('foam_line_supervisor', 'مشرف خط الإسفنج'), ('spring_line_supervisor', 'مشرف خط السوست'), ('upholstery_supervisor', 'مشرف خط التنجيد'), ('shift_lead', 'قائد وردية'), ('production_technician', 'فني إنتاج'), ('production_staff', 'عامل إنتاج'), ('packaging_worker', 'عامل تغليف'), ('dispatch_controller', 'مسؤول تسليمات المصنع'), ('maintenance_manager', 'مدير الصيانة'), ('mech_tech', 'فني ميكانيكا'), ('elec_tech', 'فني كهرباء'), ('line_maint_tech', 'فني صيانة خطوط'), ('spareparts_controller', 'مسؤول قطع غيار'), ('qa_lab_chemist', 'كيميائي المصنع'), ('qa_raw_tester', 'اختبار المواد الخام'), ('qa_final_tester', 'فحص المنتج النهائي'), ('qa_spec_matcher', 'مطابقة المواصفات'), ('hse_officer', 'مسؤول سلامة'), ('hse_supervisor', 'مشرف وقاية'), ('hse_emergency', 'مسؤول طوارئ'), ('raw_store_keeper', 'أمين مخزن مواد خام'), ('semi_store_keeper', 'أمين مخزن مواد نصف مصنعة'), ('fg_store_keeper', 'أمين مخزن منتج نهائي'), ('labor_controller', 'مراقب عمال'), ('porter', 'شيال'), ('tea_boy', 'عامل بوفيه'), ('cleaner', 'عامل نظافة'), ('security_guard', 'أمن المصنع'), ('viewer', 'مستخدم عرض فقط')], max_length=50, unique=True, verbose_name='نوع الدور'),
        ),
    ]
