# Generated by Django 5.2.5 on 2025-12-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_securityalert_user_alter_userrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('fleet', 'الأسطول'), ('core', 'الإعدادات الأساسية'), ('pos', 'نقطة البيع'), ('ecommerce', 'المتجر الإلكتروني'), ('eservices', 'الخدمات الإلكترونية'), ('shipping', 'إدارة الشحن'), ('woocommerce_integration', 'تكامل WooCommerce')], max_length=50, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='resourcepermission',
            name='module',
            field=models.CharField(choices=[('accounting', 'المحاسبة'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('production', 'الإنتاج'), ('maintenance', 'الصيانة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة علاقات العملاء'), ('reports', 'التقارير'), ('partners', 'الشركاء'), ('fleet', 'الأسطول'), ('core', 'الإعدادات الأساسية'), ('pos', 'نقطة البيع'), ('ecommerce', 'المتجر الإلكتروني'), ('eservices', 'الخدمات الإلكترونية'), ('shipping', 'إدارة الشحن'), ('woocommerce_integration', 'تكامل WooCommerce')], max_length=50, verbose_name='الوحدة'),
        ),
    ]
