# Generated by Django 5.2.9 on 2026-03-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='رقم عرض السعر')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('valid_until', models.DateField(verbose_name='صالح حتى')),
                ('revision_number', models.IntegerField(default=0, verbose_name='رقم التعديل')),
                ('prospect_name', models.CharField(blank=True, max_length=255, verbose_name='اسم العميل المحتمل')),
                ('prospect_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل المحتمل')),
                ('prospect_email', models.EmailField(blank=True, max_length=254, verbose_name='إيميل العميل المحتمل')),
                ('prospect_address', models.TextField(blank=True, verbose_name='عنوان العميل المحتمل')),
                ('prospect_company', models.CharField(blank=True, max_length=255, verbose_name='شركة العميل المحتمل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسل'), ('negotiation', 'قيد التفاوض'), ('revised', 'معدّل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('converted', 'تحوّل لفاتورة'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الخصم')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ الخاضع')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي النهائي')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='خاضع للضريبة')),
                ('delivery_required', models.BooleanField(default=False, verbose_name='يحتاج توصيل')),
                ('delivery_address', models.TextField(blank=True, verbose_name='عنوان التوصيل')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('estimated_delivery_days', models.IntegerField(default=0, verbose_name='أيام التوصيل المتوقعة')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات للعميل')),
                ('payment_terms', models.CharField(blank=True, max_length=255, verbose_name='شروط الدفع')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('lost_to_competitor', models.CharField(blank=True, max_length=255, verbose_name='خسرنا لصالح')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('converted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='الفاتورة المحوّلة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.pricelist', verbose_name='قائمة الأسعار')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuotationFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('follow_up_type', models.CharField(choices=[('call', 'مكالمة'), ('whatsapp', 'واتساب'), ('email', 'إيميل'), ('visit', 'زيارة'), ('meeting', 'اجتماع')], max_length=20, verbose_name='نوع المتابعة')),
                ('result', models.CharField(choices=[('interested', 'مهتم'), ('thinking', 'يفكر'), ('needs_revision', 'يحتاج تعديل'), ('negotiating', 'يفاوض'), ('will_buy', 'سيشتري'), ('lost', 'خسرناه'), ('no_answer', 'لا يرد')], max_length=20, verbose_name='النتيجة')),
                ('notes', models.TextField(verbose_name='الملاحظات')),
                ('next_follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة القادمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='quotations.quotation', verbose_name='العرض')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('custom_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='العرض (سم)')),
                ('custom_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الطول (سم)')),
                ('custom_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الارتفاع (سم)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة التقديرية')),
                ('estimated_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الربح التقديري')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'سطر عرض سعر',
                'verbose_name_plural': 'سطور عرض السعر',
                'ordering': ['sort_order'],
            },
        ),
    ]
