# Generated by Django 5.2.11 on 2026-03-01 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_lines', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'خط إنتاج',
                'verbose_name_plural': 'خطوط الإنتاج',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الكمية المطلوبة')),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الكمية المنتجة')),
                ('quantity_wasted', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='كمية الهالك')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('quality_check', 'مراقبة الجودة'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المتوقع')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاكتمال الفعلي')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة المواد')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة العمالة')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكاليف الإضافية')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التكلفة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.billofmaterials', verbose_name='قائمة المواد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.product', verbose_name='المنتج')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionline', verbose_name='خط الإنتاج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('warehouse_finished', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_finished', to='core.warehouse', verbose_name='مخزن المنتجات التامة')),
                ('warehouse_raw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_raw', to='core.warehouse', verbose_name='مخزن الخامات')),
            ],
            options={
                'verbose_name': 'أمر إنتاج',
                'verbose_name_plural': 'أوامر الإنتاج',
                'ordering': ['-date', '-order_number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الكمية المخططة')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الكمية الفعلية')),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='كمية الهالك')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='inventory.product', verbose_name='المادة الخام')),
                ('stock_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_consumptions', to='inventory.stockmove', verbose_name='حركة المخزون')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'استهلاك مواد',
                'verbose_name_plural': 'استهلاكات المواد',
            },
        ),
        migrations.CreateModel(
            name='ProductionStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_templates', to='inventory.category', verbose_name='تصنيف المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'قالب مراحل إنتاج',
                'verbose_name_plural': 'قوالب مراحل الإنتاج',
            },
        ),
        migrations.CreateModel(
            name='StageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الساعات المقدرة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionstagetemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'خطوة إنتاج',
                'verbose_name_plural': 'خطوات الإنتاج',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('skipped', 'متجاوزة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاكتمال')),
                ('worker_count', models.PositiveIntegerField(default=0, verbose_name='عدد العمال')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الساعات الفعلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_stages', to='production.stagestep', verbose_name='خطوة الإنتاج')),
            ],
            options={
                'verbose_name': 'مرحلة إنتاج',
                'verbose_name_plural': 'مراحل الإنتاج',
            },
        ),
    ]
