# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractingexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='contractingreceipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='contractingworker',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التعيين'),
        ),
    ]
