# Generated by Django 5.2.9 on 2026-01-23 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping_companies/', verbose_name='الشعار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('tracking_url_template', models.CharField(blank=True, help_text='استخدم {tracking_number} كمتغير، مثل: https://example.com/track/{tracking_number}', max_length=500, verbose_name='رابط التتبع')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شركة شحن',
                'verbose_name_plural': 'شركات الشحن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم التتبع')),
                ('reference_number', models.CharField(blank=True, help_text='رقم الطلب أو الفاتورة', max_length=100, verbose_name='الرقم المرجعي')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='هاتف المرسل')),
                ('sender_address', models.TextField(verbose_name='عنوان المرسل')),
                ('sender_city', models.CharField(max_length=100, verbose_name='مدينة المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('receiver_alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف بديل')),
                ('receiver_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المستلم')),
                ('receiver_address', models.TextField(verbose_name='عنوان المستلم')),
                ('receiver_city', models.CharField(max_length=100, verbose_name='مدينة المستلم')),
                ('receiver_district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('receiver_postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('description', models.TextField(blank=True, verbose_name='وصف المحتوى')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (كجم)')),
                ('pieces_count', models.PositiveIntegerField(default=1, verbose_name='عدد القطع')),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='القيمة المعلنة')),
                ('payment_method', models.CharField(choices=[('prepaid', 'مدفوع مسبقاً'), ('cod', 'الدفع عند الاستلام')], default='cod', max_length=20, verbose_name='طريقة الدفع')),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الدفع عند الاستلام')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('status', models.CharField(choices=[('pending', '⏳ قيد الانتظار'), ('picked_up', '📦 تم الاستلام'), ('in_transit', '🚚 قيد النقل'), ('out_for_delivery', '🏃 خارج للتوصيل'), ('delivered', '✅ تم التسليم'), ('failed', '❌ فشل التوصيل'), ('returned', '↩️ مرتجع'), ('cancelled', '🚫 ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='الموقع الحالي')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم الفعلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
                ('special_instructions', models.TextField(blank=True, verbose_name='تعليمات خاصة')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('customer_notified', models.BooleanField(default=False, verbose_name='تم إشعار العميل')),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True, verbose_name='آخر إشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipment_tracking.shippingcompany', verbose_name='شركة الشحن')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('label', 'بوليصة الشحن'), ('invoice', 'الفاتورة'), ('pod', 'إثبات التسليم'), ('photo', 'صورة'), ('signature', 'التوقيع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('file', models.FileField(upload_to='shipment_documents/%Y/%m/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipment_tracking.shipment', verbose_name='الشحنة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند شحنة',
                'verbose_name_plural': 'مستندات الشحنات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'رسالة نصية'), ('email', 'بريد إلكتروني'), ('push', 'إشعار تطبيق'), ('whatsapp', 'واتساب')], max_length=20, verbose_name='نوع الإشعار')),
                ('recipient', models.CharField(max_length=200, verbose_name='المستلم')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الإرسال')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipment_tracking.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'إشعار شحنة',
                'verbose_name_plural': 'إشعارات الشحنات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ قيد الانتظار'), ('picked_up', '📦 تم الاستلام'), ('in_transit', '🚚 قيد النقل'), ('out_for_delivery', '🏃 خارج للتوصيل'), ('delivered', '✅ تم التسليم'), ('failed', '❌ فشل التوصيل'), ('returned', '↩️ مرتجع'), ('cancelled', '🚫 ملغي')], max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ والوقت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipment_tracking.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'سجل الحالة',
                'verbose_name_plural': 'سجل الحالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipment_tr_trackin_4ff88f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipment_tr_status_4da8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['receiver_phone'], name='shipment_tr_receive_4c1650_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-created_at'], name='shipment_tr_created_a078b3_idx'),
        ),
    ]
