# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=100, unique=True, verbose_name='رقم التصريح')),
                ('permit_type', models.CharField(max_length=100, verbose_name='نوع التصريح')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('government_entity', models.CharField(max_length=200, verbose_name='الجهة الحكومية')),
                ('application_date', models.DateField(verbose_name='تاريخ التقديم')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('validity_period_days', models.IntegerField(blank=True, null=True, verbose_name='فترة الصلاحية (أيام)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التقديم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تصريح حكومي',
                'verbose_name_plural': 'التصاريح الحكومية',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الترخيص')),
                ('license_type', models.CharField(choices=[('business', 'تجاري'), ('health', 'صحي'), ('industrial', 'صناعي'), ('food', 'غذائي'), ('environmental', 'بيئي'), ('safety', 'سلامة'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الترخيص')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='الجهة المصدرة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'موقوف'), ('pending_renewal', 'معلق التجديد'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('renewal_required', models.BooleanField(default=True, verbose_name='يتطلب تجديد')),
                ('renewal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التجديد')),
                ('document_url', models.URLField(blank=True, verbose_name='رابط المستند')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reminder_days_before_expiry', models.IntegerField(default=30, verbose_name='تذكير قبل (أيام)')),
                ('last_reminder_sent', models.DateField(blank=True, null=True, verbose_name='آخر تذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ترخيص',
                'verbose_name_plural': 'التراخيص',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(verbose_name='تاريخ التجديد')),
                ('new_expiry_date', models.DateField(verbose_name='تاريخ الانتهاء الجديد')),
                ('renewal_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رسوم التجديد')),
                ('payment_status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة السداد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='license_management.license')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تجديد ترخيص',
                'verbose_name_plural': 'تجديدات التراخيص',
                'ordering': ['-renewal_date'],
            },
        ),
    ]
