# Generated by Django 5.2.11 on 2026-03-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('cogs', 'تكلفة المبيعات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('nature', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='طبيعة الحساب')),
                ('is_detail', models.BooleanField(default=True, verbose_name='حساب تفصيلي')),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب النظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('center_type', models.CharField(choices=[('branch', 'فرع'), ('product_line', 'خط إنتاج'), ('warehouse', 'مخزن'), ('department', 'قسم')], max_length=20, verbose_name='نوع المركز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='البيان')),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('purchase', 'مشتريات'), ('sale', 'مبيعات'), ('production', 'إنتاج'), ('stock_move', 'حركة مخزون'), ('payroll', 'رواتب'), ('expense', 'مصروفات'), ('adjustment', 'تسوية')], default='manual', max_length=20, verbose_name='المصدر')),
                ('source_document', models.CharField(blank=True, max_length=100, verbose_name='المستند المصدر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في الانتظار'), ('approved', 'معتمد'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الدائن')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='البيان')),
                ('partner_type', models.CharField(blank=True, choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('', 'لا يوجد')], max_length=20, verbose_name='نوع الطرف')),
                ('partner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الطرف')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'أسطر القيود',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('tax_type', models.CharField(choices=[('input', 'ضريبة مدخلات'), ('output', 'ضريبة مخرجات')], max_length=10, verbose_name='نوع الضريبة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount_before_tax', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ قبل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('is_taxable_purchase', models.BooleanField(default=False, verbose_name='مشتريات خاضعة للضريبة')),
                ('is_taxable_sale', models.BooleanField(default=False, verbose_name='مبيعات خاضعة للضريبة')),
            ],
            options={
                'verbose_name': 'معاملة ضريبية',
                'verbose_name_plural': 'المعاملات الضريبية',
                'ordering': ['-date'],
            },
        ),
    ]
