# Generated by Django 5.2.11 on 2026-03-02 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('expenses', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الميزانية')),
                ('period_type', models.CharField(choices=[('monthly', 'شهرية'), ('quarterly', 'ربع سنوية'), ('annual', 'سنوية')], default='monthly', max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.fiscalyear', verbose_name='السنة المالية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('cost_type', models.CharField(choices=[('material', 'خامات مباشرة'), ('labor', 'عمالة مباشرة'), ('overhead', 'تكاليف غير مباشرة'), ('depreciation', 'إهلاك'), ('utility', 'مرافق'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التكلفة')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'تحميل تكلفة',
                'verbose_name_plural': 'تحميلات التكاليف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WIPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الخامات')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة العمالة')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكاليف غير مباشرة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التكلفة')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلق')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wip_account', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'حساب WIP',
                'verbose_name_plural': 'حسابات WIP',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='يناير')),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='فبراير')),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مارس')),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='أبريل')),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مايو')),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='يونيو')),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='يوليو')),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='أغسطس')),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سبتمبر')),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='أكتوبر')),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='نوفمبر')),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ديسمبر')),
                ('annual_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي السنوي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.budget', verbose_name='الميزانية')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory', verbose_name='تصنيف المصروف')),
            ],
            options={
                'verbose_name': 'سطر ميزانية',
                'verbose_name_plural': 'سطور الميزانية',
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
