# Generated by Django 5.2.5 on 2025-12-15 03:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المقاول')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='التخصص')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقاول',
                'verbose_name_plural': 'المقاولين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع مشروع',
                'verbose_name_plural': 'أنواع المشاريع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المشروع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('planning', 'تخطيط'), ('in_progress', 'قيد التنفيذ'), ('on_hold', 'معلق'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='البداية الفعلية')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='النهاية الفعلية')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الميزانية')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='التكلفة الفعلية')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('client_contact', models.CharField(blank=True, max_length=200, verbose_name='جهة اتصال العميل')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('description', models.TextField(verbose_name='وصف العقد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('terminated', 'منتهي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.contractor', verbose_name='المقاول')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_contracts', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عقد مقاول',
                'verbose_name_plural': 'عقود المقاولين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='كود البند')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('unit', models.CharField(max_length=20, verbose_name='الوحدة')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'بند كميات',
                'verbose_name_plural': 'جدول الكميات',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('budget', 'تعديل ميزانية'), ('schedule', 'تعديل جدول'), ('scope', 'تعديل نطاق'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التعديل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'تعديل مشروع',
                'verbose_name_plural': 'تعديلات المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف مشروع',
                'verbose_name_plural': 'تصنيفات المشاريع',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory', verbose_name='التصنيف'),
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('material', 'مواد'), ('labour', 'عمالة'), ('equipment', 'معدات'), ('transport', 'نقل'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('paid_to', models.CharField(blank=True, max_length=200, verbose_name='مدفوع إلى')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مصروف مشروع',
                'verbose_name_plural': 'مصروفات المشاريع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'فاتورة مشروع',
                'verbose_name_plural': 'فواتير المشاريع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العامل')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الأجر اليومي')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمالة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttype', verbose_name='نوع المشروع'),
        ),
        migrations.CreateModel(
            name='LabourAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ساعات العمل')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='ساعات إضافية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='projects.projectlabour', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'حضور عامل',
                'verbose_name_plural': 'سجل الحضور',
                'ordering': ['-date'],
                'unique_together': {('labour', 'date')},
            },
        ),
    ]
