[mypy]
python_version = 3.13

ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = True
warn_redundant_casts = True
warn_no_return = True
warn_unreachable = True
show_error_codes = True
pretty = True
# plugins = mypy_django_plugin.main

exclude = (?x)^(_migration_package/|dist/|build/)
files = accountant_pro, core, inventory, purchases, sales, accounting, partners, reports

[mypy-*.migrations.*]
ignore_errors = True

# Relaxed for initial adoption; tighten later progressively
strict_optional = False

# [mypy.plugins.django-stubs]
# django_settings_module = accountant_pro.settings
