# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الوثيقة')),
                ('policy_type', models.CharField(choices=[('property', 'الممتلكات'), ('liability', 'المسؤولية'), ('workers_comp', 'تعويض العمال'), ('auto', 'السيارات'), ('health', 'الصحة'), ('professional', 'المسؤولية المهنية'), ('cyber', 'الأمان السيبراني')], max_length=20, verbose_name='نوع الوثيقة')),
                ('insurer_name', models.CharField(max_length=200, verbose_name='اسم شركة التأمين')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ التغطية')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قسط التأمين')),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الخصم')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'غير نشطة'), ('expired', 'منتهية الصلاحية'), ('pending', 'قيد الانتظار')], default='active', max_length=20, verbose_name='الحالة')),
                ('coverage_details', models.TextField(blank=True, verbose_name='تفاصيل التغطية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وثيقة تأمين',
                'verbose_name_plural': 'وثائق التأمين',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('color_code', models.CharField(default='#3498db', max_length=7, verbose_name='كود اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة المخاطر',
                'verbose_name_plural': 'فئات المخاطر',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المطالبة')),
                ('claim_date', models.DateField(verbose_name='تاريخ المطالبة')),
                ('incident_date', models.DateField(verbose_name='تاريخ الحادثة')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ المطالبة')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ المعتمد')),
                ('status', models.CharField(choices=[('submitted', 'مُقدَّمة'), ('under_review', 'قيد المراجعة'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('paid', 'مدفوعة')], default='submitted', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='وصف المطالبة')),
                ('attachment', models.FileField(blank=True, upload_to='insurance_claims/', verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='risk_management.insurancepolicy')),
            ],
            options={
                'verbose_name': 'مطالبة تأمين',
                'verbose_name_plural': 'مطالبات التأمين',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('probability', models.IntegerField(choices=[(1, 'منخفضة جداً'), (2, 'منخفضة'), (3, 'متوسطة'), (4, 'عالية'), (5, 'عالية جداً')], verbose_name='احتمالية الحدوث')),
                ('impact', models.IntegerField(choices=[(1, 'منخفضة جداً'), (2, 'منخفضة'), (3, 'متوسطة'), (4, 'عالية'), (5, 'عالية جداً')], verbose_name='مستوى التأثير')),
                ('risk_score', models.IntegerField(default=0, verbose_name='درجة المخاطر')),
                ('status', models.CharField(choices=[('identified', 'محددة'), ('assessed', 'مقيمة'), ('mitigating', 'قيد التخفيف'), ('monitored', 'مراقبة'), ('closed', 'مغلقة')], default='identified', max_length=20, verbose_name='الحالة')),
                ('identified_date', models.DateField(verbose_name='تاريخ التحديد')),
                ('mitigation_plan', models.TextField(blank=True, verbose_name='خطة التخفيف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risk_management.riskcategory')),
            ],
            options={
                'verbose_name': 'مخاطرة',
                'verbose_name_plural': 'المخاطر',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التحليل')),
                ('coverage_gaps', models.TextField(verbose_name='الفجوات في التغطية')),
                ('recommendations', models.TextField(verbose_name='التوصيات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policies', models.ManyToManyField(related_name='coverage_analyses', to='risk_management.insurancepolicy')),
                ('identified_risks', models.ManyToManyField(related_name='coverage_analyses', to='risk_management.risk')),
            ],
            options={
                'verbose_name': 'تحليل التغطية',
                'verbose_name_plural': 'تحليلات التغطية',
            },
        ),
    ]
