# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الشكوى')),
                ('channel', models.CharField(choices=[('phone', 'هاتف'), ('email', 'بريد'), ('website', 'موقع'), ('social_media', 'وسائل تواصل'), ('in_person', 'شخصياً'), ('mobile_app', 'تطبيق')], max_length=20, verbose_name='قناة الشكوى')),
                ('category', models.CharField(choices=[('product_quality', 'جودة منتج'), ('service_quality', 'جودة خدمة'), ('delivery', 'توصيل'), ('pricing', 'تسعير'), ('staff_behavior', 'سلوك موظفين'), ('other', 'أخرى')], max_length=50, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة'), ('escalated', 'مصعَّدة')], default='open', max_length=20, verbose_name='الحالة')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام')),
                ('response_deadline', models.DateTimeField(verbose_name='الموعد النهائي للرد')),
                ('resolution_deadline', models.DateTimeField(verbose_name='الموعد النهائي للحل')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='أول رد')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('customer_satisfaction_rating', models.IntegerField(blank=True, help_text='من 1 إلى 5', null=True, verbose_name='تقييم رضا العميل')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='تعليق العميل')),
                ('root_cause', models.TextField(blank=True, verbose_name='السبب الجذري')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي')),
                ('preventive_action', models.TextField(blank=True, verbose_name='الإجراء الوقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='crm.customer')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('initiative_type', models.CharField(choices=[('process_improvement', 'تحسين عملية'), ('quality_improvement', 'تحسين جودة'), ('cost_reduction', 'خفض تكلفة'), ('customer_satisfaction', 'رضا العميل'), ('efficiency', 'كفاءة')], max_length=30, verbose_name='نوع المبادرة')),
                ('status', models.CharField(choices=[('proposed', 'مقترحة'), ('approved', 'معتمدة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='proposed', max_length=20, verbose_name='الحالة')),
                ('current_state', models.TextField(verbose_name='الحالة الحالية')),
                ('target_state', models.TextField(verbose_name='الحالة المستهدفة')),
                ('expected_benefits', models.TextField(verbose_name='الفوائد المتوقعة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('target_completion_date', models.DateField(verbose_name='تاريخ الانتهاء المستهدف')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('results_achieved', models.TextField(blank=True, verbose_name='النتائج المحققة')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='الدروس المستفادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_initiatives', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='participating_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مبادرة تحسين',
                'verbose_name_plural': 'مبادرات التحسين',
                'ordering': ['-created_at'],
            },
        ),
    ]
