# Generated by Django 5.2.5 on 2025-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'بيانات الشركة',
            },
        ),
    ]
