# Generated by Django 5.2.5 on 2025-08-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EGP', 'الجنيه المصري'), ('USD', 'الدولار الأمريكي'), ('SAR', 'الج.م السعودي'), ('AED', 'الدرهم الإماراتي'), ('KWD', 'الدينار الكويتي'), ('EUR', 'اليورو')], max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العملة')),
                ('symbol', models.CharField(max_length=10, verbose_name='رمز العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='العملة الافتراضية')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة الافتراضية'),
        ),
    ]
