# Generated by Django 5.2.5 on 2025-08-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings_audit_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_created_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_model_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='auditlog_obj_lookup_idx',
        ),
    ]
