# Generated by Django 5.2.5 on 2025-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_auditlog_auditlog_created_action_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='safety_incident_alert_threshold',
            field=models.PositiveIntegerField(default=3, help_text='الحد الشهري للحوادث لإطلاق تنبيه سلامة'),
        ),
    ]
