# Generated by Django 5.2.5 on 2025-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appsettings_safety_incident_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='safety_alert_emails',
            field=models.JSONField(blank=True, default=list, help_text='عناوين بريد لإشعارات السلامة'),
        ),
    ]
