# Generated by Django 5.2.5 on 2025-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appsettings_safety_alert_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'عملة', 'verbose_name_plural': 'العملات'},
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='decimal_places',
            field=models.PositiveIntegerField(default=2, verbose_name='عدد الخانات العشرية'),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='سعر الصرف مقابل العملة الافتراضية', max_digits=15, verbose_name='سعر الصرف مقابل العملة الأساسية'),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('EGP', 'الجنيه المصري'), ('USD', 'الدولار الأمريكي'), ('EUR', 'اليورو'), ('SAR', 'الج.م السعودي'), ('AED', 'الدرهم الإماراتي'), ('KWD', 'الدينار الكويتي'), ('QAR', 'الج.م القطري'), ('OMR', 'الج.م العماني'), ('BHD', 'الدينار البحريني'), ('JOD', 'الدينار الأردني'), ('LBP', 'الليرة اللبنانية'), ('SYP', 'الليرة السورية'), ('IQD', 'الدينار العراقي'), ('YER', 'الج.م اليمني'), ('SDG', 'الجنيه السوداني'), ('MAD', 'الدرهم المغربي'), ('TND', 'الدينار التونسي'), ('DZD', 'الدينار الجزائري'), ('LYD', 'الدينار الليبي'), ('MRU', 'الأوقية الموريتانية')], max_length=3, unique=True, verbose_name='رمز العملة'),
        ),
    ]
