# Generated by Django 5.2.5 on 2025-08-16 08:22

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_currency_options_currency_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='سعر الصرف مقابل العملة الافتراضية', max_digits=18, verbose_name='سعر الصرف مقابل العملة الأساسية'),
        ),
    ]
