# Generated by Django 5.2.5 on 2025-12-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_auditlog_content_type_country_page_state_and_more'),
        ('users', '0011_alter_securityalert_user_alter_userrole_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['module', 'order', 'name'], 'verbose_name': 'صفحة', 'verbose_name_plural': 'الصفحات'},
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الصفحة'),
        ),
        migrations.AddField(
            model_name='page',
            name='module',
            field=models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('accounting', 'الحسابات'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('hr', 'الموارد البشرية'), ('crm', 'العملاء'), ('production', 'الإنتاج'), ('fleet', 'الأسطول'), ('pos', 'نقاط البيع'), ('reports', 'التقارير'), ('settings', 'الإعدادات'), ('projects', 'المشاريع'), ('contracting', 'المقاولات'), ('shipping', 'الشحن'), ('eservices', 'الخدمات الإلكترونية')], default='settings', max_length=50, verbose_name='الموديول'),
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=True, verbose_name='عرض')),
                ('can_create', models.BooleanField(default=False, verbose_name='إنشاء')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_export', models.BooleanField(default=False, verbose_name='تصدير')),
                ('can_print', models.BooleanField(default=False, verbose_name='طباعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.page', verbose_name='الصفحة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='users.userrole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية صفحة',
                'verbose_name_plural': 'صلاحيات الصفحات',
                'ordering': ['page__module', 'page__order'],
                'unique_together': {('page', 'role')},
            },
        ),
    ]
