# Generated by Django 5.2.5 on 2025-12-15 14:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_create_mosool_models'),
        ('core', '0019_alter_page_options_page_description_page_module_and_more'),
        ('hr', '0008_leaverequest_replacement_employee'),
        ('inventory', '0019_product_production_department_code'),
        ('partners', '0009_supplierdocument'),
        ('projects', '0001_initial'),
        ('users', '0011_alter_securityalert_user_alter_userrole_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم المستند')),
                ('document_type', models.CharField(choices=[('pr', 'طلب شراء'), ('po', 'أمر شراء'), ('pay', 'طلب صرف'), ('exp', 'طلب مصروفات'), ('bt', 'نقل موازنة'), ('contract', 'عقد'), ('sa', 'سلفة راتب'), ('custody', 'عهدة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المستند')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ المعتمد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في انتظار الاعتماد'), ('partial', 'معتمد جزئياً'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('current_approval_level', models.IntegerField(default=0, verbose_name='مستوى الاعتماد الحالي')),
                ('required_approval_level', models.IntegerField(default=1, verbose_name='مستوى الاعتماد المطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='approval_docs/', verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenterbudget', verbose_name='بند الموازنة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_docs', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المستند')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='العملة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'مستند استماد',
                'verbose_name_plural': 'مستندات الاستماد',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_level_1', 'اعتماد المستوى الأول'), ('can_approve_level_2', 'اعتماد المستوى الثاني'), ('can_approve_level_3', 'اعتماد المستوى الثالث'), ('can_approve_level_4', 'اعتماد المستوى الرابع'), ('can_approve_level_5', 'اعتماد المستوى الخامس'), ('can_reject_approval', 'رفض المستندات')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='الكمية')),
                ('unit', models.CharField(default='قطعة', max_length=50, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='سعر الوحدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account', verbose_name='الحساب')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.approvaldocument', verbose_name='المستند')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند استماد',
                'verbose_name_plural': 'بنود الاستماد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1, verbose_name='مستوى الاعتماد')),
                ('action', models.CharField(choices=[('approve', 'موافقة'), ('reject', 'رفض'), ('return', 'إرجاع للتعديل'), ('comment', 'تعليق')], max_length=20, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='المبلغ المعتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.approvaldocument', verbose_name='المستند')),
            ],
            options={
                'verbose_name': 'اعتماد مستند',
                'verbose_name_plural': 'اعتمادات المستندات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('request_type', models.CharField(choices=[('purchase', 'طلب شراء'), ('material_issue', 'صرف مواد'), ('production', 'إنتاج'), ('maintenance', 'صيانة'), ('other', 'أخرى')], default='purchase', max_length=30, verbose_name='نوع الطلب')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاحتياج')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ التقديري')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='preparations/', verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_preparations', to=settings.AUTH_USER_MODEL, verbose_name='المكلف بالتنفيذ')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_requests', to='hr.department', verbose_name='القسم الطالب')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_requests', to='projects.project', verbose_name='المشروع')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_preparations', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب تحضير',
                'verbose_name_plural': 'طلبات التحضير',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_preparation', 'يمكنه اعتماد طلبات التحضير'), ('can_process_preparation', 'يمكنه معالجة طلبات التحضير')],
            },
        ),
        migrations.CreateModel(
            name='PreparationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('quantity_requested', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='الكمية المطلوبة')),
                ('unit', models.CharField(default='قطعة', max_length=50, verbose_name='الوحدة')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='السعر التقديري')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('quantity_approved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية المعتمدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.preparationrequest', verbose_name='طلب التحضير')),
            ],
            options={
                'verbose_name': 'بند تحضير',
                'verbose_name_plural': 'بنود التحضير',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PreparationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'موافقة'), ('reject', 'رفض'), ('return', 'إرجاع للتعديل'), ('comment', 'تعليق')], max_length=20, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.preparationrequest', verbose_name='طلب التحضير')),
            ],
            options={
                'verbose_name': 'اعتماد تحضير',
                'verbose_name_plural': 'اعتمادات التحضير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='preparation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_documents', to='core.preparationrequest', verbose_name='طلب التحضير المرتبط'),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pr', 'طلب شراء'), ('po', 'أمر شراء'), ('pay', 'طلب صرف'), ('exp', 'طلب مصروفات'), ('bt', 'نقل موازنة'), ('contract', 'عقد'), ('sa', 'سلفة راتب'), ('custody', 'عهدة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المستند')),
                ('approval_level', models.IntegerField(default=1, verbose_name='مستوى الاعتماد')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الحد الأدنى للمبلغ')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأقصى للمبلغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflows', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userrole', verbose_name='دور المعتمد')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'سير عمل اعتماد',
                'verbose_name_plural': 'سير عمل الاعتمادات',
                'ordering': ['document_type', 'approval_level', 'min_amount'],
                'unique_together': {('document_type', 'approval_level', 'department')},
            },
        ),
        migrations.AddIndex(
            model_name='preparationrequest',
            index=models.Index(fields=['status'], name='core_prepar_status_ecf3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationrequest',
            index=models.Index(fields=['request_type'], name='core_prepar_request_4173f1_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationrequest',
            index=models.Index(fields=['request_date'], name='core_prepar_request_3a8a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationrequest',
            index=models.Index(fields=['priority'], name='core_prepar_priorit_533562_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldocument',
            index=models.Index(fields=['status'], name='core_approv_status_5f553f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldocument',
            index=models.Index(fields=['document_type'], name='core_approv_documen_282b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldocument',
            index=models.Index(fields=['document_date'], name='core_approv_documen_5ede90_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldocument',
            index=models.Index(fields=['current_approval_level'], name='core_approv_current_f04f72_idx'),
        ),
    ]
