# Generated by Django 5.2.5 on 2025-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customsclearance_exportorder_exportcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='module',
            field=models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('accounting', 'الحسابات'), ('inventory', 'المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('hr', 'الموارد البشرية'), ('crm', 'العملاء'), ('production', 'الإنتاج'), ('fleet', 'الأسطول'), ('pos', 'نقاط البيع'), ('reports', 'التقارير'), ('settings', 'الإعدادات'), ('projects', 'المشاريع'), ('contracting', 'المقاولات'), ('shipping', 'الشحن'), ('eservices', 'الخدمات الإلكترونية'), ('ecommerce', 'المتجر الإلكتروني')], default='settings', max_length=50, verbose_name='الموديول'),
        ),
    ]
