# Generated by Django 5.2.5 on 2025-12-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_page_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=100, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='انستجرام'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لينكدإن'),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='الموبايل'),
        ),
        migrations.AddField(
            model_name='company',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='تويتر/X'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='واتساب'),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='يوتيوب'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20, verbose_name='بادئة الفواتير'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='الرقم الضريبي'),
        ),
    ]
