# Generated by Django 5.2.9 on 2026-02-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='نص تذييل المطبوعات'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, verbose_name='شعار الشركة النصي'),
        ),
        migrations.CreateModel(
            name='CompanyPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(choices=[('main', 'رئيسي'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('complaints', 'الشكاوى'), ('support', 'الدعم الفني'), ('fax', 'فاكس'), ('whatsapp', 'واتساب'), ('hotline', 'خط ساخن'), ('other', 'أخرى')], default='main', max_length=20, verbose_name='نوع الرقم')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='الشخص المسؤول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_on_print', models.BooleanField(default=True, verbose_name='يظهر على المطبوعات')),
                ('show_on_store', models.BooleanField(default=True, verbose_name='يظهر على المتجر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'رقم هاتف الشركة',
                'verbose_name_plural': 'أرقام هواتف الشركة',
                'ordering': ['sort_order', 'phone_type'],
            },
        ),
    ]
