# Generated by Django 5.2.9 on 2026-02-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_company_footer_text_company_slogan_companyphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='نسبة VAT الافتراضية التي تظهر في الفواتير الضريبية', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة %'),
        ),
    ]
