# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_default_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocument',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المستند'),
        ),
        migrations.AlterField(
            model_name='exportorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='financialapproval',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الأمر'),
        ),
        migrations.AlterField(
            model_name='importwaiver',
            name='waiver_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التنازل'),
        ),
        migrations.AlterField(
            model_name='preexportinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='preparationrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
    ]
