# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('category', models.CharField(max_length=100, verbose_name='الفئة')),
                ('subject_template', models.CharField(max_length=200, verbose_name='قالب الموضوع')),
                ('body_template', models.TextField(verbose_name='قالب المحتوى')),
                ('available_variables', models.TextField(help_text='مثل: {sender_name}, {date}, {subject}', verbose_name='المتغيرات المتاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قالب مراسلة',
                'verbose_name_plural': 'قوالب المراسلات',
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المرجع')),
                ('correspondence_type', models.CharField(choices=[('incoming', 'واردة'), ('outgoing', 'صادرة')], max_length=20, verbose_name='النوع')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('sender', models.CharField(max_length=200, verbose_name='المرسل')),
                ('recipient', models.CharField(max_length=200, verbose_name='المستقبل')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='الفئة')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='الوسوم')),
                ('attachments', models.FileField(blank=True, upload_to='correspondence/', verbose_name='الملفات المرفقة')),
                ('status', models.CharField(choices=[('received', 'مستلمة'), ('opened', 'مفتوحة'), ('reviewed', 'تمت مراجعتها'), ('replied', 'تمت الإجابة عليها'), ('closed', 'مغلقة'), ('archived', 'مؤرشفة')], default='received', max_length=20, verbose_name='الحالة')),
                ('received_date', models.DateField(verbose_name='تاريخ الاستقبال')),
                ('reviewed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_correspondence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مراسلة',
                'verbose_name_plural': 'المراسلات',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الأرشفة')),
                ('archive_location', models.CharField(max_length=200, verbose_name='موقع الأرشيف')),
                ('indexed_keywords', models.TextField(blank=True, verbose_name='الكلمات المفتاحية')),
                ('access_restricted', models.BooleanField(default=False, verbose_name='وصول مقيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='correspondence_management.correspondence')),
            ],
            options={
                'verbose_name': 'أرشيف مراسلة',
                'verbose_name_plural': 'أرشيف المراسلات',
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم حلها')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('original_correspondence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='correspondence_management.correspondence')),
                ('replies', models.ManyToManyField(blank=True, related_name='reply_to_thread', to='correspondence_management.correspondence')),
            ],
            options={
                'verbose_name': 'سلسلة مراسلات',
                'verbose_name_plural': 'سلاسل المراسلات',
            },
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['status'], name='corresponde_status_c96ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['correspondence_type'], name='corresponde_corresp_739c65_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['received_date'], name='corresponde_receive_f36d80_idx'),
        ),
    ]
