# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('standard_type', models.CharField(choices=[('iso', 'ISO'), ('regulatory', 'تنظيمي'), ('industry', 'صناعي'), ('internal', 'داخلي'), ('quality', 'جودة'), ('safety', 'سلامة')], max_length=30, verbose_name='نوع المعيار')),
                ('issuing_body', models.CharField(max_length=200, verbose_name='الجهة المصدرة')),
                ('version', models.CharField(max_length=50, verbose_name='الإصدار')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('reference_url', models.URLField(blank=True, verbose_name='رابط المرجع')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'معيار امتثال',
                'verbose_name_plural': 'معايير الامتثال',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المراجعة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('audit_type', models.CharField(choices=[('internal', 'داخلية'), ('external', 'خارجية'), ('compliance', 'امتثال'), ('financial', 'مالية'), ('operational', 'تشغيلية'), ('quality', 'جودة')], max_length=30, verbose_name='نوع المراجعة')),
                ('scope', models.TextField(verbose_name='النطاق')),
                ('objectives', models.TextField(verbose_name='الأهداف')),
                ('scheduled_date', models.DateField(verbose_name='التاريخ المجدول')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء الفعلي')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('status', models.CharField(choices=[('planned', 'مخططة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='planned', max_length=20, verbose_name='الحالة')),
                ('findings_summary', models.TextField(blank=True, verbose_name='ملخص النتائج')),
                ('overall_compliance_score', models.IntegerField(blank=True, help_text='من 0 إلى 100', null=True, verbose_name='نقاط الامتثال الإجمالية')),
                ('report_document_url', models.URLField(blank=True, verbose_name='رابط تقرير المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_team', models.ManyToManyField(blank=True, related_name='audits_participated', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=50, verbose_name='رقم النتيجة')),
                ('severity', models.CharField(choices=[('minor', 'بسيطة'), ('major', 'كبيرة'), ('critical', 'حرجة'), ('observation', 'ملاحظة')], max_length=20, verbose_name='الخطورة')),
                ('category', models.CharField(choices=[('non_compliance', 'عدم امتثال'), ('deficiency', 'نقص'), ('opportunity', 'فرصة تحسين'), ('best_practice', 'ممارسة جيدة')], max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('evidence', models.TextField(blank=True, verbose_name='الدليل')),
                ('impact', models.TextField(blank=True, verbose_name='التأثير')),
                ('corrective_action_required', models.BooleanField(default=True, verbose_name='يتطلب إجراء تصحيحي')),
                ('corrective_action_plan', models.TextField(blank=True, verbose_name='خطة الإجراء التصحيحي')),
                ('corrective_action_deadline', models.DateField(blank=True, null=True, verbose_name='الموعد النهائي للإجراء')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('resolution_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance_management.audit')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتيجة مراجعة',
                'verbose_name_plural': 'نتائج المراجعات',
                'ordering': ['-severity', 'finding_number'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('checklist_items', models.JSONField(default=list, help_text='قائمة بنود المراجعة', verbose_name='بنود القائمة')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('annually', 'سنوي'), ('ad_hoc', 'عند الطلب')], max_length=20, verbose_name='التكرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checklists', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='compliance_management.compliancestandard')),
            ],
            options={
                'verbose_name': 'قائمة مراجعة',
                'verbose_name_plural': 'قوائم المراجعة',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance_management.compliancechecklist'),
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('report_period_start', models.DateField(verbose_name='بداية فترة التقرير')),
                ('report_period_end', models.DateField(verbose_name='نهاية فترة التقرير')),
                ('executive_summary', models.TextField(verbose_name='الملخص التنفيذي')),
                ('overall_compliance_status', models.CharField(choices=[('compliant', 'ملتزم'), ('partially_compliant', 'ملتزم جزئياً'), ('non_compliant', 'غير ملتزم'), ('under_review', 'قيد المراجعة')], max_length=20, verbose_name='حالة الامتثال الإجمالية')),
                ('compliance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الامتثال %')),
                ('detailed_findings', models.TextField(verbose_name='النتائج التفصيلية')),
                ('areas_of_concern', models.TextField(blank=True, verbose_name='مجالات القلق')),
                ('recommendations', models.TextField(verbose_name='التوصيات')),
                ('total_audits_conducted', models.IntegerField(default=0, verbose_name='إجمالي المراجعات')),
                ('total_findings', models.IntegerField(default=0, verbose_name='إجمالي النتائج')),
                ('critical_findings', models.IntegerField(default=0, verbose_name='النتائج الحرجة')),
                ('major_findings', models.IntegerField(default=0, verbose_name='النتائج الكبيرة')),
                ('minor_findings', models.IntegerField(default=0, verbose_name='النتائج البسيطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compliance_reports', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to=settings.AUTH_USER_MODEL)),
                ('standards_covered', models.ManyToManyField(to='compliance_management.compliancestandard', verbose_name='المعايير المغطاة')),
            ],
            options={
                'verbose_name': 'تقرير امتثال',
                'verbose_name_plural': 'تقارير الامتثال',
                'ordering': ['-report_period_end'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance_management.compliancestandard'),
        ),
    ]
