# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('market_position', models.CharField(choices=[('leader', 'رائد'), ('challenger', 'منافس قوي'), ('follower', 'تابع'), ('niche', 'متخصص')], default='follower', max_length=20, verbose_name='المركز السوقي')),
                ('estimated_market_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الحصة السوقية المقدرة %')),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيراد المقدر')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط القوة')),
                ('weaknesses', models.TextField(blank=True, verbose_name='نقاط الضعف')),
                ('opportunities', models.TextField(blank=True, verbose_name='الفرص')),
                ('threats', models.TextField(blank=True, verbose_name='التهديدات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منافس',
                'verbose_name_plural': 'المنافسون',
                'ordering': ['-estimated_market_share'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التحليل')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('key_findings', models.TextField(verbose_name='النتائج الرئيسية')),
                ('market_positioning', models.TextField(verbose_name='المركز السوقي')),
                ('competitive_advantages', models.TextField(verbose_name='المزايا التنافسية')),
                ('competitive_disadvantages', models.TextField(verbose_name='العيوب التنافسية')),
                ('strategic_recommendations', models.TextField(verbose_name='التوصيات الاستراتيجية')),
                ('action_items', models.TextField(verbose_name='بنود العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_reviewed', to=settings.AUTH_USER_MODEL)),
                ('competitors_analyzed', models.ManyToManyField(to='competitive_intelligence.competitor', verbose_name='المنافسون المحللون')),
            ],
            options={
                'verbose_name': 'تحليل تنافسي',
                'verbose_name_plural': 'التحليلات التنافسية',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('our_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعرنا')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='فرق السعر')),
                ('price_difference_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='فرق السعر %')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('quality_rating', models.IntegerField(default=3, help_text='من 1 إلى 5', verbose_name='تقييم الجودة')),
                ('last_price_update', models.DateField(auto_now=True, verbose_name='آخر تحديث للسعر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='competitive_intelligence.competitor')),
                ('our_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_equivalents', to='inventory.product')),
            ],
            options={
                'verbose_name': 'منتج منافس',
                'verbose_name_plural': 'منتجات المنافسين',
                'ordering': ['competitor', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('trend_type', models.CharField(choices=[('pricing', 'تسعير'), ('technology', 'تقنية'), ('customer_preference', 'تفضيلات عملاء'), ('regulation', 'تنظيمات'), ('competition', 'منافسة'), ('economic', 'اقتصادي')], max_length=30, verbose_name='نوع الاتجاه')),
                ('impact_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='مستوى التأثير')),
                ('trend_direction', models.CharField(choices=[('increasing', 'متزايد'), ('decreasing', 'متناقص'), ('stable', 'مستقر'), ('volatile', 'متقلب')], max_length=20, verbose_name='اتجاه التطور')),
                ('identified_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الرصد')),
                ('relevance_start', models.DateField(blank=True, null=True, verbose_name='بداية الصلاحية')),
                ('relevance_end', models.DateField(blank=True, null=True, verbose_name='نهاية الصلاحية')),
                ('strategic_implications', models.TextField(blank=True, verbose_name='الآثار الاستراتيجية')),
                ('recommended_actions', models.TextField(blank=True, verbose_name='الإجراءات الموصى بها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اتجاه سوق',
                'verbose_name_plural': 'اتجاهات السوق',
                'ordering': ['-identified_date'],
            },
        ),
    ]
