"""
Factory classes for generating test data across all Tony ERP models.

This module provides factory classes using factory_boy to create test instances
of models with realistic data. Factories reduce test setup code and ensure
consistent, valid test data.

Usage:
    from tests.factories import UserFactory, ProductFactory
    
    user = UserFactory()
    product = ProductFactory(price=100.00)
"""

import factory
from factory import fuzzy
from factory.django import DjangoModelFactory
from django.contrib.auth import get_user_model
from django.utils import timezone
from decimal import Decimal
from datetime import date, timedelta
import random

User = get_user_model()


# ============================================================================
# User and Authentication Factories
# ============================================================================

class UserFactory(DjangoModelFactory):
    """Factory for creating User instances."""
    
    class Meta:
        model = User

    username = factory.Sequence(lambda n: f'user{n}')
    email = factory.LazyAttribute(lambda o: f"{o.username}@example.com")
    first_name = factory.Faker('first_name', locale='ar_SA')
    last_name = factory.Faker('last_name', locale='ar_SA')
    password = factory.PostGenerationMethodCall('set_password', 'testpass123')
    is_active = True
    is_staff = False
    is_superuser = False


class UserRoleFactory(DjangoModelFactory):
    """Factory for UserRole."""
    
    class Meta:
        model = 'users.UserRole'
        django_get_or_create = ('name',)
    
    name = 'accountant'
    display_name = 'Accountant'
    description = 'Accounting staff member'
    is_active = True
    can_approve = False
    approval_level = 0


class UserProfileFactory(DjangoModelFactory):
    """Factory for UserProfile."""
    
    class Meta:
        model = 'users.UserProfile'
    
    user = factory.SubFactory(UserFactory)
    arabic_name = factory.Faker('name', locale='ar_SA')
    employee_id = factory.Sequence(lambda n: f'EMP{n:04d}')
    phone = factory.Faker('phone_number', locale='ar_SA')
    position = factory.Faker('job', locale='ar_SA')
    is_approved = True


# ============================================================================
# Accounting Factories
# ============================================================================

class CostCenterFactory(DjangoModelFactory):
    """Factory for CostCenter."""
    
    class Meta:
        model = 'accounting.CostCenter'
    
    code = factory.Sequence(lambda n: f'CC{n:03d}')
    name = factory.Faker('company', locale='ar_SA')
    description = factory.Faker('text', max_nb_chars=100, locale='ar_SA')
    is_active = True


class AccountFactory(DjangoModelFactory):
    """Factory for Account."""
    
    class Meta:
        model = 'accounting.Account'
    
    code = factory.Sequence(lambda n: f'{n:04d}')
    name = factory.Faker('word', locale='ar_SA')
    account_type = fuzzy.FuzzyChoice(['asset', 'liability', 'equity', 'revenue', 'expense'])
    description = factory.Faker('text', max_nb_chars=100, locale='ar_SA')
    is_active = True
    can_post = True
    requires_cost_center = False
    is_group = False
    level = 1
    
    @factory.lazy_attribute
    def path(self):
        return f"/{self.code}/"


class FiscalYearFactory(DjangoModelFactory):
    """Factory for FiscalYear."""
    
    class Meta:
        model = 'accounting.FiscalYear'
    
    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        kwargs.pop('created_by', None)
        return super()._create(model_class, *args, **kwargs)
    
    name = factory.LazyAttribute(lambda o: str(o.start_date.year))
    start_date = factory.LazyFunction(lambda: date(2026, 1, 1))
    end_date = factory.LazyFunction(lambda: date(2026, 12, 31))
    is_active = True


class JournalEntryFactory(DjangoModelFactory):
    """Factory for JournalEntry."""
    
    class Meta:
        model = 'accounting.JournalEntry'
    
    # number is auto-generated by model
    date = factory.LazyFunction(date.today)
    entry_type = fuzzy.FuzzyChoice(['manual', 'sales', 'purchase', 'payment', 'receipt'])
    description = factory.Faker('sentence', locale='ar_SA')
    auto_generated = False
    is_posted = False


class JournalEntryItemFactory(DjangoModelFactory):
    """Factory for JournalEntryItem."""
    
    class Meta:
        model = 'accounting.JournalEntryItem'
    
    journal_entry = factory.SubFactory(JournalEntryFactory)
    account = factory.SubFactory(AccountFactory)
    type = fuzzy.FuzzyChoice(['debit', 'credit'])
    amount = fuzzy.FuzzyDecimal(100.0, 10000.0, precision=2)
    description = factory.Faker('sentence', locale='ar_SA')


# ============================================================================
# Inventory Factories
# ============================================================================

class CategoryFactory(DjangoModelFactory):
    """Factory for product Category."""
    
    class Meta:
        model = 'inventory.Category'
        django_get_or_create = ('name',)
    
    name = factory.Faker('word', locale='ar_SA')
    description = factory.Faker('text', max_nb_chars=200, locale='ar_SA')
    is_active = True
    sort_order = factory.Sequence(lambda n: n)


class LocationFactory(DjangoModelFactory):
    """Factory for warehouse Location."""
    
    class Meta:
        model = 'inventory.Location'
    
    code = factory.Sequence(lambda n: f'LOC{n:03d}')
    name = factory.Faker('city', locale='ar_SA')
    type = fuzzy.FuzzyChoice(['finished', 'wip', 'raw', 'spare', 'store', 'other'])
    is_active = True


class ProductFactory(DjangoModelFactory):
    """Factory for Product."""
    
    class Meta:
        model = 'inventory.Product'
        django_get_or_create = ('sku',)
    
    sku = factory.Sequence(lambda n: f'SKU{n:06d}')
    name = factory.Faker('word', locale='ar_SA')
    description = factory.Faker('text', max_nb_chars=200, locale='ar_SA')
    category = factory.SubFactory(CategoryFactory)
    price = fuzzy.FuzzyDecimal(50.0, 5000.0, precision=2)
    cost = factory.LazyAttribute(lambda o: o.price * Decimal('0.6'))  # 40% margin
    product_type = fuzzy.FuzzyChoice(['finished', 'raw_material', 'semi_finished', 'service'])
    purchase_uom = 'unit'
    usage_uom = 'unit'
    conversion_factor = 1
    is_active = True
    min_stock = 10
    
    @factory.lazy_attribute
    def barcode(self):
        """Generate unique barcode."""
        return f"{random.randint(100000000000, 999999999999)}"
    
    @factory.lazy_attribute
    def internal_code(self):
        """Generate unique internal code."""
        return f"INT{random.randint(100000, 999999)}"


class StockFactory(DjangoModelFactory):
    """Factory for Stock."""
    
    class Meta:
        model = 'inventory.Stock'
        django_get_or_create = ('product', 'location')
    
    product = factory.SubFactory(ProductFactory)
    location = factory.SubFactory(LocationFactory)
    quantity = fuzzy.FuzzyInteger(0, 1000)


# ============================================================================
# Partner Factories (Customer/Supplier)
# ============================================================================

class PartnerFactory(DjangoModelFactory):
    """Factory for Partner."""
    
    class Meta:
        model = 'partners.Partner'
    
    name = factory.Faker('company', locale='ar_SA')
    email = factory.Faker('email')
    phone = factory.Faker('phone_number', locale='ar_SA')
    address = factory.Faker('address', locale='ar_SA')
    partner_type = 'customer'
    is_active = True


class CustomerFactory(DjangoModelFactory):
    """Factory for Customer."""
    
    class Meta:
        model = 'partners.Customer'
    
    partner = factory.SubFactory(PartnerFactory, partner_type='customer')
    name = factory.LazyAttribute(lambda o: o.partner.name if o.partner else factory.Faker('company', locale='ar_SA').generate({}))
    phone = factory.Faker('phone_number', locale='ar_SA')
    email = factory.Faker('email')
    address = factory.Faker('address', locale='ar_SA')
    is_key_account = False


class SupplierFactory(DjangoModelFactory):
    """Factory for Supplier."""
    
    class Meta:
        model = 'partners.Supplier'
    
    partner = factory.SubFactory(PartnerFactory, partner_type='supplier')
    name = factory.LazyAttribute(lambda o: o.partner.name if o.partner else factory.Faker('company', locale='ar_SA').generate({}))
    phone = factory.Faker('phone_number', locale='ar_SA')
    email = factory.Faker('email')
    address = factory.Faker('address', locale='ar_SA')
    city = factory.Faker('city', locale='ar_SA')
    is_active = True


# ============================================================================
# Sales Factories
# ============================================================================

class InvoiceFactory(DjangoModelFactory):
    """Factory for Invoice."""
    
    class Meta:
        model = 'sales.Invoice'
    
    # number is auto-generated by model
    customer = factory.SubFactory(CustomerFactory)
    date = factory.LazyFunction(date.today)
    due_date = factory.LazyAttribute(lambda o: o.date + timedelta(days=30))
    discount = Decimal('0.00')
    is_tax_inclusive = True
    is_withholding_applied = False
    paid = Decimal('0.00')
    is_posted = False


class InvoiceItemFactory(DjangoModelFactory):
    """Factory for InvoiceItem."""
    
    class Meta:
        model = 'sales.InvoiceItem'
    
    invoice = factory.SubFactory(InvoiceFactory)
    product = factory.SubFactory(ProductFactory)
    location = factory.SubFactory(LocationFactory)
    quantity = fuzzy.FuzzyInteger(1, 100)
    price = factory.LazyAttribute(lambda o: o.product.price if o.product else Decimal('100.00'))


class PaymentMethodFactory(DjangoModelFactory):
    """Factory for PaymentMethod."""
    
    class Meta:
        model = 'payments.PaymentMethod'
    
    name = factory.Sequence(lambda n: f"Method {n}")
    type = fuzzy.FuzzyChoice(['cash', 'bank_transfer', 'credit_card'])
    is_active = True


class InvoicePaymentFactory(DjangoModelFactory):
    """Factory for InvoicePayment."""
    
    class Meta:
        model = 'sales.InvoicePayment'
    
    invoice = factory.SubFactory(InvoiceFactory)
    date = factory.LazyFunction(date.today)
    amount = fuzzy.FuzzyDecimal(100.0, 10000.0, precision=2)
    payment_method = 'cash'
    reference = factory.Sequence(lambda n: f'PAY{n:06d}')


# ============================================================================
# Purchase Factories
# ============================================================================

class PurchaseBillFactory(DjangoModelFactory):
    """Factory for PurchaseBill."""
    
    class Meta:
        model = 'purchases.PurchaseBill'
    
    # number is auto-generated by model
    supplier = factory.SubFactory(SupplierFactory)
    date = factory.LazyFunction(date.today)
    due_date = factory.LazyAttribute(lambda o: o.date + timedelta(days=30))
    discount = Decimal('0.00')
    is_tax_inclusive = True
    paid = Decimal('0.00')
    is_posted = False


class PurchaseItemFactory(DjangoModelFactory):
    """Factory for PurchaseItem."""
    
    class Meta:
        model = 'purchases.PurchaseItem'
    
    purchase_bill = factory.SubFactory(PurchaseBillFactory)
    product = factory.SubFactory(ProductFactory)
    location = factory.SubFactory(LocationFactory)
    quantity = fuzzy.FuzzyInteger(1, 100)
    price = factory.LazyAttribute(lambda o: o.product.cost if o.product else Decimal('60.00'))


# ============================================================================
# Production Factories
# ============================================================================

class ProductionWorkCenterFactory(DjangoModelFactory):
    """Factory for ProductionWorkCenter."""
    
    class Meta:
        model = 'production.ProductionWorkCenter'
        django_get_or_create = ('code',)
    
    code = factory.Sequence(lambda n: f'WC{n:03d}')
    name = factory.Faker('word', locale='ar_SA')
    work_center_type = fuzzy.FuzzyChoice(['assembly', 'packaging', 'testing', 'cutting'])
    hourly_rate = fuzzy.FuzzyDecimal(30.0, 100.0, precision=2)
    capacity_per_hour = fuzzy.FuzzyInteger(10, 100)
    working_hours_per_day = 8
    is_active = True


class BOMFactory(DjangoModelFactory):
    """Factory for Bill of Materials."""
    
    class Meta:
        model = 'production.BillOfMaterials'
    
    product = factory.SubFactory(ProductFactory)
    version = factory.Sequence(lambda n: f'v{n+1}.0')
    name = factory.LazyAttribute(lambda o: f'BOM for {o.product.name}')
    description = factory.Faker('text', max_nb_chars=200, locale='ar_SA')
    base_quantity = 1
    effective_date = factory.LazyFunction(date.today)
    is_active = True
    is_default = True


class BOMItemFactory(DjangoModelFactory):
    """Factory for BOMItem."""
    
    class Meta:
        model = 'production.BOMItem'
    
    bom = factory.SubFactory(BOMFactory)
    material = factory.SubFactory(ProductFactory, product_type='raw_material')
    item_type = fuzzy.FuzzyChoice(['material', 'labor', 'overhead'])
    quantity = fuzzy.FuzzyDecimal(0.5, 10.0, precision=2)
    unit_cost = factory.LazyAttribute(lambda o: o.material.cost if o.material else Decimal('30.00'))
    wastage_percentage = fuzzy.FuzzyDecimal(0.0, 5.0, precision=1)
    sequence = factory.Sequence(lambda n: n)


class ProductionOrderFactory(DjangoModelFactory):
    """Factory for ProductionOrder."""
    
    class Meta:
        model = 'production.ProductionOrder'
    
    # order_number is auto-generated by model
    product = factory.SubFactory(ProductFactory, product_type='finished')
    quantity = fuzzy.FuzzyInteger(10, 1000)
    bom = factory.LazyAttribute(lambda o: BOMFactory(product=o.product))
    status = 'draft'
    start_date = factory.LazyFunction(date.today)
    expected_end_date = factory.LazyAttribute(lambda o: o.start_date + timedelta(days=7))


# ============================================================================
# Branch Factories
# ============================================================================

class BranchFactory(DjangoModelFactory):
    """Factory for Branch."""
    
    class Meta:
        model = 'branches.Branch'
        django_get_or_create = ('code',)
    
    code = factory.Sequence(lambda n: f'BR{n:03d}')
    name = factory.Faker('city', locale='ar_SA')
    address = factory.Faker('address', locale='ar_SA')
    phone = factory.Faker('phone_number', locale='ar_SA')
    is_active = True


# ============================================================================
# Helper Functions
# ============================================================================

def create_complete_invoice(num_items=3, with_stock=True):
    """
    Create a complete invoice with items and stock.
    
    Args:
        num_items: Number of invoice items to create
        with_stock: If True, creates stock for products
    
    Returns:
        Invoice instance with items
    """
    invoice = InvoiceFactory()
    location = LocationFactory()
    
    for _ in range(num_items):
        product = ProductFactory()
        if with_stock:
            StockFactory(product=product, location=location, quantity=1000)
        InvoiceItemFactory(
            invoice=invoice,
            product=product,
            location=location,
            quantity=fuzzy.FuzzyInteger(1, 10).fuzz()
        )
    
    return invoice


def create_balanced_journal_entry(debit_account=None, credit_account=None, amount=None):
    """
    Create a balanced journal entry.
    
    Args:
        debit_account: Account for debit entry (creates one if None)
        credit_account: Account for credit entry (creates one if None)
        amount: Amount for the entry (random if None)
    
    Returns:
        JournalEntry instance with balanced items
    """
    if debit_account is None:
        debit_account = AccountFactory(account_type='asset')
    if credit_account is None:
        credit_account = AccountFactory(account_type='revenue')
    if amount is None:
        amount = Decimal('1000.00')
    
    entry = JournalEntryFactory()
    
    # Create debit item
    JournalEntryItemFactory(
        journal_entry=entry,
        account=debit_account,
        type='debit',
        amount=amount
    )
    
    # Create credit item
    JournalEntryItemFactory(
        journal_entry=entry,
        account=credit_account,
        type='credit',
        amount=amount
    )
    
    return entry
