# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0011_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('points_per_unit', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='النقاط لكل وحدة عملة')),
                ('redemption_rate', models.DecimalField(decimal_places=2, default=0.01, help_text='قيمة كل نقطة بالعملة', max_digits=10, verbose_name='معدل الاستبدال')),
                ('min_points_redeem', models.IntegerField(default=100, verbose_name='الحد الأدنى للاستبدال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'برنامج ولاء',
                'verbose_name_plural': 'برامج الولاء',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المكافأة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('points_cost', models.IntegerField(verbose_name='تكلفة النقاط')),
                ('reward_type', models.CharField(choices=[('discount', 'خصم'), ('product', 'منتج'), ('voucher', 'قسيمة')], max_length=50, verbose_name='نوع المكافأة')),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المكافأة')),
                ('quantity_available', models.IntegerField(blank=True, null=True, verbose_name='الكمية المتاحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستوى')),
                ('min_points', models.IntegerField(verbose_name='الحد الأدنى من النقاط')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='مضاعف النقاط')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('benefits', models.TextField(blank=True, verbose_name='المزايا')),
                ('color', models.CharField(default='#6c757d', max_length=20, verbose_name='اللون')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'مستوى ولاء',
                'verbose_name_plural': 'مستويات الولاء',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.IntegerField(default=0, verbose_name='النقاط الحالية')),
                ('total_earned', models.IntegerField(default=0, verbose_name='إجمالي المكتسب')),
                ('total_redeemed', models.IntegerField(default=0, verbose_name='إجمالي المستبدل')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='partners.customer')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.loyaltyprogram')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier')),
            ],
            options={
                'verbose_name': 'حساب ولاء العميل',
                'verbose_name_plural': 'حسابات ولاء العملاء',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'اكتساب'), ('redeem', 'استبدال'), ('expire', 'انتهاء صلاحية'), ('adjust', 'تعديل'), ('bonus', 'مكافأة')], max_length=20, verbose_name='نوع العملية')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('balance_after', models.IntegerField(verbose_name='الرصيد بعد العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty')),
            ],
            options={
                'verbose_name': 'حركة نقاط',
                'verbose_name_plural': 'حركات النقاط',
                'ordering': ['-created_at'],
            },
        ),
    ]
