# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('sales', 'عقد بيع'), ('purchase', 'عقد شراء'), ('service', 'عقد خدمة'), ('employment', 'عقد عمل'), ('lease', 'عقد إيجار'), ('partnership', 'عقد شراكة'), ('nda', 'اتفاقية سرية'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العقد')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('party_a', models.CharField(max_length=200, verbose_name='الطرف الأول')),
                ('party_b', models.CharField(max_length=200, verbose_name='الطرف الثاني')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة العقد')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('document', models.FileField(upload_to='contracts/', verbose_name='ملف العقد')),
                ('document_hash', models.CharField(blank=True, max_length=255, verbose_name='بصمة الملف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'قيد الموافقة'), ('approved', 'موافق عليه'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('on_hold', 'معلق')], default='draft', max_length=50, verbose_name='الحالة')),
                ('is_digitally_signed', models.BooleanField(default=False, verbose_name='موقع رقمياً')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('signed_by', models.CharField(blank=True, max_length=200, verbose_name='موقع من قبل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('attachments', models.FileField(blank=True, upload_to='contracts/attachments/', verbose_name='ملفات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(max_length=100, verbose_name='رقم التعديل')),
                ('amendment_date', models.DateField(verbose_name='تاريخ التعديل')),
                ('description', models.TextField(verbose_name='وصف التعديل')),
                ('old_terms', models.TextField(verbose_name='الشروط القديمة')),
                ('new_terms', models.TextField(verbose_name='الشروط الجديدة')),
                ('amendment_document', models.FileField(upload_to='contracts/amendments/', verbose_name='وثيقة التعديل')),
                ('is_signed', models.BooleanField(default=False, verbose_name='موقع عليه')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contract_management.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعديل عقد',
                'verbose_name_plural': 'تعديلات العقود',
                'ordering': ['-amendment_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_number', models.CharField(max_length=50, verbose_name='رقم البند')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contract_management.contract')),
            ],
            options={
                'verbose_name': 'بند عقد',
                'verbose_name_plural': 'بنود العقود',
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('milestone_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قيمة المرحلة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد الإنجاز'), ('completed', 'مكتملة'), ('delayed', 'متأخرة')], max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contract_management.contract')),
            ],
            options={
                'verbose_name': 'مرحلة عقد',
                'verbose_name_plural': 'مراحل العقود',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_ma_status_81e305_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type'], name='contract_ma_contrac_dd9a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='contract_ma_end_dat_e85438_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractamendment',
            unique_together={('contract', 'amendment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='contractclause',
            unique_together={('contract', 'clause_number')},
        ),
    ]
