# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السمة')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('theme_type', models.CharField(choices=[('light', 'فاتح'), ('dark', 'مظلم'), ('custom', 'مخصص')], default='light', max_length=20, verbose_name='نوع السمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('primary_color', models.CharField(default='#3498db', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(default='#9b59b6', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون التمييز')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون الخلفية')),
                ('surface_color', models.CharField(default='#f8f9fa', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون السطح')),
                ('card_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون البطاقات')),
                ('text_primary', models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون النص الأساسي')),
                ('text_secondary', models.CharField(default='#6c757d', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون النص الثانوي')),
                ('text_muted', models.CharField(default='#adb5bd', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون النص الخافت')),
                ('sidebar_bg', models.CharField(default='#343a40', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='خلفية الشريط الجانبي')),
                ('sidebar_text', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='نص الشريط الجانبي')),
                ('sidebar_active', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='العنصر النشط')),
                ('header_bg', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='خلفية الهيدر')),
                ('header_text', models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='نص الهيدر')),
                ('success_color', models.CharField(default='#28a745', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون النجاح')),
                ('warning_color', models.CharField(default='#ffc107', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون التحذير')),
                ('danger_color', models.CharField(default='#dc3545', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون الخطر')),
                ('info_color', models.CharField(default='#17a2b8', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب أن يكون اللون بصيغة HEX مثل #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون المعلومات')),
                ('border_radius', models.CharField(default='0.375rem', max_length=10, verbose_name='نصف قطر الحواف')),
                ('box_shadow', models.CharField(default='0 0.125rem 0.25rem rgba(0,0,0,0.075)', max_length=100, verbose_name='الظل')),
                ('font_family', models.CharField(default="'Tajawal', 'Segoe UI', sans-serif", max_length=200, verbose_name='الخط')),
                ('custom_css', models.TextField(blank=True, verbose_name='CSS مخصص')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سمة',
                'verbose_name_plural': 'السمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'فاتح'), ('dark', 'مظلم'), ('auto', 'تلقائي')], default='auto', max_length=10, verbose_name='الوضع')),
                ('compact_mode', models.BooleanField(default=False, verbose_name='الوضع المضغوط')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='طي الشريط الجانبي')),
                ('font_size', models.CharField(default='medium', max_length=10, verbose_name='حجم الخط')),
                ('auto_switch_enabled', models.BooleanField(default=True, verbose_name='تبديل تلقائي')),
                ('dark_mode_start', models.TimeField(default='18:00', verbose_name='بداية الوضع المظلم')),
                ('dark_mode_end', models.TimeField(default='06:00', verbose_name='نهاية الوضع المظلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme_system.theme', verbose_name='السمة المختارة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات سمة المستخدم',
                'verbose_name_plural': 'تفضيلات سمات المستخدمين',
            },
        ),
    ]
