# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('block_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('gallery', 'معرض صور'), ('video', 'فيديو'), ('html', 'HTML'), ('quote', 'اقتباس'), ('table', 'جدول'), ('accordion', 'أكورديون'), ('tabs', 'تبويبات'), ('cta', 'دعوة للإجراء'), ('form', 'نموذج')], max_length=20, verbose_name='نوع الكتلة')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('content_json', models.JSONField(blank=True, default=dict, verbose_name='بيانات المحتوى')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='فئة CSS')),
                ('background_color', models.CharField(blank=True, max_length=20, verbose_name='لون الخلفية')),
                ('is_global', models.BooleanField(default=False, verbose_name='كتلة عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'كتلة محتوى',
                'verbose_name_plural': 'كتل المحتوى',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='المعرف')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قائمة',
                'verbose_name_plural': 'القوائم',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('file', models.FileField(upload_to='cms/media/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('document', 'مستند'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الملف')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('caption', models.TextField(blank=True, verbose_name='التعليق')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='المعرف')),
                ('excerpt', models.TextField(blank=True, verbose_name='المقتطف')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('content_blocks', models.JSONField(blank=True, default=list, verbose_name='كتل المحتوى')),
                ('featured_image', models.ImageField(blank=True, upload_to='cms/pages/', verbose_name='الصورة البارزة')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='وصف SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='كلمات مفتاحية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('scheduled', 'مجدول'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد النشر المجدول')),
                ('template', models.CharField(default='default', max_length=100, verbose_name='القالب')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='الصفحة الرئيسية')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='عرض في القائمة')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='السماح بالتعليقات')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('link_type', models.CharField(choices=[('page', 'صفحة'), ('url', 'رابط خارجي'), ('category', 'تصنيف')], default='url', max_length=20, verbose_name='نوع الرابط')),
                ('url', models.URLField(blank=True, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='فئة CSS')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='فتح في تبويب جديد')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu', verbose_name='القائمة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem', verbose_name='العنصر الأب')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='الصفحة')),
            ],
            options={
                'verbose_name': 'عنصر قائمة',
                'verbose_name_plural': 'عناصر القائمة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='المعرف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='اللون')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.pagecategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms.pagecategory', verbose_name='التصنيف'),
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='cms.page', verbose_name='الصفحة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cms.pagecomment', verbose_name='الرد على')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
