# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0027_rename_accounting__entry_t_abc123_idx_accounting__entry_t_bba407_idx_and_more'),
        ('payments', '0007_alter_paymenttransaction_installment'),
        ('sales', '0027_customerdiscountnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحساب')),
                ('account_holder', models.CharField(max_length=200, verbose_name='صاحب الحساب')),
                ('account_type', models.CharField(choices=[('checking', 'حساب جاري'), ('savings', 'حساب توفير'), ('business', 'حساب تجاري'), ('investment', 'حساب استثماري')], max_length=20, verbose_name='نوع الحساب')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('iban', models.CharField(max_length=50, unique=True, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='رمز البنك')),
                ('branch_code', models.CharField(blank=True, max_length=10, verbose_name='رمز الفرع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='سر API')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL Webhook')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='تفعيل المزامنة')),
                ('auto_reconcile', models.BooleanField(default=True, verbose_name='مطابقة تلقائية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_number'], name='bank_integr_account_4f4d2d_idx'), models.Index(fields=['status'], name='bank_integr_status_c55991_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(max_length=100, verbose_name='نوع الرسم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('fee_date', models.DateField(verbose_name='تاريخ الرسم')),
                ('frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('per_transaction', 'لكل عملية')], max_length=20, verbose_name='التكرار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='bank_integration.bankaccount')),
            ],
            options={
                'verbose_name': 'رسم بنكي',
                'verbose_name_plural': 'الرسوم البنكية',
                'ordering': ['-fee_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(verbose_name='تاريخ العملية')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='تاريخ القيمة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('debit', 'خصم'), ('credit', 'إيداع'), ('transfer', 'تحويل'), ('fee', 'رسوم'), ('interest', 'فائدة')], max_length=20, verbose_name='نوع العملية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المرجع')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع البنك')),
                ('counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الطرف الآخر')),
                ('counterparty_account', models.CharField(blank=True, max_length=50, verbose_name='حساب الطرف الآخر')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('failed', 'فشلت'), ('reconciled', 'متطابقة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('matching_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة المطابقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستقبال')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_integration.bankaccount')),
                ('matched_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.invoice')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'عملية بنكية',
                'verbose_name_plural': 'العمليات البنكية',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField(verbose_name='تاريخ كشف الحساب')),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رصيد كشف الحساب')),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رصيد النظام')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الفرق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد المطابقة'), ('completed', 'مكتملة'), ('rejected', 'مرفوضة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المطابقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='bank_integration.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciled_transactions', models.ManyToManyField(blank=True, related_name='reconciliations', to='bank_integration.banktransaction')),
                ('unreconciled_transactions', models.ManyToManyField(blank=True, related_name='unreconciled_in', to='bank_integration.banktransaction')),
            ],
            options={
                'verbose_name': 'مطابقة بنكية',
                'verbose_name_plural': 'المطابقات البنكية',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matching_confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الثقة')),
                ('auto_matched', models.BooleanField(default=False, verbose_name='مطابقة تلقائية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='bank_integration.banktransaction')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_mappings', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'ربط عملية بنكية',
                'verbose_name_plural': 'روابط العمليات البنكية',
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['account', 'transaction_date'], name='bank_integr_account_722c60_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status'], name='bank_integr_status_a78072_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference_number'], name='bank_integr_referen_b4c438_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('account', 'reference_number')},
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['account', 'statement_date'], name='bank_integr_account_c26fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['status'], name='bank_integr_status_c9cb83_idx'),
        ),
    ]
