# Generated by Django 5.2.5 on 2025-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_key_account',
            field=models.BooleanField(default=False, verbose_name='عميل رئيسي'),
        ),
    ]
