# Generated by Django 5.2.5 on 2025-08-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_customer_is_key_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_key_account'], name='customer_key_idx'),
        ),
    ]
