# Generated by Django 5.2.5 on 2025-08-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_customer_customer_key_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='partners.partner', verbose_name='الشريك المرتبط'),
        ),
    ]
