# Generated by Django 5.2.5 on 2025-08-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_supplier_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='raw_material',
            field=models.CharField(blank=True, help_text='وصف مختصر أو اسم المادة الأساسية التي يوردها', max_length=255, verbose_name='المادة الخام / الصنف الرئيسي'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('raw_materials', 'خامات'), ('packaging', 'مواد تعبئة'), ('services', 'خدمات'), ('spare_parts', 'قطع غيار'), ('other', 'أخرى')], max_length=30, verbose_name='نوع التوريد'),
        ),
    ]
