# Generated by Django 5.2.5 on 2025-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_supplier_raw_material_supplier_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
