# Generated by Django 5.2.5 on 2025-12-09 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_alter_customer_id_alter_partner_id_alter_supplier_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('commercial_register', 'السجل التجاري'), ('tax_card', 'البطاقة الضريبية'), ('vat_certificate', 'شهادة ضريبة القيمة المضافة'), ('contract', 'عقد توريد'), ('quality_certificate', 'شهادة جودة'), ('insurance', 'بوليصة تأمين'), ('bank_account', 'بيانات حساب بنكي'), ('authorization', 'تفويض / توكيل'), ('id_copy', 'صورة الهوية / جواز السفر'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المستند')),
                ('document_number', models.CharField(blank=True, help_text='مثل: رقم السجل التجاري أو رقم البطاقة الضريبية', max_length=100, verbose_name='رقم المستند')),
                ('title', models.CharField(help_text='وصف مختصر للمستند', max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(help_text='الصيغ المدعومة: PDF, Word, Excel, صور', upload_to='suppliers/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='الملف')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, help_text='اتركه فارغاً إذا كان المستند لا ينتهي', null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_verified', models.BooleanField(default=False, help_text='هل تم مراجعة والتحقق من صحة المستند؟', verbose_name='تم التحقق منه')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.supplier', verbose_name='المورد')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند مورد',
                'verbose_name_plural': 'مستندات الموردين',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['supplier', 'document_type'], name='partners_su_supplie_739517_idx'), models.Index(fields=['expiry_date'], name='partners_su_expiry__a3c95f_idx')],
            },
        ),
    ]
