# Generated by Django 5.2.5 on 2025-12-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_add_enterprise_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_active_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_name_idx',
        ),
    ]
