# Generated by Django 5.2.5 on 2026-01-13 10:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_add_is_active_to_product'),
        ('partners', '0011_product_unit_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(blank=True, help_text='الكود الذي يستخدمه المورد لهذا المنتج', max_length=100, verbose_name='كود المنتج عند المورد')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر الشراء من هذا المورد', max_digits=15, verbose_name='سعر الشراء')),
                ('currency', models.CharField(default='EGP', help_text='EGP, USD, EUR, etc.', max_length=3, verbose_name='العملة')),
                ('minimum_order_quantity', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='أقل كمية يمكن طلبها من هذا المورد', max_digits=15, verbose_name='الحد الأدنى للطلب')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, default=0, help_text='عدد الأيام من الطلب حتى التسليم', verbose_name='مدة التوريد (أيام)')),
                ('is_preferred', models.BooleanField(default=False, help_text='هل هذا هو المورد المفضل لهذا المنتج؟', verbose_name='مورد مفضل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='آخر تاريخ شراء')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='آخر سعر تم الشراء به فعلياً', max_digits=15, null=True, verbose_name='آخر سعر شراء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='inventory.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'منتج مورد',
                'verbose_name_plural': 'منتجات الموردين',
                'ordering': ['supplier', 'product'],
                'indexes': [models.Index(fields=['supplier', 'product'], name='partners_su_supplie_5473a2_idx'), models.Index(fields=['product', 'is_preferred'], name='partners_su_product_0db9ae_idx'), models.Index(fields=['is_active'], name='partners_su_is_acti_b184d9_idx')],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
