# Generated by Django 5.2.5 on 2026-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text='كود فريد للمورد', max_length=50, null=True, unique=True, verbose_name='الكود'),
        ),
    ]
