# Generated by Django 5.2.5 on 2026-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commercial_register',
            field=models.CharField(blank=True, help_text='رقم السجل التجاري للمورد', max_length=100, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, help_text='الرقم الضريبي أو رقم ضريبة القيمة المضافة', max_length=100, verbose_name='الرقم الضريبي'),
        ),
    ]
