# Generated by Django 5.2.5 on 2026-01-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_supplier_commercial_register_supplier_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر'), ('l', 'لتر'), ('ml', 'مللي لتر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('pcs', 'قطعة'), ('pack', 'عبوة'), ('box', 'صندوق'), ('roll', 'رول'), ('ton', 'طن')], default='unit', help_text='الوحدة التي يبيع بها المورد هذا المنتج', max_length=10, verbose_name='وحدة القياس'),
        ),
    ]
