# Generated by Django 5.2.5 on 2026-02-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_add_uom_to_supplierproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, help_text='اسم الشخص المسؤول عن هذا الرقم', max_length=255, verbose_name='اسم المسؤول')),
                ('phone', models.CharField(help_text='رقم الهاتف أو الموبايل', max_length=50, verbose_name='رقم الهاتف')),
                ('is_primary', models.BooleanField(default=False, help_text='هل هذا هو رقم الاتصال الأساسي؟', verbose_name='رقم أساسي')),
                ('notes', models.CharField(blank=True, help_text='مثل: مدير المبيعات، قسم المشتريات', max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ['-is_primary', 'contact_name'],
                'indexes': [models.Index(fields=['partner', 'is_primary'], name='partners_pa_partner_ff1a32_idx')],
            },
        ),
    ]
