# Generated by Django 5.2.5 on 2025-12-15 08:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0019_product_production_department_code'),
        ('partners', '0009_supplierdocument'),
        ('sales', '0023_add_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للخصم')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='EcommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='اسم المتجر')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='ecommerce/logo/', verbose_name='شعار المتجر')),
                ('store_description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('products_per_page', models.PositiveIntegerField(default=12, verbose_name='المنتجات في الصفحة')),
                ('show_out_of_stock', models.BooleanField(default=True, verbose_name='عرض المنتجات غير المتوفرة')),
                ('enable_reviews', models.BooleanField(default=True, verbose_name='تفعيل التقييمات')),
                ('enable_wishlist', models.BooleanField(default=True, verbose_name='تفعيل قائمة الأمنيات')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='حد الشحن المجاني')),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='تكلفة الشحن الافتراضية')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='المتجر مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='مفتاح الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_carts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سلة التسوق',
                'verbose_name_plural': 'سلات التسوق',
            },
        ),
        migrations.CreateModel(
            name='OnlineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العرض')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='وصف قصير')),
                ('full_description', models.TextField(blank=True, verbose_name='الوصف الكامل')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/products/', verbose_name='الصورة الرئيسية')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر مخصص')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخصم')),
                ('discount_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية الخصم')),
                ('discount_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الخصم')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='معروض')),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_product', to='inventory.product', verbose_name='المنتج في المخزون')),
            ],
            options={
                'verbose_name': 'منتج إلكتروني',
                'verbose_name_plural': 'المنتجات الإلكترونية',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('shipping_address', models.TextField(verbose_name='عنوان الشحن')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('shipping_country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المجموع الفرعي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='تكلفة الشحن')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الخصم')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='partners.customer', verbose_name='العميل')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order', to='sales.invoice', verbose_name='الفاتورة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب إلكتروني',
                'verbose_name_plural': 'الطلبات الإلكترونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع الفرعي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.onlineproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الطلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/categories/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ecommerce.productcategory', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئة المنتج',
                'verbose_name_plural': 'فئات المنتجات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.productcategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecommerce/products/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.onlineproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.cart', verbose_name='السلة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.onlineproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر السلة',
                'verbose_name_plural': 'عناصر السلة',
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.onlineproduct', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم المنتج',
                'verbose_name_plural': 'تقييمات المنتجات',
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.onlineproduct', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_wishlists', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قائمة الأمنيات',
                'verbose_name_plural': 'قوائم الأمنيات',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
