# Generated by Django 5.2.5 on 2025-12-17 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البوابة')),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('tap', 'Tap Payments'), ('moyasar', 'Moyasar'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('myfatoorah', 'MyFatoorah'), ('payfort', 'PayFort'), ('telr', 'Telr'), ('cod', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي')], max_length=50, unique=True, verbose_name='نوع البوابة')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret')),
                ('merchant_id', models.CharField(blank=True, max_length=200, verbose_name='معرف التاجر')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='وضع الاختبار')),
                ('sandbox_api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key للاختبار')),
                ('sandbox_api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret للاختبار')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ecommerce/payment_gateways/', verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بوابة الدفع',
                'verbose_name_plural': 'بوابات الدفع',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('company_type', models.CharField(choices=[('aramex', 'Aramex'), ('dhl', 'DHL'), ('fedex', 'FedEx'), ('smsa', 'SMSA Express'), ('saudi_post', 'البريد السعودي'), ('zajil', 'Zajil Express'), ('naqel', 'Naqel Express'), ('imile', 'iMile'), ('jnt', 'J&T Express'), ('custom', 'شركة مخصصة')], max_length=50, verbose_name='نوع الشركة')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب')),
                ('calculation_type', models.CharField(choices=[('flat', 'سعر ثابت'), ('weight', 'حسب الوزن'), ('price', 'حسب قيمة الطلب'), ('api', 'من API الشركة')], default='flat', max_length=20, verbose_name='طريقة الحساب')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السعر الثابت')),
                ('weight_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر الكيلو')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حد الشحن المجاني')),
                ('available_countries', models.JSONField(blank=True, default=list, verbose_name='الدول المتاحة')),
                ('available_cities', models.JSONField(blank=True, default=list, verbose_name='المدن المتاحة')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='وضع الاختبار')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ecommerce/shipping_companies/', verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('tracking_url', models.URLField(blank=True, verbose_name='رابط التتبع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة الشحن',
                'verbose_name_plural': 'شركات الشحن',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp Business'), ('telegram', 'Telegram'), ('pinterest', 'Pinterest')], max_length=50, unique=True, verbose_name='المنصة')),
                ('profile_url', models.URLField(blank=True, verbose_name='رابط الحساب')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='اسم المستخدم')),
                ('app_id', models.CharField(blank=True, max_length=200, verbose_name='App ID')),
                ('app_secret', models.CharField(blank=True, max_length=500, verbose_name='App Secret')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('pixel_id', models.CharField(blank=True, max_length=100, verbose_name='Pixel ID')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('enable_sharing', models.BooleanField(default=True, verbose_name='تفعيل المشاركة')),
                ('enable_login', models.BooleanField(default=False, verbose_name='تفعيل تسجيل الدخول')),
                ('enable_tracking', models.BooleanField(default=False, verbose_name='تفعيل التتبع')),
                ('show_in_header', models.BooleanField(default=True, verbose_name='عرض في الهيدر')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='عرض في الفوتر')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تكامل التواصل الاجتماعي',
                'verbose_name_plural': 'تكاملات التواصل الاجتماعي',
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='ecommerce/banners/', verbose_name='الصورة')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='ecommerce/banners/', verbose_name='صورة الموبايل')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط البانر')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='نص الزر')),
                ('position', models.CharField(choices=[('home_slider', 'السلايدر الرئيسي'), ('home_top', 'أعلى الصفحة الرئيسية'), ('home_middle', 'وسط الصفحة الرئيسية'), ('sidebar', 'الشريط الجانبي'), ('category_top', 'أعلى صفحة الفئات'), ('product_top', 'أعلى صفحة المنتج')], default='home_slider', max_length=50, verbose_name='الموضع')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StorePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('about', 'من نحن'), ('contact', 'اتصل بنا'), ('faq', 'الأسئلة الشائعة'), ('privacy', 'سياسة الخصوصية'), ('terms', 'الشروط والأحكام'), ('shipping', 'سياسة الشحن'), ('returns', 'سياسة الإرجاع')], max_length=50, unique=True, verbose_name='الصفحة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوى الصفحة',
                'verbose_name_plural': 'محتويات الصفحات',
            },
        ),
    ]
