# Generated by Django 5.2.5 on 2025-12-17 22:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_add_store_admin_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('apple', 'Apple'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], max_length=50, unique=True, verbose_name='المزود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('client_id', models.CharField(max_length=500, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('auth_url', models.URLField(blank=True, verbose_name='Authorization URL')),
                ('token_url', models.URLField(blank=True, verbose_name='Token URL')),
                ('userinfo_url', models.URLField(blank=True, verbose_name='User Info URL')),
                ('scopes', models.CharField(default='email profile', max_length=500, verbose_name='Scopes')),
                ('extra_params', models.JSONField(blank=True, default=dict, verbose_name='معاملات إضافية')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='CSS Class للأيقونة')),
                ('button_color', models.CharField(blank=True, max_length=20, verbose_name='لون الزر')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مزود تسجيل الدخول',
                'verbose_name_plural': 'مزودي تسجيل الدخول',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ecommerce/customers/', verbose_name='الصورة الشخصية')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('default_address', models.TextField(blank=True, verbose_name='العنوان الافتراضي')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='إجمالي المشتريات')),
                ('newsletter_subscribed', models.BooleanField(default=True, verbose_name='مشترك في النشرة البريدية')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='إشعارات SMS')),
                ('email_verified', models.BooleanField(default=False, verbose_name='البريد موثق')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='الهاتف موثق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'المنزل'), ('work', 'العمل'), ('other', 'آخر')], default='home', max_length=20, verbose_name='نوع العنوان')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address_line1', models.CharField(max_length=300, verbose_name='العنوان - السطر 1')),
                ('address_line2', models.CharField(blank=True, max_length=300, verbose_name='العنوان - السطر 2')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ecommerce.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عنوان العميل',
                'verbose_name_plural': 'عناوين العملاء',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='التوكن')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='ecommerce.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'توكن تأكيد البريد',
                'verbose_name_plural': 'توكنات تأكيد البريد',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='التوكن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='ecommerce.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'توكن إعادة تعيين كلمة المرور',
                'verbose_name_plural': 'توكنات إعادة تعيين كلمة المرور',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('apple', 'Apple'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], max_length=50, verbose_name='المزود')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='معرف المستخدم لدى المزود')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الاسم')),
                ('picture_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء التوكن')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='ecommerce.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حساب اجتماعي',
                'verbose_name_plural': 'الحسابات الاجتماعية',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
