# Generated by Django 5.2.5 on 2025-12-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_socialauthprovider_customer_customeraddress_and_more'),
        ('partners', '0009_supplierdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partner_customer',
            field=models.OneToOneField(blank=True, help_text='ربط العميل بنظام المبيعات لإنشاء الفواتير تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_profile', to='partners.customer', verbose_name='ملف العميل في المبيعات'),
        ),
    ]
