# Generated by Django 5.2.5 on 2025-12-23 17:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_add_partner_customer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العرض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='ecommerce/flash_sales/', verbose_name='البانر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='إظهار العد التنازلي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عرض سريع',
                'verbose_name_plural': 'العروض السريعة',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان العمود')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'عمود الفوتر',
                'verbose_name_plural': 'أعمدة الفوتر',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='ecommerce/footer/', verbose_name='شعار الفوتر')),
                ('footer_description', models.TextField(blank=True, verbose_name='وصف الفوتر')),
                ('footer_bg_color', models.CharField(default='#1a2538', max_length=20, verbose_name='لون خلفية الفوتر')),
                ('footer_text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='لون نص الفوتر')),
                ('copyright_text', models.CharField(blank=True, max_length=300, verbose_name='نص حقوق النشر')),
                ('show_newsletter', models.BooleanField(default=True, verbose_name='إظهار النشرة البريدية')),
                ('show_social_links', models.BooleanField(default=True, verbose_name='إظهار روابط التواصل')),
                ('show_payment_icons', models.BooleanField(default=True, verbose_name='إظهار أيقونات الدفع')),
                ('show_app_links', models.BooleanField(default=False, verbose_name='إظهار روابط التطبيق')),
                ('app_store_link', models.URLField(blank=True, verbose_name='رابط App Store')),
                ('play_store_link', models.URLField(blank=True, verbose_name='رابط Play Store')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الفوتر',
                'verbose_name_plural': 'إعدادات الفوتر',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecommerce/header/', verbose_name='الشعار')),
                ('logo_alt_text', models.CharField(blank=True, max_length=100, verbose_name='النص البديل للشعار')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='ecommerce/header/', verbose_name='أيقونة الموقع')),
                ('top_bar_text', models.CharField(blank=True, max_length=500, verbose_name='نص الشريط العلوي')),
                ('top_bar_enabled', models.BooleanField(default=True, verbose_name='إظهار الشريط العلوي')),
                ('header_bg_color', models.CharField(default='#1a2538', max_length=20, verbose_name='لون خلفية الهيدر')),
                ('header_text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='لون نص الهيدر')),
                ('top_bar_bg_color', models.CharField(default='#2c3e50', max_length=20, verbose_name='لون خلفية الشريط العلوي')),
                ('show_search', models.BooleanField(default=True, verbose_name='إظهار البحث')),
                ('show_cart', models.BooleanField(default=True, verbose_name='إظهار السلة')),
                ('show_wishlist', models.BooleanField(default=True, verbose_name='إظهار المفضلة')),
                ('show_account', models.BooleanField(default=True, verbose_name='إظهار الحساب')),
                ('show_language', models.BooleanField(default=False, verbose_name='إظهار تبديل اللغة')),
                ('sticky_header', models.BooleanField(default=True, verbose_name='هيدر ثابت عند التمرير')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الهيدر',
                'verbose_name_plural': 'إعدادات الهيدر',
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('sending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='عدد المستلمين')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تم الإرسال')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='تم الفتح')),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='تم النقر')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حملة النشرة',
                'verbose_name_plural': 'حملات النشرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إلغاء الاشتراك')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='المصدر')),
            ],
            options={
                'verbose_name': 'مشترك النشرة',
                'verbose_name_plural': 'مشتركي النشرة',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('countries', models.JSONField(default=list, verbose_name='الدول')),
                ('cities', models.JSONField(blank=True, default=list, verbose_name='المدن')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'منطقة الشحن',
                'verbose_name_plural': 'مناطق الشحن',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(max_length=500, verbose_name='الرابط')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='فتح في نافذة جديدة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ecommerce.footercolumn', verbose_name='العمود')),
            ],
            options={
                'verbose_name': 'رابط الفوتر',
                'verbose_name_plural': 'روابط الفوتر',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(max_length=500, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة FontAwesome')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='فتح في نافذة جديدة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ecommerce.headerlink', verbose_name='الرابط الأب')),
            ],
            options={
                'verbose_name': 'رابط الهيدر',
                'verbose_name_plural': 'روابط الهيدر',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='العنوان الفرعي')),
                ('section_type', models.CharField(choices=[('featured_products', 'منتجات مميزة'), ('new_arrivals', 'وصل حديثاً'), ('best_sellers', 'الأكثر مبيعاً'), ('on_sale', 'عروض وخصومات'), ('category_products', 'منتجات فئة محددة'), ('custom_products', 'منتجات مخصصة'), ('banner', 'بانر'), ('categories_grid', 'شبكة الفئات'), ('brands', 'العلامات التجارية'), ('testimonials', 'آراء العملاء'), ('custom_html', 'HTML مخصص')], max_length=50, verbose_name='نوع القسم')),
                ('display_style', models.CharField(choices=[('grid', 'شبكة'), ('slider', 'سلايدر'), ('carousel', 'كاروسيل'), ('list', 'قائمة')], default='grid', max_length=20, verbose_name='نمط العرض')),
                ('products_count', models.PositiveIntegerField(default=8, verbose_name='عدد المنتجات')),
                ('custom_html', models.TextField(blank=True, verbose_name='HTML مخصص')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('show_view_all', models.BooleanField(default=True, verbose_name='إظهار رابط عرض الكل')),
                ('view_all_url', models.CharField(blank=True, max_length=500, verbose_name='رابط عرض الكل')),
                ('bg_color', models.CharField(blank=True, max_length=20, verbose_name='لون الخلفية')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/sections/', verbose_name='صورة الخلفية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'قسم الصفحة الرئيسية',
                'verbose_name_plural': 'أقسام الصفحة الرئيسية',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('show_icon', models.BooleanField(default=True, verbose_name='إظهار الأيقونة')),
                ('custom_icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة مخصصة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'فئة الشريط الجانبي',
                'verbose_name_plural': 'فئات الشريط الجانبي',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض')),
                ('quantity_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الكمية')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='الكمية المباعة')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.flashsale', verbose_name='العرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.onlineproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج العرض',
                'verbose_name_plural': 'منتجات العرض',
                'unique_together': {('flash_sale', 'product')},
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.onlineproduct', verbose_name='المنتج')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='ecommerce.homepagesection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'منتج القسم',
                'verbose_name_plural': 'منتجات القسم',
                'ordering': ['sort_order'],
                'unique_together': {('section', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('flat', 'ثابت'), ('weight', 'حسب الوزن'), ('price', 'حسب قيمة الطلب')], default='flat', max_length=20, verbose_name='نوع السعر')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السعر الثابت')),
                ('weight_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر الكيلو')),
                ('min_order_free', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للشحن المجاني')),
                ('delivery_time_min', models.PositiveIntegerField(default=1, verbose_name='أقل وقت توصيل (أيام)')),
                ('delivery_time_max', models.PositiveIntegerField(default=3, verbose_name='أقصى وقت توصيل (أيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.shippingcompany', verbose_name='شركة الشحن')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ecommerce.shippingzone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'سعر الشحن',
                'verbose_name_plural': 'أسعار الشحن',
                'unique_together': {('zone', 'company')},
            },
        ),
    ]
