# Generated by Django 5.2.5 on 2025-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_flashsale_footercolumn_footersettings_headersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', max_length=7, verbose_name='لون التمييز'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون الخلفية'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='button_color',
            field=models.CharField(default='#0ea5e9', max_length=7, verbose_name='لون الأزرار'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون نص الأزرار'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='footer_bg_color',
            field=models.CharField(default='#111827', max_length=7, verbose_name='لون خلفية الفوتر'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='footer_text_color',
            field=models.CharField(default='#9ca3af', max_length=7, verbose_name='لون نص الفوتر'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='header_bg_color',
            field=models.CharField(default='#1e293b', max_length=7, verbose_name='لون خلفية الهيدر'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='header_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون نص الهيدر'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='primary_color',
            field=models.CharField(default='#0ea5e9', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='sale_badge_color',
            field=models.CharField(default='#ef4444', max_length=7, verbose_name='لون شارة التخفيض'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='secondary_color',
            field=models.CharField(default='#64748b', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='text_color',
            field=models.CharField(default='#1e293b', max_length=7, verbose_name='لون النص'),
        ),
    ]
