# Generated by Django 5.2.5 on 2025-12-23 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_add_color_palette'),
        ('inventory', '0022_warranty_system'),
        ('sales', '0026_add_showroom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الضمان')),
                ('description', models.TextField(blank=True, verbose_name='وصف الضمان')),
                ('duration', models.PositiveIntegerField(default=12, verbose_name='مدة الضمان')),
                ('duration_unit', models.CharField(choices=[('days', 'أيام'), ('months', 'أشهر'), ('years', 'سنوات')], default='months', max_length=10, verbose_name='وحدة المدة')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('coverage', models.TextField(blank=True, verbose_name='ما يغطيه الضمان')),
                ('exclusions', models.TextField(blank=True, verbose_name='ما لا يغطيه الضمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('requires_registration', models.BooleanField(default=True, verbose_name='يتطلب تسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سياسة الضمان',
                'verbose_name_plural': 'سياسات الضمان',
            },
        ),
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_code', models.CharField(max_length=50, unique=True, verbose_name='رمز الضمان')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='ecommerce/warranty/qr/', verbose_name='كود QR')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي للمنتج')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الضمان')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الضمان')),
                ('status', models.CharField(choices=[('pending', 'في انتظار التفعيل'), ('active', 'مفعل'), ('expired', 'منتهي'), ('claimed', 'تم المطالبة'), ('void', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_warranties', to=settings.AUTH_USER_MODEL, verbose_name='فُعِّل بواسطة')),
                ('inventory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cards', to='inventory.product', verbose_name='منتج المخزون')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='ecommerce.order', verbose_name='طلب المتجر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cards', to='ecommerce.onlineproduct', verbose_name='المنتج الإلكتروني')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='sales.invoice', verbose_name='فاتورة المبيعات')),
                ('warranty_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='ecommerce.productwarranty', verbose_name='سياسة الضمان')),
            ],
            options={
                'verbose_name': 'بطاقة ضمان',
                'verbose_name_plural': 'بطاقات الضمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('repair', 'إصلاح'), ('replacement', 'استبدال'), ('refund', 'استرداد')], default='repair', max_length=20, verbose_name='نوع المطالبة')),
                ('issue_description', models.TextField(verbose_name='وصف المشكلة')),
                ('issue_images', models.ImageField(blank=True, null=True, upload_to='ecommerce/warranty/claims/', verbose_name='صور المشكلة')),
                ('contact_name', models.CharField(max_length=200, verbose_name='اسم جهة الاتصال')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('pickup_address', models.TextField(blank=True, verbose_name='عنوان الاستلام')),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('in_repair', 'قيد الإصلاح'), ('replaced', 'تم الاستبدال'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='submitted', max_length=20, verbose_name='الحالة')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى')),
                ('warranty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ecommerce.warrantycard', verbose_name='بطاقة الضمان')),
            ],
            options={
                'verbose_name': 'مطالبة ضمان',
                'verbose_name_plural': 'مطالبات الضمان',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecommerce/warranty/claims/', verbose_name='الصورة')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='ecommerce.warrantyclaim', verbose_name='المطالبة')),
            ],
            options={
                'verbose_name': 'صورة مطالبة',
                'verbose_name_plural': 'صور المطالبات',
            },
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('customer_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('warranty_code_entered', models.CharField(max_length=50, verbose_name='رمز الضمان المدخل')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الفاتورة')),
                ('invoice_image', models.ImageField(upload_to='ecommerce/warranty/invoices/', verbose_name='صورة الفاتورة')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('product_serial', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/warranty/products/', verbose_name='صورة المنتج')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_reviews', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_registrations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('warranty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ecommerce.warrantycard', verbose_name='بطاقة الضمان')),
            ],
            options={
                'verbose_name': 'تسجيل ضمان',
                'verbose_name_plural': 'تسجيلات الضمان',
                'ordering': ['-created_at'],
            },
        ),
    ]
