# Generated by Django 5.2.5 on 2025-12-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_warranty_system'),
        ('inventory', '0025_add_ecommerce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='inventory_category',
            field=models.ForeignKey(blank=True, help_text='ربط هذه الفئة بفئة من المخزون لمزامنة المنتجات تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_categories', to='inventory.category', verbose_name='فئة المخزون المرتبطة'),
        ),
    ]
