# Generated by Django 5.2.5 on 2025-12-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_add_inventory_category_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العلامة التجارية')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='الرابط')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecommerce/brands/', verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('is_featured', models.BooleanField(default=False, verbose_name='عرض في الصفحة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
