# Generated by Django 5.2.5 on 2026-01-23 16:12

import django.db.models.deletion
# import fernet_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_add_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesettings',
            name='tax_registration_number',
            field=models.CharField(blank=True, help_text='رقم التسجيل الضريبي للشركة', max_length=50, verbose_name='رقم التسجيل الضريبي'),
        ),
        migrations.AddField(
            model_name='ecommercesettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('14.00'), help_text='ضريبة القيمة المضافة المصرية (14%)', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إتمام الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_callback_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات Callback'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='رسوم بوابة الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='الرقم المرجعي'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_transaction_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='رقم المعاملة'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce.paymentgateway', verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='ecommercesettings',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='مصر', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('tap', 'Tap Payments'), ('moyasar', 'Moyasar'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('myfatoorah', 'MyFatoorah'), ('payfort', 'PayFort'), ('telr', 'Telr'), ('paymob_card', 'Paymob - البطاقات'), ('paymob_wallet', 'Paymob - محافظ موبايل'), ('paymob_valu', 'Paymob - تقسيط ValU'), ('paymob_souhoola', 'Paymob - تقسيط سهولة'), ('fawry', 'فوري Fawry'), ('instapay', 'InstaPay'), ('cod', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي')], max_length=50, unique=True, verbose_name='نوع البوابة'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Key للاختبار'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_api_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Secret للاختبار'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Secret'),
        ),
    ]
