# Generated by Django 5.2.5 on 2026-01-24 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_ecommercesettings_tax_registration_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineproduct',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السعر الأصلي قبل الخصم للمقارنة', max_digits=10, null=True, verbose_name='سعر المقارنة'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب الفئة في القوائم', verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='صورة رئيسية'),
        ),
        migrations.AlterField(
            model_name='onlineproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_products', to='ecommerce.productcategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecommerce_push_subscription',
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'تأكيد الطلب'), ('order_shipped', 'تم الشحن'), ('order_delivered', 'تم التوصيل'), ('abandoned_cart', 'سلة متروكة'), ('price_drop', 'انخفاض السعر'), ('back_in_stock', 'متوفر مجدداً'), ('promotion', 'عرض ترويجي'), ('flash_sale', 'تخفيضات سريعة')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ecommerce.pushsubscription')),
            ],
            options={
                'db_table': 'ecommerce_push_notification_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
