# Generated by Django 5.2.5 on 2026-01-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_onlineproduct_compare_price_productcategory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_products', to='ecommerce.brand', verbose_name='العلامة التجارية'),
        ),
        migrations.AddField(
            model_name='onlineproduct',
            name='slug',
            field=models.SlugField(allow_unicode=False, blank=True, null=True, max_length=255, db_index=True, verbose_name='الرابط'),
        ),
    ]
