# Generated by Django 5.2.9 on 2026-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_add_slug_brand_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineproduct',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='الرابط'),
        ),
    ]
