# Generated by Django 5.2.9 on 2026-02-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_onlineproduct_slug'),
        ('inventory', '0041_alter_supplierproductprice_purchase_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineproduct',
            name='inventory_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_product', to='inventory.product', verbose_name='المنتج في المخزون'),
        ),
    ]
