# Generated by Django 5.2.5 on 2026-02-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_allow_standalone_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='PushNotificationLog',
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
