# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سمة أصوات',
                'verbose_name_plural': 'سمات الأصوات',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_type', models.CharField(max_length=50, verbose_name='نوع الصوت')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التشغيل')),
                ('was_muted', models.BooleanField(default=False, verbose_name='كان مكتوم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل صوت',
                'verbose_name_plural': 'سجل الأصوات',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSoundPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='تفعيل الأصوات')),
                ('master_volume', models.IntegerField(default=80, verbose_name='مستوى الصوت العام')),
                ('enable_new_order', models.BooleanField(default=True, verbose_name='صوت الطلب الجديد')),
                ('enable_payment', models.BooleanField(default=True, verbose_name='صوت الدفع')),
                ('enable_low_stock', models.BooleanField(default=True, verbose_name='صوت المخزون المنخفض')),
                ('enable_approval', models.BooleanField(default=True, verbose_name='صوت الموافقات')),
                ('enable_tasks', models.BooleanField(default=True, verbose_name='صوت المهام')),
                ('enable_messages', models.BooleanField(default=True, verbose_name='صوت الرسائل')),
                ('enable_reminders', models.BooleanField(default=True, verbose_name='صوت التذكيرات')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='صوت الدردشة')),
                ('enable_calls', models.BooleanField(default=True, verbose_name='صوت المكالمات')),
                ('do_not_disturb', models.BooleanField(default=False, verbose_name='وضع عدم الإزعاج')),
                ('dnd_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية عدم الإزعاج')),
                ('dnd_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية عدم الإزعاج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sound_notifications.soundtheme', verbose_name='السمة المختارة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات صوت المستخدم',
                'verbose_name_plural': 'تفضيلات أصوات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='NotificationSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_type', models.CharField(choices=[('new_order', 'طلب جديد'), ('new_invoice', 'فاتورة جديدة'), ('payment_received', 'دفعة مستلمة'), ('low_stock', 'مخزون منخفض'), ('approval_needed', 'موافقة مطلوبة'), ('task_assigned', 'مهمة جديدة'), ('message_received', 'رسالة جديدة'), ('reminder', 'تذكير'), ('error', 'خطأ'), ('success', 'نجاح'), ('warning', 'تحذير'), ('chat', 'دردشة'), ('call', 'مكالمة'), ('meeting', 'اجتماع'), ('birthday', 'عيد ميلاد'), ('contract_expiry', 'انتهاء عقد'), ('custom', 'مخصص')], max_length=50, verbose_name='نوع الصوت')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصوت')),
                ('sound_file', models.FileField(upload_to='sounds/notifications/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'webm'])], verbose_name='ملف الصوت')),
                ('volume', models.IntegerField(default=80, verbose_name='مستوى الصوت')),
                ('duration', models.FloatField(default=1.0, verbose_name='المدة (ثواني)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='sound_notifications.soundtheme', verbose_name='السمة')),
            ],
            options={
                'verbose_name': 'صوت إشعار',
                'verbose_name_plural': 'أصوات الإشعارات',
                'ordering': ['theme', 'sound_type'],
                'unique_together': {('theme', 'sound_type')},
            },
        ),
    ]
