# Generated by Django 5.2.5 on 2025-12-24 03:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0017_add_showroom_field'),
        ('sales', '0026_add_showroom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفئة')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_exempt', models.BooleanField(default=False, verbose_name='معفى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('eta_code', models.CharField(blank=True, max_length=20, verbose_name='كود مصلحة الضرائب')),
            ],
            options={
                'verbose_name': 'فئة ضريبية',
                'verbose_name_plural': 'الفئات الضريبية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الإعفاء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('exemption_type', models.CharField(choices=[('product', 'منتج معفى'), ('customer', 'عميل معفى'), ('transaction', 'معاملة معفاة'), ('sector', 'قطاع معفى')], max_length=50, verbose_name='نوع الإعفاء')),
                ('legal_reference', models.CharField(blank=True, help_text='رقم المادة أو القرار', max_length=200, verbose_name='المرجع القانوني')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعفاء ضريبي',
                'verbose_name_plural': 'الإعفاءات الضريبية',
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_registration_number', models.CharField(help_text='رقم التسجيل في مصلحة الضرائب', max_length=50, verbose_name='رقم التسجيل الضريبي')),
                ('tax_file_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الملف الضريبي')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة الافتراضية %')),
                ('einvoice_enabled', models.BooleanField(default=False, verbose_name='تفعيل الفاتورة الإلكترونية')),
                ('einvoice_api_key', models.CharField(blank=True, max_length=500, verbose_name='مفتاح API للفاتورة الإلكترونية')),
                ('einvoice_client_id', models.CharField(blank=True, max_length=200, verbose_name='Client ID')),
                ('einvoice_client_secret', models.CharField(blank=True, max_length=500, verbose_name='Client Secret')),
                ('einvoice_environment', models.CharField(choices=[('production', 'إنتاج'), ('preprod', 'اختبار')], default='preprod', max_length=20, verbose_name='بيئة العمل')),
                ('exemption_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='المبيعات السنوية التي تعفى من الضريبة إذا كانت أقل من هذا الحد', max_digits=15, verbose_name='حد الإعفاء السنوي')),
                ('is_exempt', models.BooleanField(default=False, help_text='هل الشركة معفاة من ضريبة القيمة المضافة؟', verbose_name='معفى من الضريبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الضرائب',
                'verbose_name_plural': 'إعدادات الضرائب',
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('internal_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الداخلي')),
                ('invoice_type', models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], max_length=20, verbose_name='نوع الفاتورة')),
                ('tax_type', models.CharField(choices=[('taxable', 'خاضع للضريبة'), ('exempt', 'معفى'), ('zero_rated', 'صفري')], default='taxable', max_length=20, verbose_name='نوع الضريبة')),
                ('invoice_date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('partner_name', models.CharField(max_length=200, verbose_name='اسم العميل/المورد')),
                ('partner_tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي للعميل/المورد')),
                ('partner_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي قبل الضريبة')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الخصم')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي شامل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في انتظار الإرسال'), ('submitted', 'تم الإرسال'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('uuid', models.CharField(blank=True, max_length=100, verbose_name='UUID')),
                ('submission_id', models.CharField(blank=True, max_length=100, verbose_name='رقم الإرسال')),
                ('long_id', models.CharField(blank=True, max_length=200, verbose_name='Long ID')),
                ('hash_key', models.CharField(blank=True, max_length=500, verbose_name='Hash Key')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_invoices', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices', to='sales.invoice', verbose_name='فاتورة المبيعات')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices', to='purchases.purchasebill', verbose_name='فاتورة المشتريات')),
            ],
            options={
                'verbose_name': 'فاتورة ضريبية',
                'verbose_name_plural': 'الفواتير الضريبية',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50, verbose_name='كود الصنف')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('item_description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الخصم')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الضريبة')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي البند')),
                ('eta_item_code', models.CharField(blank=True, max_length=50, verbose_name='كود ETA')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='taxes.taxinvoice', verbose_name='الفاتورة')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.taxcategory', verbose_name='فئة الضريبة')),
            ],
            options={
                'verbose_name': 'بند فاتورة ضريبية',
                'verbose_name_plural': 'بنود الفاتورة الضريبية',
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('annually', 'سنوي')], default='monthly', max_length=20, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('due_date', models.DateField(verbose_name='تاريخ استحقاق الإقرار')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('filed', 'تم تقديم الإقرار')], default='open', max_length=20, verbose_name='الحالة')),
                ('total_output_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='إجمالي ضريبة المخرجات')),
                ('total_input_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='إجمالي ضريبة المدخلات')),
                ('net_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='موجب = مستحق علينا، سالب = لنا', max_digits=15, verbose_name='صافي الضريبة')),
                ('filed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تقديم الإقرار')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم مرجع الإقرار')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='قُدم بواسطة')),
            ],
            options={
                'verbose_name': 'فترة ضريبية',
                'verbose_name_plural': 'الفترات الضريبية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('vat', 'ضريبة قيمة مضافة'), ('income', 'ضريبة دخل'), ('withholding', 'ضريبة خصم'), ('other', 'أخرى')], default='vat', max_length=20, verbose_name='نوع الضريبة')),
                ('payment_date', models.DateField(verbose_name='تاريخ السداد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم إيصال السداد')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='البنك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='taxes.taxperiod', verbose_name='الفترة الضريبية')),
            ],
            options={
                'verbose_name': 'سداد ضريبة',
                'verbose_name_plural': 'سداد الضرائب',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['invoice_type', 'status'], name='taxes_taxin_invoice_7d2d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['invoice_date'], name='taxes_taxin_invoice_531141_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['partner_tax_id'], name='taxes_taxin_partner_0e1475_idx'),
        ),
    ]
