# Generated by Django 5.2.5 on 2025-12-09 00:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_alter_activity_id_alter_activitytype_id_and_more'),
        ('inventory', '0018_printerconfiguration_and_more'),
        ('sales', '0022_salesorder_salesorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المتجر')),
                ('store_url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='رابط المتجر')),
                ('consumer_key', models.CharField(max_length=500, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(max_length=500, verbose_name='Consumer Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('auto_sync_products', models.BooleanField(default=True, verbose_name='مزامنة المنتجات تلقائياً')),
                ('auto_sync_orders', models.BooleanField(default=True, verbose_name='مزامنة الطلبات تلقائياً')),
                ('auto_sync_inventory', models.BooleanField(default=True, verbose_name='مزامنة المخزون تلقائياً')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15, verbose_name='فترة المزامنة (دقائق)')),
                ('last_product_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة منتجات')),
                ('last_order_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة طلبات')),
                ('last_inventory_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة مخزون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('default_customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customertype', verbose_name='نوع العميل الافتراضي')),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='موقع المخزون الافتراضي')),
            ],
            options={
                'verbose_name': 'إعداد WooCommerce',
                'verbose_name_plural': 'إعدادات WooCommerce',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('product_push', 'دفع منتج'), ('product_pull', 'سحب منتج'), ('inventory_push', 'دفع مخزون'), ('inventory_pull', 'سحب مخزون'), ('order_pull', 'سحب طلب'), ('customer_pull', 'سحب عميل')], max_length=20, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('success', 'نجح'), ('failed', 'فشل'), ('partial', 'جزئي')], max_length=20, verbose_name='الحالة')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات')),
                ('records_success', models.PositiveIntegerField(default=0, verbose_name='الناجحة')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='الفاشلة')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('error_details', models.TextField(blank=True, verbose_name='تفاصيل الأخطاء')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المدة (ثواني)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'سجل مزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='woocommerce_started_027e9d_idx'), models.Index(fields=['status'], name='woocommerce_status_2fb8a3_idx'), models.Index(fields=['sync_type'], name='woocommerce_sync_ty_68e743_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_product_id', models.PositiveIntegerField(verbose_name='معرف WooCommerce')),
                ('woo_sku', models.CharField(blank=True, max_length=200, verbose_name='SKU في WooCommerce')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='المزامنة مفعلة')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='مزامنة المخزون')),
                ('sync_price', models.BooleanField(default=True, verbose_name='مزامنة السعر')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('erp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='منتج ERP')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'ربط منتج',
                'verbose_name_plural': 'ربط المنتجات',
                'ordering': ['-created_at'],
                'unique_together': {('config', 'erp_product'), ('config', 'woo_product_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_order_id', models.PositiveIntegerField(verbose_name='رقم طلب WooCommerce')),
                ('woo_order_number', models.CharField(max_length=200, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('woo_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات WooCommerce')),
                ('woo_created_at', models.DateTimeField(verbose_name='تاريخ الطلب في WooCommerce')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المزامنة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('erp_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer', verbose_name='عميل ERP')),
                ('erp_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice', verbose_name='فاتورة ERP')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'ربط طلب',
                'verbose_name_plural': 'ربط الطلبات',
                'ordering': ['-woo_created_at'],
                'indexes': [models.Index(fields=['-woo_created_at'], name='woocommerce_woo_cre_77f566_idx'), models.Index(fields=['status'], name='woocommerce_status_91552f_idx')],
                'unique_together': {('config', 'woo_order_id')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_customer_id', models.PositiveIntegerField(verbose_name='معرف عميل WooCommerce')),
                ('woo_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('erp_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='عميل ERP')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر')),
            ],
            options={
                'verbose_name': 'ربط عميل',
                'verbose_name_plural': 'ربط العملاء',
                'ordering': ['-created_at'],
                'unique_together': {('config', 'erp_customer'), ('config', 'woo_customer_id')},
            },
        ),
    ]
