# Generated by Django 5.2.5 on 2025-12-09 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_activity_customer_alter_activity_opportunity_and_more'),
        ('inventory', '0018_printerconfiguration_and_more'),
        ('sales', '0022_salesorder_salesorderline_and_more'),
        ('woocommerce_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermapping',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mappings', to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='customermapping',
            name='erp_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woo_mappings', to='crm.customer', verbose_name='عميل ERP'),
        ),
        migrations.AlterField(
            model_name='ordermapping',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mappings', to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='ordermapping',
            name='erp_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woo_orders', to='crm.customer', verbose_name='عميل ERP'),
        ),
        migrations.AlterField(
            model_name='ordermapping',
            name='erp_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woo_mappings', to='sales.invoice', verbose_name='فاتورة ERP'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='woocommerce_integration.woocommerceconfig', verbose_name='المتجر'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='erp_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woo_mappings', to='inventory.product', verbose_name='منتج ERP'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['woo_product_id'], name='woocommerce_woo_pro_6f3d94_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['woo_sku'], name='woocommerce_woo_sku_db9b81_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['sync_enabled', 'last_synced'], name='woocommerce_sync_en_28ff29_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceconfig',
            index=models.Index(fields=['is_active', 'is_default'], name='woocommerce_is_acti_389645_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceconfig',
            index=models.Index(fields=['last_product_sync'], name='woocommerce_last_pr_70f8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceconfig',
            index=models.Index(fields=['last_order_sync'], name='woocommerce_last_or_30eb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceconfig',
            index=models.Index(fields=['last_inventory_sync'], name='woocommerce_last_in_a1abb2_idx'),
        ),
    ]
