# Generated by Django 5.2.5 on 2026-02-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_add_is_active_to_supplier'),
        ('woocommerce_integration', '0002_alter_customermapping_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermapping',
            name='erp_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woo_mappings', to='partners.customer', verbose_name='عميل ERP'),
        ),
        migrations.AlterField(
            model_name='ordermapping',
            name='erp_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woo_orders', to='partners.customer', verbose_name='عميل ERP'),
        ),
        migrations.AlterField(
            model_name='woocommerceconfig',
            name='default_customer_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نوع العميل الافتراضي'),
        ),
    ]
