# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0025_alter_journalentry_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(verbose_name='تاريخ الكشف')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الختامي')),
                ('file', models.FileField(blank=True, upload_to='bank_statements/', verbose_name='ملف الكشف')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('in_progress', 'قيد المطابقة'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستيراد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounting.bank', verbose_name='الحساب البنكي')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_statements', to=settings.AUTH_USER_MODEL, verbose_name='مستورد بواسطة')),
            ],
            options={
                'verbose_name': 'كشف حساب بنكي',
                'verbose_name_plural': 'كشوف الحسابات البنكية',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='تاريخ العملية')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='تاريخ القيمة')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الرصيد')),
                ('is_matched', models.BooleanField(default=False, verbose_name='مطابق')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المطابقة')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_lines', to=settings.AUTH_USER_MODEL, verbose_name='طابق بواسطة')),
                ('matched_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_lines', to='accounting.journalentry', verbose_name='القيد المطابق')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_reconciliation.bankstatement', verbose_name='الكشف')),
            ],
            options={
                'verbose_name': 'سطر كشف بنكي',
                'verbose_name_plural': 'سطور كشوف البنك',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(verbose_name='تاريخ المطابقة')),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رصيد الدفاتر')),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رصيد البنك')),
                ('adjusted_book_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='رصيد الدفاتر المعدل')),
                ('adjusted_bank_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='رصيد البنك المعدل')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الفرق')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('approved', 'معتمدة')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.bank', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مطابقة بنكية',
                'verbose_name_plural': 'المطابقات البنكية',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('outstanding_check', 'شيك صادر لم يُصرف'), ('deposit_in_transit', 'إيداع في الطريق'), ('bank_charge', 'عمولة بنكية'), ('bank_interest', 'فوائد بنكية'), ('error_correction', 'تصحيح خطأ'), ('other', 'أخرى')], max_length=30, verbose_name='النوع')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('affects_book', models.BooleanField(default=False, verbose_name='يؤثر على الدفاتر')),
                ('affects_bank', models.BooleanField(default=True, verbose_name='يؤثر على البنك')),
                ('adjustment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_adjustments', to='accounting.journalentry', verbose_name='قيد التسوية')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bank_reconciliation.reconciliation', verbose_name='المطابقة')),
            ],
            options={
                'verbose_name': 'بند مطابقة',
                'verbose_name_plural': 'بنود المطابقة',
            },
        ),
    ]
