# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_enabled', models.BooleanField(default=True, verbose_name='التشفير مفعل')),
                ('encryption_algorithm', models.CharField(default='AES-256', max_length=20, verbose_name='خوارزمية التشفير')),
                ('compression_enabled', models.BooleanField(default=True, verbose_name='الضغط مفعل')),
                ('compression_level', models.IntegerField(default=6, verbose_name='مستوى الضغط')),
                ('excluded_paths', models.JSONField(default=list, verbose_name='المسارات المستثناة')),
                ('excluded_extensions', models.JSONField(default=list, verbose_name='الامتدادات المستثناة')),
                ('default_notify_emails', models.JSONField(default=list, verbose_name='البريد الافتراضي للإشعارات')),
                ('default_retention_days', models.IntegerField(default=30, verbose_name='أيام الاحتفاظ الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النسخ الاحتياطي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('provider_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('aws_s3', 'Amazon S3'), ('azure_blob', 'Azure Blob'), ('ftp', 'FTP Server'), ('local', 'Local Storage')], max_length=30, verbose_name='نوع المزود')),
                ('credentials', models.JSONField(default=dict, verbose_name='بيانات الاعتماد')),
                ('config', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('folder_path', models.CharField(default='/backups', max_length=500, verbose_name='مسار المجلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضي')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('connection_status', models.BooleanField(default=False, verbose_name='حالة الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مزود سحابي',
                'verbose_name_plural': 'مزودون سحابيون',
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('backup_type', models.CharField(choices=[('full', 'كامل'), ('incremental', 'تزايدي'), ('differential', 'تفاضلي')], default='full', max_length=20, verbose_name='نوع النسخ')),
                ('frequency', models.CharField(choices=[('hourly', 'كل ساعة'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='التكرار')),
                ('time_of_day', models.TimeField(default='02:00', verbose_name='وقت التنفيذ')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='يوم الأسبوع')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='يوم الشهر')),
                ('include_database', models.BooleanField(default=True, verbose_name='قاعدة البيانات')),
                ('include_media', models.BooleanField(default=True, verbose_name='ملفات الوسائط')),
                ('include_static', models.BooleanField(default=False, verbose_name='الملفات الثابتة')),
                ('include_logs', models.BooleanField(default=False, verbose_name='سجلات النظام')),
                ('custom_paths', models.JSONField(default=list, verbose_name='مسارات مخصصة')),
                ('retention_days', models.IntegerField(default=30, verbose_name='أيام الاحتفاظ')),
                ('max_backups', models.IntegerField(default=10, verbose_name='أقصى عدد نسخ')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='إشعار عند النجاح')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='إشعار عند الفشل')),
                ('notification_emails', models.JSONField(default=list, verbose_name='البريد الإلكتروني للإشعارات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cloud_backup.cloudprovider', verbose_name='مزود التخزين')),
            ],
            options={
                'verbose_name': 'جدول نسخ احتياطي',
                'verbose_name_plural': 'جداول النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('backup_type', models.CharField(default='full', max_length=20, verbose_name='نوع النسخ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('progress', models.IntegerField(default=0, verbose_name='التقدم %')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('files_count', models.IntegerField(default=0, verbose_name='عدد الملفات')),
                ('includes_database', models.BooleanField(default=True, verbose_name='يتضمن قاعدة البيانات')),
                ('includes_media', models.BooleanField(default=True, verbose_name='يتضمن الوسائط')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='مشفر')),
                ('encryption_key_hash', models.CharField(blank=True, max_length=64, verbose_name='تجزئة مفتاح التشفير')),
                ('log', models.TextField(blank=True, verbose_name='السجل')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='المدة (ثانية)')),
                ('restore_count', models.IntegerField(default=0, verbose_name='عدد مرات الاستعادة')),
                ('last_restored', models.DateTimeField(blank=True, null=True, verbose_name='آخر استعادة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='cloud_backup.backupschedule', verbose_name='الجدول')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='cloud_backup.cloudprovider', verbose_name='مزود التخزين')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('restore_database', models.BooleanField(default=True, verbose_name='استعادة قاعدة البيانات')),
                ('restore_media', models.BooleanField(default=True, verbose_name='استعادة الوسائط')),
                ('restore_to_path', models.CharField(blank=True, max_length=500, verbose_name='استعادة إلى')),
                ('log', models.TextField(blank=True, verbose_name='السجل')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_points', to='cloud_backup.backup', verbose_name='النسخة الاحتياطية')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بدأ بواسطة')),
            ],
            options={
                'verbose_name': 'نقطة استعادة',
                'verbose_name_plural': 'نقاط الاستعادة',
                'ordering': ['-created_at'],
            },
        ),
    ]
