# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('source_type', models.CharField(choices=[('model', 'نموذج Django'), ('sql', 'استعلام SQL'), ('api', 'واجهة API'), ('file', 'ملف')], max_length=20, verbose_name='نوع المصدر')),
                ('sql_query', models.TextField(blank=True, verbose_name='استعلام SQL')),
                ('api_url', models.URLField(blank=True, verbose_name='رابط API')),
                ('api_method', models.CharField(default='GET', max_length=10, verbose_name='طريقة الطلب')),
                ('api_headers', models.JSONField(default=dict, verbose_name='الرؤوس')),
                ('file', models.FileField(blank=True, upload_to='report_builder/sources/', verbose_name='الملف')),
                ('available_fields', models.JSONField(default=list, verbose_name='الحقول المتاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='النموذج')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مصدر بيانات',
                'verbose_name_plural': 'مصادر البيانات',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('report_type', models.CharField(choices=[('table', 'جدول'), ('chart', 'رسم بياني'), ('pivot', 'جدول محوري'), ('card', 'بطاقات'), ('mixed', 'مختلط')], default='table', max_length=20, verbose_name='نوع التقرير')),
                ('config', models.JSONField(default=dict, verbose_name='التكوين')),
                ('filters', models.JSONField(default=list, verbose_name='الفلاتر')),
                ('sorting', models.JSONField(default=list, verbose_name='الترتيب')),
                ('grouping', models.JSONField(default=list, verbose_name='التجميع')),
                ('selected_columns', models.JSONField(default=list, verbose_name='الأعمدة')),
                ('calculations', models.JSONField(default=list, verbose_name='الحسابات')),
                ('styling', models.JSONField(default=dict, verbose_name='التنسيق')),
                ('export_config', models.JSONField(default=dict, verbose_name='إعدادات التصدير')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('schedule_config', models.JSONField(default=dict, verbose_name='تكوين الجدول')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='آخر مشاهدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_created_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report_builder.datasource', verbose_name='مصدر البيانات')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشارك مع')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('parameters', models.JSONField(default=dict, verbose_name='المعلمات')),
                ('result_file', models.FileField(blank=True, upload_to='report_builder/results/', verbose_name='ملف النتيجة')),
                ('rows_count', models.IntegerField(default=0, verbose_name='عدد الصفوف')),
                ('execution_time', models.FloatField(default=0, verbose_name='وقت التنفيذ (ثانية)')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_report_executions', to=settings.AUTH_USER_MODEL, verbose_name='نفذ بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='report_builder.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تنفيذ تقرير',
                'verbose_name_plural': 'تنفيذات التقارير',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('preview_image', models.ImageField(blank=True, upload_to='report_builder/templates/', verbose_name='صورة المعاينة')),
                ('config', models.JSONField(default=dict, verbose_name='التكوين')),
                ('widgets_config', models.JSONField(default=list, verbose_name='تكوين العناصر')),
                ('is_system', models.BooleanField(default=False, verbose_name='قالب نظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('table', 'جدول'), ('bar_chart', 'رسم أعمدة'), ('line_chart', 'رسم خطي'), ('pie_chart', 'رسم دائري'), ('area_chart', 'رسم مساحة'), ('donut_chart', 'رسم دونات'), ('card', 'بطاقة'), ('gauge', 'مقياس'), ('map', 'خريطة'), ('text', 'نص'), ('image', 'صورة')], max_length=20, verbose_name='نوع العنصر')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموقع X')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموقع Y')),
                ('width', models.IntegerField(default=6, verbose_name='العرض')),
                ('height', models.IntegerField(default=4, verbose_name='الارتفاع')),
                ('config', models.JSONField(default=dict, verbose_name='التكوين')),
                ('data_config', models.JSONField(default=dict, verbose_name='تكوين البيانات')),
                ('styling', models.JSONField(default=dict, verbose_name='التنسيق')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='report_builder.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'عنصر تقرير',
                'verbose_name_plural': 'عناصر التقرير',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='يوم الأسبوع')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='يوم الشهر')),
                ('time_of_day', models.TimeField(verbose_name='وقت التنفيذ')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10, verbose_name='صيغة التصدير')),
                ('send_email', models.BooleanField(default=True, verbose_name='إرسال بالبريد')),
                ('email_recipients', models.JSONField(default=list, verbose_name='المستلمون')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع البريد')),
                ('email_body', models.TextField(blank=True, verbose_name='نص البريد')),
                ('save_to_storage', models.BooleanField(default=False, verbose_name='حفظ في التخزين')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الحفظ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='report_builder.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تقرير مجدول',
                'verbose_name_plural': 'التقارير المجدولة',
            },
        ),
    ]
