# Generated by Django 5.2.5 on 2025-08-17 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_issue_inventory_i_status_e12400_idx_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_life_days', models.PositiveIntegerField(default=0, verbose_name='مدة الصلاحية (أيام)')),
                ('default_size_text', models.CharField(blank=True, max_length=100, verbose_name='المقاس الافتراضي (مثال: 10x10 سم)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfg_profile', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'إعداد تصنيع المنتج',
                'verbose_name_plural': 'إعدادات تصنيع المنتجات',
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_serial', models.CharField(max_length=30, verbose_name='رقم تسلسلي')),
                ('barcode', models.CharField(max_length=20, unique=True, verbose_name='باركود القطعة')),
                ('manufacture_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التصنيع')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('size_text', models.CharField(blank=True, help_text='مثال: 10x10 سم أو 10x5 سم؛ قابل للتعديل يدويًا', max_length=100, verbose_name='المقاس')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_units', to='inventory.product', verbose_name='المنتج')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_units', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'وحدة منتج نهائي',
                'verbose_name_plural': 'وحدات منتجات نهائية',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['barcode'], name='production__barcode_69a18f_idx'), models.Index(fields=['product', 'production_order'], name='production__product_cf62e3_idx')],
            },
        ),
    ]
