# Generated by Django 5.2.5 on 2025-12-07 23:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employeeidcard_options_and_more'),
        ('inventory', '0018_printerconfiguration_and_more'),
        ('production', '0003_alter_billofmaterials_id_alter_bomitem_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProductionEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإنتاج')),
                ('shift', models.CharField(blank=True, max_length=50, verbose_name='الوردية')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المنتجة')),
                ('unit_of_measure', models.CharField(default='متر', max_length=20, verbose_name='وحدة القياس')),
                ('machine_code', models.CharField(blank=True, max_length=50, verbose_name='كود الماكينة')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='ساعات العمل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('inventory_transaction_created', models.BooleanField(default=False, verbose_name='تم إنشاء حركة مخزون')),
                ('inventory_transaction_id', models.IntegerField(blank=True, null=True, verbose_name='رقم حركة المخزون')),
                ('labor_cost_calculated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة العمالة المحسوبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='hr.employee', verbose_name='العامل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج/القماشة')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_production_entries', to='hr.employee', verbose_name='المشرف')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionworkcenter', verbose_name='مركز العمل')),
            ],
            options={
                'verbose_name': 'تسجيل إنتاج عامل',
                'verbose_name_plural': 'تسجيلات إنتاج العمال',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='production__employe_430bb3_idx'), models.Index(fields=['product', 'date'], name='production__product_7e77a6_idx'), models.Index(fields=['status'], name='production__status_97b343_idx'), models.Index(fields=['date', 'status'], name='production__date_1eff9f_idx')],
            },
        ),
    ]
