# Generated by Django 5.2.5 on 2025-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_workerproductionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerproductionentry',
            name='size_description',
            field=models.CharField('المقاس', max_length=50, blank=True),
        ),
    ]
