# Generated by Django 5.2.5 on 2025-12-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_workerproductionentry_size_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorderstage', verbose_name='مرحلة الإنتاج'),
        ),
        migrations.AlterField(
            model_name='productionalert',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder', verbose_name='أمر الإنتاج'),
        ),
        migrations.AlterField(
            model_name='productionalert',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionworkcenter', verbose_name='مركز العمل'),
        ),
    ]
