# Generated by ChatGPT on 2025-12-18
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_materialconsumption_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_stages', to='production.billofmaterials', verbose_name='قائمة المواد'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='stage_type',
            field=models.CharField(choices=[('cutting', 'تقطيع'), ('sewing', 'خياطة'), ('assembly', 'تجميع'), ('finishing', 'تشطيب'), ('quality', 'جودة'), ('maintenance', 'صيانة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المرحلة'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='standard_time',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='الوقت القياسي (ساعة/وحدة)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='work_centers',
            field=models.ManyToManyField(blank=True, related_name='production_stages', to='production.productionworkcenter', verbose_name='مراكز العمل'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='كود المرحلة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='operation_time',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='وقت العملية (دقيقة/وحدة)'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionworkcenter', verbose_name='مركز العمل'),
        ),
    ]
