# Generated by Django 5.2.5 on 2025-12-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_warranty_system'),
        ('inventory', '0023_product_unit_warranty'),
        ('partners', '0011_product_unit_warranty'),
        ('production', '0007_productionstage_fields'),
        ('sales', '0026_add_showroom_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='عنوان العميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد العميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='finished_units/invoices/', verbose_name='صورة فاتورة العميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البيع للعميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='customer_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع للعميل'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_finished_units', to='partners.partner', verbose_name='التاجر/الموزع'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='dealer_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_finished_units', to='sales.invoice', verbose_name='فاتورة التاجر'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='dealer_sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البيع للتاجر'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='dealer_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع للتاجر'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500, verbose_name='بيانات QR Code'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='finished_units/qr/', verbose_name='صورة QR Code'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='status',
            field=models.CharField(choices=[('produced', 'تم الإنتاج'), ('in_stock', 'في المخزن'), ('sold_to_dealer', 'مباع لتاجر'), ('sold_to_customer', 'مباع لعميل'), ('warranty_registered', 'ضمان مسجل'), ('warranty_claimed', 'مطالبة ضمان'), ('returned', 'مرتجع'), ('defective', 'معيب'), ('scrapped', 'خردة')], default='produced', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الضمان'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='warranty_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productwarranty', verbose_name='سياسة الضمان'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='warranty_registered',
            field=models.BooleanField(default=False, verbose_name='تم تسجيل الضمان'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='warranty_registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تسجيل الضمان'),
        ),
        migrations.AddField(
            model_name='finishedgoodunit',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الضمان'),
        ),
        migrations.AlterField(
            model_name='finishedgoodunit',
            name='barcode',
            field=models.CharField(max_length=30, unique=True, verbose_name='باركود القطعة'),
        ),
        migrations.AlterField(
            model_name='finishedgoodunit',
            name='unit_serial',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم تسلسلي'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodunit',
            index=models.Index(fields=['unit_serial'], name='production__unit_se_6b5144_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodunit',
            index=models.Index(fields=['status'], name='production__status_a2a3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodunit',
            index=models.Index(fields=['customer_phone'], name='production__custome_899c0a_idx'),
        ),
    ]
