# Generated by Django 5.2.5 on 2026-01-05 13:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_accounting__entry_t_abc123_idx_accounting__entry_t_bba407_idx_and_more'),
        ('branches', '0003_autoreplenishmentrule_showroomreplenishmentrequest_and_more'),
        ('inventory', '0025_add_ecommerce_fields'),
        ('production', '0008_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReorderPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الحد الأدنى')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='نقطة إعادة الطلب')),
                ('maximum_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الحد الأقصى')),
                ('economic_order_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية الاقتصادية للطلب (EOQ)')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='وقت التوريد (أيام)')),
                ('safety_stock_days', models.PositiveIntegerField(default=3, verbose_name='أيام المخزون الآمن')),
                ('auto_calculate', models.BooleanField(default=True, verbose_name='حساب تلقائي')),
                ('last_calculated', models.DateTimeField(blank=True, null=True, verbose_name='آخر حساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_point', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'نقطة إعادة الطلب',
                'verbose_name_plural': 'نقاط إعادة الطلب',
            },
        ),
        migrations.CreateModel(
            name='MRPPlanningModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخطة')),
                ('plan_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي')], default='monthly', max_length=20, verbose_name='نوع الخطة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='عدد الأوامر')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='عدد المنتجات')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='التكلفة التقديرية')),
                ('requirements_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات المتطلبات')),
                ('schedule_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الجدول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_plans', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'خطة MRP',
                'verbose_name_plural': 'خطط MRP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverheadAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('allocation_method', models.CharField(choices=[('labor_hours', 'ساعات العمل'), ('labor_cost', 'تكلفة العمالة'), ('material_cost', 'تكلفة المواد'), ('machine_hours', 'ساعات التشغيل'), ('units_produced', 'الوحدات المنتجة'), ('equal', 'بالتساوي')], max_length=20, verbose_name='طريقة التوزيع')),
                ('allocation_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قاعدة التوزيع')),
                ('allocation_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='معدل التوزيع')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الموزع')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overhead_allocations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overhead_allocations', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_allocations', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_allocations', to='production.productionworkcenter', verbose_name='مركز العمل')),
            ],
            options={
                'verbose_name': 'توزيع تكاليف إضافية',
                'verbose_name_plural': 'توزيعات التكاليف الإضافية',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CostVarianceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variance_type', models.CharField(choices=[('material_price', 'انحراف سعر المواد'), ('material_quantity', 'انحراف كمية المواد'), ('labor_rate', 'انحراف معدل العمالة'), ('labor_efficiency', 'انحراف كفاءة العمالة'), ('overhead_spending', 'انحراف إنفاق التكاليف الإضافية'), ('overhead_efficiency', 'انحراف كفاءة التكاليف الإضافية')], max_length=30, verbose_name='نوع الانحراف')),
                ('variance_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانحراف')),
                ('standard_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة المعيارية')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة الفعلية')),
                ('variance_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الانحراف')),
                ('is_favorable', models.BooleanField(default=False, verbose_name='انحراف مفضل')),
                ('analysis', models.TextField(blank=True, verbose_name='تحليل الانحراف')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_records_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_variances', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'سجل انحراف تكلفة',
                'verbose_name_plural': 'سجلات انحرافات التكلفة',
                'ordering': ['-variance_date', '-created_at'],
                'indexes': [models.Index(fields=['production_order', 'variance_type'], name='production__product_20e076_idx'), models.Index(fields=['variance_date'], name='production__varianc_c1c14a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(verbose_name='تاريخ التوقع')),
                ('forecast_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المتوقعة')),
                ('historical_avg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='متوسط تاريخي')),
                ('trend_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='معامل الاتجاه')),
                ('seasonality_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='معامل الموسمية')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=5, verbose_name='مستوى الثقة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='branches.branch', verbose_name='الفرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'توقع طلب',
                'verbose_name_plural': 'توقعات الطلب',
                'ordering': ['forecast_date'],
                'unique_together': {('product', 'branch', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('demand_collected', 'جمع طلبات'), ('production_created', 'إنشاء أمر إنتاج'), ('transfer_created', 'إنشاء تحويل'), ('status_updated', 'تحديث حالة'), ('auto_process', 'معالجة تلقائية'), ('error', 'خطأ')], max_length=30, verbose_name='نوع العملية')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='branches.branch', verbose_name='الفرع')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to='branches.branchtransfer', verbose_name='التحويل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تكامل',
                'verbose_name_plural': 'سجلات التكامل',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['action_type', 'action_date'], name='production__action__d3cd90_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionShowroomLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('in_production', 'قيد الإنتاج'), ('ready', 'جاهز للشحن'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_links', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('replenishment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_links', to='branches.showroomreplenishmentrequest', verbose_name='طلب التموين')),
                ('target_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_links', to='branches.branch', verbose_name='الفرع المستهدف')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_links', to='branches.branchtransfer', verbose_name='أمر التحويل')),
            ],
            options={
                'verbose_name': 'رابط إنتاج-معرض',
                'verbose_name_plural': 'روابط الإنتاج-المعارض',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['production_order', 'target_branch'], name='production__product_1420e7_idx'), models.Index(fields=['status'], name='production__status_5c7e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='StandardCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السريان')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة المواد')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة العمالة')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='التكاليف الإضافية')),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكاليف أخرى')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='ساعات العمل')),
                ('machine_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='ساعات التشغيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_costs_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_costs', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تكلفة معيارية',
                'verbose_name_plural': 'التكاليف المعيارية',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['product', 'effective_date'], name='production__product_778545_idx')],
            },
        ),
    ]
