# Generated by Django 5.2.5 on 2026-02-11 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_materialreorderpoint_mrpplanningmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السريان'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الأمر'),
        ),
    ]
