# Generated by Django 5.2.9 on 2026-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_billofmaterials_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', max_length=10, verbose_name='وحدة الاستخدام'),
        ),
    ]
