# Generated by Django 5.2.9 on 2026-02-18 05:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_bomitem_usage_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('overall_progress', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الإنجاز الكلية')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_board', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'لوحة خط الأنابيب',
                'verbose_name_plural': 'لوحات خط الأنابيب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('ready', 'جاهز للبدء'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'متوقف - عطل'), ('skipped', 'تم تخطيه')], default='waiting', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنجاز')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='سبب التوقف')),
                ('failure_category', models.CharField(blank=True, choices=[('machine_breakdown', 'عطل ماكينة'), ('material_shortage', 'نقص مواد'), ('quality_issue', 'مشكلة جودة'), ('power_outage', 'انقطاع كهرباء'), ('labor_shortage', 'نقص عمالة'), ('other', 'أخرى')], default='', max_length=50, verbose_name='تصنيف العطل')),
                ('print_status', models.CharField(blank=True, choices=[('', 'غير مطلوب'), ('pending', 'في انتظار الطباعة'), ('printing', 'جاري الطباعة'), ('printed', 'تم الطباعة'), ('print_error', 'خطأ في الطباعة')], default='', max_length=20, verbose_name='حالة الطباعة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_entries', to='production.pipelineboard', verbose_name='لوحة الأنابيب')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_completed', to=settings.AUTH_USER_MODEL, verbose_name='أكمل بواسطة')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_started', to=settings.AUTH_USER_MODEL, verbose_name='بدأ بواسطة')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='production.productionworkcenter', verbose_name='مركز العمل')),
            ],
            options={
                'verbose_name': 'مرحلة في خط الأنابيب',
                'verbose_name_plural': 'مراحل خط الأنابيب',
                'ordering': ['sequence'],
                'unique_together': {('board', 'work_center')},
            },
        ),
        migrations.CreateModel(
            name='PipelinePrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode_data', models.TextField(verbose_name='بيانات الباركود')),
                ('zpl_command', models.TextField(blank=True, default='', verbose_name='أمر ZPL')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='عدد النسخ')),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('sent', 'تم الإرسال'), ('printing', 'جاري الطباعة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='queued', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_print_jobs', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('stage_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='production.pipelinestageentry', verbose_name='مرحلة الأنابيب')),
            ],
            options={
                'verbose_name': 'مهمة طباعة باركود',
                'verbose_name_plural': 'مهام طباعة الباركود',
                'ordering': ['-created_at'],
            },
        ),
    ]
