# Generated by Django 5.2.9 on 2026-02-18 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_pipeline_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material_defect', 'عيب في المواد الخام'), ('machine_failure', 'عطل آلة'), ('quality_issue', 'مشكلة جودة'), ('missing_material', 'نقص مواد'), ('worker_error', 'خطأ عامل'), ('design_issue', 'مشكلة تصميم'), ('power_outage', 'انقطاع كهرباء'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='التصنيف')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=10, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('investigating', 'قيد التحقيق'), ('resolved', 'تم الحل'), ('escalated', 'تم التصعيد'), ('closed', 'مغلق')], default='open', max_length=15, verbose_name='الحالة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('units_affected', models.PositiveIntegerField(default=0, verbose_name='عدد الوحدات المتأثرة')),
                ('downtime_minutes', models.PositiveIntegerField(default=0, verbose_name='وقت التوقف (دقائق)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة التقديرية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='production_issues/', verbose_name='صورة المشكلة')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإبلاغ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='المُبلِّغ')),
                ('stage_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='production.pipelinestageentry', verbose_name='مرحلة الأنبوب')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='production.productionworkcenter', verbose_name='مركز العمل')),
            ],
            options={
                'verbose_name': 'مشكلة إنتاج',
                'verbose_name_plural': 'مشاكل الإنتاج',
                'ordering': ['-reported_at'],
            },
        ),
    ]
