# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_interbranchtransfer_interbranchtransferitem_and_more'),
        ('production', '0013_auto_pipeline_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة مواد معيارية')),
                ('actual_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة مواد فعلية')),
                ('standard_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة عمالة معيارية')),
                ('actual_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة عمالة فعلية')),
                ('standard_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكاليف غير مباشرة معيارية')),
                ('actual_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكاليف غير مباشرة فعلية')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التحليل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُعد بواسطة')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_variance', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'تحليل تباين تكاليف',
                'verbose_name_plural': 'تحليلات تباين التكاليف',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم خط الإنتاج')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الطاقة الإنتاجية لكل ساعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'خط إنتاج',
                'verbose_name_plural': 'خطوط الإنتاج',
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField(verbose_name='بداية مخططة')),
                ('planned_end', models.DateTimeField(verbose_name='نهاية مخططة')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية فعلية')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية فعلية')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المخططة')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الفعلية')),
                ('defective_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المعيبة')),
                ('priority', models.IntegerField(choices=[(1, 'عاجل جداً'), (2, 'عاجل'), (3, 'عالي'), (5, 'عادي'), (7, 'منخفض'), (10, 'غير مستعجل')], default=5, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('delayed', 'متأخر'), ('cancelled', 'ملغي')], default='planned', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_workers', models.ManyToManyField(blank=True, related_name='production_schedules', to=settings.AUTH_USER_MODEL, verbose_name='العمال المكلفون')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='production.productionline', verbose_name='خط الإنتاج')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'جدولة إنتاج',
                'verbose_name_plural': 'جدولة الإنتاج',
                'ordering': ['priority', 'planned_start'],
            },
        ),
    ]
