# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_costvariance_productionline_productionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodunit',
            name='manufacture_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التصنيع'),
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='consumption_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاستهلاك'),
        ),
        migrations.AlterField(
            model_name='productioncostanalysis',
            name='cost_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التكلفة'),
        ),
        migrations.AlterField(
            model_name='workerproductionentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الإنتاج'),
        ),
    ]
