# Generated by Django 5.2.5 on 2025-08-16 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentmethod_type'),
        ('purchases', '0003_po_bill_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع (شيك/تحويل/Instapay/محفظة)'),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchases.purchasebill')),
            ],
            options={
                'verbose_name': 'مرتجع شراء',
                'verbose_name_plural': 'مرتجعات الشراء',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
        ),
    ]
