# Generated by Django 5.2.5 on 2025-08-19 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingsettings_ar_account'),
        ('partners', '0006_supplier_account_fields'),
        ('payments', '0004_paymentmethod_account'),
        ('purchases', '0004_purchasebill_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحلة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم إيصال المورد')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع (شيك/تحويل)')),
                ('description', models.TextField(blank=True, verbose_name='بيان')),
                ('locked', models.BooleanField(default=False, help_text='يمنع التعديل بعد الترحيل أو الطباعة', verbose_name='مقفول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='purchases.purchasebill', verbose_name='فاتورة شراء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'دفعة مورد',
                'verbose_name_plural': 'دفعات الموردين',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='supppay_date_idx')],
            },
        ),
    ]
