# Generated by Django 5.2.5 on 2025-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchasebill_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('partial', 'استلام جزئي'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
