# Generated by Django 5.2.5 on 2025-08-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchaseorder_created_by_purchaseorder_requested_by'),
        ('purchases', '0009_purchaseorder_requested_by_created_by'),
    ]

    operations = [
    ]
