# Generated by Django 5.2.5 on 2025-12-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_advanced_purchasing'),
        ('purchases', '0012_alter_purchasebill_id_alter_purchaseitem_id_and_more'),
    ]

    operations = [
    ]
