# Generated by Django 5.2.5 on 2025-12-08 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printerconfiguration_and_more'),
        ('partners', '0008_alter_customer_id_alter_partner_id_alter_supplier_id'),
        ('payments', '0006_alter_loan_id_alter_loaninstallment_id_and_more'),
        ('purchases', '0013_merge_20251208_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBillOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ربط فاتورة بأمر شراء',
                'verbose_name_plural': 'روابط فواتير أوامر الشراء',
            },
        ),
        migrations.RenameIndex(
            model_name='goodsreceipt',
            new_name='purchases_g_purchas_b206c1_idx',
            old_name='gr_po_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='goodsreceipt',
            new_name='purchases_g_receipt_72483b_idx',
            old_name='gr_date_idx',
        ),
        migrations.RenameIndex(
            model_name='productpricehistory',
            new_name='purchases_p_product_587983_idx',
            old_name='pph_prod_supp_date',
        ),
        migrations.RenameIndex(
            model_name='productpricehistory',
            new_name='purchases_p_product_611dc2_idx',
            old_name='pph_prod_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchases_p_status_bf2e6d_idx',
            old_name='pr_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchases_p_request_1fc60f_idx',
            old_name='pr_reqby_date_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='purchases_s_purchas_132ee8_idx',
            old_name='ship_po_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='purchases_s_trackin_9ac066_idx',
            old_name='ship_track_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierleadtime',
            new_name='purchases_s_supplie_8c1b65_idx',
            old_name='slt_supp_active_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierquotation',
            new_name='purchases_s_rfq_id_2bcfd3_idx',
            old_name='quot_rfq_supp_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierquotation',
            new_name='purchases_s_status_c6813a_idx',
            old_name='quot_stat_date_idx',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم فاتورة المورد (خارجي)'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_quotation_items', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_invoice_number', ''), _negated=True), fields=('supplier', 'supplier_invoice_number'), name='uniq_supplier_ext_invoice'),
        ),
        migrations.AddField(
            model_name='purchasebillorderlink',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='purchases.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebillorderlink',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_links', to='purchases.purchaseorder'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasebillorderlink',
            unique_together={('bill', 'order')},
        ),
    ]
