# Generated by Django 5.2.5 on 2025-12-09 00:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printerconfiguration_and_more'),
        ('purchases', '0014_purchasebillorderlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='القسم')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحاجة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدّم'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('converted', 'مُحوّل لأمر شراء'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('justification', models.TextField(blank=True, help_text='سبب الطلب', verbose_name='المبرر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approval_notes', models.TextField(blank=True, verbose_name='ملاحظات الاعتماد')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='حُوّل بواسطة')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requisition', to='purchases.purchaseorder', verbose_name='أمر الشراء')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='رفضه')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
                'ordering': ['-date', '-id'],
                'permissions': [('can_review_pr', 'يمكنه مراجعة طلبات الشراء'), ('can_approve_pr', 'يمكنه اعتماد طلبات الشراء'), ('can_convert_pr_to_po', 'يمكنه تحويل طلب الشراء لأمر شراء')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر التقديري')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='الرصيد وقت إنشاء الطلب', max_digits=12, verbose_name='الرصيد الحالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('location', models.ForeignKey(help_text='المستودع المطلوب استلام المادة فيه', on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequisition', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'بند طلب شراء',
                'verbose_name_plural': 'بنود طلبات الشراء',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['-date'], name='purchases_p_date_81b777_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status'], name='purchases_p_status_cb14db_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['priority'], name='purchases_p_priorit_116e16_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requested_by'], name='purchases_p_request_414ddd_idx'),
        ),
    ]
