# Generated by Django 5.2.5 on 2025-12-15 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_supplierdocument'),
        ('payments', '0007_alter_paymenttransaction_installment'),
        ('purchases', '0015_purchaserequisition_purchaserequisitionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['date'], name='purchasebill_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['supplier', 'date'], name='purchasebill_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['status'], name='purchasebill_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['is_deleted', 'date'], name='purchasebill_deleted_date_idx'),
        ),
    ]
