# Generated by Django 5.2.5 on 2025-12-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_add_performance_indexes'),
        ('showrooms', '0009_remove_showroomshiftassignment_showroom_shift_employee_day_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='showrooms.showroom', verbose_name='المعرض/الفرع'),
        ),
    ]
