# Generated by Django 5.2.5 on 2025-12-29 02:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_journalentry_created_by'),
        ('partners', '0011_product_unit_warranty'),
        ('purchases', '0017_add_showroom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDiscountNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الإشعار الدائن')),
                ('supplier_note_number', models.CharField(blank=True, help_text='رقم الإشعار الصادر من المورد', max_length=100, verbose_name='رقم إشعار المورد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الخصم')),
                ('is_percentage', models.BooleanField(default=False, help_text='إذا كان نعم، سيتم احتساب النسبة من الفاتورة المرتبطة', verbose_name='نسبة مئوية')),
                ('percentage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='النسبة من 0 إلى 100', max_digits=5, verbose_name='النسبة المئوية')),
                ('reason', models.CharField(choices=[('early_payment', 'خصم تعجيل دفع'), ('quantity', 'خصم كمية / تاريخ'), ('damaged_goods', 'تسوية بضاعة تالفة'), ('price_diff', 'فرق أسعار'), ('other', 'سبب آخر')], default='early_payment', max_length=30, verbose_name='سبب الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_notes', to='purchases.purchasebill', verbose_name='فاتورة الشراء المرتبطة')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_supplier_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_discount_notes', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_supplier_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='رحّله')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_notes', to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'إشعار خصم مكتسب',
                'verbose_name_plural': 'إشعارات الخصم المكتسبة',
                'ordering': ['-date', '-id'],
                'permissions': [('can_post_supplier_discount', 'يمكنه ترحيل إشعار خصم المورد'), ('can_cancel_supplier_discount', 'يمكنه إلغاء إشعار خصم المورد')],
                'indexes': [models.Index(fields=['-date'], name='purchases_s_date_df72b6_idx'), models.Index(fields=['supplier', '-date'], name='purchases_s_supplie_036099_idx'), models.Index(fields=['status'], name='purchases_s_status_77e2aa_idx')],
            },
        ),
    ]
