# Generated by Django 5.2.5 on 2026-01-14 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_rename_spp_prod_supp_active_idx_inventory_s_product_2d38ac_idx_and_more'),
        ('partners', '0015_add_uom_to_supplierproduct'),
        ('purchases', '0018_supplierdiscountnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['id'], 'verbose_name': 'بند فاتورة شراء', 'verbose_name_plural': 'بنود فواتير الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'أمر شراء', 'verbose_name_plural': 'أوامر الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['id'], 'verbose_name': 'بند أمر شراء', 'verbose_name_plural': 'بنود أوامر الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'مرتجع شراء', 'verbose_name_plural': 'مرتجعات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnitem',
            options={'ordering': ['id'], 'verbose_name': 'بند مرتجع شراء', 'verbose_name_plural': 'بنود مرتجعات الشراء'},
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='رفض بواسطة'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='reason',
            field=models.TextField(blank=True, verbose_name='سبب الإرجاع'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('posted', 'مرحل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='reason',
            field=models.TextField(blank=True, verbose_name='سبب الإرجاع'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasebill', verbose_name='فاتورة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع/المخزن'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order', to='purchases.purchasebill', verbose_name='فاتورة الشراء المرتبطة'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع/المخزن'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchases.purchasebill', verbose_name='فاتورة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='bill_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseitem', verbose_name='بند فاتورة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn', verbose_name='مرتجع الشراء'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسل'), ('received', 'استُلمت عروض'), ('evaluated', 'تم التقييم'), ('awarded', 'تم الترسية'), ('cancelled', 'ملغى'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='rfqsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='supplierleadtime',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_times', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='partners.partner', verbose_name='المورد'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['bill', 'product'], name='purchases_p_bill_id_f43a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product', 'location'], name='purchases_p_product_377ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'date'], name='purchases_p_status_9882c2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'date'], name='purchases_p_supplie_278808_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_date'], name='purchases_p_expecte_ad6b41_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['order', 'product'], name='purchases_p_order_i_76b8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product', 'location'], name='purchases_p_product_e6ae1c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['priority', 'status'], name='purchases_p_priorit_433a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['required_date'], name='purchases_p_require_40c670_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['status', 'date'], name='purchases_p_status_808ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['bill', 'date'], name='purchases_p_bill_id_bc13d3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['purchase_return', 'bill_item'], name='purchases_p_purchas_a374f4_idx'),
        ),
    ]
