# Generated by Django 5.2.9 on 2026-02-13 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_alter_purchaseitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
    ]
