# Generated by Django 5.2.5 on 2026-02-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_alter_purchasebill_date_alter_purchaseorder_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierDiscountNote',
        ),
    ]
