# Generated by Django 5.2.5 on 2025-12-30 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0011_product_unit_warranty'),
        ('payments', '0007_alter_paymenttransaction_installment'),
        ('sales', '0027_customerdiscountnote'),
        ('showrooms', '0010_showroom_country_showroom_governorate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_reminders_enabled', models.BooleanField(default=True, verbose_name='تفعيل التذكيرات التلقائية')),
                ('reminder_days_before', models.PositiveIntegerField(default=3, verbose_name='أيام قبل الاستحقاق للتذكير')),
                ('overdue_reminder_interval', models.PositiveIntegerField(default=7, verbose_name='الفترة بين تذكيرات التأخير (أيام)')),
                ('max_reminders_per_installment', models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى لعدد التذكيرات لكل قسط')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='SMS')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='واتساب')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='البريد الإلكتروني')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='إشعارات التطبيق')),
                ('default_after_days', models.PositiveIntegerField(default=90, verbose_name='يُعتبر متعثر بعد (أيام)')),
                ('upcoming_message_template', models.TextField(default='عزيزي {customer_name}، نذكرك بأن القسط رقم {installment_number} بمبلغ {amount} يستحق بتاريخ {due_date}. العقد رقم: {contract_number}', verbose_name='قالب رسالة قبل الاستحقاق')),
                ('due_message_template', models.TextField(default='عزيزي {customer_name}، اليوم يستحق القسط رقم {installment_number} بمبلغ {amount}. يرجى السداد لتجنب رسوم التأخير. العقد رقم: {contract_number}', verbose_name='قالب رسالة يوم الاستحقاق')),
                ('overdue_message_template', models.TextField(default='عزيزي {customer_name}، القسط رقم {installment_number} متأخر بمبلغ {amount} منذ {days_overdue} يوم. رسوم التأخير: {late_fee}. يرجى السداد فوراً. العقد رقم: {contract_number}', verbose_name='قالب رسالة التأخير')),
            ],
            options={
                'verbose_name': 'إعدادات التقسيط',
                'verbose_name_plural': 'إعدادات التقسيط',
            },
        ),
        migrations.CreateModel(
            name='InstallmentContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم العقد')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الأصلي')),
                ('down_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المقدم')),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الممول')),
                ('admin_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المصاريف الإدارية')),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='إجمالي الفوائد')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القسط الشهري')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي النهائي')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الأقساط')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الأقساط')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'في انتظار الموافقة'), ('approved', 'معتمد'), ('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر'), ('cancelled', 'ملغي'), ('legal', 'تحت إجراء قانوني')], default='draft', max_length=20, verbose_name='حالة العقد')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('national_id_image', models.ImageField(blank=True, upload_to='installments/ids/', verbose_name='صورة الهوية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف بديل')),
                ('work_address', models.TextField(blank=True, verbose_name='عنوان العمل')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('customer_signature', models.ImageField(blank=True, upload_to='installments/signatures/', verbose_name='توقيع العميل')),
                ('signed_contract', models.FileField(blank=True, upload_to='installments/contracts/', verbose_name='العقد الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_installment_contracts', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_contracts', to='partners.customer', verbose_name='العميل')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installment_contract', to='sales.invoice', verbose_name='الفاتورة')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_contracts', to='showrooms.showroom', verbose_name='الفرع/المعرض')),
            ],
            options={
                'verbose_name': 'عقد تقسيط',
                'verbose_name_plural': 'عقود التقسيط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ القسط')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ المدفوع')),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='رسوم التأخير')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('partially_paid', 'مدفوع جزئياً'), ('overdue', 'متأخر'), ('waived', 'معفى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='عدد التذكيرات')),
                ('last_reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='installments.installmentcontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('national_id', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('national_id_image', models.ImageField(blank=True, upload_to='installments/guarantor_ids/', verbose_name='صورة الهوية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف بديل')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='جهة العمل')),
                ('work_address', models.TextField(blank=True, verbose_name='عنوان العمل')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العمل')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الدخل الشهري')),
                ('relationship', models.CharField(choices=[('relative', 'قريب'), ('friend', 'صديق'), ('colleague', 'زميل عمل'), ('employer', 'صاحب عمل'), ('other', 'أخرى')], default='relative', max_length=50, verbose_name='العلاقة بالعميل')),
                ('relationship_details', models.CharField(blank=True, max_length=100, verbose_name='تفاصيل العلاقة')),
                ('signature', models.ImageField(blank=True, upload_to='installments/guarantor_signatures/', verbose_name='التوقيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='installments.installmentcontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'ضامن',
                'verbose_name_plural': 'الضامنين',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installment', verbose_name='القسط')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_installment_payments', to=settings.AUTH_USER_MODEL, verbose_name='استلمها')),
            ],
            options={
                'verbose_name': 'دفعة قسط',
                'verbose_name_plural': 'دفعات الأقساط',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('duration_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='المدة بالأشهر')),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='نسبة الفائدة السنوية %')),
                ('admin_fee_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية')], default='percentage', max_length=20, verbose_name='نوع المصاريف الإدارية')),
                ('admin_fee_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة المصاريف الإدارية')),
                ('min_down_payment_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='الحد الأدنى للمقدم %')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=15, verbose_name='الحد الأدنى للمبلغ')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأقصى للمبلغ')),
                ('late_fee_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة من القسط'), ('daily', 'رسم يومي')], default='percentage', max_length=20, verbose_name='نوع رسوم التأخير')),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='قيمة رسوم التأخير')),
                ('grace_period_days', models.PositiveIntegerField(default=3, verbose_name='فترة السماح (أيام)')),
                ('requires_guarantor', models.BooleanField(default=False, verbose_name='يتطلب ضامن')),
                ('min_guarantors', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للضامنين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_smart_installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'خطة تقسيط',
                'verbose_name_plural': 'خطط التقسيط',
                'ordering': ['duration_months'],
            },
        ),
        migrations.AddField(
            model_name='installmentcontract',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='installments.installmentplan', verbose_name='خطة التقسيط'),
        ),
        migrations.CreateModel(
            name='InstallmentReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('upcoming', 'قبل الاستحقاق'), ('due', 'يوم الاستحقاق'), ('overdue', 'متأخر')], max_length=20, verbose_name='نوع التذكير')),
                ('channel', models.CharField(choices=[('sms', 'رسالة SMS'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('push', 'إشعار تطبيق'), ('call', 'اتصال هاتفي')], max_length=20, verbose_name='قناة الإرسال')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('delivered', models.BooleanField(default=False, verbose_name='تم التوصيل')),
                ('read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='installments.installment', verbose_name='القسط')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_installment_reminders', to=settings.AUTH_USER_MODEL, verbose_name='أرسل بواسطة')),
            ],
            options={
                'verbose_name': 'تذكير قسط',
                'verbose_name_plural': 'تذكيرات الأقساط',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date', 'status'], name='installment_due_dat_052ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status'], name='installment_status_517beb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('contract', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='installmentcontract',
            index=models.Index(fields=['contract_number'], name='installment_contrac_cfa2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentcontract',
            index=models.Index(fields=['status'], name='installment_status_9ed285_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentcontract',
            index=models.Index(fields=['customer', 'status'], name='installment_custome_fbc204_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentcontract',
            index=models.Index(fields=['start_date', 'end_date'], name='installment_start_d_d94f33_idx'),
        ),
    ]
