# Generated by Django 5.2.5 on 2025-12-30 10:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0001_initial'),
        ('partners', '0011_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('phone_call', 'اتصال هاتفي'), ('sms', 'رسالة SMS'), ('whatsapp', 'رسالة واتساب'), ('email', 'بريد إلكتروني'), ('visit', 'زيارة ميدانية'), ('legal_notice', 'إنذار قانوني'), ('legal_action', 'إجراء قانوني'), ('settlement_offer', 'عرض تسوية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجراء')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإجراء')),
                ('result', models.CharField(blank=True, choices=[('promise_to_pay', 'وعد بالسداد'), ('partial_payment', 'سداد جزئي'), ('full_payment', 'سداد كامل'), ('no_response', 'لا رد'), ('refused', 'رفض'), ('wrong_contact', 'بيانات اتصال خاطئة'), ('not_available', 'غير متاح'), ('dispute', 'نزاع'), ('other', 'أخرى')], max_length=20, verbose_name='النتيجة')),
                ('promise_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الوعد')),
                ('promise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='المبلغ الموعود')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('follow_up_done', models.BooleanField(default=False, verbose_name='تمت المتابعة')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_actions', to='installments.installment', verbose_name='القسط')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_actions', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
            ],
            options={
                'verbose_name': 'إجراء تحصيل',
                'verbose_name_plural': 'إجراءات التحصيل',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractReschedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القسط الشهري الأصلي')),
                ('original_remaining_months', models.PositiveIntegerField(verbose_name='الأشهر المتبقية الأصلية')),
                ('original_remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المتبقي الأصلي')),
                ('new_monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القسط الشهري الجديد')),
                ('new_duration_months', models.PositiveIntegerField(verbose_name='المدة الجديدة بالأشهر')),
                ('new_start_date', models.DateField(verbose_name='تاريخ البدء الجديد')),
                ('additional_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='فوائد إضافية')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('applied', 'مطبق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(verbose_name='سبب إعادة الجدولة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reschedules', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='installments.installmentcontract', verbose_name='العقد')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reschedules', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'إعادة جدولة',
                'verbose_name_plural': 'إعادات الجدولة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='رسوم النقل')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النقل')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transfer_document', models.FileField(blank=True, upload_to='installments/transfers/', verbose_name='مستند النقل')),
                ('reason', models.TextField(blank=True, verbose_name='سبب النقل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contract_transfers', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='installments.installmentcontract', verbose_name='العقد')),
                ('new_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_to_contracts', to='partners.customer', verbose_name='العميل الجديد')),
                ('original_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from_contracts', to='partners.customer', verbose_name='العميل الأصلي')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_contract_transfers', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'نقل ملكية',
                'verbose_name_plural': 'نقل الملكيات',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='النتيجة')),
                ('level', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'ضعيف'), ('bad', 'سيء')], default='fair', max_length=20, verbose_name='المستوى')),
                ('total_contracts', models.PositiveIntegerField(default=0, verbose_name='إجمالي العقود')),
                ('completed_contracts', models.PositiveIntegerField(default=0, verbose_name='العقود المكتملة')),
                ('defaulted_contracts', models.PositiveIntegerField(default=0, verbose_name='العقود المتعثرة')),
                ('on_time_payments', models.PositiveIntegerField(default=0, verbose_name='الدفعات في الموعد')),
                ('late_payments', models.PositiveIntegerField(default=0, verbose_name='الدفعات المتأخرة')),
                ('total_late_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي أيام التأخير')),
                ('max_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الحد الائتماني الأقصى')),
                ('available_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الائتمان المتاح')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to='partners.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تقييم ائتماني',
                'verbose_name_plural': 'التقييمات الائتمانية',
            },
        ),
        migrations.CreateModel(
            name='EarlySettlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_principal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الأصلي المتبقي')),
                ('remaining_interest', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الفوائد المتبقية')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='مبلغ الخصم')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ التسوية النهائي')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسوية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_settlements', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_settlements', to='installments.installmentcontract', verbose_name='العقد')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_early_settlements', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'تسوية مبكرة',
                'verbose_name_plural': 'التسويات المبكرة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentWaiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waiver_type', models.CharField(choices=[('late_fee', 'إعفاء من رسوم التأخير'), ('partial', 'إعفاء جزئي'), ('full', 'إعفاء كامل')], max_length=20, verbose_name='نوع الإعفاء')),
                ('waiver_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الإعفاء')),
                ('reason', models.TextField(verbose_name='سبب الإعفاء')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='installments.installment', verbose_name='القسط')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_waivers', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'إعفاء',
                'verbose_name_plural': 'الإعفاءات',
                'ordering': ['-request_date'],
            },
        ),
    ]
