# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_collectionaction_contractreschedule_contracttransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentcontract',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ العقد'),
        ),
    ]
