# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('api_key', models.CharField(max_length=255, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='سر API')),
                ('endpoint_url', models.URLField(verbose_name='رابط API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موفر SMS',
                'verbose_name_plural': 'موفري SMS',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('api_key', models.CharField(max_length=255, verbose_name='مفتاح API')),
                ('phone_number_id', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('business_account_id', models.CharField(max_length=100, verbose_name='رقم الحساب التجاري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موفر WhatsApp',
                'verbose_name_plural': 'موفري WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('channel', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('sms', 'الرسائل النصية'), ('whatsapp', 'واتس آب'), ('push', 'إشعار فوري'), ('in_app', 'داخل التطبيق')], max_length=20, verbose_name='القناة')),
                ('trigger_event', models.CharField(choices=[('invoice_created', 'إنشاء فاتورة'), ('payment_received', 'استقبال دفعة'), ('order_shipped', 'شحن طلب'), ('low_stock', 'مخزون منخفض'), ('task_assigned', 'تعيين مهمة'), ('payment_due', 'موعد الدفع'), ('contract_expiring', 'انتهاء العقد قريباً'), ('policy_expiring', 'انتهاء البوليصة قريباً'), ('custom', 'مخصص')], max_length=50, verbose_name='حدث الفعل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('footer', models.TextField(blank=True, verbose_name='التذييل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], max_length=20, verbose_name='الأولوية')),
                ('available_variables', models.TextField(help_text='مثل: {customer_name}, {amount}, {date}', verbose_name='المتغيرات المتاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
                'unique_together': {('name', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='تفعيل البريد الإلكتروني')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='تفعيل الرسائل النصية')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='تفعيل واتس آب')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات الفورية')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات داخل التطبيق')),
                ('invoice_notifications', models.BooleanField(default=True, verbose_name='إشعارات الفواتير')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='إشعارات الدفعات')),
                ('inventory_notifications', models.BooleanField(default=True, verbose_name='إشعارات المخزون')),
                ('task_notifications', models.BooleanField(default=True, verbose_name='إشعارات المهام')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='الإشعارات النظامية')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل أوقات الهدوء')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية أوقات الهدوء')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية أوقات الهدوء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيل الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجدولة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('schedule_type', models.CharField(choices=[('immediate', 'فوري'), ('delayed', 'مؤجل'), ('recurring', 'متكرر'), ('scheduled', 'مجدول')], max_length=50, verbose_name='نوع الجدولة')),
                ('delay_hours', models.IntegerField(blank=True, null=True, verbose_name='تأخير (ساعات)')),
                ('recurrence_pattern', models.CharField(blank=True, help_text='مثل: daily, weekly, monthly', max_length=100, verbose_name='نمط التكرار')),
                ('max_retries', models.IntegerField(default=3, verbose_name='محاولات إعادة الإرسال')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية أوقات الهدوء')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية أوقات الهدوء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='advanced_notifications.messagetemplate')),
            ],
            options={
                'verbose_name': 'جدولة إشعار',
                'verbose_name_plural': 'جدولة الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المستقبل')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف المستقبل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sending', 'قيد الإرسال'), ('sent', 'مرسلة'), ('failed', 'فشلت'), ('bounced', 'مرتدة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('retry_count', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('delivery_status', models.CharField(blank=True, max_length=50, verbose_name='حالة التوصيل')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advanced_notifications.messagetemplate')),
            ],
            options={
                'verbose_name': 'إشعار مرسل',
                'verbose_name_plural': 'الإشعارات المرسلة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='advanced_no_status_087e03_idx'), models.Index(fields=['recipient'], name='advanced_no_recipie_0e241c_idx')],
            },
        ),
    ]
