# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'عضو'), ('admin', 'مدير'), ('owner', 'مالك')], default='member', max_length=20, verbose_name='الدور')),
                ('is_muted', models.BooleanField(default=False, verbose_name='مكتوم')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='الإشعارات')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر قراءة')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('room_type', models.CharField(choices=[('private', 'خاص'), ('group', 'مجموعة'), ('channel', 'قناة'), ('department', 'قسم'), ('project', 'مشروع')], default='private', max_length=20, verbose_name='نوع الغرفة')),
                ('avatar', models.ImageField(blank=True, upload_to='chat/rooms/', verbose_name='الصورة')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('is_muted', models.BooleanField(default=False, verbose_name='مكتومة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='internal_chat.ChatParticipant', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'غرفة دردشة',
                'verbose_name_plural': 'غرف الدردشة',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_chat.chatroom'),
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='الصوت')),
                ('desktop_notifications', models.BooleanField(default=True, verbose_name='إشعارات سطح المكتب')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='إشعارات البريد')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='إظهار الحالة')),
                ('show_read_receipts', models.BooleanField(default=True, verbose_name='إظهار علامة القراءة')),
                ('chat_theme', models.CharField(default='default', max_length=20, verbose_name='السمة')),
                ('message_size', models.CharField(default='medium', max_length=20, verbose_name='حجم الخط')),
                ('status', models.CharField(default='متاح', max_length=50, verbose_name='الحالة')),
                ('custom_status', models.CharField(blank=True, max_length=100, verbose_name='حالة مخصصة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات دردشة',
                'verbose_name_plural': 'إعدادات الدردشة',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('audio', 'صوت'), ('video', 'فيديو'), ('system', 'نظام'), ('reply', 'رد')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, upload_to='chat/attachments/', verbose_name='المرفق')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المرفق')),
                ('attachment_size', models.IntegerField(default=0, verbose_name='حجم المرفق')),
                ('is_edited', models.BooleanField(default=False, verbose_name='معدلة')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوفة')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='internal_chat.message', verbose_name='رد على')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='internal_chat.chatroom', verbose_name='الغرفة')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حالة اتصال',
                'verbose_name_plural': 'حالات الاتصال',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('room', 'user')},
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='الإيموجي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='internal_chat.message', verbose_name='الرسالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفاعل',
                'verbose_name_plural': 'التفاعلات',
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القراءة')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='internal_chat.message', verbose_name='الرسالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قراءة',
                'verbose_name_plural': 'القراءات',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
