# Generated by Django 5.2.5 on 2025-08-11 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_department_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المقياس')),
                ('metric_type', models.CharField(choices=[('sales_volume', 'حجم المبيعات'), ('sales_value', 'قيمة المبيعات'), ('production_quantity', 'كمية الإنتاج'), ('quality_rate', 'معدل الجودة'), ('attendance_rate', 'معدل الحضور'), ('customer_satisfaction', 'رضا العملاء'), ('cost_efficiency', 'كفاءة التكلفة'), ('delivery_time', 'وقت التسليم'), ('training_completion', 'إكمال التدريب'), ('safety_incidents', 'حوادث السلامة'), ('custom', 'مخصص')], max_length=30, verbose_name='نوع المقياس')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('calculation_formula', models.TextField(blank=True, help_text='معادلة لحساب المقياس تلقائياً', verbose_name='معادلة الحساب')),
                ('data_source', models.CharField(blank=True, max_length=100, verbose_name='مصدر البيانات')),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='القيمة المرجعية')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='القيمة المستهدفة')),
                ('is_higher_better', models.BooleanField(default=True, help_text='هل القيمة الأعلى أفضل أم الأقل؟', verbose_name='الأعلى أفضل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقياس أداء',
                'verbose_name_plural': 'مقاييس الأداء',
            },
        ),
        migrations.CreateModel(
            name='TargetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('category_type', models.CharField(choices=[('sales', 'مبيعات'), ('production', 'إنتاج'), ('quality', 'جودة'), ('attendance', 'حضور'), ('customer_service', 'خدمة العملاء'), ('cost_reduction', 'تقليل التكاليف'), ('training', 'تدريب'), ('safety', 'سلامة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة الأهداف',
                'verbose_name_plural': 'فئات الأهداف',
            },
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الهدف')),
                ('description', models.TextField(verbose_name='وصف الهدف')),
                ('target_period', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('custom', 'فترة مخصصة')], max_length=20, verbose_name='فترة الهدف')),
                ('target_type', models.CharField(choices=[('quantity', 'كمية'), ('percentage', 'نسبة مئوية'), ('amount', 'مبلغ مالي'), ('time', 'وقت'), ('score', 'نقاط'), ('boolean', 'تحقق/عدم تحقق')], max_length=20, verbose_name='نوع الهدف')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة المستهدفة')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='القيمة الحالية')),
                ('unit', models.CharField(default='عدد', max_length=50, verbose_name='الوحدة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='الوزن النسبي لهذا الهدف من إجمالي أهداف الموظف', max_digits=5, verbose_name='الوزن النسبي %')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('min_acceptable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأدنى المقبول')),
                ('excellence_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='حد التميز')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مكافأة عند تحقيق الهدف', max_digits=10, verbose_name='مبلغ المكافأة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('expired', 'منتهي')], default='draft', max_length=15, verbose_name='الحالة')),
                ('auto_calculate', models.BooleanField(default=False, help_text='هل يتم حساب التقدم تلقائياً من النظام؟', verbose_name='حساب تلقائي')),
                ('calculation_query', models.TextField(blank=True, help_text='استعلام SQL لحساب التقدم تلقائياً', verbose_name='استعلام الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_targets', to=settings.AUTH_USER_MODEL, verbose_name='محدد الهدف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='hr.employee', verbose_name='الموظف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.targetcategory', verbose_name='فئة الهدف')),
            ],
            options={
                'verbose_name': 'هدف أداء',
                'verbose_name_plural': 'أهداف الأداء',
                'ordering': ['-start_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TargetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة السابقة')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة الجديدة')),
                ('change_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='مقدار التغيير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التحديث')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='hr.performancetarget', verbose_name='الهدف')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='محدث بواسطة')),
            ],
            options={
                'verbose_name': 'تقدم الهدف',
                'verbose_name_plural': 'تقدم الأهداف',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeamTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, verbose_name='اسم الفريق')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الهدف')),
                ('description', models.TextField(verbose_name='وصف الهدف')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة المستهدفة')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='القيمة الحالية')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('expired', 'منتهي')], default='active', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.targetcategory', verbose_name='فئة الهدف')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'هدف فريق',
                'verbose_name_plural': 'أهداف الفرق',
            },
        ),
        migrations.CreateModel(
            name='TeamTargetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5, verbose_name='وزن المساهمة %')),
                ('individual_target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الهدف الفردي')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('team_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.teamtarget')),
            ],
            options={
                'unique_together': {('team_target', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='teamtarget',
            name='team_members',
            field=models.ManyToManyField(through='hr.TeamTargetMembership', to='hr.employee', verbose_name='أعضاء الفريق'),
        ),
        migrations.CreateModel(
            name='EmployeeMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.performancemetric', verbose_name='المقياس')),
            ],
            options={
                'verbose_name': 'قيمة مقياس الأداء',
                'verbose_name_plural': 'قيم مقاييس الأداء',
                'ordering': ['-timestamp'],
                'unique_together': {('employee', 'metric', 'period_start', 'period_end')},
            },
        ),
    ]
