# Generated by Django 5.2.5 on 2025-08-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_performancemetric_targetcategory_performancetarget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ التفتيش')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('findings', models.TextField(verbose_name='الملاحظات')),
                ('actions', models.TextField(blank=True, verbose_name='الإجراءات التصحيحية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تفتيش سلامة',
                'verbose_name_plural': 'تفتيشات السلامة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeekendDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], unique=True, verbose_name='اليوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'يوم عطلة أسبوعية',
                'verbose_name_plural': 'أيام العطلة الأسبوعية',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'شكوى/ملاحظة',
                'verbose_name_plural': 'شكاوى وملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'إنذار'), ('deduction', 'خصم'), ('suspension', 'إيقاف'), ('termination', 'إنهاء خدمة')], max_length=20, verbose_name='نوع الجزاء')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جزاء/مخالفة',
                'verbose_name_plural': 'جزاءات ومخالفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HSEIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الحادث')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('investigating', 'قيد التحقيق'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حادث سلامة',
                'verbose_name_plural': 'حوادث السلامة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HSETraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تدريب السلامة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('done', 'منفذ')], default='planned', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, to='hr.employee', verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'تدريب سلامة',
                'verbose_name_plural': 'تدريبات السلامة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العطلة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='تُكرر سنوياً (حسب اليوم والشهر)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عطلة رسمية',
                'verbose_name_plural': 'عطل رسمية',
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
