# Generated by Django 5.2.5 on 2025-12-07 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hseinspection_weekendday_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsencePolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم السياسة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('deduct_from_leave_first', models.BooleanField(default=True, verbose_name='خصم من الإجازات أولاً')),
                ('salary_deduction_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='خصم يومي من الراتب')),
                ('salary_deduction_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم من الراتب اليومي %')),
                ('warning_days', models.PositiveIntegerField(default=0, verbose_name='أيام التحذير')),
                ('unauthorized_absence_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5, verbose_name='مضاعف الخصم للغياب بدون عذر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سياسة غياب',
                'verbose_name_plural': 'سياسات الغياب',
            },
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeemetricvalue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hrsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hseincident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hseinspection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hsetraining',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancetarget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamtarget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamtargetmembership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weekendday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('absence_date', models.DateField(verbose_name='تاريخ الغياب')),
                ('absence_type', models.CharField(choices=[('unauthorized', 'غياب بدون عذر'), ('late', 'تأخر'), ('leave_exhausted', 'إجازة منتهية'), ('sick_no_certificate', 'مرضي بدون شهادة')], max_length=30, verbose_name='نوع الغياب')),
                ('deducted_from_leave', models.BooleanField(default=False, verbose_name='خُصم من الإجازات')),
                ('leave_days_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='أيام الإجازة المخصومة')),
                ('deducted_from_salary', models.BooleanField(default=False, verbose_name='خُصم من الراتب')),
                ('salary_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='قيمة الخصم')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='hr.employee', verbose_name='الموظف')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
            ],
            options={
                'verbose_name': 'غياب موظف',
                'verbose_name_plural': 'سجل الغياب',
                'ordering': ['-absence_date'],
                'indexes': [models.Index(fields=['employee', 'absence_date'], name='hr_employee_employe_befa5f_idx'), models.Index(fields=['is_processed'], name='hr_employee_is_proc_0a8678_idx')],
                'unique_together': {('employee', 'absence_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeIDCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='رقم البطاقة')),
                ('qr_code_data', models.TextField(verbose_name='بيانات QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='id_cards/qr/', verbose_name='صورة QR Code')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'فعالة'), ('expired', 'منتهية'), ('lost', 'مفقودة'), ('replaced', 'تم استبدالها')], default='active', max_length=20, verbose_name='الحالة')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الطباعة')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الطباعة')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مسح')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='عدد المسحات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='hr.employee', verbose_name='الموظف')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_cards', to=settings.AUTH_USER_MODEL, verbose_name='طبعت بواسطة')),
            ],
            options={
                'verbose_name': 'بطاقة هوية',
                'verbose_name_plural': 'بطاقات الهوية',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['card_number'], name='hr_employee_card_nu_b27748_idx'), models.Index(fields=['employee', 'status'], name='hr_employee_employe_108ee5_idx')],
            },
        ),
    ]
