# Generated by Django 5.2.5 on 2025-12-07 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_absencepolicy_alter_attendancerecord_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeidcard',
            options={'ordering': ['-issue_date'], 'verbose_name': 'بطاقة تعريف', 'verbose_name_plural': 'بطاقات التعريف'},
        ),
        migrations.RemoveField(
            model_name='employeeidcard',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employeeidcard',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='employeeidcard',
            name='qr_code_image',
        ),
        migrations.AddField(
            model_name='employeeidcard',
            name='qr_data',
            field=models.TextField(blank=True, verbose_name='بيانات QR Code'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='card_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم البطاقة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='issue_date',
            field=models.DateField(verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='print_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات الطباعة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_id_cards', to=settings.AUTH_USER_MODEL, verbose_name='طبعت بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='scan_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات المسح'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='status',
            field=models.CharField(choices=[('active', 'فعالة'), ('expired', 'منتهية'), ('lost', 'مفقودة'), ('suspended', 'معلقة')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='employeeidcard',
            index=models.Index(fields=['status', 'expiry_date'], name='hr_employee_status_c43866_idx'),
        ),
    ]
