# Generated by Django 5.2.5 on 2025-12-08 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employeeidcard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeidcard',
            options={'ordering': ['-issue_date'], 'verbose_name': 'بطاقة هوية', 'verbose_name_plural': 'بطاقات الهوية'},
        ),
        migrations.RemoveIndex(
            model_name='employeeidcard',
            name='hr_employee_status_c43866_idx',
        ),
        migrations.RemoveField(
            model_name='employeeidcard',
            name='qr_data',
        ),
        migrations.AddField(
            model_name='employeeidcard',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='employeeidcard',
            name='qr_code_data',
            field=models.TextField(blank=True, default='', verbose_name='بيانات QR Code'),
        ),
        migrations.AddField(
            model_name='employeeidcard',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/qr/', verbose_name='صورة QR Code'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='card_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم البطاقة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='print_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات الطباعة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_cards', to=settings.AUTH_USER_MODEL, verbose_name='طبعت بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المسحات'),
        ),
        migrations.AlterField(
            model_name='employeeidcard',
            name='status',
            field=models.CharField(choices=[('active', 'فعالة'), ('expired', 'منتهية'), ('lost', 'مفقودة'), ('replaced', 'تم استبدالها')], default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
