# Generated by Django 5.2.5 on 2025-12-15 20:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_leaverequest_replacement_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم البدل')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود البدل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='خاضع للضريبة')),
                ('is_fixed', models.BooleanField(default=True, verbose_name='مبلغ ثابت')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='تستخدم إذا كان البدل نسبة من الراتب', max_digits=5, verbose_name='النسبة المئوية')),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='المبلغ الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع بدل',
                'verbose_name_plural': 'أنواع البدلات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخصم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الخصم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('calculation_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة من الراتب'), ('days', 'أيام غياب'), ('hours', 'ساعات')], default='fixed', max_length=15, verbose_name='طريقة الحساب')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='النسبة المئوية')),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='المبلغ الافتراضي')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='إجباري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع خصم',
                'verbose_name_plural': 'أنواع الخصومات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.allowancetype', verbose_name='نوع البدل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_allowances', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بدل موظف',
                'verbose_name_plural': 'بدلات الموظفين',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.deductiontype', verbose_name='نوع الخصم')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_deductions', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'خصم موظف',
                'verbose_name_plural': 'خصومات الموظفين',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('allowance', 'بدل'), ('deduction', 'خصم')], max_length=15, verbose_name='النوع')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payroll', verbose_name='الراتب')),
            ],
            options={
                'verbose_name': 'بند راتب',
                'verbose_name_plural': 'بنود الراتب',
                'ordering': ['item_type', 'name'],
            },
        ),
    ]
