# Generated by Django 5.2.5 on 2025-12-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_jobposition_salary_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsettings',
            name='company_address',
            field=models.TextField(blank=True, default='', verbose_name='عنوان الشركة'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='هاتف الشركة'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='company_vat_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي'),
        ),
    ]
