# Generated by Django 5.2.5 on 2025-12-30 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_add_company_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('orientation', models.CharField(choices=[('horizontal', 'أفقي'), ('vertical', 'عمودي')], default='horizontal', max_length=20, verbose_name='الاتجاه')),
                ('size', models.CharField(choices=[('pvc', 'PVC قياسي (85.6 × 53.98 مم)'), ('a4', 'A4 للطباعة العادية'), ('a6', 'A6'), ('custom', 'مخصص')], default='pvc', max_length=20, verbose_name='الحجم')),
                ('custom_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='العرض (مم)')),
                ('custom_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الارتفاع (مم)')),
                ('primary_color', models.CharField(default='#0f172a', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#0ea5e9', max_length=7, verbose_name='اللون الثانوي')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='لون النص')),
                ('background_color', models.CharField(default='#f8fafc', max_length=7, verbose_name='لون الخلفية')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='id_cards/logos/', verbose_name='شعار الشركة')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='id_cards/backgrounds/', verbose_name='صورة الخلفية')),
                ('show_qr_code', models.BooleanField(default=True, verbose_name='إظهار QR Code')),
                ('show_barcode', models.BooleanField(default=True, verbose_name='إظهار الباركود')),
                ('show_photo', models.BooleanField(default=True, verbose_name='إظهار الصورة')),
                ('show_department', models.BooleanField(default=True, verbose_name='إظهار القسم')),
                ('show_position', models.BooleanField(default=True, verbose_name='إظهار الوظيفة')),
                ('show_employee_id', models.BooleanField(default=True, verbose_name='إظهار رقم الموظف')),
                ('show_national_id', models.BooleanField(default=False, verbose_name='إظهار الرقم القومي')),
                ('show_issue_date', models.BooleanField(default=True, verbose_name='إظهار تاريخ الإصدار')),
                ('show_expiry_date', models.BooleanField(default=True, verbose_name='إظهار تاريخ الانتهاء')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='نوع الخط')),
                ('name_font_size', models.PositiveIntegerField(default=14, verbose_name='حجم خط الاسم')),
                ('info_font_size', models.PositiveIntegerField(default=10, verbose_name='حجم خط المعلومات')),
                ('back_instructions', models.TextField(blank=True, default='• هذه البطاقة ملك للشركة ويجب إرجاعها عند انتهاء الخدمة\n• يجب حمل البطاقة في جميع الأوقات داخل المنشأة\n• في حالة الفقد يرجى الإبلاغ فوراً لقسم الموارد البشرية\n• عدم إساءة استخدام البطاقة أو إعارتها للغير', verbose_name='تعليمات الظهر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب بطاقة هوية',
                'verbose_name_plural': 'قوالب بطاقات الهوية',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardBatchPrint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('total_cards', models.PositiveIntegerField(default=0, verbose_name='إجمالي البطاقات')),
                ('printed_cards', models.PositiveIntegerField(default=0, verbose_name='البطاقات المطبوعة')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='id_cards/batches/', verbose_name='ملف PDF')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('cards', models.ManyToManyField(related_name='batch_prints', to='hr.employeeidcard', verbose_name='البطاقات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.idcardtemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'طباعة دفعة بطاقات',
                'verbose_name_plural': 'طباعات الدفعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
