# Generated by Django 5.2.9 on 2026-01-05 09:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_accounting__entry_t_abc123_idx_accounting__entry_t_bba407_idx_and_more'),
        ('hr', '0012_idcardtemplate_idcardbatchprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_number', models.CharField(help_text='يتم توليده تلقائياً', max_length=50, unique=True, verbose_name='رقم السلفة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ السلفة')),
                ('reason', models.TextField(verbose_name='سبب طلب السلفة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('installments_count', models.PositiveIntegerField(default=1, help_text='عدد الأشهر لتسديد السلفة', verbose_name='عدد الأقساط')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قسط شهري')),
                ('start_deduction_date', models.DateField(help_text='الشهر الذي سيبدأ فيه الخصم من الراتب', verbose_name='تاريخ بدء الخصم')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المتبقي')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('active', 'نشطة'), ('completed', 'مسددة بالكامل'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='حالة السلفة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='سلفة طارئة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='hr.employee', verbose_name='اعتمدها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('deducted', 'مخصوم'), ('deferred', 'مؤجل'), ('waived', 'معفى منه')], default='pending', max_length=20, verbose_name='الحالة')),
                ('deduction_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخصم')),
                ('deferred_to_date', models.DateField(blank=True, null=True, verbose_name='مؤجل إلى تاريخ')),
                ('deferment_reason', models.TextField(blank=True, verbose_name='سبب التأجيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='hr.employeeloan', verbose_name='السلفة')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_deductions', to='hr.payroll', verbose_name='كشف الراتب')),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'ordering': ['loan', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_90799c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['loan_number'], name='hr_employee_loan_nu_17b3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['status'], name='hr_employee_status_97d763_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'status'], name='hr_loaninst_loan_id_cb7be6_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date'], name='hr_loaninst_due_dat_1ec5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['status'], name='hr_loaninst_status_6ebdfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'installment_number')},
        ),
    ]
