# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_employee_attendance_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidcard',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الإصدار'),
        ),
    ]
