apiVersion: v1
kind: ConfigMap
metadata:
  name: tony-erp-config
  namespace: tony-erp
data:
  DJANGO_SETTINGS_MODULE: "accountant_pro.settings"
  DEBUG: "0"
  ENVIRONMENT: "production"
  LANGUAGE_CODE: "ar"
  TIME_ZONE: "Asia/Riyadh"
  DB_ENGINE: "postgresql"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "tony_erb"
  REDIS_URL: "redis://redis-service:6379/1"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
