# Generated by Django 5.2.9 on 2026-01-06 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-lightning', max_length=50, verbose_name='أيقونة Bootstrap')),
                ('url', models.CharField(max_length=200, verbose_name='رابط URL')),
                ('category', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخزون'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('crm', 'إدارة العملاء'), ('reports', 'التقارير'), ('settings', 'الإعدادات'), ('other', 'أخرى')], default='other', max_length=50)),
                ('permission_required', models.CharField(blank=True, help_text='الصلاحية المطلوبة', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('keyboard_shortcut', models.CharField(blank=True, help_text='مثل: Ctrl+Alt+S', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إجراء سريع',
                'verbose_name_plural': 'الإجراءات السريعة',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BulkActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='نوع العملية')),
                ('model_name', models.CharField(max_length=100)),
                ('affected_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('errors_log', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية جماعية',
                'verbose_name_plural': 'سجل العمليات الجماعية',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(max_length=100, verbose_name='نوع التقرير')),
                ('report_url', models.CharField(max_length=300)),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي')], default='daily', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('time_of_day', models.TimeField()),
                ('email_recipients', models.TextField(help_text='عناوين البريد الإلكتروني، مفصولة بفواصل')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير مجدول',
                'verbose_name_plural': 'التقارير المجدولة',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_shortcuts', models.JSONField(blank=True, default=list, help_text='قائمة الاختصارات المفضلة')),
                ('dashboard_widgets', models.JSONField(blank=True, default=list, help_text='Widgets المعروضة في اللوحة')),
                ('default_view', models.CharField(choices=[('grid', 'شبكة'), ('list', 'قائمة'), ('compact', 'مضغوط')], default='grid', max_length=50)),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('auto', 'تلقائي')], default='auto', max_length=20)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_access_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيلات المستخدم',
                'verbose_name_plural': 'تفضيلات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='FrequentlyUsedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200)),
                ('report_url', models.CharField(max_length=300)),
                ('report_type', models.CharField(max_length=50)),
                ('access_count', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير متكرر',
                'verbose_name_plural': 'التقارير المتكررة',
                'ordering': ['-access_count', '-last_accessed'],
                'unique_together': {('user', 'report_name')},
            },
        ),
    ]
