# Generated by Django 5.2.9 on 2026-03-01 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('invoice', 'فاتورة بيع'), ('receipt', 'إيصال قبض'), ('purchase', 'أمر توريد'), ('production', 'أمر إنتاج'), ('barcode', 'باركود')], max_length=20, verbose_name='النوع')),
                ('paper_size', models.CharField(choices=[('thermal_80', 'حرارية 80mm'), ('a4', 'A4'), ('a5', 'A5')], max_length=20, verbose_name='حجم الورق')),
                ('html_content', models.TextField(verbose_name='محتوى HTML')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'قالب طباعة',
                'verbose_name_plural': 'قوالب الطباعة',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
