# Generated by Django 5.2.11 on 2026-03-01 02:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='الشعار')),
                ('default_currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة الافتراضية')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة')),
                ('fiscal_year_start', models.DateField(blank=True, null=True, verbose_name='بداية السنة المالية')),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'الشركة',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='موظف نشط')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('branch_type', models.CharField(choices=[('owned', 'فرع مملوك'), ('franchise', 'توكيل'), ('distributor', 'موزع')], default='owned', max_length=20, verbose_name='نوع الفرع')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم (للتوكيلات)')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='بداية العقد')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='نهاية العقد')),
                ('contract_terms', models.TextField(blank=True, verbose_name='شروط العقد')),
                ('has_warehouse', models.BooleanField(default=False, verbose_name='لديه مخزن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخزن')),
                ('warehouse_type', models.CharField(choices=[('factory', 'مصنع'), ('branch', 'فرع'), ('raw_materials', 'خامات'), ('finished', 'منتجات تامة'), ('wip', 'إنتاج تحت التشغيل')], default='branch', max_length=20, verbose_name='نوع المخزن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='core.branch', verbose_name='الفرع')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kept_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='أمين المخزن')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
    ]
