# Generated by Django 5.2.11 on 2026-03-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شركة', 'verbose_name_plural': 'الشركات'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='fiscal_year_start',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default='MAIN', max_length=20, unique=True, verbose_name='كود الشركة'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='مصر', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_valuation_method',
            field=models.CharField(choices=[('weighted_average', 'متوسط مرجح'), ('fifo', 'FIFO'), ('lifo', 'LIFO')], default='weighted_average', max_length=20, verbose_name='طريقة تقييم المخزون'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='فاكس'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, verbose_name='شهر بداية السنة المالية'),
        ),
        migrations.AddField(
            model_name='company',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_register',
            field=models.CharField(blank=True, max_length=50, verbose_name='سجل صناعي'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_footer',
            field=models.TextField(blank=True, verbose_name='تذييل الفاتورة'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_header',
            field=models.TextField(blank=True, verbose_name='رأس الفاتورة'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_terms',
            field=models.TextField(blank=True, verbose_name='شروط الفاتورة'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='الاسم القانوني'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_small',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار صغير'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_login_attempts',
            field=models.IntegerField(default=5, verbose_name='أقصى محاولات دخول'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزي'),
        ),
        migrations.AddField(
            model_name='company',
            name='password_min_length',
            field=models.IntegerField(default=8, verbose_name='أقل طول كلمة مرور'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='company',
            name='quotation_terms',
            field=models.TextField(blank=True, verbose_name='شروط عرض السعر'),
        ),
        migrations.AddField(
            model_name='company',
            name='session_timeout_minutes',
            field=models.IntegerField(default=480, verbose_name='انتهاء الجلسة (دقائق)'),
        ),
        migrations.AddField(
            model_name='company',
            name='setup_completed',
            field=models.BooleanField(default=False, verbose_name='اكتمل الإعداد الأولي'),
        ),
        migrations.AddField(
            model_name='company',
            name='warranty_terms',
            field=models.TextField(blank=True, verbose_name='شروط الضمان'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
    ]
