# Generated by Django 5.2.11 on 2026-03-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint24_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الحساب مقفل حتى'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد محاولات الدخول الفاشلة'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP للدخول'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('sms', 'رسالة نصية')], default='email', max_length=10, verbose_name='طريقة المصادقة'),
        ),
    ]
