# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_autoreplenishmentrule_showroomreplenishmentrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العداد')),
                ('utility_type', models.CharField(choices=[('electricity', 'كهرباء'), ('water', 'مياه'), ('gas', 'غاز'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المرفق')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('installation_date', models.DateField(verbose_name='تاريخ التركيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_meters', to='branches.branch')),
            ],
            options={
                'verbose_name': 'عداد مرافق',
                'verbose_name_plural': 'عدادات المرافق',
            },
        ),
        migrations.CreateModel(
            name='EnergyConsumptionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الاستهلاك')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التكلفة')),
                ('average_daily_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='متوسط الاستهلاك اليومي')),
                ('previous_period_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='استهلاك الفترة السابقة')),
                ('consumption_variance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='انحراف الاستهلاك')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الانحراف %')),
                ('efficiency_score', models.IntegerField(default=50, help_text='من 0 إلى 100', verbose_name='نقاط الكفاءة')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('savings_potential', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إمكانية التوفير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='energy_management.utilitymeter')),
            ],
            options={
                'verbose_name': 'تحليل استهلاك الطاقة',
                'verbose_name_plural': 'تحليلات استهلاك الطاقة',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='EnergyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_consumption', 'استهلاك عالي'), ('spike', 'قفزة في الاستهلاك'), ('budget_exceeded', 'تجاوز الميزانية'), ('anomaly', 'استهلاك شاذ')], max_length=20, verbose_name='نوع التنبيه')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الخطورة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة الحدية')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة الفعلية')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='energy_management.utilitymeter')),
            ],
            options={
                'verbose_name': 'تنبيه استهلاك',
                'verbose_name_plural': 'تنبيهات الاستهلاك',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='تاريخ القراءة')),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القراءة الحالية')),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='القراءة السابقة')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الاستهلاك')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy_management.utilitymeter')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قراءة عداد',
                'verbose_name_plural': 'قراءات العدادات',
                'ordering': ['-reading_date'],
            },
        ),
    ]
