# Generated by Django 5.2.5 on 2025-12-08 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='Unique token to identify this device', max_length=64, unique=True, verbose_name='رمز الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الجهاز')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, device trust expires at this time', null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز موثوق',
                'verbose_name_plural': 'أجهزة موثوقة',
                'db_table': 'accounts_trusted_device',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='المفتاح السري TOTP')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='مفعّل')),
                ('backup_codes', models.TextField(blank=True, help_text='JSON array of hashed backup codes', verbose_name='رموز النسخ الاحتياطي (مشفرة)')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مصادقة ثنائية',
                'verbose_name_plural': 'مصادقات ثنائية',
                'db_table': 'accounts_two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('success', models.BooleanField(verbose_name='نجح')),
                ('method', models.CharField(choices=[('password', 'كلمة المرور'), ('totp', 'TOTP'), ('otp', 'OTP'), ('backup_code', 'رمز نسخ احتياطي')], default='password', max_length=20, verbose_name='طريقة المصادقة')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الفشل')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محاولة تسجيل دخول',
                'verbose_name_plural': 'محاولات تسجيل الدخول',
                'db_table': 'accounts_login_attempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='accounts_lo_usernam_24513e_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_82ce5a_idx'), models.Index(fields=['success', '-timestamp'], name='accounts_lo_success_d2ca25_idx')],
            },
        ),
    ]
