# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0004_add_property_contract_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='ترتيب الخطوة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخطوة')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='هذه الخطوة مطلوبة فقط إذا كان المبلغ أكبر من أو يساوي هذا الحد', max_digits=14, verbose_name='الحد الأدنى للمبلغ')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='اختياري: فارغ = بدون حد أقصى', max_digits=14, null=True, verbose_name='الحد الأقصى للمبلغ')),
                ('auto_approve_below', models.DecimalField(blank=True, decimal_places=2, help_text='موافقة تلقائية إذا المبلغ أقل من هذا الحد', max_digits=14, null=True, verbose_name='موافقة تلقائية تحت')),
                ('timeout_hours', models.PositiveIntegerField(default=24, verbose_name='مهلة الموافقة (ساعات)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('approver_role', models.ForeignKey(help_text='أي مستخدم بهذا الدور يمكنه الاعتماد', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='دور المعتمِد')),
                ('approver_user', models.ForeignKey(blank=True, help_text='اختياري: تحديد مستخدم بعينه للاعتماد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='معتمِد محدد')),
                ('escalate_to', models.ForeignKey(blank=True, help_text='في حالة انتهاء المهلة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='تصعيد إلى')),
            ],
            options={
                'verbose_name': 'خطوة موافقة',
                'verbose_name_plural': 'خطوات الموافقة',
                'ordering': ['workflow', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='نوع المستند')),
                ('document_id', models.PositiveIntegerField(verbose_name='رقم المستند')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المستند المرجعي')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('escalated', 'مُصعَّد'), ('cancelled', 'ملغي'), ('auto_approved', 'موافقة تلقائية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='الفرع')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='accounts.approvalstep', verbose_name='الخطوة الحالية')),
            ],
            options={
                'verbose_name': 'طلب موافقة',
                'verbose_name_plural': 'طلبات الموافقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'معتمد'), ('rejected', 'مرفوض'), ('escalated', 'مُصعَّد'), ('returned', 'مُرجع للتعديل'), ('auto_approved', 'موافقة تلقائية')], max_length=20, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.approvalrequest', verbose_name='طلب الموافقة')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.approvalstep', verbose_name='الخطوة')),
            ],
            options={
                'verbose_name': 'إجراء موافقة',
                'verbose_name_plural': 'إجراءات الموافقة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم سير العمل')),
                ('document_type', models.CharField(choices=[('purchase_order', 'أمر شراء'), ('sales_order', 'أمر بيع'), ('invoice', 'فاتورة'), ('payment', 'دفعة'), ('expense', 'مصروف'), ('journal_entry', 'قيد يومية'), ('inventory_transfer', 'تحويل مخزون'), ('production_order', 'أمر إنتاج'), ('price_change', 'تغيير سعر'), ('discount', 'خصم'), ('refund', 'مرتجع'), ('write_off', 'إعدام')], max_length=50, verbose_name='نوع المستند')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('apply_to_all_branches', models.BooleanField(default=True, verbose_name='تطبيق على جميع الفروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branches', models.ManyToManyField(blank=True, help_text='اتركه فارغاً إذا كان يطبق على جميع الفروع', related_name='approval_workflows', to='branches.branch', verbose_name='الفروع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'سير عمل الموافقات',
                'verbose_name_plural': 'مسارات عمل الموافقات',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.approvalworkflow', verbose_name='سير العمل'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.approvalworkflow', verbose_name='سير العمل'),
        ),
        migrations.CreateModel(
            name='DataAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخازن'), ('accounting', 'المحاسبة'), ('crm', 'علاقات العملاء'), ('production', 'الإنتاج'), ('hr', 'الموارد البشرية'), ('pos', 'نقاط البيع')], max_length=50, verbose_name='الوحدة')),
                ('access_level', models.CharField(choices=[('own_only', 'بياناته فقط'), ('own_branch', 'فرعه فقط'), ('own_department', 'قسمه فقط'), ('selected_branches', 'فروع محددة'), ('all_branches', 'جميع الفروع')], default='own_branch', max_length=30, verbose_name='مستوى الوصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_rules', to='auth.group', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'قاعدة وصول',
                'verbose_name_plural': 'قواعد الوصول',
                'ordering': ['role', 'module'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8, verbose_name='الحد الأدنى لطول كلمة المرور')),
                ('require_uppercase', models.BooleanField(default=True, verbose_name='تتطلب حروف كبيرة')),
                ('require_lowercase', models.BooleanField(default=True, verbose_name='تتطلب حروف صغيرة')),
                ('require_numbers', models.BooleanField(default=True, verbose_name='تتطلب أرقام')),
                ('require_special_chars', models.BooleanField(default=True, verbose_name='تتطلب رموز خاصة')),
                ('password_expiry_days', models.IntegerField(default=90, help_text='0 = لا تنتهي', verbose_name='مدة صلاحية كلمة المرور (أيام)')),
                ('password_history_count', models.IntegerField(default=5, help_text='لمنع إعادة استخدام كلمات المرور', verbose_name='عدد كلمات المرور السابقة المحفوظة')),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='الحد الأقصى لمحاولات تسجيل الدخول')),
                ('lockout_duration_minutes', models.IntegerField(default=30, verbose_name='مدة القفل (دقائق)')),
                ('session_timeout_minutes', models.IntegerField(default=480, help_text='480 = 8 ساعات', verbose_name='مهلة انتهاء الجلسة (دقائق)')),
                ('require_2fa_for_admins', models.BooleanField(default=True, verbose_name='تتطلب مصادقة ثنائية للمديرين')),
                ('allowed_ips', models.TextField(blank=True, default='', help_text='عنوان واحد لكل سطر. اتركه فارغاً للسماح لجميع العناوين.', verbose_name='عناوين IP المسموحة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة الأمان',
                'verbose_name_plural': 'سياسات الأمان',
            },
        ),
        migrations.CreateModel(
            name='UserBranchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_branch', models.BooleanField(default=False, help_text='هل هذا هو الفرع الافتراضي للمستخدم؟', verbose_name='الفرع الافتراضي')),
                ('can_view', models.BooleanField(default=True, verbose_name='عرض')),
                ('can_create', models.BooleanField(default=False, verbose_name='إنشاء')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_approve', models.BooleanField(default=False, verbose_name='اعتماد')),
                ('can_export', models.BooleanField(default=False, verbose_name='تصدير')),
                ('financial_limit', models.DecimalField(decimal_places=2, default=0, help_text='الحد الأقصى للموافقة المالية (0 = بدون حد)', max_digits=14, verbose_name='الحد المالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='branches.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية فرع',
                'verbose_name_plural': 'صلاحيات الفروع',
                'ordering': ['user', 'branch'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['document_type', 'document_id'], name='accounts_ap_documen_9f9b87_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ap_status_6bbf0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataaccessrule',
            unique_together={('role', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='userbranchpermission',
            unique_together={('user', 'branch')},
        ),
    ]
