"""
Sidebar Menu Configuration v3 — 6 Parent Categories
=====================================================
Reorganized 80+ modules into 6 collapsible parent groups
to minimize scrolling and maximize discoverability.

Uses the same CATEGORY_DAILY / CATEGORY_MASTER / CATEGORY_REPORTS
constants as the existing sidebar_config.py for consistency.
"""

from django.utils.translation import gettext_lazy as _


# ===============================================
# Category Types (same as sidebar_config.py)
# ===============================================
CATEGORY_DAILY = 'daily'
CATEGORY_MASTER = 'master'
CATEGORY_REPORTS = 'reports'


# ===============================================
# 6 Parent Groups
# ===============================================
PARENT_GROUPS = [
    {
        'id': 'reporting_hub',
        'label': _('مركز التقارير والتحليلات'),
        'label_en': 'Reporting & Analytics Hub',
        'icon': 'bi-graph-up-arrow',
        'color': '#7c7bff',
        'order': 1,
    },
    {
        'id': 'factory_ops',
        'label': _('عمليات المصنع'),
        'label_en': 'Core Factory Operations',
        'icon': 'bi-gear-wide-connected',
        'color': '#17e9b5',
        'order': 2,
    },
    {
        'id': 'commercial',
        'label': _('الفروع والعمليات التجارية'),
        'label_en': 'Commercial & Branches',
        'icon': 'bi-shop-window',
        'color': '#f59e0b',
        'order': 3,
    },
    {
        'id': 'finance_hr',
        'label': _('الإدارة المالية والأفراد'),
        'label_en': 'Finance & HR',
        'icon': 'bi-cash-stack',
        'color': '#3b82f6',
        'order': 4,
    },
    {
        'id': 'logistics',
        'label': _('الدعم والخدمات اللوجستية'),
        'label_en': 'Logistics & Support',
        'icon': 'bi-truck',
        'color': '#ef4444',
        'order': 5,
    },
    {
        'id': 'tech_control',
        'label': _('مركز التحكم الفني'),
        'label_en': 'Technical Control Center',
        'icon': 'bi-cpu',
        'color': '#a855f7',
        'order': 6,
    },
]


# ===============================================
# All sections → mapped to parent groups
# URL names MUST match the existing urls.py in each app.
# ===============================================
SIDEBAR_SECTIONS = {

    # ─── A. Reporting & Analytics Hub ────────────────────────
    'master_dashboard': {
        'id': 'master_dashboard',
        'parent': 'reporting_hub',
        'label': _('لوحة التحكم الرئيسية'),
        'icon': 'bi-speedometer2',
        'order': 1,
        'module': None,
        'items': [
            {
                'id': 'dashboard_main',
                'label': _('لوحة التحكم'),
                'url': 'core:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'unified_dashboard',
                'label': _('لوحة تحكم موحدة'),
                'url': 'core:unified_dashboard',
                'icon': 'bi-bar-chart-line',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'enhanced_dashboard',
                'label': _('لوحة تحكم متقدمة'),
                'url': 'core:enhanced_dashboard',
                'icon': 'bi-graph-up',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'branch_monitor': {
        'id': 'branch_monitor',
        'parent': 'reporting_hub',
        'label': _('مراقبة الفروع'),
        'icon': 'bi-diagram-3',
        'order': 2,
        'module': 'branches',
        'items': [
            {
                'id': 'branch_dashboard',
                'label': _('لوحة الفروع'),
                'url': 'branches:dashboard',
                'icon': 'bi-bar-chart-steps',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'branch_transfers',
                'label': _('تحويلات الفروع'),
                'url': 'branches:transfer_list',
                'icon': 'bi-arrow-left-right',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'ai_insights': {
        'id': 'ai_insights',
        'parent': 'reporting_hub',
        'label': _('التحليل الذكي'),
        'icon': 'bi-robot',
        'order': 3,
        'module': None,
        'items': [
            {
                'id': 'mrp_dashboard',
                'label': _('لوحة التصنيع'),
                'url': 'core:mrp_dashboard',
                'icon': 'bi-cpu',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'costing_dashboard',
                'label': _('لوحة التكاليف'),
                'url': 'core:costing_dashboard',
                'icon': 'bi-calculator',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'distribution_dashboard',
                'label': _('لوحة التوزيع'),
                'url': 'core:distribution_dashboard',
                'icon': 'bi-diagram-3-fill',
                'category': CATEGORY_REPORTS,
            },
        ],
    },

    # ─── B. Core Factory Operations ─────────────────────────
    'production_pipeline': {
        'id': 'production_pipeline',
        'parent': 'factory_ops',
        'label': _('خط الإنتاج'),
        'icon': 'bi-activity',
        'order': 1,
        'module': 'production',
        'items': [
            {
                'id': 'production_orders',
                'label': _('أوامر الإنتاج'),
                'url': 'production:orders_list',
                'icon': 'bi-clipboard-check',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'production_pipeline_view',
                'label': _('خط الإنتاج الحي'),
                'url': 'production:pipeline_dashboard',
                'icon': 'bi-broadcast-pin',
                'category': CATEGORY_DAILY,
                'badge_source': 'active_production_count',
            },
            {
                'id': 'work_centers',
                'label': _('مراكز العمل'),
                'url': 'production:work_centers_list',
                'icon': 'bi-building-gear',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'production_stages',
                'label': _('مراحل الإنتاج'),
                'url': 'production:stages_list',
                'icon': 'bi-list-ol',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'production_scheduling',
                'label': _('جدولة الإنتاج'),
                'url': 'production:scheduling_dashboard',
                'icon': 'bi-calendar3',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'quality_control': {
        'id': 'quality_control',
        'parent': 'factory_ops',
        'label': _('مراقبة الجودة'),
        'icon': 'bi-shield-check',
        'order': 2,
        'module': 'production',
        'items': [
            {
                'id': 'qc_dashboard',
                'label': _('لوحة الجودة'),
                'url': 'production:quality_dashboard',
                'icon': 'bi-clipboard2-check',
                'category': CATEGORY_DAILY,
                'badge_source': 'pending_qc_count',
            },
            {
                'id': 'production_analytics',
                'label': _('تحليلات الإنتاج'),
                'url': 'production:analytics_dashboard',
                'icon': 'bi-graph-up',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'oee_monitoring',
                'label': _('كفاءة المعدات OEE'),
                'url': 'production:oee_dashboard',
                'icon': 'bi-speedometer',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'materials_inventory': {
        'id': 'materials_inventory',
        'parent': 'factory_ops',
        'label': _('مخزون المواد'),
        'icon': 'bi-box2',
        'order': 3,
        'module': 'inventory',
        'items': [
            {
                'id': 'raw_materials',
                'label': _('المواد الخام'),
                'url': 'inventory:raw_material_list',
                'icon': 'bi-archive',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'bom_list',
                'label': _('وصفة التصنيع (BOM)'),
                'url': 'inventory:bom_list',
                'icon': 'bi-list-nested',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'stock_alerts',
                'label': _('تنبيهات المخزون'),
                'url': 'inventory:stock_alert_list',
                'icon': 'bi-bell',
                'category': CATEGORY_DAILY,
                'badge_source': 'low_stock_alerts',
            },
        ],
    },

    # ─── C. Commercial & Branches ───────────────────────────
    'branches_mgmt': {
        'id': 'branches_mgmt',
        'parent': 'commercial',
        'label': _('إدارة الفروع'),
        'icon': 'bi-building',
        'order': 1,
        'module': 'branches',
        'items': [
            {
                'id': 'branches_list',
                'label': _('قائمة الفروع'),
                'url': 'branches:branch_list',
                'icon': 'bi-list-ul',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'branch_staff',
                'label': _('موظفو الفروع'),
                'url': 'branches:staff_list',
                'icon': 'bi-people',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'branch_expenses',
                'label': _('مصروفات الفروع'),
                'url': 'branches:expense_list',
                'icon': 'bi-cash',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'retail_pos': {
        'id': 'retail_pos',
        'parent': 'commercial',
        'label': _('نقاط البيع'),
        'icon': 'bi-cart3',
        'order': 2,
        'module': 'pos',
        'items': [
            {
                'id': 'pos_terminal',
                'label': _('شاشة البيع'),
                'url': 'pos:new_order',
                'icon': 'bi-display',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'pos_shifts',
                'label': _('الورديات'),
                'url': 'pos:shifts',
                'icon': 'bi-clock-history',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'pos_dashboard',
                'label': _('لوحة نقطة البيع'),
                'url': 'pos:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'pos_sales_details',
                'label': _('تقارير المبيعات'),
                'url': 'pos:sales_details',
                'icon': 'bi-file-earmark-bar-graph',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'sales_crm': {
        'id': 'sales_crm',
        'parent': 'commercial',
        'label': _('المبيعات والعملاء'),
        'icon': 'bi-people',
        'order': 3,
        'module': 'sales',
        'items': [
            {
                'id': 'sales_dashboard',
                'label': _('لوحة المبيعات'),
                'url': 'sales:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'sales_invoices',
                'label': _('الفواتير'),
                'url': 'sales:invoice_list',
                'icon': 'bi-receipt',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'sales_customers',
                'label': _('العملاء'),
                'url': 'crm:customer_list',
                'icon': 'bi-person-lines-fill',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'crm_opportunities',
                'label': _('الفرص البيعية'),
                'url': 'crm:opportunity_list',
                'icon': 'bi-funnel',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'crm_followups',
                'label': _('المتابعات'),
                'url': 'crm:followup_list',
                'icon': 'bi-telephone-outbound',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'sales_invoice_create',
                'label': _('فاتورة مبيعات جديدة'),
                'url': 'sales:invoice_create',
                'icon': 'bi-file-earmark-plus',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'sales_returns',
                'label': _('المرتجعات'),
                'url': 'sales:sales_return_list',
                'icon': 'bi-arrow-return-left',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'customer_create',
                'label': _('عميل جديد'),
                'url': 'crm:customer_create',
                'icon': 'bi-person-plus',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'sales_reports',
                'label': _('تقارير المبيعات'),
                'url': 'sales:reporting_analytics',
                'icon': 'bi-bar-chart',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'online_store': {
        'id': 'online_store',
        'parent': 'commercial',
        'label': _('المتجر الإلكتروني'),
        'icon': 'bi-globe',
        'order': 4,
        'module': 'ecommerce',
        'items': [
            {
                'id': 'ecommerce_dashboard',
                'label': _('لوحة المتجر'),
                'url': 'ecommerce:admin_dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'online_orders',
                'label': _('طلبات أونلاين'),
                'url': 'ecommerce:admin_orders',
                'icon': 'bi-bag-check',
                'category': CATEGORY_DAILY,
                'badge_source': 'pending_online_orders',
            },
            {
                'id': 'store_products',
                'label': _('منتجات المتجر'),
                'url': 'ecommerce:admin_products',
                'icon': 'bi-grid',
                'category': CATEGORY_MASTER,
            },
        ],
    },

    # ─── D. Finance & HR ────────────────────────────────────
    'accounting': {
        'id': 'accounting',
        'parent': 'finance_hr',
        'label': _('المحاسبة'),
        'icon': 'bi-journal-bookmark',
        'order': 1,
        'module': 'accounting',
        'items': [
            {
                'id': 'accounting_dashboard',
                'label': _('لوحة المحاسبة'),
                'url': 'accounting:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'chart_of_accounts',
                'label': _('شجرة الحسابات'),
                'url': 'accounting:chart_of_accounts',
                'icon': 'bi-diagram-3',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'journal_entries',
                'label': _('قيود يومية'),
                'url': 'accounting:journal_entries_list',
                'icon': 'bi-journal-text',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'cash_receipt',
                'label': _('سند قبض'),
                'url': 'accounting:cash_receipt_create',
                'icon': 'bi-cash',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'cash_payment',
                'label': _('سند صرف'),
                'url': 'accounting:cash_payment_create',
                'icon': 'bi-cash-stack',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'trial_balance',
                'label': _('ميزان المراجعة'),
                'url': 'accounting:trial_balance',
                'icon': 'bi-clipboard-data',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'income_statement',
                'label': _('قائمة الدخل'),
                'url': 'accounting:income_statement',
                'icon': 'bi-file-earmark-spreadsheet',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'balance_sheet',
                'label': _('الميزانية العمومية'),
                'url': 'accounting:balance_sheet',
                'icon': 'bi-building',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'fiscal_years',
                'label': _('السنوات المالية'),
                'url': 'accounting:fiscal_year_list',
                'icon': 'bi-calendar-range',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'cost_centers',
                'label': _('مراكز التكلفة'),
                'url': 'accounting:cost_centers_list',
                'icon': 'bi-bullseye',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'revenue_create',
                'label': _('تسجيل إيراد'),
                'url': 'accounting:revenue_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'expense_create',
                'label': _('تسجيل مصروف'),
                'url': 'accounting:expense_create',
                'icon': 'bi-dash-circle',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'cheques_management',
                'label': _('إدارة الشيكات'),
                'url': 'accounting:cheque_list',
                'icon': 'bi-credit-card',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'cfo_dashboard',
                'label': _('لوحة CFO'),
                'url': 'accounting:cfo_dashboard',
                'icon': 'bi-graph-up',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'purchases_section': {
        'id': 'purchases_section',
        'parent': 'finance_hr',
        'label': _('المشتريات'),
        'icon': 'bi-bag',
        'order': 2,
        'module': 'purchases',
        'items': [
            {
                'id': 'purchases_list',
                'label': _('فواتير المشتريات'),
                'url': 'purchases:purchase_list',
                'icon': 'bi-receipt-cutoff',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'purchases_create',
                'label': _('فاتورة شراء جديدة'),
                'url': 'purchases:purchase_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'po_list',
                'label': _('أوامر الشراء'),
                'url': 'purchases:po_list',
                'icon': 'bi-clipboard-check',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'po_create',
                'label': _('أمر شراء جديد'),
                'url': 'purchases:po_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'suppliers_list',
                'label': _('الموردين'),
                'url': 'purchases:supplier_material_prices',
                'icon': 'bi-truck',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'purchase_returns',
                'label': _('مرتجعات المشتريات'),
                'url': 'purchases:purchase_return_start',
                'icon': 'bi-arrow-return-left',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'purchase_reports',
                'label': _('تقارير المشتريات'),
                'url': 'purchases:purchasing_analytics',
                'icon': 'bi-bar-chart',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'hr_payroll': {
        'id': 'hr_payroll',
        'parent': 'finance_hr',
        'label': _('الموارد البشرية'),
        'icon': 'bi-person-badge',
        'order': 3,
        'module': 'hr',
        'items': [
            {
                'id': 'hr_dashboard',
                'label': _('لوحة HR'),
                'url': 'hr:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'employees',
                'label': _('الموظفين'),
                'url': 'hr:employee_list',
                'icon': 'bi-people-fill',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'departments',
                'label': _('الأقسام'),
                'url': 'hr:department_list',
                'icon': 'bi-building',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'attendance',
                'label': _('الحضور والانصراف'),
                'url': 'hr:attendance_dashboard',
                'icon': 'bi-calendar-check',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'payroll',
                'label': _('الرواتب'),
                'url': 'hr:payroll_dashboard',
                'icon': 'bi-cash-coin',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'hr_leaves',
                'label': _('الإجازات'),
                'url': 'hr:leave_dashboard',
                'icon': 'bi-calendar-x',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'hr_employee_welcome',
                'label': _('بوابة الموظف'),
                'url': 'hr:employee_welcome',
                'icon': 'bi-person-badge',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'hr_id_cards',
                'label': _('بطاقات التعريف'),
                'url': 'hr:id_card_template_list',
                'icon': 'bi-person-vcard',
                'category': CATEGORY_MASTER,
            },
        ],
    },

    # ─── E. Logistics & Support ─────────────────────────────
    'shipping_logistics': {
        'id': 'shipping_logistics',
        'parent': 'logistics',
        'label': _('الشحن والتوصيل'),
        'icon': 'bi-truck',
        'order': 1,
        'module': 'shipping',
        'items': [
            {
                'id': 'shipping_dashboard',
                'label': _('لوحة الشحن'),
                'url': 'shipping:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'shipment_list',
                'label': _('الشحنات'),
                'url': 'shipping:shipment_list',
                'icon': 'bi-box-seam',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'shipping_companies',
                'label': _('شركات الشحن'),
                'url': 'shipping:company_list',
                'icon': 'bi-building',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'shipping_zones',
                'label': _('المناطق'),
                'url': 'shipping:zone_list',
                'icon': 'bi-geo-alt',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'fleet_mgmt': {
        'id': 'fleet_mgmt',
        'parent': 'logistics',
        'label': _('الأسطول'),
        'icon': 'bi-truck-front',
        'order': 2,
        'module': 'fleet',
        'items': [
            {
                'id': 'fleet_dashboard',
                'label': _('لوحة الأسطول'),
                'url': 'fleet:dashboard',
                'icon': 'bi-truck-front',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'fleet_vehicles',
                'label': _('المركبات'),
                'url': 'fleet:vehicle_list',
                'icon': 'bi-car-front',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'fleet_fuel',
                'label': _('استهلاك الوقود'),
                'url': 'fleet:fuel_list',
                'icon': 'bi-fuel-pump',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'fleet_maintenance_req',
                'label': _('صيانة المركبات'),
                'url': 'fleet:vehicle_list',
                'icon': 'bi-wrench',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'maintenance_section': {
        'id': 'maintenance_section',
        'parent': 'logistics',
        'label': _('الصيانة'),
        'icon': 'bi-wrench-adjustable',
        'order': 3,
        'module': 'maintenance',
        'items': [
            {
                'id': 'maintenance_dashboard',
                'label': _('لوحة الصيانة'),
                'url': 'maintenance:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
                'badge_source': 'open_maintenance_tickets',
            },
            {
                'id': 'maintenance_machines',
                'label': _('الآلات والمعدات'),
                'url': 'maintenance:machine_list',
                'icon': 'bi-tools',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'maintenance_add_machine',
                'label': _('إضافة آلة'),
                'url': 'maintenance:machine_add',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── F. Technical Control Center ────────────────────────
    'inventory_mgmt': {
        'id': 'inventory_mgmt',
        'parent': 'tech_control',
        'label': _('إدارة المخزون'),
        'icon': 'bi-box2',
        'order': 0,
        'module': 'inventory',
        'items': [
            {
                'id': 'inventory_dashboard',
                'label': _('لوحة المخزون'),
                'url': 'inventory:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'product_list',
                'label': _('المنتجات'),
                'url': 'inventory:product_list',
                'icon': 'bi-grid-3x3-gap',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'category_list',
                'label': _('التصنيفات'),
                'url': 'inventory:category_list',
                'icon': 'bi-tags',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'stock_management',
                'label': _('إدارة المخزون'),
                'url': 'inventory:stock_management',
                'icon': 'bi-boxes',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'stock_receiving',
                'label': _('استلام بضاعة'),
                'url': 'inventory:receiving_list',
                'icon': 'bi-box-arrow-in-down',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'stock_issue',
                'label': _('صرف بضاعة'),
                'url': 'inventory:issue_list',
                'icon': 'bi-box-arrow-up',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'barcode_mgmt',
                'label': _('إدارة الباركود'),
                'url': 'inventory:barcode_management',
                'icon': 'bi-upc-scan',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'inventory_transfers',
                'label': _('التحويلات المخزنية'),
                'url': 'inventory:transfer_list',
                'icon': 'bi-arrow-left-right',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'inventory_locations',
                'label': _('المواقع والمخازن'),
                'url': 'inventory:location_list',
                'icon': 'bi-geo-alt',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'inventory_reports',
                'label': _('تقارير المخزون'),
                'url': 'inventory:valuation_report',
                'icon': 'bi-file-earmark-bar-graph',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'printing_section': {
        'id': 'printing_section',
        'parent': 'tech_control',
        'label': _('محطات الطباعة'),
        'icon': 'bi-printer',
        'order': 1,
        'module': None,
        'items': [
            {
                'id': 'printing_dashboard',
                'label': _('لوحة الطباعة'),
                'url': 'printing:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'printer_settings',
                'label': _('إعدادات الطابعات'),
                'url': 'printing:printer_settings',
                'icon': 'bi-gear',
                'category': CATEGORY_MASTER,
                'badge_source': 'offline_printers_count',
            },
            {
                'id': 'printer_mapping',
                'label': _('ربط الطابعات'),
                'url': 'printing:station_mapping',
                'icon': 'bi-diagram-2',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'user_security': {
        'id': 'user_security',
        'parent': 'tech_control',
        'label': _('الأمان والصلاحيات'),
        'icon': 'bi-shield-lock',
        'order': 2,
        'module': None,
        'items': [
            {
                'id': 'user_list',
                'label': _('المستخدمين'),
                'url': 'users:list',
                'icon': 'bi-person-gear',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'role_list',
                'label': _('الأدوار والصلاحيات'),
                'url': 'users:role_list',
                'icon': 'bi-key',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'permissions_manager',
                'label': _('مدير الصلاحيات'),
                'url': 'users:permissions_manager',
                'icon': 'bi-shield-lock',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'access_logs',
                'label': _('سجلات الدخول'),
                'url': 'core:audit_logs',
                'icon': 'bi-file-earmark-lock',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'system_settings',
                'label': _('إعدادات النظام'),
                'url': 'core:company_settings',
                'icon': 'bi-sliders',
                'category': CATEGORY_MASTER,
            },
        ],
    },

    # ─── إضافات جديدة: المالية المتقدمة (finance_hr) ───────────────────────────
    'treasury_mgmt': {
        'id': 'treasury_mgmt',
        'parent': 'finance_hr',
        'label': _('إدارة الخزينة'),
        'icon': 'bi-safe2',
        'order': 4,
        'module': 'treasury_management',
        'items': [
            {
                'id': 'treasury_dashboard',
                'label': _('لوحة الخزينة'),
                'url': 'treasury_management:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'bank_integration_section': {
        'id': 'bank_integration_section',
        'parent': 'finance_hr',
        'label': _('التكامل البنكي'),
        'icon': 'bi-bank',
        'order': 5,
        'module': 'bank_integration',
        'items': [
            {
                'id': 'bank_integration_dashboard',
                'label': _('لوحة التكامل البنكي'),
                'url': 'bank_integration:dashboard',
                'icon': 'bi-bank',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'zatca_section': {
        'id': 'zatca_section',
        'parent': 'finance_hr',
        'label': _('الفوترة الإلكترونية ZATCA'),
        'icon': 'bi-receipt-cutoff',
        'order': 6,
        'module': 'zatca_integration',
        'items': [
            {
                'id': 'zatca_dashboard',
                'label': _('لوحة ZATCA'),
                'url': 'zatca:dashboard',
                'icon': 'bi-receipt-cutoff',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'payments_section': {
        'id': 'payments_section',
        'parent': 'finance_hr',
        'label': _('طرق الدفع'),
        'icon': 'bi-credit-card-2-front',
        'order': 7,
        'module': 'payments',
        'items': [
            {
                'id': 'payments_dashboard',
                'label': _('لوحة المدفوعات'),
                'url': 'payments:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'payment_methods',
                'label': _('طرق الدفع'),
                'url': 'payments:payment_methods_list',
                'icon': 'bi-credit-card',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'budgeting_section': {
        'id': 'budgeting_section',
        'parent': 'finance_hr',
        'label': _('الميزانيات'),
        'icon': 'bi-pie-chart-fill',
        'order': 8,
        'module': 'budgeting',
        'items': [
            {
                'id': 'budgeting_dashboard',
                'label': _('لوحة الميزانيات'),
                'url': 'budgeting:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'bank_reconciliation_section': {
        'id': 'bank_reconciliation_section',
        'parent': 'finance_hr',
        'label': _('التسوية البنكية'),
        'icon': 'bi-bank2',
        'order': 9,
        'module': 'bank_reconciliation',
        'items': [
            {
                'id': 'bank_recon_dashboard',
                'label': _('التسوية البنكية'),
                'url': 'bank_reconciliation:dashboard',
                'icon': 'bi-bank2',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── إضافات جديدة: الأعمال والشراكات (commercial) ─────────────────────────
    'advanced_crm_section': {
        'id': 'advanced_crm_section',
        'parent': 'commercial',
        'label': _('CRM المتقدم'),
        'icon': 'bi-person-lines-fill',
        'order': 5,
        'module': 'advanced_crm',
        'items': [
            {
                'id': 'advanced_crm_dashboard',
                'label': _('لوحة CRM المتقدم'),
                'url': 'advanced_crm:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'correspondence_section': {
        'id': 'correspondence_section',
        'parent': 'commercial',
        'label': _('إدارة المراسلات'),
        'icon': 'bi-envelope-paper',
        'order': 6,
        'module': 'correspondence_management',
        'items': [
            {
                'id': 'correspondence_dashboard',
                'label': _('لوحة المراسلات'),
                'url': 'correspondence_management:dashboard',
                'icon': 'bi-envelope-paper',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'contract_section': {
        'id': 'contract_section',
        'parent': 'commercial',
        'label': _('العقود والاتفاقيات'),
        'icon': 'bi-file-earmark-ruled',
        'order': 7,
        'module': 'contract_management',
        'items': [
            {
                'id': 'contract_dashboard',
                'label': _('لوحة العقود'),
                'url': 'contract_management:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'intellectual_property_section': {
        'id': 'intellectual_property_section',
        'parent': 'commercial',
        'label': _('الملكية الفكرية'),
        'icon': 'bi-lightbulb',
        'order': 8,
        'module': 'intellectual_property',
        'items': [
            {
                'id': 'ip_dashboard',
                'label': _('لوحة الملكية الفكرية'),
                'url': 'intellectual_property:dashboard',
                'icon': 'bi-lightbulb',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'tender_section': {
        'id': 'tender_section',
        'parent': 'commercial',
        'label': _('المناقصات والعطاءات'),
        'icon': 'bi-trophy',
        'order': 9,
        'module': 'tender_bidding',
        'items': [
            {
                'id': 'tender_dashboard',
                'label': _('لوحة المناقصات'),
                'url': 'tender_bidding:dashboard',
                'icon': 'bi-trophy',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'competitive_intel_section': {
        'id': 'competitive_intel_section',
        'parent': 'commercial',
        'label': _('الاستخبارات التنافسية'),
        'icon': 'bi-graph-up-arrow',
        'order': 10,
        'module': 'competitive_intelligence',
        'items': [
            {
                'id': 'competitive_dashboard',
                'label': _('لوحة الاستخبارات التنافسية'),
                'url': 'competitive_intelligence:dashboard',
                'icon': 'bi-graph-up-arrow',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'approvals_section': {
        'id': 'approvals_section',
        'parent': 'commercial',
        'label': _('الموافقات والاعتمادات'),
        'icon': 'bi-check2-all',
        'order': 11,
        'module': 'approvals',
        'items': [
            {
                'id': 'approvals_list',
                'label': _('قائمة الموافقات'),
                'url': 'approvals:list',
                'icon': 'bi-check2-all',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'partners_section': {
        'id': 'partners_section',
        'parent': 'commercial',
        'label': _('الشركاء والعملاء'),
        'icon': 'bi-people-fill',
        'order': 12,
        'module': 'partners',
        'items': [
            {
                'id': 'partners_dashboard',
                'label': _('لوحة الشركاء'),
                'url': 'partners:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'partners_list',
                'label': _('قائمة الشركاء'),
                'url': 'partners:partners_list',
                'icon': 'bi-people',
                'category': CATEGORY_MASTER,
            },
        ],
    },

    # ─── إضافات جديدة: خدمات العملاء والامتثال (logistics) ────────────────────
    'complaint_section': {
        'id': 'complaint_section',
        'parent': 'logistics',
        'label': _('إدارة الشكاوى'),
        'icon': 'bi-chat-square-text',
        'order': 4,
        'module': 'complaint_management',
        'items': [
            {
                'id': 'complaint_dashboard',
                'label': _('لوحة الشكاوى'),
                'url': 'complaint_management:dashboard',
                'icon': 'bi-chat-square-text',
                'category': CATEGORY_DAILY,
                'badge_source': 'open_complaints_count',
            },
        ],
    },
    'warranty_section': {
        'id': 'warranty_section',
        'parent': 'logistics',
        'label': _('إدارة الضمانات'),
        'icon': 'bi-patch-check',
        'order': 5,
        'module': 'warranty_management',
        'items': [
            {
                'id': 'warranty_dashboard',
                'label': _('لوحة الضمانات'),
                'url': 'warranty_management:dashboard',
                'icon': 'bi-patch-check',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'eservices_section': {
        'id': 'eservices_section',
        'parent': 'logistics',
        'label': _('الخدمات الإلكترونية'),
        'icon': 'bi-globe',
        'order': 6,
        'module': 'eservices',
        'items': [
            {
                'id': 'eservices_dashboard',
                'label': _('لوحة الخدمات الإلكترونية'),
                'url': 'eservices:dashboard',
                'icon': 'bi-globe',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'subscriptions_section': {
        'id': 'subscriptions_section',
        'parent': 'logistics',
        'label': _('الاشتراكات'),
        'icon': 'bi-calendar-check',
        'order': 7,
        'module': 'subscriptions',
        'items': [
            {
                'id': 'subscriptions_plans',
                'label': _('خطط الاشتراك'),
                'url': 'subscriptions:plans_list',
                'icon': 'bi-calendar-check',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'my_subscription',
                'label': _('اشتراكي'),
                'url': 'subscriptions:my_subscription',
                'icon': 'bi-person-check',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'compliance_section': {
        'id': 'compliance_section',
        'parent': 'logistics',
        'label': _('الامتثال والرقابة'),
        'icon': 'bi-clipboard2-check',
        'order': 8,
        'module': 'compliance_management',
        'items': [
            {
                'id': 'compliance_dashboard',
                'label': _('لوحة الامتثال'),
                'url': 'compliance_management:dashboard',
                'icon': 'bi-clipboard2-check',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'license_section': {
        'id': 'license_section',
        'parent': 'logistics',
        'label': _('إدارة التراخيص'),
        'icon': 'bi-card-checklist',
        'order': 9,
        'module': 'license_management',
        'items': [
            {
                'id': 'license_dashboard',
                'label': _('لوحة التراخيص'),
                'url': 'license_management:dashboard',
                'icon': 'bi-card-checklist',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'digital_signatures_section': {
        'id': 'digital_signatures_section',
        'parent': 'logistics',
        'label': _('التوقيعات الرقمية'),
        'icon': 'bi-pen',
        'order': 10,
        'module': 'digital_signatures',
        'items': [
            {
                'id': 'signatures_dashboard',
                'label': _('لوحة التوقيعات'),
                'url': 'digital_signatures:dashboard',
                'icon': 'bi-pen',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── إضافات جديدة: الأدوات التقنية (tech_control) ─────────────────────────
    'energy_section': {
        'id': 'energy_section',
        'parent': 'tech_control',
        'label': _('إدارة الطاقة'),
        'icon': 'bi-lightning-charge-fill',
        'order': 3,
        'module': 'energy_management',
        'items': [
            {
                'id': 'energy_dashboard',
                'label': _('لوحة الطاقة'),
                'url': 'energy_management:dashboard',
                'icon': 'bi-lightning-charge-fill',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'monitoring_section': {
        'id': 'monitoring_section',
        'parent': 'tech_control',
        'label': _('مراقبة النظام'),
        'icon': 'bi-activity',
        'order': 4,
        'module': 'monitoring',
        'items': [
            {
                'id': 'monitoring_anomaly',
                'label': _('كشف الشذوذ'),
                'url': 'monitoring:anomaly_dashboard',
                'icon': 'bi-activity',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'ai_tools_section': {
        'id': 'ai_tools_section',
        'parent': 'tech_control',
        'label': _('الأدوات الذكية'),
        'icon': 'bi-robot',
        'order': 5,
        'module': None,
        'items': [
            {
                'id': 'ai_assistant_admin',
                'label': _('المساعد الذكي'),
                'url': 'ai_assistant:admin_dashboard',
                'icon': 'bi-robot',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'voice_assistant_dash',
                'label': _('المساعد الصوتي'),
                'url': 'voice_assistant:dashboard',
                'icon': 'bi-mic-fill',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'data_tools_section': {
        'id': 'data_tools_section',
        'parent': 'tech_control',
        'label': _('أدوات البيانات'),
        'icon': 'bi-database-gear',
        'order': 6,
        'module': None,
        'items': [
            {
                'id': 'data_import_dash',
                'label': _('استيراد البيانات'),
                'url': 'data_import:dashboard',
                'icon': 'bi-file-earmark-arrow-up',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'quick_access_dash',
                'label': _('الوصول السريع'),
                'url': 'quick_access:dashboard',
                'icon': 'bi-lightning-charge',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    # الموديولات المضافة - لضمان ظهور جميع الميزات في القائمة الجانبية
    # ═══════════════════════════════════════════════════════════════════

    # ─── التحليلات والتقارير (reporting_hub) ─────────────────────────
    'ai_analytics_section': {
        'id': 'ai_analytics_section',
        'parent': 'reporting_hub',
        'label': _('تحليلات AI'),
        'icon': 'bi-robot',
        'order': 4,
        'module': 'ai_analytics',
        'items': [
            {
                'id': 'ai_analytics_dashboard',
                'label': _('لوحة تحليلات AI'),
                'url': 'ai_analytics:dashboard',
                'icon': 'bi-robot',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'ai_sales_forecast',
                'label': _('توقعات المبيعات'),
                'url': 'ai_analytics:sales_forecast',
                'icon': 'bi-graph-up-arrow',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'ai_churn_prediction',
                'label': _('توقع فقدان العملاء'),
                'url': 'ai_analytics:churn_prediction',
                'icon': 'bi-person-dash',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'ai_inventory_analysis',
                'label': _('تحليل المخزون الذكي'),
                'url': 'ai_analytics:inventory_analysis',
                'icon': 'bi-box-seam',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'bi_section': {
        'id': 'bi_section',
        'parent': 'reporting_hub',
        'label': _('ذكاء الأعمال'),
        'icon': 'bi-bar-chart-steps',
        'order': 5,
        'module': 'business_intelligence',
        'items': [
            {
                'id': 'bi_dashboard',
                'label': _('لوحة ذكاء الأعمال'),
                'url': 'business_intelligence:dashboard',
                'icon': 'bi-bar-chart-steps',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'bi_dashboards_list',
                'label': _('اللوحات المخصصة'),
                'url': 'business_intelligence:dashboard_list',
                'icon': 'bi-grid-1x2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'report_builder_section': {
        'id': 'report_builder_section',
        'parent': 'reporting_hub',
        'label': _('منشئ التقارير'),
        'icon': 'bi-tools',
        'order': 6,
        'module': 'report_builder',
        'items': [
            {
                'id': 'report_builder_dashboard',
                'label': _('لوحة منشئ التقارير'),
                'url': 'report_builder:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'report_builder_list',
                'label': _('التقارير المنشأة'),
                'url': 'report_builder:list',
                'icon': 'bi-file-earmark-bar-graph',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'report_builder_create',
                'label': _('إنشاء تقرير جديد'),
                'url': 'report_builder:create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'reports_general_section': {
        'id': 'reports_general_section',
        'parent': 'reporting_hub',
        'label': _('التقارير العامة'),
        'icon': 'bi-clipboard-data',
        'order': 7,
        'module': 'reports',
        'items': [
            {
                'id': 'reports_dashboard',
                'label': _('لوحة التقارير'),
                'url': 'reports:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'custom_dashboard_section': {
        'id': 'custom_dashboard_section',
        'parent': 'reporting_hub',
        'label': _('لوحتي المخصصة'),
        'icon': 'bi-layout-text-window-reverse',
        'order': 8,
        'module': 'custom_dashboard',
        'items': [
            {
                'id': 'custom_dash',
                'label': _('لوحة مخصصة'),
                'url': 'custom_dashboard:dashboard',
                'icon': 'bi-layout-text-window-reverse',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'risk_management_section': {
        'id': 'risk_management_section',
        'parent': 'reporting_hub',
        'label': _('إدارة المخاطر'),
        'icon': 'bi-shield-exclamation',
        'order': 9,
        'module': 'risk_management',
        'items': [
            {
                'id': 'risk_dashboard',
                'label': _('لوحة المخاطر'),
                'url': 'risk_management:dashboard',
                'icon': 'bi-shield-exclamation',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'risk_list',
                'label': _('سجل المخاطر'),
                'url': 'risk_management:risks_list',
                'icon': 'bi-exclamation-triangle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'customer_profitability_section': {
        'id': 'customer_profitability_section',
        'parent': 'reporting_hub',
        'label': _('ربحية العملاء'),
        'icon': 'bi-pie-chart',
        'order': 10,
        'module': 'customer_profitability',
        'items': [
            {
                'id': 'customer_profitability_dash',
                'label': _('تحليل ربحية العملاء'),
                'url': 'customer_profitability:dashboard',
                'icon': 'bi-pie-chart',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'sales_forecasting_section': {
        'id': 'sales_forecasting_section',
        'parent': 'reporting_hub',
        'label': _('التنبؤ بالمبيعات'),
        'icon': 'bi-graph-up-arrow',
        'order': 11,
        'module': 'sales_forecasting',
        'items': [
            {
                'id': 'sales_forecasting_dash',
                'label': _('لوحة التنبؤ بالمبيعات'),
                'url': 'sales_forecasting:dashboard',
                'icon': 'bi-graph-up-arrow',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'forecast_list',
                'label': _('التنبؤات'),
                'url': 'sales_forecasting:forecast_list',
                'icon': 'bi-list-ul',
                'category': CATEGORY_REPORTS,
            },
        ],
    },

    # ─── التصنيع المتقدم (factory_ops) ──────────────────────────────
    'mattress_builder_section': {
        'id': 'mattress_builder_section',
        'parent': 'factory_ops',
        'label': _('بناء المراتب المخصصة'),
        'icon': 'bi-layers-half',
        'order': 4,
        'module': 'mattress_builder',
        'items': [
            {
                'id': 'mattress_builder_page',
                'label': _('أداة بناء المراتب'),
                'url': 'ecommerce:mattress_builder:home',
                'icon': 'bi-layers-half',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── التجاري والفروع (commercial) ───────────────────────────────
    'showrooms_section': {
        'id': 'showrooms_section',
        'parent': 'commercial',
        'label': _('المعارض'),
        'icon': 'bi-shop-window',
        'order': 13,
        'module': 'showrooms',
        'items': [
            {
                'id': 'showrooms_list',
                'label': _('قائمة المعارض'),
                'url': 'showrooms:showroom_list',
                'icon': 'bi-shop-window',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'showrooms_kpis',
                'label': _('مؤشرات أداء المعارض'),
                'url': 'showrooms:kpis',
                'icon': 'bi-bar-chart',
                'category': CATEGORY_REPORTS,
            },
        ],
    },
    'marketing_section': {
        'id': 'marketing_section',
        'parent': 'commercial',
        'label': _('التسويق والحملات'),
        'icon': 'bi-megaphone',
        'order': 14,
        'module': 'marketing_campaigns',
        'items': [
            {
                'id': 'marketing_dashboard',
                'label': _('لوحة التسويق'),
                'url': 'marketing_campaigns:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'campaign_list',
                'label': _('الحملات التسويقية'),
                'url': 'marketing_campaigns:campaign_list',
                'icon': 'bi-megaphone',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'campaign_create',
                'label': _('حملة جديدة'),
                'url': 'marketing_campaigns:campaign_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'loyalty_section': {
        'id': 'loyalty_section',
        'parent': 'commercial',
        'label': _('برنامج الولاء'),
        'icon': 'bi-heart-fill',
        'order': 15,
        'module': 'loyalty',
        'items': [
            {
                'id': 'loyalty_dashboard',
                'label': _('لوحة الولاء'),
                'url': 'loyalty:dashboard',
                'icon': 'bi-heart-fill',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'loyalty_programs',
                'label': _('برامج الولاء'),
                'url': 'loyalty:program_list',
                'icon': 'bi-gift',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'loyalty_members',
                'label': _('الأعضاء'),
                'url': 'loyalty:member_list',
                'icon': 'bi-people',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'smart_pricing_section': {
        'id': 'smart_pricing_section',
        'parent': 'commercial',
        'label': _('التسعير الذكي'),
        'icon': 'bi-tags',
        'order': 16,
        'module': 'smart_pricing',
        'items': [
            {
                'id': 'smart_pricing_dashboard',
                'label': _('لوحة التسعير'),
                'url': 'smart_pricing:dashboard',
                'icon': 'bi-tags',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'pricing_rules',
                'label': _('قواعد التسعير'),
                'url': 'smart_pricing:rules_list',
                'icon': 'bi-sliders',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'woocommerce_section': {
        'id': 'woocommerce_section',
        'parent': 'commercial',
        'label': _('تكامل WooCommerce'),
        'icon': 'bi-wordpress',
        'order': 17,
        'module': 'woocommerce_integration',
        'items': [
            {
                'id': 'woocommerce_dashboard',
                'label': _('لوحة WooCommerce'),
                'url': 'woocommerce_integration:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'woocommerce_config',
                'label': _('إعدادات التكامل'),
                'url': 'woocommerce_integration:config_list',
                'icon': 'bi-gear',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'contracting_section': {
        'id': 'contracting_section',
        'parent': 'commercial',
        'label': _('المقاولات'),
        'icon': 'bi-building-gear',
        'order': 18,
        'module': 'contracting',
        'items': [
            {
                'id': 'contracting_dashboard',
                'label': _('لوحة المقاولات'),
                'url': 'contracting:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'contracting_projects',
                'label': _('مشاريع المقاولات'),
                'url': 'contracting:project_list',
                'icon': 'bi-building-gear',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'contracting_project_create',
                'label': _('مشروع مقاولات جديد'),
                'url': 'contracting:project_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── المالية المتقدمة (finance_hr) ──────────────────────────────
    'fixed_assets_section': {
        'id': 'fixed_assets_section',
        'parent': 'finance_hr',
        'label': _('الأصول الثابتة'),
        'icon': 'bi-building-fill-gear',
        'order': 10,
        'module': 'fixed_assets',
        'items': [
            {
                'id': 'asset_list',
                'label': _('قائمة الأصول'),
                'url': 'fixed_assets:asset_list',
                'icon': 'bi-building-fill-gear',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'asset_create',
                'label': _('إضافة أصل'),
                'url': 'fixed_assets:asset_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'taxes_section': {
        'id': 'taxes_section',
        'parent': 'finance_hr',
        'label': _('الضرائب'),
        'icon': 'bi-percent',
        'order': 11,
        'module': 'taxes',
        'items': [
            {
                'id': 'taxes_dashboard',
                'label': _('لوحة الضرائب'),
                'url': 'taxes:dashboard',
                'icon': 'bi-percent',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'tax_settings',
                'label': _('إعدادات الضرائب'),
                'url': 'taxes:settings',
                'icon': 'bi-gear',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'installments_section': {
        'id': 'installments_section',
        'parent': 'finance_hr',
        'label': _('التقسيط'),
        'icon': 'bi-calendar2-week',
        'order': 12,
        'module': 'installments',
        'items': [
            {
                'id': 'installments_dashboard',
                'label': _('لوحة التقسيط'),
                'url': 'installments:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'installment_plans',
                'label': _('خطط التقسيط'),
                'url': 'installments:plan_list',
                'icon': 'bi-calendar2-week',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'installment_plan_create',
                'label': _('خطة تقسيط جديدة'),
                'url': 'installments:plan_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'projects_section': {
        'id': 'projects_section',
        'parent': 'finance_hr',
        'label': _('إدارة المشاريع'),
        'icon': 'bi-kanban',
        'order': 13,
        'module': 'projects',
        'items': [
            {
                'id': 'projects_dashboard',
                'label': _('لوحة المشاريع'),
                'url': 'projects:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'project_list',
                'label': _('قائمة المشاريع'),
                'url': 'projects:project_list',
                'icon': 'bi-kanban',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'project_create',
                'label': _('مشروع جديد'),
                'url': 'projects:project_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'attendance_section': {
        'id': 'attendance_section',
        'parent': 'finance_hr',
        'label': _('الحضور والانصراف'),
        'icon': 'bi-fingerprint',
        'order': 14,
        'module': 'attendance',
        'items': [
            {
                'id': 'attendance_dashboard',
                'label': _('لوحة الحضور'),
                'url': 'attendance:dashboard',
                'icon': 'bi-fingerprint',
                'category': CATEGORY_REPORTS,
            },
        ],
    },

    # ─── الشحن والخدمات اللوجستية (logistics) ───────────────────────
    'exports_section': {
        'id': 'exports_section',
        'parent': 'logistics',
        'label': _('التصدير'),
        'icon': 'bi-box-arrow-up-right',
        'order': 11,
        'module': 'exports',
        'items': [
            {
                'id': 'export_list',
                'label': _('قائمة التصديرات'),
                'url': 'exports:export_list',
                'icon': 'bi-box-arrow-up-right',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'export_create',
                'label': _('طلب تصدير جديد'),
                'url': 'exports:export_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'helpdesk_section': {
        'id': 'helpdesk_section',
        'parent': 'logistics',
        'label': _('مركز الدعم'),
        'icon': 'bi-headset',
        'order': 12,
        'module': 'helpdesk',
        'items': [
            {
                'id': 'helpdesk_dashboard',
                'label': _('لوحة الدعم'),
                'url': 'helpdesk:dashboard',
                'icon': 'bi-headset',
                'category': CATEGORY_REPORTS,
                'badge_source': 'open_tickets_count',
            },
            {
                'id': 'helpdesk_tickets',
                'label': _('التذاكر'),
                'url': 'helpdesk:ticket_list',
                'icon': 'bi-ticket-detailed',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'helpdesk_create',
                'label': _('تذكرة جديدة'),
                'url': 'helpdesk:ticket_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'helpdesk_kb',
                'label': _('قاعدة المعرفة'),
                'url': 'helpdesk:knowledge_base',
                'icon': 'bi-book',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'home_services_section': {
        'id': 'home_services_section',
        'parent': 'logistics',
        'label': _('الخدمات المنزلية'),
        'icon': 'bi-house-gear',
        'order': 13,
        'module': 'home_services',
        'items': [
            {
                'id': 'home_services_page',
                'label': _('صفحة الخدمات المنزلية'),
                'url': 'home_services:services_home',
                'icon': 'bi-house-gear',
                'category': CATEGORY_DAILY,
            },
        ],
    },

    # ─── التواصل والتعاون (tech_control) ────────────────────────────
    'communication_section': {
        'id': 'communication_section',
        'parent': 'tech_control',
        'label': _('التواصل والتعاون'),
        'icon': 'bi-chat-dots-fill',
        'order': 7,
        'module': None,
        'items': [
            {
                'id': 'internal_chat_home',
                'label': _('الدردشة الداخلية'),
                'url': 'internal_chat:home',
                'icon': 'bi-chat-left-text',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'video_calls_dash',
                'label': _('مكالمات الفيديو'),
                'url': 'video_calls:dashboard',
                'icon': 'bi-camera-video',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'whatsapp_dashboard',
                'label': _('واتساب'),
                'url': 'whatsapp_integration:dashboard',
                'icon': 'bi-whatsapp',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'whatsapp_ai_dash',
                'label': _('واتساب AI'),
                'url': 'whatsapp_ai:dashboard',
                'icon': 'bi-whatsapp',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'collaborative_docs_dash',
                'label': _('المستندات التعاونية'),
                'url': 'collaborative_docs:dashboard',
                'icon': 'bi-file-earmark-text',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'tasks_section': {
        'id': 'tasks_section',
        'parent': 'tech_control',
        'label': _('المهام والتذكيرات'),
        'icon': 'bi-check2-square',
        'order': 8,
        'module': 'tasks',
        'items': [
            {
                'id': 'tasks_dashboard',
                'label': _('لوحة المهام'),
                'url': 'tasks:dashboard',
                'icon': 'bi-speedometer2',
                'category': CATEGORY_REPORTS,
            },
            {
                'id': 'tasks_list',
                'label': _('قائمة المهام'),
                'url': 'tasks:list',
                'icon': 'bi-check2-square',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'task_create',
                'label': _('مهمة جديدة'),
                'url': 'tasks:task_create',
                'icon': 'bi-plus-circle',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'notifications_section': {
        'id': 'notifications_section',
        'parent': 'tech_control',
        'label': _('الإشعارات'),
        'icon': 'bi-bell-fill',
        'order': 9,
        'module': None,
        'items': [
            {
                'id': 'notifications_list',
                'label': _('كل الإشعارات'),
                'url': 'notifications:list',
                'icon': 'bi-bell',
                'category': CATEGORY_DAILY,
                'badge_source': 'unread_notifications_count',
            },
            {
                'id': 'advanced_notifications_dash',
                'label': _('الإشعارات المتقدمة'),
                'url': 'advanced_notifications:dashboard',
                'icon': 'bi-bell-slash',
                'category': CATEGORY_MASTER,
            },
            {
                'id': 'sound_notifications_settings',
                'label': _('إعدادات الأصوات'),
                'url': 'sound_notifications:settings',
                'icon': 'bi-volume-up',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'cloud_backup_section': {
        'id': 'cloud_backup_section',
        'parent': 'tech_control',
        'label': _('النسخ الاحتياطي السحابي'),
        'icon': 'bi-cloud-arrow-up',
        'order': 10,
        'module': 'cloud_backup',
        'items': [
            {
                'id': 'cloud_backup_dashboard',
                'label': _('لوحة النسخ الاحتياطي'),
                'url': 'cloud_backup:dashboard',
                'icon': 'bi-cloud-arrow-up',
                'category': CATEGORY_DAILY,
            },
        ],
    },
    'cms_section': {
        'id': 'cms_section',
        'parent': 'tech_control',
        'label': _('إدارة المحتوى'),
        'icon': 'bi-file-richtext',
        'order': 11,
        'module': 'cms',
        'items': [
            {
                'id': 'cms_dashboard',
                'label': _('لوحة المحتوى'),
                'url': 'cms:dashboard',
                'icon': 'bi-file-richtext',
                'category': CATEGORY_DAILY,
            },
            {
                'id': 'cms_pages',
                'label': _('إدارة الصفحات'),
                'url': 'cms:page_list',
                'icon': 'bi-files',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'theme_section': {
        'id': 'theme_section',
        'parent': 'tech_control',
        'label': _('تخصيص المظهر'),
        'icon': 'bi-palette',
        'order': 12,
        'module': None,
        'items': [
            {
                'id': 'theme_settings',
                'label': _('إعدادات المظهر'),
                'url': 'theme_system:settings',
                'icon': 'bi-palette',
                'category': CATEGORY_MASTER,
            },
        ],
    },
    'smartwatch_section': {
        'id': 'smartwatch_section',
        'parent': 'tech_control',
        'label': _('الساعة الذكية'),
        'icon': 'bi-smartwatch',
        'order': 13,
        'module': 'smartwatch',
        'items': [
            {
                'id': 'smartwatch_dashboard',
                'label': _('لوحة الساعة الذكية'),
                'url': 'smartwatch:dashboard',
                'icon': 'bi-smartwatch',
                'category': CATEGORY_DAILY,
            },
        ],
    },
}


# ─── Helper Functions ──────────────────────────────────────

def get_parent_groups():
    """Return ordered list of parent groups."""
    return sorted(PARENT_GROUPS, key=lambda g: g['order'])


def get_sections_for_parent(parent_id):
    """Return sections belonging to a specific parent group, sorted by order."""
    sections = [
        s for s in SIDEBAR_SECTIONS.values()
        if s.get('parent') == parent_id
    ]
    return sorted(sections, key=lambda s: s.get('order', 99))


def get_all_items_flat():
    """Return a flat list of all items for global search indexing."""
    items = []
    for section in SIDEBAR_SECTIONS.values():
        for item in section.get('items', []):
            items.append({
                'id': item['id'],
                'label': str(item['label']),
                'url': item.get('url', ''),
                'icon': item.get('icon', ''),
                'section_label': str(section['label']),
                'parent': section.get('parent', ''),
            })
    return items
