# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('widget_type', models.CharField(choices=[('stats', 'إحصائيات'), ('tasks', 'مهام'), ('calendar', 'تقويم'), ('messages', 'رسائل'), ('weather', 'الطقس'), ('health', 'الصحة')], max_length=20, verbose_name='نوع الويدجت')),
                ('data_source', models.CharField(blank=True, max_length=200, verbose_name='مصدر البيانات')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='فترة التحديث (ثانية)')),
                ('size', models.CharField(default='small', max_length=20, verbose_name='الحجم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'ويدجت ساعة',
                'verbose_name_plural': 'ويدجتات الساعات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('action_type', models.CharField(choices=[('check_in', 'تسجيل حضور'), ('check_out', 'تسجيل انصراف'), ('approve', 'موافقة'), ('reject', 'رفض'), ('call', 'اتصال'), ('message', 'رسالة'), ('timer', 'مؤقت'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع الإجراء')),
                ('icon', models.CharField(default='fas fa-bolt', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='اللون')),
                ('api_endpoint', models.CharField(blank=True, max_length=200, verbose_name='نقطة API')),
                ('request_method', models.CharField(default='POST', max_length=10, verbose_name='طريقة الطلب')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('is_global', models.BooleanField(default=False, verbose_name='متاح للجميع')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('available_for', models.ManyToManyField(blank=True, related_name='watch_quick_actions', to=settings.AUTH_USER_MODEL, verbose_name='متاح لـ')),
            ],
            options={
                'verbose_name': 'إجراء سريع',
                'verbose_name_plural': 'الإجراءات السريعة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WatchDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('apple_watch', 'Apple Watch'), ('galaxy_watch', 'Samsung Galaxy Watch'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('wear_os', 'Wear OS'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الجهاز')),
                ('device_id', models.CharField(max_length=200, unique=True, verbose_name='معرف الجهاز')),
                ('access_token', models.TextField(blank=True, verbose_name='رمز الوصول')),
                ('refresh_token', models.TextField(blank=True, verbose_name='رمز التحديث')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_connected', models.BooleanField(default=False, verbose_name='متصل')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='الإشعارات مفعلة')),
                ('quick_actions_enabled', models.BooleanField(default=True, verbose_name='الإجراءات السريعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ساعة ذكية',
                'verbose_name_plural': 'الساعات الذكية',
            },
        ),
        migrations.CreateModel(
            name='WatchActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, verbose_name='اسم الإجراء')),
                ('action_type', models.CharField(max_length=20, verbose_name='نوع الإجراء')),
                ('is_success', models.BooleanField(default=True, verbose_name='ناجح')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartwatch.quickaction', verbose_name='الإجراء')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='smartwatch.watchdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل إجراء',
                'verbose_name_plural': 'سجل الإجراءات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'تنبيه'), ('reminder', 'تذكير'), ('message', 'رسالة'), ('task', 'مهمة'), ('approval', 'موافقة'), ('call', 'مكالمة')], max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('action_url', models.URLField(blank=True, verbose_name='رابط الإجراء')),
                ('action_buttons', models.JSONField(blank=True, default=list, verbose_name='أزرار الإجراءات')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='smartwatch.watchdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'إشعار ساعة',
                'verbose_name_plural': 'إشعارات الساعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_task', models.BooleanField(default=True, verbose_name='إشعار المهام')),
                ('notify_on_message', models.BooleanField(default=True, verbose_name='إشعار الرسائل')),
                ('notify_on_approval', models.BooleanField(default=True, verbose_name='إشعار الموافقات')),
                ('notify_on_reminder', models.BooleanField(default=True, verbose_name='إشعار التذكيرات')),
                ('vibration_enabled', models.BooleanField(default=True, verbose_name='الاهتزاز')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='الصوت')),
                ('do_not_disturb_start', models.TimeField(blank=True, null=True, verbose_name='بداية عدم الإزعاج')),
                ('do_not_disturb_end', models.TimeField(blank=True, null=True, verbose_name='نهاية عدم الإزعاج')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('enabled_widgets', models.ManyToManyField(blank=True, related_name='enabled_for', to='smartwatch.watchdashboardwidget', verbose_name='الويدجتات المفعلة')),
                ('favorite_actions', models.ManyToManyField(blank=True, related_name='favorited_by', to='smartwatch.quickaction', verbose_name='الإجراءات المفضلة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات ساعة',
                'verbose_name_plural': 'إعدادات الساعات',
            },
        ),
    ]
