# Generated by Django 5.2.9 on 2026-03-01 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الضمان')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('expiry_date', models.DateField(verbose_name='تاريخ انتهاء الضمان')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('void', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='هاتف العميل')),
                ('customer_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_warranties', to=settings.AUTH_USER_MODEL, verbose_name='فعّله')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_cards', to='sales.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_cards', to='sales.salesinvoice', verbose_name='الفاتورة')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_cards', to='sales.salesinvoiceline', verbose_name='سطر الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_cards', to='inventory.product', verbose_name='المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'بطاقة ضمان',
                'verbose_name_plural': 'بطاقات الضمان',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('claim_date', models.DateField(verbose_name='تاريخ المطالبة')),
                ('issue_description', models.TextField(verbose_name='وصف المشكلة')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'جاري'), ('resolved', 'محلولة'), ('rejected', 'مرفوضة')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='warranty.warrantycard', verbose_name='بطاقة الضمان')),
            ],
            options={
                'verbose_name': 'مطالبة ضمان',
                'verbose_name_plural': 'مطالبات الضمان',
                'ordering': ['-claim_date'],
            },
        ),
    ]
