# Generated by Django 6.0 on 2026-01-04 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرع/المعرض')),
                ('code', models.CharField(help_text='كود فريد للفرع أو المعرض', max_length=20, unique=True, verbose_name='الكود')),
                ('branch_type', models.CharField(choices=[('branch', 'فرع'), ('showroom', 'معرض'), ('warehouse', 'مخزن'), ('outlet', 'منفذ بيع')], default='branch', max_length=20, verbose_name='النوع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_main', models.BooleanField(default=False, verbose_name='الفرع/المعرض الرئيسي')),
                ('can_sell', models.BooleanField(default=True, verbose_name='يمكنه البيع')),
                ('can_purchase', models.BooleanField(default=False, verbose_name='يمكنه الشراء')),
                ('has_inventory', models.BooleanField(default=True, verbose_name='له مخزون خاص')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية الدوام')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الدوام')),
                ('working_days', models.CharField(default='0,1,2,3,4,5', help_text='أرقام الأيام مفصولة بفواصل (0=الأحد)', max_length=50, verbose_name='أيام العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='المدير المسؤول')),
                ('parent_branch', models.ForeignKey(blank=True, help_text='المعرض أو المنفذ التابع لفرع رئيسي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='branches.branch', verbose_name='الفرع الرئيسي')),
            ],
            options={
                'verbose_name': 'فرع/معرض',
                'verbose_name_plural': 'الفروع والمعارض',
                'ordering': ['branch_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في الانتظار'), ('approved', 'معتمد'), ('in_transit', 'في الطريق'), ('received', 'مستلم'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('transfer_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='branches.branch', verbose_name='من فرع/معرض')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='branches.branch', verbose_name='إلى فرع/معرض')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
