# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفرع')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('branch_type', models.CharField(choices=[('main', 'فرع رئيسي'), ('branch', 'فرع'), ('warehouse', 'مستودع'), ('showroom', 'صالة عرض'), ('factory', 'مصنع')], default='branch', max_length=20, verbose_name='نوع الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='المنطقة/الإمارة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='الفاكس')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_main', models.BooleanField(default=False, verbose_name='هل هو الفرع الرئيسي؟')),
                ('is_warehouse', models.BooleanField(default=False, verbose_name='هل هو مستودع؟')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بالمخزون السالب')),
                ('auto_approve_transfers', models.BooleanField(default=False, verbose_name='الموافقة التلقائية على التحويلات')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الافتتاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='branches.branch', verbose_name='الفرع الرئيسي')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['code'],
                'permissions': [('view_branch_stock', 'عرض مخزون الفرع'), ('manage_branch_transfers', 'إدارة تحويلات الفرع'), ('view_branch_reports', 'عرض تقارير الفرع'), ('manage_all_branches', 'إدارة جميع الفروع')],
            },
        ),
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('transfer_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('expected_arrival', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول المتوقع')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول الفعلي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('in_transit', 'في الطريق'), ('received', 'مستلم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='طريقة الشحن')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الشحن')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التتبع')),
                ('carrier_name', models.CharField(blank=True, max_length=200, verbose_name='اسم شركة الشحن')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='branches.branch', verbose_name='من فرع')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='branches.branch', verbose_name='إلى فرع')),
            ],
            options={
                'verbose_name': 'تحويل بين فروع',
                'verbose_name_plural': 'التحويلات بين الفروع',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية المطلوبة')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المستلمة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الوحدة')),
                ('is_received', models.BooleanField(default=False, verbose_name='مستلم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branches.branchtransfer', verbose_name='التحويل')),
            ],
            options={
                'verbose_name': 'بند تحويل',
                'verbose_name_plural': 'بنود التحويلات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='المنصب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'موظف فرع',
                'verbose_name_plural': 'موظفو الفروع',
                'ordering': ['-is_active', 'user__username'],
                'unique_together': {('branch', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['transfer_number'], name='branches_br_transfe_86ca2f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['from_branch', 'status'], name='branches_br_from_br_083d43_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['to_branch', 'status'], name='branches_br_to_bran_d71161_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['transfer_date'], name='branches_br_transfe_a5ae76_idx'),
        ),
    ]
