# Generated by Django 5.2.5 on 2026-01-03 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0025_add_ecommerce_fields'),
        ('partners', '0011_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('device_identifier', models.CharField(blank=True, max_length=120, verbose_name='معرف الجهاز')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
            },
        ),
        migrations.CreateModel(
            name='BranchExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('category', models.CharField(choices=[('salary', 'رواتب'), ('wages', 'أجور'), ('electricity', 'كهرباء'), ('water', 'مياه'), ('rent', 'إيجار'), ('operating', 'مشتريات تشغيل'), ('advance', 'سُلف'), ('maintenance', 'صيانة'), ('marketing', 'تسويق'), ('other', 'أخرى')], default='other', max_length=40, verbose_name='نوع المصروف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'قيد الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يحتاج موافقة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='branches/expenses/', verbose_name='مرفق/إيصال')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('rejection_note', models.CharField(blank=True, max_length=255, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مصروف فرع',
                'verbose_name_plural': 'مصروفات الفروع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='أول يوم في الشهر', verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('entry_type', models.CharField(choices=[('salary', 'راتب'), ('bonus', 'مكافأة'), ('commission', 'عمولة'), ('deduction', 'خصم'), ('advance', 'سلفة')], default='salary', max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قيد رواتب فرع',
                'verbose_name_plural': 'قيود رواتب الفروع',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='BranchPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='رقم المستند')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='branches/purchases/', verbose_name='فاتورة/مرفق')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'شراء مباشر للفرع',
                'verbose_name_plural': 'مشتريات مباشرة للفروع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة')),
            ],
            options={
                'verbose_name': 'بند شراء فرع',
                'verbose_name_plural': 'بنود شراء الفرع',
            },
        ),
        migrations.CreateModel(
            name='BranchShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الوردية')),
                ('start_time', models.TimeField(verbose_name='بداية الوردية')),
                ('end_time', models.TimeField(verbose_name='نهاية الوردية')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الراحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وردية فرع',
                'verbose_name_plural': 'ورديات الفروع',
                'ordering': ['branch', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BranchShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تعيين وردية',
                'verbose_name_plural': 'تعيينات الورديات',
            },
        ),
        migrations.CreateModel(
            name='BranchStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية (+/-)')),
                ('movement_type', models.CharField(choices=[('purchase_in', 'شراء مباشر'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('adjustment', 'تسوية مخزون'), ('sale', 'بيع'), ('return_in', 'مرتجع'), ('expense_consume', 'صرف مصروف')], max_length=30, verbose_name='نوع الحركة')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'حركة مخزون فرع',
                'verbose_name_plural': 'حركات مخزون الفروع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=80, unique=True, verbose_name='التوكن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('revoked', models.BooleanField(default=False, verbose_name='ملغي')),
            ],
            options={
                'verbose_name': 'توكن جهاز',
                'verbose_name_plural': 'توكنات الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('identifier', models.CharField(help_text='Serial / MAC / UUID', max_length=120, unique=True, verbose_name='المعرف')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='مفتاح API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'جهاز نقطة بيع',
                'verbose_name_plural': 'أجهزة نقاط البيع',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code'], 'permissions': [('view_branch_stock', 'عرض مخزون الفرع'), ('manage_branch_transfers', 'إدارة تحويلات الفرع'), ('view_branch_reports', 'عرض تقارير الفرع'), ('manage_all_branches', 'إدارة جميع الفروع'), ('manage_branch_expenses', 'إدارة مصروفات الفرع'), ('approve_branch_expenses', 'اعتماد مصروفات الفرع'), ('manage_branch_pos', 'إدارة أجهزة نقاط البيع')], 'verbose_name': 'فرع', 'verbose_name_plural': 'الفروع'},
        ),
        migrations.AlterModelOptions(
            name='branchstaff',
            options={'ordering': ['-is_active', 'role', 'user__username'], 'verbose_name': 'موظف فرع', 'verbose_name_plural': 'موظفو الفروع'},
        ),
        migrations.AlterModelOptions(
            name='branchtransfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'تحويل بين الفروع', 'verbose_name_plural': 'تحويلات بين الفروع'},
        ),
        migrations.AlterModelOptions(
            name='branchtransferitem',
            options={'verbose_name': 'بند تحويل', 'verbose_name_plural': 'بنود التحويل'},
        ),
        migrations.RemoveIndex(
            model_name='branchtransfer',
            name='branches_br_from_br_083d43_idx',
        ),
        migrations.RemoveIndex(
            model_name='branchtransfer',
            name='branches_br_to_bran_d71161_idx',
        ),
        migrations.RemoveIndex(
            model_name='branchtransfer',
            name='branches_br_transfe_a5ae76_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_warehouse',
        ),
        migrations.RemoveField(
            model_name='branchtransfer',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='branchtransfer',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='branchtransfer',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='branchtransfer',
            name='tracking_number',
        ),
        migrations.AlterUniqueTogether(
            name='branchtransferitem',
            unique_together={('transfer', 'product')},
        ),
        migrations.AddField(
            model_name='branch',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120, verbose_name='مسؤول التواصل'),
        ),
        migrations.AddField(
            model_name='branch',
            name='expense_approval_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الأقصى للمصروفات بدون موافقة', max_digits=12, verbose_name='حد اعتماد المصروفات'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='inventory.location', verbose_name='الموقع المخزني'),
        ),
        migrations.AddField(
            model_name='branch',
            name='require_expense_approval',
            field=models.BooleanField(default=True, verbose_name='يتطلب موافقة للمصروفات'),
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='can_cross_access',
            field=models.BooleanField(default=False, verbose_name='صلاحية الوصول لجميع الفروع'),
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='extra_perms',
            field=models.JSONField(blank=True, default=list, help_text='مثال: ["pos.export","inventory.view"]', verbose_name='صلاحيات إضافية'),
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير'), ('supervisor', 'مشرف'), ('cashier', 'أمين صندوق'), ('sales', 'مبيعات'), ('storekeeper', 'أمين مخزن'), ('warehouse_worker', 'عامل مستودع'), ('accountant', 'محاسب'), ('hr', 'شؤون موظفين'), ('call_center', 'كول سنتر'), ('customer_service', 'خدمة عملاء'), ('porter', 'حامل/عامل تحميل'), ('pantry', 'بانتري/ضيافة'), ('worker', 'عامل'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('main', 'فرع رئيسي'), ('branch', 'فرع'), ('warehouse', 'مستودع'), ('showroom', 'معرض/صالة عرض'), ('factory', 'مصنع'), ('store', 'متجر')], default='branch', max_length=20, verbose_name='نوع الفرع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة/المحافظة'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transfer_approvals', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transfer_receipts', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='branchtransferitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='branchtransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_transfer_items', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='branchtransferitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='branchtransferitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة'),
        ),
        migrations.AlterField(
            model_name='branchtransferitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='branches_br_code_9f8882_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['branch_type'], name='branches_br_branch__395ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='branches_br_is_acti_22f294_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstaff',
            index=models.Index(fields=['branch', 'user'], name='branches_br_branch__048c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstaff',
            index=models.Index(fields=['user', 'is_active'], name='branches_br_user_id_8f3321_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['status'], name='branches_br_status_67a2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['from_branch', 'to_branch'], name='branches_br_from_br_0d4610_idx'),
        ),
        migrations.AddField(
            model_name='branchattendance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='branches.branchstaff', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='branchattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_attendance', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='branchexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='branchexpense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='branchpayroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_payroll_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='branchpayroll',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchpayroll',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='branches.branchstaff', verbose_name='موظف الفرع'),
        ),
        migrations.AddField(
            model_name='branchpayroll',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_payroll_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='branchpurchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchases', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchpurchase',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_purchases_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أكد بواسطة'),
        ),
        migrations.AddField(
            model_name='branchpurchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_purchases_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='branchpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_purchases', to='partners.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='branchpurchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='branchpurchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branches.branchpurchase', verbose_name='المستند'),
        ),
        migrations.AddField(
            model_name='branchshift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchshiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='branches.branchstaff', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='branchshiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='branches.branchshift', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='branchstockmovement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='branchstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='branchstockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock_movements', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='deviceauthtoken',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='branches.posdevice', verbose_name='الجهاز'),
        ),
        migrations.RemoveField(
            model_name='branchtransferitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branchtransferitem',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='branchtransferitem',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='branchattendance',
            index=models.Index(fields=['branch', 'date'], name='branches_br_branch__006c33_idx'),
        ),
        migrations.AddIndex(
            model_name='branchattendance',
            index=models.Index(fields=['employee', 'date'], name='branches_br_employe_b7458c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchattendance',
            unique_together={('branch', 'employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['branch', 'status'], name='branches_br_branch__f86cad_idx'),
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['category'], name='branches_br_categor_d710d7_idx'),
        ),
        migrations.AddIndex(
            model_name='branchexpense',
            index=models.Index(fields=['date'], name='branches_br_date_3d292f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpayroll',
            index=models.Index(fields=['branch', 'period'], name='branches_br_branch__6b1df2_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpayroll',
            index=models.Index(fields=['status'], name='branches_br_status_1b7362_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpurchase',
            index=models.Index(fields=['branch', 'status'], name='branches_br_branch__34dc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpurchase',
            index=models.Index(fields=['number'], name='branches_br_number_8bff51_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchpurchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='branch_purchase_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='branchshift',
            index=models.Index(fields=['branch', 'is_active'], name='branches_br_branch__bf11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='branchshiftassignment',
            index=models.Index(fields=['employee', 'active'], name='branches_br_employe_57f005_idx'),
        ),
        migrations.AddIndex(
            model_name='branchshiftassignment',
            index=models.Index(fields=['shift', 'day_of_week'], name='branches_br_shift_i_37a40b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchshiftassignment',
            unique_together={('shift', 'employee', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='branchstockmovement',
            index=models.Index(fields=['branch', 'movement_type'], name='branches_br_branch__e82934_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstockmovement',
            index=models.Index(fields=['product'], name='branches_br_product_2ab76c_idx'),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['branch', 'is_active'], name='branches_po_branch__dbb29b_idx'),
        ),
        migrations.AddIndex(
            model_name='posdevice',
            index=models.Index(fields=['identifier'], name='branches_po_identif_ce00af_idx'),
        ),
    ]
