# Generated by Django 5.2.5 on 2026-01-05 13:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_merged_with_showrooms'),
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplenishmentRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('apply_to_all_showrooms', models.BooleanField(default=False, verbose_name='تطبيق على جميع المعارض')),
                ('apply_to_all_products', models.BooleanField(default=False, verbose_name='تطبيق على جميع المنتجات')),
                ('trigger_at_reorder_point', models.BooleanField(default=True, verbose_name='التشغيل عند نقطة إعادة الطلب')),
                ('trigger_at_minimum', models.BooleanField(default=False, verbose_name='التشغيل عند الحد الأدنى')),
                ('replenish_to_maximum', models.BooleanField(default=True, verbose_name='التموين للحد الأقصى')),
                ('fixed_replenish_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='كمية تموين ثابتة')),
                ('check_frequency_hours', models.PositiveIntegerField(default=24, verbose_name='تكرار الفحص (ساعات)')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('notify_on_trigger', models.BooleanField(default=True, verbose_name='إشعار عند التشغيل')),
                ('notification_emails', models.TextField(blank=True, help_text='بريد إلكتروني واحد في كل سطر', verbose_name='بريد الإشعارات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_replenishment_rules', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('target_branches', models.ManyToManyField(blank=True, related_name='auto_replenishment_rules', to='branches.branch', verbose_name='الفروع المستهدفة')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='auto_replenishment_rules', to='inventory.category', verbose_name='فئات المنتجات')),
                ('target_products', models.ManyToManyField(blank=True, related_name='auto_replenishment_rules', to='inventory.product', verbose_name='المنتجات المستهدفة')),
            ],
            options={
                'verbose_name': 'قاعدة تموين تلقائي',
                'verbose_name_plural': 'قواعد التموين التلقائي',
            },
        ),
        migrations.CreateModel(
            name='ShowroomReplenishmentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('processing', 'قيد التنفيذ'), ('shipped', 'تم الشحن'), ('received', 'مستلم'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'مرتفع'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_approvals', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_requests', to='branches.branch', verbose_name='المعرض')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_requests', to='branches.branchtransfer', verbose_name='أمر التحويل')),
            ],
            options={
                'verbose_name': 'طلب تموين معرض',
                'verbose_name_plural': 'طلبات تموين المعارض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRequestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المطلوبة')),
                ('approved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية المعتمدة')),
                ('shipped_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية المشحونة')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الكمية المستلمة')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='المخزون الحالي')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='نقطة إعادة الطلب')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_items', to='inventory.product', verbose_name='المنتج')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branches.showroomreplenishmentrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'بند طلب تموين',
                'verbose_name_plural': 'بنود طلبات التموين',
            },
        ),
        migrations.CreateModel(
            name='BranchStockSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الحد الأدنى')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='نقطة إعادة الطلب')),
                ('maximum_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='الحد الأقصى')),
                ('auto_replenish', models.BooleanField(default=False, verbose_name='تموين تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_settings', to='branches.branch', verbose_name='الفرع')),
                ('preferred_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='branches.branch', verbose_name='مصدر التموين المفضل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock_settings', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'إعدادات مخزون فرع',
                'verbose_name_plural': 'إعدادات مخزون الفروع',
                'indexes': [models.Index(fields=['branch', 'product'], name='branches_br_branch__49f880_idx')],
                'unique_together': {('branch', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='showroomreplenishmentrequest',
            index=models.Index(fields=['branch', 'status'], name='branches_sh_branch__224387_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomreplenishmentrequest',
            index=models.Index(fields=['request_date'], name='branches_sh_request_d8376d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentrequestitem',
            unique_together={('request', 'product')},
        ),
    ]
