# Generated by Django 5.2.5 on 2026-01-09 22:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_autoreplenishmentrule_showroomreplenishmentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='annual_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإيجار السنوي'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة العقد (بالأشهر)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/branches/', verbose_name='ملف العقد'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات العقد'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العقد'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_reminder_days',
            field=models.PositiveIntegerField(default=30, verbose_name='التنبيه قبل انتهاء العقد (أيام)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AddField(
            model_name='branch',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مبلغ التأمين'),
        ),
        migrations.AddField(
            model_name='branch',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإيجار الشهري'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='حساب المالك البنكي'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم هوية المالك'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المالك'),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='هاتف المالك'),
        ),
        migrations.AddField(
            model_name='branch',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'مملوك'), ('rented', 'مؤجر'), ('temporary', 'مؤقت')], default='owned', max_length=20, verbose_name='نوع الملكية'),
        ),
        migrations.AddField(
            model_name='branch',
            name='property_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مساحة العقار (م²)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='property_type',
            field=models.CharField(blank=True, help_text='مثال: معرض تجاري، مستودع، فيلا، شقة، أرض', max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.AddField(
            model_name='branch',
            name='rent_due_day',
            field=models.PositiveIntegerField(default=1, help_text='اليوم من الشهر الذي يستحق فيه الإيجار', verbose_name='يوم استحقاق الإيجار'),
        ),
    ]
