# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_property_contract_fields'),
        ('inventory', '0041_alter_supplierproductprice_purchase_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterBranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('status', models.CharField(choices=[('requested', 'مطلوب'), ('approved', 'معتمد'), ('in_transit', 'قيد النقل'), ('received', 'مستلم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='requested', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التحويل')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('ship_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('receive_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_branch_transfers', to=settings.AUTH_USER_MODEL, verbose_name='اعتُمد بواسطة')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_transfers_out', to='branches.branch', verbose_name='من فرع')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_branch_transfers', to=settings.AUTH_USER_MODEL, verbose_name='استُلم بواسطة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='طُلب بواسطة')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_transfers_in', to='branches.branch', verbose_name='إلى فرع')),
            ],
            options={
                'verbose_name': 'تحويل بين فروع',
                'verbose_name_plural': 'تحويلات بين الفروع',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='InterBranchTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المستلمة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branches.interbranchtransfer', verbose_name='التحويل')),
            ],
            options={
                'verbose_name': 'بند تحويل',
                'verbose_name_plural': 'بنود التحويل',
            },
        ),
        migrations.CreateModel(
            name='BranchProfitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='بتنسيق YYYY-MM', max_length=7, verbose_name='الفترة')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الإيرادات')),
                ('returns_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المرتجعات')),
                ('cost_of_goods', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة البضاعة المباعة')),
                ('salary_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصاريف الرواتب')),
                ('rent_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصاريف الإيجار')),
                ('utilities_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصاريف المرافق')),
                ('marketing_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصاريف التسويق')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصاريف أخرى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحساب')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_reports', to='branches.branch', verbose_name='الفرع')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حُسبت بواسطة')),
            ],
            options={
                'verbose_name': 'ربحية فرع',
                'verbose_name_plural': 'تقارير ربحية الفروع',
                'ordering': ['-period', 'branch'],
                'unique_together': {('branch', 'period')},
            },
        ),
        migrations.CreateModel(
            name='BranchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='بتنسيق YYYY-MM مثل 2026-01', max_length=7, verbose_name='الفترة')),
                ('sales_target', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='هدف المبيعات')),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبيعات الفعلية')),
                ('new_customers_target', models.PositiveIntegerField(default=0, verbose_name='هدف العملاء الجدد')),
                ('actual_new_customers', models.PositiveIntegerField(default=0, verbose_name='العملاء الجدد الفعلي')),
                ('collection_target', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='هدف التحصيل')),
                ('actual_collection', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التحصيل الفعلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'هدف فرع',
                'verbose_name_plural': 'أهداف الفروع',
                'ordering': ['-period', 'branch'],
                'unique_together': {('branch', 'period')},
            },
        ),
    ]
