# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_interbranchtransfer_interbranchtransferitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='branchexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='branchpurchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التحويل'),
        ),
    ]
