# Generated by Django 5.2.5 on 2025-08-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم السائق')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('license_number', models.CharField(blank=True, max_length=60, verbose_name='رقم الرخصة')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الرخصة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المركبة')),
                ('plate_number', models.CharField(max_length=40, unique=True, verbose_name='رقم اللوحة')),
                ('type', models.CharField(blank=True, max_length=60, verbose_name='النوع/التصنيف')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('in_use', 'قيد الاستخدام'), ('maintenance', 'صيانة'), ('inactive', 'متوقفة')], default='available', max_length=20, verbose_name='الحالة')),
                ('current_odometer', models.PositiveIntegerField(default=0, verbose_name='عداد (كم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('origin', models.CharField(max_length=120, verbose_name='نقطة الانطلاق')),
                ('destination', models.CharField(max_length=120, verbose_name='الوجهة')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المسافة (كم)')),
                ('purpose', models.CharField(blank=True, max_length=160, verbose_name='الغرض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=80, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='vehicles/docs/', verbose_name='الملف')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'مستند مركبة',
                'verbose_name_plural': 'مستندات المركبات',
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'صيانة'), ('license', 'ترخيص / تأمين'), ('fine', 'مخالفة'), ('fuel', 'وقود'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'مصروف مركبة',
                'verbose_name_plural': 'مصروفات المركبات',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
