# Generated by Django 5.2.5 on 2025-08-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicleexpense_journal_entry_fleetaccountingsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'permissions': [('manage_driver', 'إدارة السائق')], 'verbose_name': 'سائق', 'verbose_name_plural': 'السائقون'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time'], 'permissions': [('manage_trip', 'إدارة رحلة')], 'verbose_name': 'رحلة', 'verbose_name_plural': 'الرحلات'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('manage_vehicle', 'إدارة مركبة')], 'verbose_name': 'مركبة', 'verbose_name_plural': 'المركبات'},
        ),
        migrations.AlterModelOptions(
            name='vehicleexpense',
            options={'ordering': ['-date', '-id'], 'permissions': [('manage_vehicleexpense', 'إدارة مصروف مركبة')], 'verbose_name': 'مصروف مركبة', 'verbose_name_plural': 'مصروفات المركبات'},
        ),
    ]
