# Generated by Django 5.2.5 on 2025-08-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_add_trip_odometer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveradvance',
            options={'ordering': ['-date', '-id'], 'permissions': [('manage_driveradvance', 'إدارة عهدة سائق')], 'verbose_name': 'عهدة سائق', 'verbose_name_plural': 'عهد السائقين'},
        ),
        migrations.AlterModelOptions(
            name='driverviolation',
            options={'ordering': ['-date', '-id'], 'permissions': [('manage_driverviolation', 'إدارة مخالفة سائق')], 'verbose_name': 'مخالفة سائق', 'verbose_name_plural': 'مخالفات السائقين'},
        ),
    ]
