# Generated by Django 5.2.5 on 2025-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_driveradvance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverviolation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleetaccountingsettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
