# Generated by Django 5.2.5 on 2025-12-29 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_driverviolation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول')),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الدقة (متر)')),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='السرعة (م/ث)')),
                ('heading_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الاتجاه (درجة)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التسجيل (من الجهاز)')),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='fleet.driver', verbose_name='السائق')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='fleet.trip', verbose_name='الرحلة')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'نقطة تتبع سائق',
                'verbose_name_plural': 'نقاط تتبع السائقين',
                'ordering': ['-recorded_at', '-id'],
                'permissions': [('manage_driverlocationping', 'إدارة تتبع السائق')],
                'indexes': [models.Index(fields=['driver', 'recorded_at'], name='fleet_drive_driver__d01900_idx'), models.Index(fields=['vehicle', 'recorded_at'], name='fleet_drive_vehicle_d4f06c_idx')],
            },
        ),
    ]
