# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم نوع الفحص')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع فحص',
                'verbose_name_plural': 'أنواع الفحص',
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رقم الفحص')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('inspection_date', models.DateTimeField(verbose_name='تاريخ الفحص')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري الفحص'), ('passed', 'ناجح'), ('failed', 'فاشل'), ('conditional', 'مقبول بشروط')], default='pending', max_length=20, verbose_name='الحالة')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة الإجمالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.inspectiontype', verbose_name='نوع الفحص')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'فحص جودة',
                'verbose_name_plural': 'فحوصات الجودة',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رقم المشكلة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('investigating', 'قيد التحقيق'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة')),
                ('root_cause', models.TextField(blank=True, verbose_name='السبب الجذري')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='quality_control.qualityinspection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='المنتج')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشكلة جودة',
                'verbose_name_plural': 'مشاكل الجودة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعيار')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(max_length=100, verbose_name='الفئة')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الدنيا')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة القصوى')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='وحدة القياس')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معيار جودة',
                'verbose_name_plural': 'معايير الجودة',
            },
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='inspection_types', to='quality_control.qualitystandard'),
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة المقاسة')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality_control.qualityinspection')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_control.qualitystandard', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'نتيجة فحص',
                'verbose_name_plural': 'نتائج الفحص',
            },
        ),
    ]
