# Generated by Django 5.2.5 on 2025-12-24 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('all', 'جميع الموديولات'), ('products', 'المنتجات'), ('categories', 'الفئات'), ('customers', 'العملاء'), ('suppliers', 'الموردين'), ('employees', 'الموظفين'), ('departments', 'الأقسام'), ('accounts', 'الحسابات المحاسبية'), ('locations', 'المخازن/المواقع'), ('opening_balances', 'الأرصدة الافتتاحية')], max_length=50, verbose_name='الموديول')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='ملف Excel')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('partial', 'مكتمل جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('total_rows', models.IntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='الصفوف المعالجة')),
                ('success_count', models.IntegerField(default=0, verbose_name='الناجحة')),
                ('error_count', models.IntegerField(default=0, verbose_name='الفاشلة')),
                ('error_log', models.TextField(blank=True, verbose_name='سجل الأخطاء')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص النتائج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة استيراد',
                'verbose_name_plural': 'جلسات الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(verbose_name='رقم الصف')),
                ('column_name', models.CharField(blank=True, max_length=100, verbose_name='اسم العمود')),
                ('error_type', models.CharField(max_length=50, verbose_name='نوع الخطأ')),
                ('error_message', models.TextField(verbose_name='رسالة الخطأ')),
                ('row_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='data_import.importsession')),
            ],
            options={
                'verbose_name': 'خطأ استيراد',
                'verbose_name_plural': 'أخطاء الاستيراد',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemInitialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_initialized', models.BooleanField(default=False, verbose_name='تم التهيئة')),
                ('initialized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التهيئة')),
                ('products_imported', models.BooleanField(default=False, verbose_name='تم استيراد المنتجات')),
                ('categories_imported', models.BooleanField(default=False, verbose_name='تم استيراد الفئات')),
                ('customers_imported', models.BooleanField(default=False, verbose_name='تم استيراد العملاء')),
                ('suppliers_imported', models.BooleanField(default=False, verbose_name='تم استيراد الموردين')),
                ('employees_imported', models.BooleanField(default=False, verbose_name='تم استيراد الموظفين')),
                ('departments_imported', models.BooleanField(default=False, verbose_name='تم استيراد الأقسام')),
                ('accounts_imported', models.BooleanField(default=False, verbose_name='تم استيراد الحسابات')),
                ('locations_imported', models.BooleanField(default=False, verbose_name='تم استيراد المخازن')),
                ('opening_balances_imported', models.BooleanField(default=False, verbose_name='تم استيراد الأرصدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initialized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حالة تهيئة النظام',
                'verbose_name_plural': 'حالة تهيئة النظام',
            },
        ),
    ]
