# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('campaign_type', models.CharField(choices=[('awareness', 'توعية'), ('lead_generation', 'جذب عملاء محتملين'), ('conversion', 'تحويل'), ('retention', 'احتفاظ'), ('loyalty', 'ولاء'), ('seasonal', 'موسمية'), ('product_launch', 'إطلاق منتج')], max_length=30, verbose_name='نوع الحملة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('active', 'نشطة'), ('paused', 'متوقفة مؤقتاً'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('target_audience_size', models.IntegerField(default=0, verbose_name='حجم الجمهور المستهدف')),
                ('channels', models.JSONField(default=list, help_text='قائمة القنوات المستخدمة', verbose_name='قنوات التسويق')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الميزانية')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكلفة الفعلية')),
                ('goal_description', models.TextField(verbose_name='وصف الأهداف')),
                ('target_conversions', models.IntegerField(default=0, verbose_name='التحويلات المستهدفة')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيراد المستهدف')),
                ('total_sent', models.IntegerField(default=0, verbose_name='إجمالي الرسائل المرسلة')),
                ('total_delivered', models.IntegerField(default=0, verbose_name='إجمالي الرسائل المستلمة')),
                ('total_opened', models.IntegerField(default=0, verbose_name='إجمالي مرات الفتح')),
                ('total_clicked', models.IntegerField(default=0, verbose_name='إجمالي النقرات')),
                ('total_conversions', models.IntegerField(default=0, verbose_name='إجمالي التحويلات')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('message_template', models.TextField(blank=True, verbose_name='قالب الرسالة')),
                ('landing_page_url', models.URLField(blank=True, verbose_name='رابط الصفحة المقصودة')),
                ('offer_details', models.TextField(blank=True, verbose_name='تفاصيل العرض')),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العائد على الاستثمار (ROI) %')),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة التحويل')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حملة تسويقية',
                'verbose_name_plural': 'الحملات التسويقية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاختبار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('variant_a_name', models.CharField(default='النسخة A', max_length=100, verbose_name='اسم النسخة A')),
                ('variant_a_content', models.TextField(verbose_name='محتوى النسخة A')),
                ('variant_a_sent', models.IntegerField(default=0, verbose_name='مرسل A')),
                ('variant_a_conversions', models.IntegerField(default=0, verbose_name='تحويلات A')),
                ('variant_a_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل A %')),
                ('variant_b_name', models.CharField(default='النسخة B', max_length=100, verbose_name='اسم النسخة B')),
                ('variant_b_content', models.TextField(verbose_name='محتوى النسخة B')),
                ('variant_b_sent', models.IntegerField(default=0, verbose_name='مرسل B')),
                ('variant_b_conversions', models.IntegerField(default=0, verbose_name='تحويلات B')),
                ('variant_b_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التحويل B %')),
                ('winner', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('N', 'لا فرق')], max_length=1, verbose_name='الفائز')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مستوى الثقة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='marketing_campaigns.campaign', verbose_name='الحملة')),
            ],
            options={
                'verbose_name': 'اختبار A/B',
                'verbose_name_plural': 'اختبارات A/B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة التصميم')),
                ('platform_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة المنصة')),
                ('media_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الإعلان')),
                ('staff_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الموظفين')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكاليف أخرى')),
                ('direct_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيراد المباشر')),
                ('indirect_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيراد غير المباشر')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التكلفة')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيراد')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي الربح')),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العائد على الاستثمار %')),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة اكتساب العميل (CAC)')),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة العميل مدى الحياة (CLV)')),
                ('payback_period_days', models.IntegerField(default=0, verbose_name='فترة استرداد التكلفة (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi_analysis', to='marketing_campaigns.campaign', verbose_name='الحملة')),
            ],
            options={
                'verbose_name': 'تحليل ROI للحملة',
                'verbose_name_plural': 'تحليلات ROI للحملات',
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشريحة')),
                ('segment_type', models.CharField(choices=[('demographic', 'ديموغرافي'), ('behavioral', 'سلوكي'), ('geographic', 'جغرافي'), ('psychographic', 'نفسي'), ('value_based', 'حسب القيمة')], max_length=30, verbose_name='نوع الشريحة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('criteria', models.JSONField(default=dict, help_text='معايير اختيار العملاء', verbose_name='معايير التقسيم')),
                ('customer_count', models.IntegerField(default=0, verbose_name='عدد العملاء')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='متوسط قيمة الطلب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شريحة عملاء',
                'verbose_name_plural': 'شرائح العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_segments',
            field=models.ManyToManyField(related_name='campaigns', to='marketing_campaigns.customersegment', verbose_name='الشرائح المستهدفة'),
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('push_notification', 'إشعار')], max_length=30, verbose_name='نوع الرسالة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'مرسل'), ('delivered', 'مستلم'), ('opened', 'مفتوح'), ('clicked', 'تم النقر'), ('converted', 'تم التحويل'), ('bounced', 'فشل'), ('unsubscribed', 'إلغاء اشتراك')], default='pending', max_length=20, verbose_name='الحالة')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النقر')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة التحويل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketing_campaigns.campaign', verbose_name='الحملة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='crm.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'رسالة حملة',
                'verbose_name_plural': 'رسائل الحملات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='marketing_c_campaig_12d46d_idx'), models.Index(fields=['customer'], name='marketing_c_custome_bc248a_idx'), models.Index(fields=['message_type'], name='marketing_c_message_663b7e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date'], name='marketing_c_status_fc37c0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='marketing_c_campaig_71646f_idx'),
        ),
    ]
