# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('trigger_phrases', models.JSONField(default=list, verbose_name='عبارات التفعيل')),
                ('command_type', models.CharField(max_length=20, verbose_name='نوع الأمر')),
                ('action_type', models.CharField(max_length=50, verbose_name='نوع الإجراء')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('action_params', models.JSONField(default=dict, verbose_name='معاملات الإجراء')),
                ('response_template', models.TextField(verbose_name='قالب الرد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
            ],
            options={
                'verbose_name': 'قالب أمر صوتي',
                'verbose_name_plural': 'قوالب الأوامر الصوتية',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserVoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='تفعيل المساعد')),
                ('voice_type', models.CharField(choices=[('male_ar', 'ذكر - عربي'), ('female_ar', 'أنثى - عربية'), ('male_en', 'ذكر - إنجليزي'), ('female_en', 'أنثى - إنجليزية')], default='female_ar', max_length=20, verbose_name='نوع الصوت')),
                ('speech_rate', models.FloatField(default=1.0, verbose_name='سرعة الكلام')),
                ('pitch', models.FloatField(default=1.0, verbose_name='نبرة الصوت')),
                ('auto_listen', models.BooleanField(default=False, verbose_name='استماع تلقائي')),
                ('wake_word', models.CharField(default='يا نظام', max_length=50, verbose_name='كلمة التنبيه')),
                ('language', models.CharField(default='ar-SA', max_length=10, verbose_name='لغة التعرف')),
                ('read_responses', models.BooleanField(default=True, verbose_name='قراءة الردود')),
                ('confirm_actions', models.BooleanField(default=True, verbose_name='تأكيد الإجراءات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_preference', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات المساعد الصوتي',
                'verbose_name_plural': 'تفضيلات المساعد الصوتي',
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField(verbose_name='نص الأمر')),
                ('command_type', models.CharField(choices=[('navigation', 'تنقل'), ('create', 'إنشاء'), ('search', 'بحث'), ('report', 'تقرير'), ('action', 'إجراء'), ('query', 'استعلام'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع الأمر')),
                ('detected_intent', models.CharField(blank=True, max_length=100, verbose_name='النية المكتشفة')),
                ('extracted_entities', models.JSONField(default=dict, verbose_name='الكيانات المستخرجة')),
                ('confidence', models.FloatField(default=0.0, verbose_name='مستوى الثقة')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('success', 'تم بنجاح'), ('failed', 'فشل'), ('partial', 'جزئي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('response_text', models.TextField(blank=True, verbose_name='نص الرد')),
                ('action_taken', models.CharField(blank=True, max_length=200, verbose_name='الإجراء المتخذ')),
                ('redirect_url', models.CharField(blank=True, max_length=500, verbose_name='رابط التوجيه')),
                ('audio_duration', models.FloatField(blank=True, null=True, verbose_name='مدة الصوت (ثواني)')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'أمر صوتي',
                'verbose_name_plural': 'الأوامر الصوتية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_phrase', models.CharField(max_length=200, verbose_name='عبارة التفعيل')),
                ('action_url', models.CharField(max_length=500, verbose_name='رابط الإجراء')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_shortcuts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اختصار صوتي',
                'verbose_name_plural': 'الاختصارات الصوتية',
                'unique_together': {('user', 'trigger_phrase')},
            },
        ),
    ]
