# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('insight_type', models.CharField(choices=[('trend', 'اتجاه'), ('anomaly', 'شذوذ'), ('opportunity', 'فرصة'), ('risk', 'مخاطرة'), ('recommendation', 'توصية')], max_length=20, verbose_name='نوع الرؤية')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('data', models.JSONField(default=dict, verbose_name='البيانات')),
                ('metrics', models.JSONField(default=dict, verbose_name='المقاييس')),
                ('suggested_actions', models.JSONField(default=list, verbose_name='الإجراءات المقترحة')),
                ('estimated_impact', models.CharField(blank=True, max_length=200, verbose_name='التأثير المتوقع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_actioned', models.BooleanField(default=False, verbose_name='تم اتخاذ إجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تنتهي في')),
            ],
            options={
                'verbose_name': 'رؤية ذكية',
                'verbose_name_plural': 'الرؤى الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('analysis_type', models.CharField(choices=[('descriptive', 'وصفي'), ('diagnostic', 'تشخيصي'), ('predictive', 'تنبؤي'), ('prescriptive', 'توصيفي')], max_length=20, verbose_name='نوع التحليل')),
                ('data_source', models.CharField(max_length=200, verbose_name='مصدر البيانات')),
                ('query_params', models.JSONField(default=dict, verbose_name='معلمات الاستعلام')),
                ('date_range', models.JSONField(default=dict, verbose_name='نطاق التاريخ')),
                ('results', models.JSONField(default=dict, verbose_name='النتائج')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('charts_config', models.JSONField(default=list, verbose_name='تكوين الرسوم')),
                ('ai_insights', models.TextField(blank=True, verbose_name='رؤى AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تحليل بيانات',
                'verbose_name_plural': 'تحليلات البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('model_type', models.CharField(choices=[('sales_forecast', 'توقع المبيعات'), ('demand_prediction', 'توقع الطلب'), ('churn_prediction', 'توقع فقدان العملاء'), ('price_optimization', 'تحسين الأسعار'), ('inventory_optimization', 'تحسين المخزون'), ('customer_segmentation', 'تقسيم العملاء'), ('anomaly_detection', 'كشف الشذوذ')], max_length=30, verbose_name='نوع النموذج')),
                ('config', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('parameters', models.JSONField(default=dict, verbose_name='المعلمات')),
                ('is_trained', models.BooleanField(default=False, verbose_name='مدرب')),
                ('last_trained', models.DateTimeField(blank=True, null=True, verbose_name='آخر تدريب')),
                ('training_accuracy', models.FloatField(blank=True, null=True, verbose_name='دقة التدريب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'نموذج تنبؤ',
                'verbose_name_plural': 'نماذج التنبؤ',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('input_data', models.JSONField(default=dict, verbose_name='البيانات المدخلة')),
                ('prediction_value', models.JSONField(default=dict, verbose_name='قيمة التنبؤ')),
                ('confidence', models.FloatField(default=0, verbose_name='الثقة %')),
                ('analysis', models.TextField(blank=True, verbose_name='التحليل')),
                ('recommendations', models.JSONField(default=list, verbose_name='التوصيات')),
                ('actual_value', models.JSONField(blank=True, null=True, verbose_name='القيمة الفعلية')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='الدقة الفعلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_analytics.predictionmodel', verbose_name='النموذج')),
            ],
            options={
                'verbose_name': 'تنبؤ',
                'verbose_name_plural': 'التنبؤات',
                'ordering': ['-created_at'],
            },
        ),
    ]
