# Generated by Django 5.2.5 on 2025-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='رقم الباركود الفريد للمنتج (يُولد تلقائياً إذا ترك فارغاً)', max_length=20, null=True, unique=True, verbose_name='الباركود'),
        ),
    ]
