# Generated by Django 5.2.5 on 2025-08-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False, help_text='الموقع الافتراضي لعمليات الإدخال/الإخراج في حال عدم اختيار موقع'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('finished', 'منتج تام'), ('wip', 'نصف مصنع'), ('raw', 'خامات'), ('spare', 'قطع غيار'), ('store', 'معرض/متجر'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transfers', to='inventory.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transfers', to='inventory.location')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
        ),
    ]
