# Generated by Django 5.2.5 on 2025-08-14 05:33

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_uom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('to_department', models.CharField(default='production', help_text='مثلاً: production, sales, other', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='مرجع الطلب/أمر التشغيل', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20)),
                ('allocation_method', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO')], default='fifo', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.location')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.issue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('po_reference', models.CharField(blank=True, help_text='رقم أمر الشراء إن وجد', max_length=100)),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('quality_checked', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='inventory.location')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receiving')),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('count_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('counted', 'تم العد'), ('applied', 'مُرحّل')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.location')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
            ],
        ),
    ]
