# Generated by Django 5.2.5 on 2025-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_fix_conflict'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issueitem',
            index=models.Index(fields=['issue', 'product'], name='inventory_i_issue_i_68b550_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['purchase_order_id'], name='inventory_r_purchas_15eb86_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['status'], name='inventory_r_status_532e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='receiving',
            index=models.Index(fields=['location', 'status'], name='inventory_r_locatio_9e23f1_idx'),
        ),
        migrations.AddIndex(
            model_name='receivingitem',
            index=models.Index(fields=['receiving', 'product'], name='inventory_r_receivi_0e7acc_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'location'], name='inventory_s_product_5cabe4_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['location', 'product'], name='inventory_s_locatio_380396_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='inventory_s_quantit_287c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'location', 'received_at'], name='inventory_s_product_cd2e16_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['location', 'product', 'quantity'], name='inventory_s_locatio_3430ee_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['quantity'], name='inventory_s_quantit_9d4ff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stockbatch_quantity_nonnegative'),
        ),
    ]
