# Generated by Django 5.2.5 on 2025-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_issueitem_inventory_i_issue_i_68b550_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='inventory_i_status_e12400_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['location', 'status'], name='inventory_i_locatio_07fc98_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['allocation_method', 'status'], name='inventory_i_allocat_e25df6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
    ]
