# Generated by Django 5.2.5 on 2025-08-19 13:19

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_issue_inventory_i_status_e12400_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promo_active',
            field=models.BooleanField(default=False, help_text='تشغيل/إيقاف العرض دون حذف القيم'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_end',
            field=models.DateField(blank=True, help_text='تاريخ نهاية العرض', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة الخصم المئوية (0 = بدون خصم)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر ترويجي مباشر (يتجاوز نسبة الخصم إن وُجد)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_start',
            field=models.DateField(blank=True, help_text='تاريخ بداية العرض', null=True),
        ),
    ]
