# Generated by Django 5.2.5 on 2025-08-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_is_promo_active_product_promo_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, help_text='كود داخلي يُولد تلقائياً عند عدم الإدخال', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_third_party',
            field=models.BooleanField(default=False, help_text='منتج طرف ثالث (مُشترى وليس مُصنع داخلياً)'),
        ),
    ]
