# Generated by Django 5.2.5 on 2025-08-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_0012_dual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issues_issued', to=settings.AUTH_USER_MODEL, verbose_name='المُصدر'),
        ),
        migrations.AddField(
            model_name='issue',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستلم'),
        ),
    ]
