# Generated by Django 5.2.5 on 2025-08-24 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_issue_issued_by_issue_received_by_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('from_department', models.CharField(default='production', help_text='القسم الطالب (غالباً الإنتاج)', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='مرجع اختياري مثل رقم أمر الإنتاج', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدّم'), ('approved', 'موافق عليه'), ('converted', 'تم التحويل لصرف'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('linked_issue_id', models.IntegerField(blank=True, help_text='رقم مستند الصرف الناتج (اختياري)', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requisitions_approved', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requisitions_requested', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('production_order_id', models.IntegerField(blank=True, help_text='معرّف أمر الإنتاج المرتبط (اختياري)', null=True)),
                ('stage_id', models.IntegerField(blank=True, help_text='مرحلة الأمر (اختياري)', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.requisition')),
            ],
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['status'], name='inventory_r_status_4033ef_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionitem',
            index=models.Index(fields=['requisition', 'product'], name='inventory_r_requisi_ee4e30_idx'),
        ),
    ]
