# Generated by Django 5.2.5 on 2025-09-15 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_requisition_requisitionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='purchase_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر')], default='unit', max_length=10),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='inventory_l_name_93296b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
    ]
