# Generated by Django 5.2.5 on 2025-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_lowstockevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطابعة')),
                ('printer_type', models.CharField(choices=[('zebra', 'Zebra (باركود)'), ('xprinter', 'Xprinter (حراري)'), ('hp_laserjet', 'HP LaserJet'), ('generic', 'طابعة عامة')], max_length=20, verbose_name='نوع الطابعة')),
                ('document_type', models.CharField(choices=[('barcode', 'باركود'), ('invoice', 'فاتورة'), ('receipt', 'إيصال'), ('report', 'تقرير'), ('id_card', 'بطاقة هوية'), ('label', 'ليبل')], max_length=20, verbose_name='نوع المستند')),
                ('connection_type', models.CharField(choices=[('network', 'شبكة (IP)'), ('usb', 'USB'), ('shared', 'مشاركة ويندوز')], default='network', max_length=20, verbose_name='نوع الاتصال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(blank=True, default=9100, null=True, verbose_name='المنفذ')),
                ('usb_device_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسار USB')),
                ('shared_printer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطابعة المشاركة')),
                ('paper_size', models.CharField(default='80mm', max_length=20, verbose_name='حجم الورق')),
                ('dpi', models.PositiveIntegerField(default=203, verbose_name='DPI')),
                ('label_width_mm', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='عرض الليبل (مم)')),
                ('label_height_mm', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='طول الليبل (مم)')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('total_prints', models.PositiveIntegerField(default=0, verbose_name='عدد المطبوعات')),
                ('last_print_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر طباعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طابعة',
                'verbose_name_plural': 'الطابعات',
            },
        ),
        migrations.RenameIndex(
            model_name='lowstockevent',
            new_name='inventory_l_last_no_cb7e62_idx',
            old_name='inventory_l_last_no_abc123',
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issueitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lowstockevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receivingitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockcountitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='printerconfiguration',
            index=models.Index(fields=['printer_type', 'is_active'], name='inventory_p_printer_a8c912_idx'),
        ),
        migrations.AddIndex(
            model_name='printerconfiguration',
            index=models.Index(fields=['document_type', 'is_default'], name='inventory_p_documen_769f1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='printerconfiguration',
            unique_together={('document_type', 'is_default')},
        ),
    ]
