# Generated by Django 5.2.5 on 2025-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printerconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_department_code',
            field=models.CharField(
                max_length=50,
                blank=True,
                help_text='كود قسم الإنتاج المرتبط (اختياري، يطابق كود القسم في الموارد البشرية إن استخدمته)'
            ),
        ),
    ]
