# Generated by Django 5.2.5 on 2025-12-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_add_enterprise_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_barcode_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_product_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_quantity_idx',
        ),
    ]
