# Generated by Django 5.2.5 on 2025-12-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_warranty_system'),
        ('inventory', '0022_warranty_system'),
        ('partners', '0011_product_unit_warranty'),
        ('production', '0007_productionstage_fields'),
        ('sales', '0026_add_showroom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(help_text='رقم فريد لكل وحدة منتج', max_length=50, unique=True, verbose_name='الرقم التسلسلي')),
                ('barcode', models.CharField(blank=True, help_text='باركود فريد للمسح', max_length=50, unique=True, verbose_name='الباركود')),
                ('qr_code_data', models.CharField(blank=True, help_text='البيانات المشفرة في QR Code', max_length=255, unique=True, verbose_name='بيانات QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='product_units/qr/', verbose_name='صورة QR Code')),
                ('status', models.CharField(choices=[('produced', 'تم الإنتاج'), ('in_stock', 'في المخزن'), ('sold_to_dealer', 'مباع لتاجر'), ('sold_to_customer', 'مباع لعميل'), ('warranty_registered', 'ضمان مسجل'), ('warranty_claimed', 'مطالبة ضمان'), ('returned', 'مرتجع'), ('defective', 'معيب'), ('scrapped', 'خردة')], default='produced', max_length=20, verbose_name='الحالة')),
                ('production_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنتاج')),
                ('production_batch', models.CharField(blank=True, max_length=50, verbose_name='رقم الدفعة')),
                ('dealer_sale_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البيع للتاجر')),
                ('dealer_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع للتاجر')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد العميل')),
                ('customer_address', models.TextField(blank=True, verbose_name='عنوان العميل')),
                ('customer_national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('customer_sale_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البيع للعميل')),
                ('customer_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر البيع للعميل')),
                ('customer_invoice_image', models.ImageField(blank=True, null=True, upload_to='product_units/invoices/', verbose_name='صورة فاتورة العميل')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الضمان')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الضمان')),
                ('warranty_registered', models.BooleanField(default=False, verbose_name='تم تسجيل الضمان')),
                ('warranty_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تسجيل الضمان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_units', to='partners.partner', verbose_name='التاجر/الموزع')),
                ('dealer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_units', to='sales.invoice', verbose_name='فاتورة التاجر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product', verbose_name='المنتج')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_units', to='production.productionorder', verbose_name='أمر الإنتاج')),
                ('warranty_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productwarranty', verbose_name='سياسة الضمان')),
            ],
            options={
                'verbose_name': 'وحدة منتج',
                'verbose_name_plural': 'وحدات المنتجات',
                'ordering': ['-production_date', '-id'],
                'indexes': [models.Index(fields=['serial_number'], name='inventory_p_serial__10e472_idx'), models.Index(fields=['barcode'], name='inventory_p_barcode_aa91fc_idx'), models.Index(fields=['status'], name='inventory_p_status_a57074_idx'), models.Index(fields=['production_date'], name='inventory_p_product_004590_idx'), models.Index(fields=['customer_phone'], name='inventory_p_custome_5cf0fb_idx')],
            },
        ),
    ]
