# Generated by Django 5.2.5 on 2025-12-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='علامة المنتج كـ "جديد" للعرض في المتجر', verbose_name='منتج جديد'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_until',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء ظهور علامة "جديد" (اختياري)', null=True, verbose_name='تاريخ انتهاء علامة جديد'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_store',
            field=models.BooleanField(default=True, help_text='هل يظهر هذا المنتج في المتجر الإلكتروني؟', verbose_name='إظهار في المتجر الإلكتروني'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_description',
            field=models.TextField(blank=True, help_text='وصف مفصل للعرض في المتجر الإلكتروني', verbose_name='وصف المتجر'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_featured',
            field=models.BooleanField(default=False, help_text='عرض المنتج كمميز في الصفحة الرئيسية', verbose_name='منتج مميز'),
        ),
    ]
