# Generated by Django 5.2.9 on 2026-01-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        ('partners', '0011_product_unit_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_barcode',
            field=models.BooleanField(default=False, help_text='إذا كان محدداً، لن يتم توليد باركود تلقائياً', verbose_name='باركود يدوي'),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='partners.supplier', verbose_name='المورد المفضل'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('raw_material', 'مادة خام'), ('semi_finished', 'نصف مصنع'), ('finished', 'منتج تام'), ('spare_part', 'قطعة غيار'), ('service', 'خدمة')], default='finished', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر'), ('m3', 'متر مكعب'), ('ton', 'طن'), ('liter', 'لتر'), ('box', 'صندوق'), ('roll', 'لفة')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر'), ('m3', 'متر مكعب'), ('ton', 'طن'), ('liter', 'لتر'), ('box', 'صندوق'), ('roll', 'لفة')], default='unit', max_length=10),
        ),
    ]
