# Generated by Django 5.2.5 on 2026-01-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_add_raw_material_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='ارتفاع المنتج بالسنتيمتر', null=True, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, help_text='طول المنتج بالسنتيمتر', null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='عرض المنتج بالسنتيمتر', null=True, verbose_name='العرض (سم)'),
        ),
    ]
