# Generated by Django 5.2.5 on 2026-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_height_product_length_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='هل المنتج نشط ويظهر في القوائم؟', verbose_name='نشط'),
        ),
    ]
