# Generated by Django 5.2.5 on 2026-01-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_add_is_active_to_product'),
        ('partners', '0014_supplier_commercial_register_supplier_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='مثل: صفيحة 20 كجم، برميل 200 كجم، لوح 200×100×10', max_length=100, verbose_name='اسم وحدة التعبئة')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, help_text='مثل: 20 كجم للصفيحة، 200 كجم للبرميل', max_digits=12, verbose_name='الكمية في الوحدة')),
                ('packaging_type', models.CharField(choices=[('tin', 'صفيحة'), ('barrel', 'برميل'), ('sheet', 'لوح/فرخ'), ('roll', 'لفة/رول'), ('bag', 'شيكارة/كيس'), ('box', 'كرتونة/صندوق'), ('pallet', 'باليت'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع التعبئة')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='طول اللوح بالسنتيمتر', max_digits=8, null=True, verbose_name='الطول (سم)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='عرض اللوح بالسنتيمتر', max_digits=8, null=True, verbose_name='العرض (سم)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='ارتفاع أو سُمك اللوح بالسنتيمتر', max_digits=8, null=True, verbose_name='الارتفاع/السُمك (سم)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='وزن الوحدة بالكيلوجرام', max_digits=10, null=True, verbose_name='الوزن (كجم)')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, help_text='سعر الوحدة محسوب من سعر الكيلو/المتر المكعب', max_digits=12, null=True, verbose_name='السعر المحسوب')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وحدة تعبئة',
                'verbose_name_plural': 'وحدات التعبئة',
                'ordering': ['product', 'sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'ordering': ['received_at', 'id'], 'verbose_name': 'دفعة مخزون', 'verbose_name_plural': 'دفعات المخزون'},
        ),
        migrations.AddField(
            model_name='product',
            name='raw_material_type',
            field=models.CharField(blank=True, choices=[('foam', 'إسفنج'), ('pad', 'باد/لباد'), ('glue', 'غراء'), ('fiber', 'فيبر'), ('thread', 'خيوط'), ('vaseline', 'فازلين'), ('fabric', 'أقمشة'), ('spring', 'سوست'), ('wood', 'خشب'), ('metal', 'معدن'), ('other', 'أخرى')], default='', help_text='يحدد كيفية إدخال المادة ووحداتها', max_length=20, verbose_name='نوع المادة الخام'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='receiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.receiving', verbose_name='مستند الاستلام'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='المورد الذي تم استلام هذه الدفعة منه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='partners.supplier', verbose_name='المورد'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['supplier'], name='inventory_s_supplie_a575a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'supplier'], name='inventory_s_product_81e66a_idx'),
        ),
        migrations.AddField(
            model_name='packagingunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['product', 'is_active'], name='inventory_p_product_4722bd_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['packaging_type'], name='inventory_p_packagi_5e0873_idx'),
        ),
    ]
