# Generated by Django 5.2.5 on 2026-01-14 11:25

from django.db import migrations, models


def fix_indexes(apps, schema_editor):
    """إصلاح الفهارس بشكل آمن"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # التحقق من وجود الفهرس القديم وإعادة تسميته
            cursor.execute("""
                SELECT indexname FROM pg_indexes
                WHERE indexname = 'spp_prod_supp_active_idx'
            """)
            if cursor.fetchone():
                # حذف الفهرس الجديد إذا كان موجوداً
                cursor.execute("""
                    DROP INDEX IF EXISTS inventory_s_product_2d38ac_idx
                """)
                cursor.execute("""
                    ALTER INDEX spp_prod_supp_active_idx
                    RENAME TO inventory_s_product_2d38ac_idx
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_supplier_product_price'),
        ('partners', '0015_add_uom_to_supplierproduct'),
    ]

    operations = [
        # إصلاح الفهارس بشكل آمن
        migrations.RunPython(fix_indexes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='المدة المتوقعة للتوريد بالأيام', null=True, verbose_name='مدة التوريد (أيام)'),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='min_order_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='أقل كمية يمكن طلبها من هذا المورد', max_digits=12, null=True, verbose_name='الحد الأدنى للطلب'),
        ),
        # لا نضيف الفهرس لأنه موجود بالفعل - نستخدم SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='supplierproductprice',
                    index=models.Index(fields=['effective_date'], name='inventory_s_effecti_b7e6a1_idx'),
                ),
            ],
            database_operations=[],  # لا شيء - الفهرس موجود
        ),
    ]
