# Generated by Django 5.2.5 on 2026-01-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_rename_spp_prod_supp_active_idx_inventory_s_product_2d38ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='conversion_to_base',
            field=models.DecimalField(decimal_places=4, default=1, help_text='عدد الوحدات الأساسية في وحدة شراء واحدة من المورد', max_digits=12, verbose_name='معامل التحويل'),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='purchase_unit',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('m', 'متر'), ('cm', 'سنتيمتر'), ('m3', 'متر مكعب'), ('ton', 'طن'), ('liter', 'لتر'), ('box', 'صندوق'), ('roll', 'لفة')], default='unit', help_text='الوحدة التي يبيع بها المورد هذه المادة', max_length=10, verbose_name='وحدة الشراء'),
        ),
    ]
