# Generated by Django 5.2.9 on 2026-01-14 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_add_purchase_unit_to_supplier_price'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='supplierproductprice',
        #     new_name='inventory_s_product_2d38ac_idx',
        #     old_name='spp_prod_supp_active_idx',
        # ),
        migrations.AddField(
            model_name='product',
            name='auto_calculate_conversion',
            field=models.BooleanField(default=False, help_text='إذا كان محدداً، سيتم حساب معامل التحويل من الأبعاد (طول × عرض × ارتفاع)', verbose_name='حساب معامل التحويل تلقائياً'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='يتم حسابها تلقائياً = سعر الشراء ÷ معامل التحويل', max_digits=15, verbose_name='تكلفة وحدة الاستخدام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_uom',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', max_length=10),
        ),
    ]
