# Generated by Django 5.2.9 on 2026-01-14 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rename_spp_prod_supp_active_idx_inventory_s_product_2d38ac_idx_and_more'),
    ]

    operations = [
        # Skip RenameIndex - index was already handled
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر الشراء من المورد بوحدة الشراء (طن، كيلو، صفيحة، الخ)', max_digits=15, verbose_name='سعر وحدة الشراء'),
        ),
    ]
