# Generated by Django 5.2.5 on 2026-01-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_add_purchase_price_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplierproductprice',
            new_name='inventory_s_product_2d38ac_idx',
            old_name='spp_prod_supp_active_idx',
        ),
    ]
