# Generated by Django 5.2.5 on 2026-01-17 14:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_rename_spp_prod_supp_active_idx_inventory_s_product_2d38ac_idx'),
        ('partners', '0015_add_uom_to_supplierproduct'),
        ('production', '0009_materialreorderpoint_mrpplanningmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPriceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='السعر الجديد')),
                ('price_change', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='السعر الجديد - السعر القديم', max_digits=15, verbose_name='قيمة التغيير')),
                ('change_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='نسبة التغيير %')),
                ('unit', models.CharField(default='unit', max_length=20, verbose_name='الوحدة')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('change_type', models.CharField(choices=[('manual', 'تغيير يدوي'), ('supplier_update', 'تحديث من المورد'), ('bulk_update', 'تحديث جماعي'), ('import', 'استيراد من ملف'), ('api', 'تحديث عبر API'), ('system', 'تحديث تلقائي من النظام')], default='manual', max_length=20, verbose_name='نوع التغيير')),
                ('change_reason', models.CharField(choices=[('market_change', 'تغير أسعار السوق'), ('currency_fluctuation', 'تذبذب العملة'), ('supplier_negotiation', 'تفاوض مع المورد'), ('new_contract', 'عقد جديد'), ('seasonal', 'تغير موسمي'), ('shortage', 'نقص في المعروض'), ('correction', 'تصحيح خطأ'), ('other', 'سبب آخر')], default='market_change', max_length=30, verbose_name='سبب التغيير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التغيير')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السريان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_price_history', to='inventory.product', verbose_name='المادة الخام')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='partners.supplier', verbose_name='المورد')),
                ('supplier_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='inventory.supplierproductprice', verbose_name='سعر المورد')),
            ],
            options={
                'verbose_name': 'سجل تغيير السعر',
                'verbose_name_plural': 'سجل تغييرات الأسعار',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_price_increase', models.BooleanField(default=True, verbose_name='إشعارات ارتفاع الأسعار')),
                ('receive_price_decrease', models.BooleanField(default=True, verbose_name='إشعارات انخفاض الأسعار')),
                ('min_change_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='لن يتم إرسال إشعار إذا كان التغيير أقل من هذه النسبة', max_digits=5, verbose_name='الحد الأدنى لنسبة التغيير %')),
                ('receive_margin_alerts', models.BooleanField(default=True, verbose_name='تنبيهات هامش الربح')),
                ('min_margin_threshold', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='إرسال تنبيه إذا انخفض الهامش عن هذه النسبة', max_digits=5, verbose_name='الحد الأدنى لهامش الربح %')),
                ('notify_dashboard', models.BooleanField(default=True, verbose_name='إشعارات لوحة التحكم')),
                ('notify_email', models.BooleanField(default=False, verbose_name='إشعارات البريد الإلكتروني')),
                ('notify_websocket', models.BooleanField(default=True, verbose_name='إشعارات فورية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='PriceChangeImpact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='الكمية المستخدمة')),
                ('unit_cost_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تأثير على تكلفة الوحدة')),
                ('old_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='هامش الربح القديم %')),
                ('new_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='هامش الربح الجديد %')),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='المخزون الحالي')),
                ('stock_value_impact', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تأثير على قيمة المخزون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_impacts', to='inventory.product', verbose_name='المنتج المتأثر')),
                ('price_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='inventory.materialpricehistory', verbose_name='تغيير السعر')),
            ],
            options={
                'verbose_name': 'تأثير تغيير السعر',
                'verbose_name_plural': 'تأثيرات تغييرات الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceChangeNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('price_increase', 'زيادة سعر'), ('price_decrease', 'انخفاض سعر'), ('new_price', 'سعر جديد'), ('cost_impact', 'تأثير على التكلفة'), ('margin_alert', 'تنبيه هامش الربح'), ('bulk_update', 'تحديث جماعي')], max_length=20, verbose_name='نوع الإشعار')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], default='info', max_length=10, verbose_name='الأهمية')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('old_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='القيمة القديمة')),
                ('new_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='القيمة الجديدة')),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='نسبة التغيير')),
                ('affected_products_count', models.PositiveIntegerField(default=0, verbose_name='عدد المنتجات المتأثرة')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('status', models.CharField(choices=[('unread', 'غير مقروء'), ('read', 'مقروء'), ('dismissed', 'تم تجاهله'), ('actioned', 'تم اتخاذ إجراء')], default='unread', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialpricehistory', verbose_name='سجل السعر')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_notifications', to='inventory.product', verbose_name='المنتج')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'إشعار تغيير السعر',
                'verbose_name_plural': 'إشعارات تغييرات الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة المواد القديمة')),
                ('new_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة المواد الجديدة')),
                ('old_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='التكلفة الإجمالية القديمة')),
                ('new_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='التكلفة الإجمالية الجديدة')),
                ('cost_change', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='قيمة تغير التكلفة')),
                ('change_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='نسبة تغير التكلفة %')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التغيير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.billofmaterials', verbose_name='قائمة المواد')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='inventory.product', verbose_name='المنتج')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_products', to='inventory.materialpricehistory', verbose_name='ناتج عن تغيير')),
            ],
            options={
                'verbose_name': 'سجل تغيير تكلفة المنتج',
                'verbose_name_plural': 'سجل تغييرات تكاليف المنتجات',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='materialpricehistory',
            index=models.Index(fields=['product', '-changed_at'], name='inventory_m_product_30f75d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpricehistory',
            index=models.Index(fields=['supplier', '-changed_at'], name='inventory_m_supplie_fc8019_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpricehistory',
            index=models.Index(fields=['-changed_at'], name='inventory_m_changed_422985_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpricehistory',
            index=models.Index(fields=['change_type'], name='inventory_m_change__f482a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricechangenotification',
            index=models.Index(fields=['recipient', 'status', '-created_at'], name='inventory_p_recipie_77ab99_idx'),
        ),
        migrations.AddIndex(
            model_name='pricechangenotification',
            index=models.Index(fields=['notification_type', '-created_at'], name='inventory_p_notific_9c0b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcosthistory',
            index=models.Index(fields=['product', '-changed_at'], name='inventory_p_product_d9058f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcosthistory',
            index=models.Index(fields=['-changed_at'], name='inventory_p_changed_3da7e2_idx'),
        ),
    ]
