# Generated by Django 5.2.5 on 2026-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_price_history_and_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_unit', models.CharField(help_text='الوحدة المصدر', max_length=20, verbose_name='من وحدة')),
                ('to_unit', models.CharField(help_text='الوحدة الهدف', max_length=20, verbose_name='إلى وحدة')),
                ('factor', models.DecimalField(decimal_places=6, help_text='1 من_وحدة = factor إلى_وحدة', max_digits=12, verbose_name='معامل التحويل')),
                ('material_type', models.CharField(choices=[('general', 'عام'), ('wood', 'خشب'), ('foam', 'إسفنج'), ('metal', 'معدن'), ('fabric', 'قماش'), ('liquid', 'سائل'), ('other', 'أخرى')], default='general', help_text='تحديد نوع المادة لمعامل تحويل مخصص', max_length=20, verbose_name='نوع المادة')),
                ('description', models.TextField(blank=True, help_text='مثال: 1 متر مكعب خشب زان = 650 كجم', verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'معامل تحويل',
                'verbose_name_plural': 'معاملات التحويل',
                'ordering': ['material_type', 'from_unit', 'to_unit'],
                'indexes': [models.Index(fields=['from_unit', 'to_unit'], name='inventory_c_from_un_b972f6_idx'), models.Index(fields=['material_type', 'is_active'], name='inventory_c_materia_873555_idx')],
                'unique_together': {('from_unit', 'to_unit', 'material_type')},
            },
        ),
    ]
