# Generated by Django 5.2.9 on 2026-01-17 21:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_add_conversion_factors'),
        ('partners', '0015_add_uom_to_supplierproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='اسم وصفي للقالب (مثل: قالب إسفنج قياسي)', max_length=255, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, help_text='وصف القالب ومتى يستخدم', verbose_name='الوصف')),
                ('product_type', models.CharField(choices=[('raw_material', 'مادة خام'), ('semi_finished', 'نصف مصنع'), ('finished', 'منتج تام'), ('spare_part', 'قطعة غيار'), ('service', 'خدمة')], default='raw_material', max_length=20, verbose_name='نوع المنتج')),
                ('raw_material_type', models.CharField(blank=True, choices=[('foam', 'إسفنج'), ('pad', 'باد/لباد'), ('glue', 'غراء'), ('fiber', 'فيبر'), ('thread', 'خيوط'), ('vaseline', 'فازلين'), ('fabric', 'أقمشة'), ('spring', 'سوست'), ('wood', 'خشب'), ('metal', 'معدن'), ('other', 'أخرى')], default='', max_length=20, verbose_name='نوع المادة الخام')),
                ('purchase_uom', models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', max_length=10, verbose_name='وحدة الشراء')),
                ('usage_uom', models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', max_length=10, verbose_name='وحدة الاستخدام')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='عدد وحدات الاستخدام في وحدة الشراء', max_digits=12, verbose_name='معامل التحويل')),
                ('auto_calculate_conversion', models.BooleanField(default=False, verbose_name='حساب معامل التحويل تلقائياً')),
                ('length', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='الطول')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='العرض')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='الارتفاع/السُمك')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='عدد المرات التي استخدم فيها هذا القالب', verbose_name='عدد الاستخدامات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates', to='inventory.category', verbose_name='الفئة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_templates', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates', to='partners.supplier', verbose_name='المورد المفضل')),
            ],
            options={
                'verbose_name': 'قالب منتج',
                'verbose_name_plural': 'قوالب المنتجات',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['product_type'], name='inventory_p_product_27c860_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_c698fc_idx'), models.Index(fields=['-usage_count'], name='inventory_p_usage_c_842b26_idx')],
            },
        ),
    ]
