# Generated by Django 5.2.5 on 2026-01-24 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_producttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة الهدر المتوقعة (مثلاً 5% للقص) تضاف للتكلفة', max_digits=5, verbose_name='نسبة الهدر %'),
        ),
    ]
