# Generated by Django 5.2.5 on 2026-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_product_waste_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد')], default='draft', max_length=20),
        ),
    ]
