# Generated by Django 5.2.9 on 2026-02-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_add_pending_status_to_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductprice',
            name='purchase_unit',
            field=models.CharField(choices=[('unit', 'وحدة'), ('kg', 'كيلوجرام'), ('g', 'جرام'), ('ton', 'طن'), ('m', 'متر'), ('m2', 'متر مربع'), ('m3', 'متر مكعب'), ('cm', 'سنتيمتر'), ('mm', 'مليمتر'), ('liter', 'لتر'), ('gallon', 'جالون'), ('barrel', 'برميل'), ('can', 'صفيحة'), ('box', 'صندوق'), ('carton', 'كرتونة'), ('pallet', 'بالت'), ('roll', 'لفة'), ('sheet', 'لوح/ورقة'), ('bag', 'كيس/شكارة'), ('piece', 'قطعة')], default='unit', help_text='الوحدة التي يبيع بها المورد هذه المادة', max_length=10, verbose_name='وحدة الشراء'),
        ),
    ]
