# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_supplierproductprice_purchase_unit'),
        ('partners', '0017_add_is_active_to_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجرد')),
                ('count_type', models.CharField(choices=[('full', 'جرد كامل'), ('partial', 'جرد جزئي'), ('abc_a', 'جرد فئة A'), ('abc_b', 'جرد فئة B'), ('abc_c', 'جرد فئة C'), ('random', 'جرد عشوائي')], default='full', max_length=20, verbose_name='نوع الجرد')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ الجرد المجدول')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأصناف')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='الأصناف المجرودة')),
                ('discrepancies_count', models.PositiveIntegerField(default=0, verbose_name='عدد الفروقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cycle_counts', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='inventory.location', verbose_name='الموقع')),
                ('supervised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cycle_counts', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'جرد دوري',
                'verbose_name_plural': 'الجرد الدوري',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='LotTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, unique=True, verbose_name='رقم اللوت')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدُفعة')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التصنيع')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الأولية')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الحالية')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.location', verbose_name='الموقع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'لوت (دُفعة)',
                'verbose_name_plural': 'اللوتات (الدُفعات)',
                'ordering': ['expiry_date', 'manufacturing_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية في النظام')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية المجرودة')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='يوجد فرق')),
                ('discrepancy_reason', models.CharField(blank=True, max_length=200, verbose_name='سبب الفرق')),
                ('adjustment_created', models.BooleanField(default=False, verbose_name='تم إنشاء تسوية')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='جُرد بواسطة')),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cyclecount', verbose_name='الجرد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند جرد',
                'verbose_name_plural': 'بنود الجرد',
                'unique_together': {('cycle_count', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'مخزون منخفض'), ('overstock', 'مخزون زائد'), ('out_of_stock', 'نفد المخزون'), ('expiring', 'قرب انتهاء الصلاحية'), ('no_movement', 'بدون حركة'), ('reorder_point', 'نقطة إعادة الطلب')], max_length=20, verbose_name='نوع التنبيه')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], default='warning', max_length=10, verbose_name='مستوى الخطورة')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='الحد الأدنى/الأقصى للكمية حسب نوع التنبيه', max_digits=10, verbose_name='الحد')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='تم الاطلاع')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('trigger_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات التشغيل')),
                ('no_movement_days', models.PositiveIntegerField(default=30, help_text='لنوع "بدون حركة" فقط', verbose_name='أيام بدون حركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_stock_alerts', to=settings.AUTH_USER_MODEL, verbose_name='اطلع عليه')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.location', verbose_name='الموقع')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='subscribed_stock_alerts', to=settings.AUTH_USER_MODEL, verbose_name='إشعار المستخدمين')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تنبيه مخزون',
                'verbose_name_plural': 'تنبيهات المخزون',
                'ordering': ['-last_triggered', '-severity'],
                'unique_together': {('product', 'location', 'alert_type')},
            },
        ),
    ]
