# Generated by Django 5.2.9 on 2026-02-23 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_cyclecount_lottracking_cyclecountitem_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='material_name',
            field=models.CharField(blank=True, default='', help_text='اسم المادة كما تعرفها أنت — مثال: اسفنج كثافة 26', max_length=200, verbose_name='اسم المادة الخام'),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='product',
            field=models.ForeignKey(blank=True, help_text='اربط بمنتج موجود في المخزون إن أردت — اختياري تماماً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_prices', to='inventory.product', verbose_name='المنتج (اختياري)'),
        ),
    ]
