# Generated by Django 5.2.9 on 2026-01-04 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_add_company_social_media'),
        ('sales', '0027_customerdiscountnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('invoice_counter', models.IntegerField(verbose_name='رقم تسلسلي')),
                ('invoice_type', models.CharField(choices=[('B2B', 'فاتورة ضريبية - B2B'), ('B2C', 'فاتورة ضريبية مبسطة - B2C'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين')], max_length=20, verbose_name='نوع الفاتورة')),
                ('invoice_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash')),
                ('previous_invoice_hash', models.CharField(blank=True, max_length=255, verbose_name='Previous Hash')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code')),
                ('qr_code_image', models.ImageField(blank=True, upload_to='zatca/qr/', verbose_name='صورة QR Code')),
                ('xml_invoice', models.TextField(blank=True, verbose_name='XML Invoice')),
                ('signed_xml', models.TextField(blank=True, verbose_name='Signed XML')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الإرسال'), ('reported', 'تم الإبلاغ'), ('cleared', 'تم التخليص'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('zatca_response', models.JSONField(blank=True, default=dict, verbose_name='ZATCA Response')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإبلاغ')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التخليص')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='أخطاء التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة إلكترونية',
                'verbose_name_plural': 'فواتير إلكترونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('compliance_check', 'فحص التوافق'), ('report', 'إبلاغ'), ('clearance', 'تخليص')], max_length=20, verbose_name='الإجراء')),
                ('request_data', models.JSONField(default=dict, verbose_name='بيانات الطلب')),
                ('response_data', models.JSONField(default=dict, verbose_name='بيانات الاستجابة')),
                ('success', models.BooleanField(default=False, verbose_name='نجح')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('einvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='zatca_integration.einvoice')),
            ],
            options={
                'verbose_name': 'سجل فاتورة إلكترونية',
                'verbose_name_plural': 'سجلات الفواتير الإلكترونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZATCAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'يجب أن يكون 15 رقم')], verbose_name='الرقم الضريبي')),
                ('crn', models.CharField(max_length=50, verbose_name='رقم السجل التجاري')),
                ('environment', models.CharField(choices=[('sandbox', 'بيئة تجريبية'), ('simulation', 'بيئة محاكاة'), ('production', 'بيئة إنتاج')], default='sandbox', max_length=20, verbose_name='البيئة')),
                ('api_base_url', models.URLField(default='https://gw-fatoora.zatca.gov.sa/e-invoicing/developer-portal', verbose_name='API Base URL')),
                ('compliance_csid', models.TextField(blank=True, verbose_name='Compliance CSID')),
                ('production_csid', models.TextField(blank=True, verbose_name='Production CSID')),
                ('certificate', models.TextField(blank=True, verbose_name='الشهادة الرقمية (Certificate)')),
                ('private_key', models.TextField(blank=True, verbose_name='المفتاح الخاص (Private Key)')),
                ('certificate_password', models.CharField(blank=True, max_length=255, verbose_name='كلمة مرور الشهادة')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('is_certified', models.BooleanField(default=False, verbose_name='معتمد من ZATCA')),
                ('certification_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('seller_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البائع')),
                ('building_number', models.CharField(blank=True, max_length=10, verbose_name='رقم المبنى')),
                ('street_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشارع')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات ZATCA',
                'verbose_name_plural': 'إعدادات ZATCA',
            },
        ),
    ]
