# Generated by Django 5.2.5 on 2025-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'Can view aggregated reports'), ('export_reports', 'Can export report data')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
