# Generated by Django 5.2.5 on 2025-08-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportvarianceincident'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportvarianceincident',
            new_name='reports_rep_report_0ff9b4_idx',
            old_name='reports_variance_report_created_idx',
        ),
    ]
