# Generated by Django 5.2.5 on 2025-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_reports_variance_report_created_idx_reports_rep_report_0ff9b4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdailysnapshot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportvarianceincident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
