# Generated by Django 5.2.5 on 2025-12-08 02:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0005_alter_reportdailysnapshot_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخزون'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('production', 'الإنتاج'), ('crm', 'إدارة العملاء'), ('custom', 'مخصص')], max_length=50, verbose_name='الفئة')),
                ('is_public', models.BooleanField(default=False, help_text='متاح لجميع المستخدمين', verbose_name='عام')),
                ('data_source', models.CharField(help_text='اسم الموديل أو View', max_length=100, verbose_name='مصدر البيانات')),
                ('fields_config', models.TextField(help_text='JSON configuration', verbose_name='تكوين الحقول')),
                ('filters_config', models.TextField(blank=True, default='[]', verbose_name='تكوين الفلاتر')),
                ('grouping_config', models.TextField(blank=True, default='[]', verbose_name='تكوين التجميع')),
                ('sorting_config', models.TextField(blank=True, default='[]', verbose_name='تكوين الترتيب')),
                ('layout', models.CharField(choices=[('table', 'جدول'), ('cards', 'بطاقات'), ('chart', 'رسم بياني'), ('mixed', 'مختلط')], default='table', max_length=20, verbose_name='التخطيط')),
                ('chart_type', models.CharField(blank=True, choices=[('bar', 'أعمدة'), ('line', 'خطي'), ('pie', 'دائري'), ('area', 'مساحة'), ('scatter', 'نقطي')], max_length=50, verbose_name='نوع الرسم البياني')),
                ('theme', models.CharField(default='default', max_length=50, verbose_name='السمة')),
                ('custom_css', models.TextField(blank=True, verbose_name='CSS مخصص')),
                ('supported_formats', models.CharField(default='pdf,excel,csv', help_text='مفصولة بفاصلة', max_length=100, verbose_name='صيغ الإخراج')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='تكرار الجدولة')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('schedule_recipients', models.TextField(blank=True, help_text='بريد إلكتروني، مفصول بفاصلة', verbose_name='المستلمون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('run_count', models.IntegerField(default=0, verbose_name='عدد مرات التشغيل')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_report_templates', to='auth.group', verbose_name='المجموعات المسموح لها')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المسموح لهم')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='اسم الحقل')),
                ('operator', models.CharField(choices=[('equals', 'يساوي'), ('not_equals', 'لا يساوي'), ('greater_than', 'أكبر من'), ('greater_than_equal', 'أكبر من أو يساوي'), ('less_than', 'أصغر من'), ('less_than_equal', 'أصغر من أو يساوي'), ('contains', 'يحتوي'), ('not_contains', 'لا يحتوي'), ('starts_with', 'يبدأ بـ'), ('ends_with', 'ينتهي بـ'), ('in', 'ضمن'), ('not_in', 'ليس ضمن'), ('between', 'بين'), ('is_null', 'فارغ'), ('is_not_null', 'غير فارغ')], max_length=30, verbose_name='المشغل')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
                ('is_dynamic', models.BooleanField(default=False, help_text='يتم تحديثه عند التنفيذ', verbose_name='ديناميكي')),
                ('dynamic_value_source', models.CharField(blank=True, max_length=100, verbose_name='مصدر القيمة الديناميكية')),
                ('group_id', models.IntegerField(default=0, verbose_name='معرف المجموعة')),
                ('logical_operator', models.CharField(choices=[('AND', 'و'), ('OR', 'أو')], default='AND', max_length=5, verbose_name='مشغل منطقي')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='reports.reporttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'فلتر تقرير',
                'verbose_name_plural': 'فلاتر التقارير',
                'ordering': ['group_id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('label', models.CharField(max_length=200, verbose_name='التسمية')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('datetime', 'تاريخ ووقت'), ('boolean', 'منطقي'), ('choice', 'اختيار'), ('foreign_key', 'مرجع خارجي'), ('calculated', 'محسوب')], max_length=20, verbose_name='نوع الحقل')),
                ('source_field', models.CharField(help_text='اسم الحقل في الموديل', max_length=200, verbose_name='حقل المصدر')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='محسوب')),
                ('calculation_formula', models.TextField(blank=True, verbose_name='صيغة الحساب')),
                ('aggregation', models.CharField(choices=[('none', 'بدون'), ('sum', 'مجموع'), ('avg', 'متوسط'), ('count', 'عدد'), ('min', 'أصغر قيمة'), ('max', 'أكبر قيمة')], default='none', max_length=20, verbose_name='التجميع')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='العرض (%)')),
                ('alignment', models.CharField(choices=[('left', 'يسار'), ('center', 'وسط'), ('right', 'يمين')], default='left', max_length=10, verbose_name='المحاذاة')),
                ('format_string', models.CharField(blank=True, help_text='مثال: {:.2f} للأرقام', max_length=100, verbose_name='صيغة التنسيق')),
                ('prefix', models.CharField(blank=True, max_length=50, verbose_name='بادئة')),
                ('suffix', models.CharField(blank=True, max_length=50, verbose_name='لاحقة')),
                ('conditional_formatting', models.TextField(blank=True, help_text='JSON rules', verbose_name='التنسيق الشرطي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.reporttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'حقل تقرير',
                'verbose_name_plural': 'حقول التقارير',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField(blank=True, help_text='JSON parameters', verbose_name='المعاملات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية التنفيذ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية التنفيذ')),
                ('output_format', models.CharField(max_length=20, verbose_name='صيغة الإخراج')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/output/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'csv', 'html', 'json'])], verbose_name='ملف الإخراج')),
                ('output_file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('rows_processed', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفوف')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='وقت التنفيذ (ثواني)')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('error_traceback', models.TextField(blank=True, verbose_name='تتبع الخطأ')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الجدولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'تنفيذ تقرير',
                'verbose_name_plural': 'تنفيذات التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('data_snapshot', models.TextField(help_text='JSON snapshot', verbose_name='البيانات')),
                ('is_shared', models.BooleanField(default=False, verbose_name='مشارك')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report', to='reports.reportexecution', verbose_name='التنفيذ')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشارك مع')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='reports.reporttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'تقرير محفوظ',
                'verbose_name_plural': 'تقارير محفوظة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['category', '-created_at'], name='reports_rep_categor_3777a0_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='reports_rep_created_170369_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active', '-created_at'], name='reports_rep_is_acti_12be14_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['template', '-created_at'], name='reports_rep_templat_ed2a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['executed_by', '-created_at'], name='reports_rep_execute_f2589b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status', '-created_at'], name='reports_rep_status_6cfda6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['is_scheduled', 'scheduled_at'], name='reports_rep_is_sche_42c4a9_idx'),
        ),
    ]
