# Generated by Django 5.2.5 on 2026-02-11 03:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattressFeelingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإحساس')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('firmness_level', models.CharField(choices=[('extra_soft', 'ناعم جداً'), ('soft', 'ناعم'), ('medium_soft', 'متوسط الليونة'), ('medium', 'متوسط'), ('medium_firm', 'متوسط الصلابة'), ('firm', 'صلب'), ('extra_firm', 'صلب جداً')], max_length=20, verbose_name='مستوى الصلابة')),
                ('firmness_score', models.PositiveIntegerField(default=5, help_text='1=ناعم جداً، 10=صلب جداً', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درجة الصلابة (1-10)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='اللون')),
                ('ideal_for', models.JSONField(blank=True, default=list, help_text='مثال: ["النوم على الظهر", "آلام الظهر", "الأطفال"]', verbose_name='مناسب لـ')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='مثال: ["راحة فائقة", "دعم العمود الفقري"]', verbose_name='الفوائد')),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='سعر إضافي لهذا الإحساس إن وجد', max_digits=10, verbose_name='سعر إضافي')),
                ('auto_detect_rules', models.JSONField(blank=True, default=dict, help_text='JSON: {"min_density": 30, "max_density": 50, "required_categories": ["foam","springs"]}', verbose_name='قواعد الكشف التلقائي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع إحساس المرتبة',
                'verbose_name_plural': 'أنواع إحساس المرتبة',
                'ordering': ['firmness_score', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='enable_ai_suggestions',
            field=models.BooleanField(default=True, verbose_name='تفعيل اقتراحات الذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='enable_feeling_detection',
            field=models.BooleanField(default=True, verbose_name='تفعيل كشف الإحساس التلقائي'),
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='enable_feeling_selection',
            field=models.BooleanField(default=True, verbose_name='تفعيل اختيار الإحساس يدوياً'),
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='max_ai_suggestions',
            field=models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للاقتراحات'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='feeling_auto_detected',
            field=models.BooleanField(default=False, help_text='هل تم تحديد الإحساس تلقائياً بناءً على المكونات؟', verbose_name='تم الكشف تلقائياً'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='feeling_score',
            field=models.PositiveIntegerField(default=5, help_text='1=ناعم جداً، 10=صلب جداً', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درجة الإحساس'),
        ),
        migrations.CreateModel(
            name='AIRecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاقتراح')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('trigger_type', models.CharField(choices=[('on_size_select', 'عند اختيار المقاس'), ('on_component_add', 'عند إضافة مكون'), ('on_component_remove', 'عند إزالة مكون'), ('on_budget_exceed', 'عند تجاوز الميزانية'), ('on_category_complete', 'عند اكتمال فئة'), ('on_feeling_mismatch', 'عند عدم تطابق الإحساس'), ('on_thickness_threshold', 'عند تجاوز حد السماكة'), ('always', 'دائماً')], max_length=30, verbose_name='نوع المحفز')),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='JSON مثال: {\n            "component_category": "foam",\n            "min_price": 2000,\n            "max_thickness": 30,\n            "selected_components_count": 3,\n            "feeling_score_range": [1, 4]\n        }', verbose_name='شروط التفعيل')),
                ('suggestion_type', models.CharField(choices=[('add_component', 'اقتراح إضافة مكون'), ('remove_component', 'اقتراح إزالة مكون'), ('upgrade_component', 'اقتراح ترقية مكون'), ('change_size', 'اقتراح تغيير المقاس'), ('suggest_feeling', 'اقتراح إحساس المرتبة'), ('cost_saving', 'اقتراح توفير'), ('quality_tip', 'نصيحة جودة'), ('health_tip', 'نصيحة صحية'), ('custom_message', 'رسالة مخصصة')], max_length=30, verbose_name='نوع الاقتراح')),
                ('suggestion_data', models.JSONField(blank=True, default=dict, help_text='JSON مثال: {\n            "component_id": 5,\n            "message": "جرب إضافة طبقة ميموري فوم",\n            "discount_hint": "وفر 15% مع هذا البديل"\n        }', verbose_name='بيانات الاقتراح')),
                ('message_ar', models.TextField(verbose_name='الرسالة بالعربية')),
                ('message_en', models.TextField(blank=True, verbose_name='الرسالة بالإنجليزية')),
                ('icon', models.CharField(default='bi bi-lightbulb', max_length=50, verbose_name='أيقونة')),
                ('message_style', models.CharField(choices=[('info', 'معلومة 💡'), ('tip', 'نصيحة 🎯'), ('upgrade', 'ترقية ⬆️'), ('warning', 'تحذير ⚠️'), ('success', 'ممتاز ✅'), ('savings', 'توفير 💰'), ('health', 'صحي 🏥')], default='tip', max_length=20, verbose_name='نمط الرسالة')),
                ('priority', models.PositiveIntegerField(default=50, help_text='0-100، الأعلى يظهر أولاً', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='mattress_builder.mattresscomponent', verbose_name='المكون المقترح')),
                ('suggested_feeling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='mattress_builder.mattressfeelingtype', verbose_name='الإحساس المقترح')),
            ],
            options={
                'verbose_name': 'اقتراح ذكاء اصطناعي',
                'verbose_name_plural': 'اقتراحات الذكاء الاصطناعي',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='feeling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='mattress_builder.mattressfeelingtype', verbose_name='إحساس المرتبة'),
        ),
    ]
