# Generated by Django 5.2.5 on 2026-02-11 04:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_add_is_active_to_supplier'),
        ('mattress_builder', '0002_mattressfeelingtype_and_more'),
        ('production', '0010_alter_billofmaterials_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buildersettings',
            name='designer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='النسبة المئوية التي يحصل عليها مصمم المرتبة عند بيع تصميمه', max_digits=5, verbose_name='نسبة عمولة المصمم الافتراضية %'),
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='enable_community_designs',
            field=models.BooleanField(default=True, help_text='السماح للعملاء بنشر تصميماتهم وبيعها', verbose_name='تفعيل تصميمات المجتمع'),
        ),
        migrations.AddField(
            model_name='buildersettings',
            name='enable_duplicate_detection',
            field=models.BooleanField(default=True, help_text='إخطار العميل إذا كان تصميمه موجود مسبقاً', verbose_name='تفعيل كشف التصميمات المكررة'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='design_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash فريد للكشف عن التصميمات المتكررة', max_length=64, verbose_name='بصمة التصميم'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='designer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='النسبة المئوية التي يحصل عليها المصمم عند بيع تصميمه', max_digits=5, verbose_name='نسبة عمولة المصمم %'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='is_public',
            field=models.BooleanField(default=False, help_text='هل يمكن للعملاء الآخرين شراء هذا التصميم؟', verbose_name='منشور للجمهور'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='published_name',
            field=models.CharField(blank=True, help_text='الاسم الذي يظهر للعملاء الآخرين عند نشر التصميم', max_length=200, verbose_name='الاسم المنشور'),
        ),
        migrations.AddField(
            model_name='custommattressdesign',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات البيع'),
        ),
        migrations.CreateModel(
            name='MattressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('is_community_purchase', models.BooleanField(default=False, help_text='هل تم شراء هذا التصميم من تصميمات عملاء آخرين', verbose_name='شراء تصميم مجتمعي')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('shipping_address', models.TextField(verbose_name='عنوان التسليم')),
                ('shipping_city', models.CharField(default='القاهرة', max_length=100, verbose_name='المدينة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المجموع الفرعي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='تكلفة الشحن')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الخصم')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending_payment', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('in_production', 'قيد الإنتاج'), ('quality_check', 'فحص الجودة'), ('ready', 'جاهز للتسليم'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'مسترجع')], default='pending_payment', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'كاش'), ('visa', 'فيزا'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم الفعلي')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mattress_orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mattress_builder.custommattressdesign', verbose_name='التصميم')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattress_orders', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('original_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs_sold', to=settings.AUTH_USER_MODEL, verbose_name='المصمم الأصلي')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattress_orders', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'طلب مرتبة',
                'verbose_name_plural': 'طلبات المراتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة العمولة %')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ العمولة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'مُعتمدة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mattress_builder.custommattressdesign', verbose_name='التصميم')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_commissions', to=settings.AUTH_USER_MODEL, verbose_name='المصمم')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_commissions', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mattress_builder.mattressorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عمولة مصمم',
                'verbose_name_plural': 'عمولات المصممين',
                'ordering': ['-created_at'],
            },
        ),
    ]
