# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfitabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period_start', models.DateField(verbose_name='بداية فترة التحليل')),
                ('analysis_period_end', models.DateField(verbose_name='نهاية فترة التحليل')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('total_orders', models.IntegerField(default=0, verbose_name='عدد الطلبات')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='متوسط قيمة الطلب')),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة البضاعة المباعة')),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الخدمة')),
                ('marketing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة التسويق')),
                ('support_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة الدعم')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الربح')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي الربح')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش الربح %')),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة العميل مدى الحياة')),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة اكتساب العميل')),
                ('tier', models.CharField(choices=[('A', 'A - ممتاز'), ('B', 'B - جيد'), ('C', 'C - متوسط'), ('D', 'D - ضعيف')], default='C', max_length=10, verbose_name='التصنيف')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_analyses', to='crm.customer')),
            ],
            options={
                'verbose_name': 'تحليل ربحية عميل',
                'verbose_name_plural': 'تحليلات ربحية العملاء',
                'ordering': ['-net_profit'],
            },
        ),
        migrations.CreateModel(
            name='CustomerValueScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_score', models.IntegerField(default=0, help_text='آخر عملية شراء', verbose_name='نقاط الحداثة')),
                ('frequency_score', models.IntegerField(default=0, help_text='عدد المشتريات', verbose_name='نقاط التكرار')),
                ('monetary_score', models.IntegerField(default=0, help_text='إجمالي الإنفاق', verbose_name='نقاط القيمة النقدية')),
                ('total_score', models.IntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('segment', models.CharField(choices=[('champion', 'بطل'), ('loyal', 'مخلص'), ('potential', 'محتمل'), ('at_risk', 'معرض للخطر'), ('lost', 'مفقود')], default='potential', max_length=20, verbose_name='الشريحة')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='آخر حساب')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value_score', to='crm.customer')),
            ],
            options={
                'verbose_name': 'نقاط قيمة العميل',
                'verbose_name_plural': 'نقاط قيمة العملاء',
            },
        ),
    ]
