# Generated by Django 5.2.9 on 2026-03-01 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('count_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الجرد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('counting', 'جاري العد'), ('review', 'مراجعة'), ('applied', 'مطبّق'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'جرد مخزني',
                'verbose_name_plural': 'الجرد المخزني',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية في النظام')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الكمية الفعلية')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الفرق')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.product', verbose_name='المنتج')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='الجرد')),
            ],
            options={
                'verbose_name': 'سطر جرد',
                'verbose_name_plural': 'أسطر الجرد',
            },
        ),
    ]
