# Generated by Django 5.2.9 on 2026-03-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockcount_stockcountline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['product__name', '-version'], 'verbose_name': 'قائمة مواد (BOM)', 'verbose_name_plural': 'قوائم المواد (BOM)'},
        ),
        migrations.AlterModelOptions(
            name='bomline',
            options={'ordering': ['sort_order'], 'verbose_name': 'مكوّن BOM', 'verbose_name_plural': 'مكوّنات BOM'},
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='bom_type',
            field=models.CharField(choices=[('standard', 'قياسية'), ('phantom', 'وهمية (نصف مصنع يذوب)'), ('configurable', 'قابلة للتخصيص')], default='standard', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود BOM'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='estimated_labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة عمالة تقديرية'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='estimated_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تكلفة خامات تقديرية'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='estimated_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='overhead تقديري'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='estimated_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكلفة الإجمالية التقديرية'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='version',
            field=models.IntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='العرض (سم)'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='alternative_group',
            field=models.CharField(blank=True, max_length=20, verbose_name='مجموعة البدائل'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='is_alternative',
            field=models.BooleanField(default=False, verbose_name='مكوّن بديل'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم BOM'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.product', verbose_name='المكوّن'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة هالك %'),
        ),
    ]
