# Generated by Django 5.2.5 on 2025-12-15 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_type', models.CharField(choices=[('store', 'مساعد المتجر'), ('system', 'مساعد النظام')], max_length=20, unique=True, verbose_name='نوع المساعد')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المساعد')),
                ('welcome_message', models.TextField(blank=True, verbose_name='رسالة الترحيب')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('local', 'نموذج محلي')], default='openai', max_length=20, verbose_name='مزود الخدمة')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح API')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100, verbose_name='اسم النموذج')),
                ('system_prompt', models.TextField(blank=True, help_text='التعليمات التي يتبعها المساعد', verbose_name='تعليمات النظام')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='الحد الأقصى للتوكنز')),
                ('temperature', models.FloatField(default=0.7, verbose_name='درجة الإبداعية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('enable_product_search', models.BooleanField(default=True, help_text='للمساعد المتجر فقط', verbose_name='تفعيل البحث في المنتجات')),
                ('enable_order_tracking', models.BooleanField(default=True, verbose_name='تفعيل تتبع الطلبات')),
                ('enable_faq', models.BooleanField(default=True, verbose_name='تفعيل الأسئلة الشائعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المساعد الذكي',
                'verbose_name_plural': 'إعدادات المساعدين الذكية',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_type', models.CharField(choices=[('store', 'مساعد المتجر'), ('system', 'مساعد النظام')], max_length=20, verbose_name='نوع المساعد')),
                ('category', models.CharField(choices=[('general', 'عام'), ('products', 'المنتجات'), ('orders', 'الطلبات'), ('shipping', 'الشحن'), ('payment', 'الدفع'), ('returns', 'المرتجعات'), ('account', 'الحساب')], default='general', max_length=20, verbose_name='التصنيف')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('keywords', models.TextField(blank=True, help_text='كلمات مفتاحية مفصولة بفواصل', verbose_name='الكلمات المفتاحية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات المساعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_type', models.CharField(choices=[('store', 'مساعد المتجر'), ('system', 'مساعد النظام')], max_length=20, verbose_name='نوع المساعد')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('icon', models.CharField(default='bi-chat-dots', max_length=50, verbose_name='الأيقونة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رد سريع',
                'verbose_name_plural': 'الردود السريعة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='للزوار غير المسجلين', max_length=100, verbose_name='مفتاح الجلسة')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان المحادثة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بداية المحادثة')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية المحادثة')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('assistant_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai_assistant.aiassistantsettings', verbose_name='إعدادات المساعد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة محادثة',
                'verbose_name_plural': 'جلسات المحادثات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'المساعد'), ('system', 'النظام')], max_length=20, verbose_name='الدور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='التوكنز المستخدمة')),
                ('processing_time', models.FloatField(default=0, verbose_name='وقت المعالجة (ثواني)')),
                ('related_products', models.JSONField(blank=True, default=list, verbose_name='المنتجات المرتبطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'ordering': ['created_at'],
            },
        ),
    ]
