# Generated by Django 5.2.5 on 2025-08-19 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0009_issue_inventory_i_status_e12400_idx_and_more'),
        ('partners', '0005_customer_partner'),
        ('payments', '0003_alter_paymentmethod_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ المدفوع')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مخزن لتسريع الاستعلامات', max_digits=12, verbose_name='الإجمالي')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='partners.customer', verbose_name='العميل')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع / المعرض')),
            ],
            options={
                'verbose_name': 'طلب POS',
                'verbose_name_plural': 'طلبات POS',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.posorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة POS',
                'verbose_name_plural': 'دفعات POS',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='رصيد افتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='رصيد إغلاق')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوحة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة نقطة بيع',
                'verbose_name_plural': 'جلسات نقاط البيع',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.possession', verbose_name='الجلسة'),
        ),
        migrations.CreateModel(
            name='POSOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.posorder', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند طلب POS',
                'verbose_name_plural': 'بنود طلب POS',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='posline_qty_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['created_at'], name='posorder_created_idx'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['status'], name='posorder_status_idx'),
        ),
    ]
