# Generated by Django 5.2.5 on 2025-08-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_possession_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posorder',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('view', 'عرض أوامر نقطة البيع'), ('add', 'إضافة أوامر نقطة البيع'), ('change', 'تعديل أوامر نقطة البيع')], 'verbose_name': 'طلب POS', 'verbose_name_plural': 'طلبات POS'},
        ),
        migrations.AlterModelOptions(
            name='posorderline',
            options={'permissions': [('view', 'عرض بنود أوامر نقطة البيع'), ('add', 'إضافة بنود أوامر نقطة البيع'), ('change', 'تعديل بنود أوامر نقطة البيع')], 'verbose_name': 'بند طلب POS', 'verbose_name_plural': 'بنود طلب POS'},
        ),
    ]
