# Generated by Django 5.2.5 on 2025-08-19 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_posorder_options_alter_posorderline_options'),
        ('showrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='showrooms.showroom', verbose_name='المعرض'),
        ),
    ]
