# Generated by Django 5.2.5 on 2025-08-19 23:10

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_posorder_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة البضاعة المباعة'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='إرجاع؟'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='pos.posorder', verbose_name='الطلب الأصلي'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة VAT %'),
        ),
    ]
