# Generated by Django 5.2.5 on 2025-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_posorder_cogs_amount_posorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='possession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
