# Generated by Django 5.2.5 on 2025-12-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_unit_warranty'),
        ('pos', '0006_alter_posorder_id_alter_posorderline_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='اسم/رقم الطاولة')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='عدد المقاعد')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('reserved', 'محجوزة'), ('cleaning', 'قيد التنظيف')], default='available', max_length=20, verbose_name='الحالة')),
                ('shape', models.CharField(choices=[('square', 'مربعة'), ('round', 'دائرية'), ('rectangle', 'مستطيلة')], default='square', max_length=20, verbose_name='الشكل')),
                ('floor', models.CharField(blank=True, default='', max_length=50, verbose_name='الطابق/المنطقة')),
                ('position_x', models.PositiveIntegerField(default=0, help_text='للعرض على الخريطة', verbose_name='الموضع الأفقي')),
                ('position_y', models.PositiveIntegerField(default=0, help_text='للعرض على الخريطة', verbose_name='الموضع العمودي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_set', to='pos.posorder', verbose_name='الطلب الحالي')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='inventory.location', verbose_name='الموقع/المعرض')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
                'ordering': ['floor', 'name'],
                'unique_together': {('location', 'name')},
            },
        ),
    ]
