# Generated by Django 5.2.5 on 2025-12-24 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_product_unit_warranty'),
        ('pos', '0007_postable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الدفعة المقدمة')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المتبقي للتقسيط')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة القسط')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الفائدة %')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('customer_phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم موبايل إضافي')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('customer_national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم القومي')),
                ('guarantor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الضامن')),
                ('guarantor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم موبايل الضامن')),
                ('guarantor_national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم القومي للضامن')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='partners.customer', verbose_name='العميل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='pos.posorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'خطة تقسيط',
                'verbose_name_plural': 'خطط التقسيط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المدفوع')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='غرامة التأخير')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة الدفع')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_installments', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='pos.installmentplan', verbose_name='خطة التقسيط')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['due_date'],
                'unique_together': {('plan', 'installment_number')},
            },
        ),
    ]
