# Generated by Django 5.2.5 on 2025-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_installment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_tax_invoice',
            field=models.BooleanField(default=False, help_text='هل يتم إظهار الرقم الضريبي والضريبة في الإيصال', verbose_name='فاتورة ضريبية؟'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مصاريف الشحن'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة ضريبة المنبع'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة المنبع %'),
        ),
    ]
