# Generated by Django 5.2.9 on 2026-01-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        ('pos', '0009_add_tax_shipping_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPriceButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('label', models.CharField(blank=True, max_length=20, verbose_name='التسمية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'زر مبلغ سريع',
                'verbose_name_plural': 'أزرار المبالغ السريعة',
                'ordering': ['order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='HeldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('items_json', models.JSONField(help_text='JSON يحتوي على المنتجات والكميات والأسعار', verbose_name='بنود الطلب')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='الموقع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب معلق',
                'verbose_name_plural': 'الطلبات المعلقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='inventory.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'منتج مفضل',
                'verbose_name_plural': 'المنتجات المفضلة',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
