# Generated by Django 5.2.5 on 2026-02-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_add_hold_favorites_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='heldorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='heldorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuickPriceButton',
        ),
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
        migrations.DeleteModel(
            name='HeldOrder',
        ),
    ]
