# Generated by Django 5.2.5 on 2026-01-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0025_alter_journalentry_created_by'),
        ('hr', '0012_idcardtemplate_idcardbatchprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الميزانية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الميزانية')),
                ('budget_type', models.CharField(choices=[('annual', 'سنوية'), ('quarterly', 'ربع سنوية'), ('monthly', 'شهرية'), ('project', 'مشروع'), ('department', 'قسم')], default='annual', max_length=20, verbose_name='نوع الميزانية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدمة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('active', 'نشطة'), ('closed', 'مغلقة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي المخطط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المخطط')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ الفعلي')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المرتبط')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.account', verbose_name='الحساب')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.budget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'بند ميزانية',
                'verbose_name_plural': 'بنود الميزانية',
                'unique_together': {('budget', 'account')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('warning', 'تحذير'), ('exceeded', 'تجاوز'), ('approaching', 'اقتراب')], max_length=20, verbose_name='نوع التنبيه')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('threshold_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الحد')),
                ('current_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النسبة الحالية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgeting.budget')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_budget_alerts', to=settings.AUTH_USER_MODEL)),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgeting.budgetline')),
            ],
            options={
                'verbose_name': 'تنبيه ميزانية',
                'verbose_name_plural': 'تنبيهات الميزانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='budgeting.budgetline', verbose_name='من بند')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_budget_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='budgeting.budgetline', verbose_name='إلى بند')),
            ],
            options={
                'verbose_name': 'تحويل ميزانية',
                'verbose_name_plural': 'تحويلات الميزانية',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السنة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('closed', 'مغلقة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budgeting.fiscalyear', verbose_name='السنة المالية'),
        ),
    ]
