# Generated by Django 5.2.11 on 2026-03-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_links', to='accounts.account', verbose_name='الحساب المحاسبي')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخزنة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_box_links', to='accounts.account', verbose_name='الحساب المحاسبي')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_boxes', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_boxes', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'خزنة',
                'verbose_name_plural': 'الخزائن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('check_number', models.CharField(max_length=50, verbose_name='رقم الشيك')),
                ('check_type', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=10, verbose_name='النوع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('deposited', 'مودع'), ('cleared', 'تم التحصيل'), ('bounced', 'مرتجع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('partner_name', models.CharField(max_length=255, verbose_name='اسم الطرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='treasury.bankaccount', verbose_name='البنك')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='accounts.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'شيك',
                'verbose_name_plural': 'الشيكات',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('from_account_type', models.CharField(choices=[('cash', 'خزنة'), ('bank', 'بنك')], max_length=20, verbose_name='نوع المصدر')),
                ('to_account_type', models.CharField(choices=[('cash', 'خزنة'), ('bank', 'بنك')], max_length=20, verbose_name='نوع الوجهة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.bankaccount', verbose_name='البنك المصدر')),
                ('from_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.cashbox', verbose_name='الخزنة المصدر')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_transfers', to='accounts.journalentry')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.bankaccount', verbose_name='البنك الوجهة')),
                ('to_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.cashbox', verbose_name='الخزنة الوجهة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'التحويلات المالية',
                'ordering': ['-date'],
            },
        ),
    ]
