# Generated by Django 5.2.5 on 2025-12-09 00:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0023_add_product_costing_system'),
        ('partners', '0008_alter_customer_id_alter_partner_id_alter_supplier_id'),
        ('purchases', '0015_purchaserequisition_purchaserequisitionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'القسط الثابت'), ('declining_balance', 'القسط المتناقص'), ('units_of_production', 'وحدات الإنتاج')], default='straight_line', max_length=20, verbose_name='طريقة الاستهلاك الافتراضية')),
                ('default_useful_life_years', models.PositiveIntegerField(default=5, verbose_name='العمر الافتراضي (سنوات)')),
                ('default_salvage_value_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='قيمة الخردة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_categories', to='accounting.account', verbose_name='حساب مجمع الاستهلاك')),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='accounting.account', verbose_name='حساب الأصل')),
                ('depreciation_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_categories', to='accounting.account', verbose_name='حساب مصروف الاستهلاك')),
            ],
            options={
                'verbose_name': 'تصنيف أصل',
                'verbose_name_plural': 'تصنيفات الأصول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأصل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='الرقم التسلسلي')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='الشركة المصنعة')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='الموديل/الطراز')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='القسم')),
                ('acquisition_date', models.DateField(verbose_name='تاريخ الشراء/الاستحواذ')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='تكلفة الاستحواذ')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'القسط الثابت'), ('declining_balance', 'القسط المتناقص'), ('units_of_production', 'وحدات الإنتاج'), ('manual', 'يدوي')], default='straight_line', max_length=20, verbose_name='طريقة الاستهلاك')),
                ('useful_life_years', models.PositiveIntegerField(default=5, verbose_name='العمر الافتراضي (سنوات)')),
                ('useful_life_units', models.PositiveIntegerField(blank=True, help_text='للاستهلاك بوحدات الإنتاج', null=True, verbose_name='العمر الافتراضي (وحدات)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='قيمة الخردة')),
                ('depreciation_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الاستهلاك')),
                ('status', models.CharField(choices=[('active', 'نشط/قيد التشغيل'), ('under_maintenance', 'تحت الصيانة'), ('idle', 'متوقف'), ('disposed', 'مُتخلَّص منه'), ('sold', 'مُباع')], default='active', max_length=20, verbose_name='الحالة')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستبعاد')),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قيمة الاستبعاد')),
                ('disposal_notes', models.TextField(blank=True, verbose_name='ملاحظات الاستبعاد')),
                ('warranty_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الضمان')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='آخر صيانة')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='الصيانة القادمة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='صورة')),
                ('documents', models.FileField(blank=True, null=True, upload_to='assets/docs/', verbose_name='مستندات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='purchases.purchasebill', verbose_name='فاتورة الشراء')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
                'ordering': ['-acquisition_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'وقائية'), ('corrective', 'تصحيحية'), ('emergency', 'طارئة'), ('upgrade', 'ترقية/تحسين')], max_length=20, verbose_name='نوع الصيانة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='نُفذت بواسطة')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='التكلفة')),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ساعات التوقف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fixed_assets.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance', to='partners.supplier', verbose_name='المقاول/المورد')),
            ],
            options={
                'verbose_name': 'صيانة أصل',
                'verbose_name_plural': 'صيانة الأصول',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ النقل')),
                ('from_location', models.CharField(max_length=200, verbose_name='من موقع')),
                ('to_location', models.CharField(max_length=200, verbose_name='إلى موقع')),
                ('from_department', models.CharField(blank=True, max_length=200, verbose_name='من قسم')),
                ('to_department', models.CharField(blank=True, max_length=200, verbose_name='إلى قسم')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_transfers', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fixed_assets.asset', verbose_name='الأصل')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from_assets', to=settings.AUTH_USER_MODEL, verbose_name='من مستخدم')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_assets', to=settings.AUTH_USER_MODEL, verbose_name='إلى مستخدم')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_asset_transfers', to=settings.AUTH_USER_MODEL, verbose_name='نُفذ بواسطة')),
            ],
            options={
                'verbose_name': 'نقل أصل',
                'verbose_name_plural': 'نقل الأصول',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الاستهلاك')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مجمع الاستهلاك')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة الدفترية')),
                ('status', models.CharField(choices=[('scheduled', 'مُجدول'), ('posted', 'مُرحّل'), ('cancelled', 'ملغى')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='fixed_assets.asset', verbose_name='الأصل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُحّل بواسطة')),
            ],
            options={
                'verbose_name': 'قسط استهلاك',
                'verbose_name_plural': 'جدول الاستهلاك',
                'ordering': ['asset', 'period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='fixed_asset_status_1c273b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='fixed_asset_categor_0fde4f_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['acquisition_date'], name='fixed_asset_acquisi_18c99c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmaintenance',
            index=models.Index(fields=['asset', '-date'], name='fixed_asset_asset_i_75f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationschedule',
            index=models.Index(fields=['period_start'], name='fixed_asset_period__9b4d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationschedule',
            index=models.Index(fields=['status'], name='fixed_asset_status_be7fba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationschedule',
            unique_together={('asset', 'period_start')},
        ),
    ]
