# Generated by Django 5.2.5 on 2025-12-09 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
        ('purchases', '0015_purchaserequisition_purchaserequisitionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='fixed_asset_status_1c273b_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='fixed_asset_categor_0fde4f_idx',
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='fixed_asset_status_4c1820_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location', 'status'], name='fixed_asset_locatio_d659cf_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department'], name='fixed_asset_departm_543b57_idx'),
        ),
    ]
