# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0002_remove_asset_fixed_asset_status_1c273b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ النقل'),
        ),
    ]
