# Generated by Django 5.2.5 on 2025-08-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_product_is_promo_active_product_promo_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(blank=True, max_length=120, null=True, verbose_name='الاسم (عربي)')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الافتتاح')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='showroom', to='inventory.location', verbose_name='الموقع المخزني')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_showrooms', to=settings.AUTH_USER_MODEL, verbose_name='المدير')),
            ],
            options={
                'verbose_name': 'معرض',
                'verbose_name_plural': 'معارض',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cashier', 'أمين صندوق'), ('sales', 'مبيعات'), ('supervisor', 'مشرف'), ('manager', 'مدير')], max_length=20, verbose_name='الدور')),
                ('can_cross_access', models.BooleanField(default=False, verbose_name='صلاحية الوصول لجميع المعارض')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='showrooms.showroom', verbose_name='المعرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف معرض',
                'verbose_name_plural': 'موظفو المعارض',
            },
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['code'], name='showrooms_s_code_87d819_idx'),
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['is_active'], name='showrooms_s_is_acti_188c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomemployee',
            index=models.Index(fields=['showroom', 'user'], name='showrooms_s_showroo_0b1c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomemployee',
            index=models.Index(fields=['user', 'active'], name='showrooms_s_user_id_169d29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomemployee',
            unique_together={('showroom', 'user')},
        ),
    ]
