# Generated by Django 5.2.5 on 2025-08-19 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomemployee',
            name='extra_perms',
            field=models.JSONField(blank=True, default=list, help_text='مثال: ["pos.export","inventory.view"]', verbose_name='صلاحيات إضافية (module.action)'),
        ),
        migrations.AddConstraint(
            model_name='showroomemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('role', 'manager')), fields=('showroom',), name='uq_showroom_single_manager'),
        ),
    ]
