# Generated by Django 5.2.5 on 2025-08-21 20:09

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_0012_dual'),
        ('showrooms', '0004_alter_showroom_location_related_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='showrooms_a_showroo_4c4c49_idx',
            old_name='showroom_attendance_showroom_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='showrooms_a_employe_eeaa9c_idx',
            old_name='showroom_attendance_employee_date_idx',
        ),
        migrations.RenameIndex(
            model_name='posdevice',
            new_name='showrooms_p_showroo_04c10f_idx',
            old_name='showroom_posdevice_showroom_active_idx',
        ),
        migrations.RenameIndex(
            model_name='posdevice',
            new_name='showrooms_p_identif_36cb01_idx',
            old_name='showroom_posdevice_identifier_idx',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='showroom_link', to='inventory.location', verbose_name='الموقع المخزني'),
        ),
    ]
