# Generated by Django 5.2.5 on 2025-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0008_contact_fields_shifts_and_attachments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='showroomshiftassignment',
            name='showroom_shift_employee_day_unique',
        ),
        migrations.RenameIndex(
            model_name='showroomexpense',
            new_name='showrooms_s_showroo_dc17a8_idx',
            old_name='shexp_showroom_status_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomexpense',
            new_name='showrooms_s_categor_80bd9a_idx',
            old_name='shexp_category_idx',
        ),
        migrations.RenameIndex(
            model_name='showroompayrollentry',
            new_name='showrooms_s_showroo_4fd774_idx',
            old_name='shpay_showroom_period_idx',
        ),
        migrations.RenameIndex(
            model_name='showroompayrollentry',
            new_name='showrooms_s_status_c95451_idx',
            old_name='shpay_status_idx',
        ),
        migrations.RenameIndex(
            model_name='showroompurchase',
            new_name='showrooms_s_showroo_626b96_idx',
            old_name='shpurch_showroom_status_idx',
        ),
        migrations.RenameIndex(
            model_name='showroompurchase',
            new_name='showrooms_s_number_640abe_idx',
            old_name='shpurch_number_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomshift',
            new_name='showrooms_s_showroo_0d84cd_idx',
            old_name='showrooms_sh_showroo_6e35af_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomshiftassignment',
            new_name='showrooms_s_employe_a53412_idx',
            old_name='showrooms_sh_employee_8fecb4_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomshiftassignment',
            new_name='showrooms_s_shift_i_bdeb02_idx',
            old_name='showrooms_sh_shift_da_5c787a_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomstockmovement',
            new_name='showrooms_s_showroo_edc6f7_idx',
            old_name='shmove_showroom_type_idx',
        ),
        migrations.RenameIndex(
            model_name='showroomstockmovement',
            new_name='showrooms_s_product_6928f1_idx',
            old_name='shmove_product_location_idx',
        ),
        migrations.AlterField(
            model_name='showroomemployee',
            name='role',
            field=models.CharField(choices=[('cashier', 'أمين صندوق'), ('sales', 'مبيعات'), ('supervisor', 'مشرف'), ('manager', 'مدير'), ('storekeeper', 'أمين مخزن'), ('warehouse_worker', 'عامل مستودع'), ('hr', 'شؤون موظفين'), ('call_center', 'كول سنتر'), ('customer_service', 'خدمة عملاء'), ('porter', 'حامل/عامل تحميل'), ('pantry', 'بانتر/ضيافة'), ('worker', 'عامل متنوع')], max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomshiftassignment',
            unique_together={('shift', 'employee', 'day_of_week')},
        ),
    ]
