# Generated by Django 5.2.5 on 2025-12-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0009_remove_showroomshiftassignment_showroom_shift_employee_day_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='country',
            field=models.CharField(blank=True, default='مصر', max_length=80, verbose_name='البلد'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='governorate',
            field=models.CharField(blank=True, max_length=80, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان التفصيلي'),
        ),
    ]
