# Generated by Django 5.2.9 on 2026-01-04 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        ('showrooms', '0010_showroom_country_showroom_governorate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomPricingRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('fixed', 'سعر ثابت'), ('percentage', 'نسبة من السعر الأساسي'), ('markup', 'هامش ربح'), ('discount', 'خصم')], default='percentage', max_length=20, verbose_name='نوع التسعير')),
                ('value', models.DecimalField(decimal_places=2, help_text='السعر الثابت أو النسبة المئوية أو قيمة الهامش', max_digits=12, verbose_name='القيمة')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, help_text='اتركه فارغاً للتطبيق الدائم', null=True, verbose_name='ساري حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=1, help_text='الأولوية الأعلى تطبق أولاً', verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_prices', to='inventory.product', verbose_name='المنتج')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='showrooms.showroom', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير معرض',
                'verbose_name_plural': 'قواعد تسعير المعارض',
                'ordering': ['showroom', '-priority', 'product'],
                'indexes': [models.Index(fields=['showroom', 'product', 'is_active'], name='showrooms_s_showroo_44c406_idx'), models.Index(fields=['effective_from', 'effective_to'], name='showrooms_s_effecti_fb76e9_idx')],
            },
        ),
    ]
