# Generated by Django 5.2.9 on 2026-01-09 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_advanced_features_final'),
        ('showrooms', '0011_showroompricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomMoneyTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='رقم التحويل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('transfer_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('internal', 'تحويل داخلي'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة التحويل')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب')),
                ('cheque_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك')),
                ('cheque_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشيك')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التحويل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='showrooms.showroom', verbose_name='من معرض')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_money_transfers', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('to_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='showrooms.showroom', verbose_name='إلى معرض')),
            ],
            options={
                'verbose_name': 'تحويل أموال بين معارض',
                'verbose_name_plural': 'تحويلات الأموال بين المعارض',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_showroom', 'to_showroom'], name='showrooms_s_from_sh_0c6670_idx'), models.Index(fields=['status'], name='showrooms_s_status_ef8613_idx'), models.Index(fields=['transfer_date'], name='showrooms_s_transfe_548628_idx'), models.Index(fields=['transfer_method'], name='showrooms_s_transfe_76fe93_idx')],
            },
        ),
    ]
