# Generated by Django 5.2.9 on 2026-01-09 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        ('showrooms', '0012_showroommoneytransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomStockRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم الطلب')),
                ('quantity_requested', models.PositiveIntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية المعتمدة')),
                ('quantity_delivered', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية المستلمة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('reason', models.TextField(blank=True, help_text='مثال: طلب عميل، نفاد المخزون', verbose_name='سبب الطلب')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='اسم العميل (اختياري)')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف العميل (اختياري)')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='مطلوب بحلول')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests', to='inventory.product', verbose_name='المنتج')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('requesting_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests_out', to='showrooms.showroom', verbose_name='المعرض الطالب')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_shipped', to=settings.AUTH_USER_MODEL, verbose_name='شحن بواسطة')),
                ('source_showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests_in', to='showrooms.showroom', verbose_name='المعرض المصدر')),
                ('stock_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_stock_requests', to='inventory.stocktransfer', verbose_name='حركة المخزون')),
            ],
            options={
                'verbose_name': 'طلب نقل مخزون',
                'verbose_name_plural': 'طلبات نقل المخزون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requesting_showroom', 'status'], name='showrooms_s_request_da6010_idx'), models.Index(fields=['source_showroom', 'status'], name='showrooms_s_source__7ffa73_idx'), models.Index(fields=['product'], name='showrooms_s_product_b5f866_idx'), models.Index(fields=['status'], name='showrooms_s_status_e7a404_idx'), models.Index(fields=['priority'], name='showrooms_s_priorit_689e33_idx'), models.Index(fields=['request_date'], name='showrooms_s_request_bc9051_idx')],
            },
        ),
    ]
