# Generated by Django 5.2.9 on 2026-01-09 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        ('showrooms', '0013_showroomstockrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showroom',
            options={'ordering': ['showroom_type', 'code'], 'verbose_name': 'فرع/معرض', 'verbose_name_plural': 'الفروع والمعارض'},
        ),
        migrations.AddField(
            model_name='showroom',
            name='showroom_type',
            field=models.CharField(choices=[('showroom', 'معرض'), ('factory', 'مصنع'), ('warehouse', 'مستودع'), ('branch', 'فرع')], default='showroom', max_length=20, verbose_name='نوع الفرع'),
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['showroom_type'], name='showrooms_s_showroo_982f8c_idx'),
        ),
    ]
