# Generated by Django 5.2.9 on 2026-01-09 18:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_advanced_features_final'),
        ('showrooms', '0014_add_showroom_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='asset_account',
            field=models.ForeignKey(blank=True, help_text='حساب الأصول الثابتة للمعرض المملوك', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_assets', to='accounting.account', verbose_name='حساب الأصول'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='contract_document',
            field=models.FileField(blank=True, help_text='رفع نسخة من عقد الشراء أو الإيجار', null=True, upload_to='showrooms/contracts/%Y/%m/', verbose_name='عقد الشراء/الإيجار'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='للإيجار أو المعارض المؤقتة', null=True, verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='contract_notes',
            field=models.TextField(blank=True, help_text='أي تفاصيل إضافية عن العقد أو الاتفاقية', verbose_name='ملاحظات العقد'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قيمة الإيجار الشهري للمعارض المستأجرة', max_digits=12, null=True, verbose_name='الإيجار الشهري'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='property_type',
            field=models.CharField(choices=[('owned', 'تمليك'), ('rented', 'إيجار'), ('temporary', 'مؤقت')], default='rented', help_text='تمليك أو إيجار أو مؤقت', max_length=20, verbose_name='نوع الملكية'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر الشراء للتمليك أو قيمة التقييم', max_digits=15, null=True, verbose_name='قيمة المعرض'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='rent_expense_account',
            field=models.ForeignKey(blank=True, help_text='حساب مصروفات الإيجار للمعارض المستأجرة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_rent_expenses', to='accounting.account', verbose_name='حساب مصروفات الإيجار'),
        ),
        migrations.CreateModel(
            name='ShowroomRentPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفعة المقرر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payment_entries', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='showrooms.showroom', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'دفعة إيجار',
                'verbose_name_plural': 'دفعات الإيجار',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['showroom', 'status'], name='showrooms_s_showroo_e23fdf_idx'), models.Index(fields=['payment_date'], name='showrooms_s_payment_d96bfa_idx'), models.Index(fields=['status'], name='showrooms_s_status_b9a5c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=120, verbose_name='اسم العامل')),
                ('worker_phone', models.CharField(blank=True, max_length=40, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, help_text='رقم البطاقة أو الهوية', max_length=40, verbose_name='رقم الهوية')),
                ('worker_type', models.CharField(choices=[('daily', 'يومي'), ('hourly', 'بالساعة'), ('contract', 'عقد مؤقت')], default='daily', max_length=20, verbose_name='نوع العمل')),
                ('job_title', models.CharField(help_text='مثال: حامل، عامل تنظيف، موزع دعاية', max_length=120, verbose_name='المسمى الوظيفي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, help_text='للعمالة المؤقتة أو الموسمية', null=True, verbose_name='تاريخ النهاية')),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الأجر اليومي')),
                ('hourly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الأجر بالساعة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي المستحق')),
                ('days_worked', models.IntegerField(default=0, verbose_name='أيام العمل')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='ساعات العمل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('payment_reference', models.CharField(blank=True, help_text='رقم الإيصال أو القيد المحاسبي', max_length=100, verbose_name='مرجع السداد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_workers_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('expense_account', models.ForeignKey(blank=True, help_text='حساب مصروفات العمالة المؤقتة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_worker_expenses', to='accounting.account', verbose_name='حساب المصروفات')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_worker_entries', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_workers', to='showrooms.showroom', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'عامل مؤقت',
                'verbose_name_plural': 'العمالة المؤقتة',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['showroom', 'is_active'], name='showrooms_t_showroo_6ce76c_idx'), models.Index(fields=['start_date', 'end_date'], name='showrooms_t_start_d_09355b_idx'), models.Index(fields=['is_paid'], name='showrooms_t_is_paid_093acd_idx')],
            },
        ),
    ]
