# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0015_showroom_asset_account_showroom_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroommoneytransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='showroompricingrule',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='ساري من'),
        ),
    ]
