# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        ('inventory', '0025_add_ecommerce_fields'),
        ('sales', '0027_customerdiscountnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الضمان')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('claimed', 'تم المطالبة')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='crm.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'ضمان',
                'verbose_name_plural': 'الضمانات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المطالبة')),
                ('claim_date', models.DateField(auto_now_add=True, verbose_name='تاريخ المطالبة')),
                ('issue_description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الإصلاح')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة القطع')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة العمالة')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='warranty_management.warranty')),
            ],
            options={
                'verbose_name': 'مطالبة ضمان',
                'verbose_name_plural': 'مطالبات الضمان',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السياسة')),
                ('duration_months', models.IntegerField(verbose_name='مدة الضمان (شهور)')),
                ('coverage_type', models.CharField(choices=[('full', 'كاملة'), ('limited', 'محدودة'), ('parts_only', 'قطع غيار فقط'), ('labor_only', 'عمالة فقط')], max_length=50, verbose_name='نوع التغطية')),
                ('terms_conditions', models.TextField(verbose_name='الشروط والأحكام')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الضمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_policies', to='inventory.product')),
            ],
            options={
                'verbose_name': 'سياسة ضمان',
                'verbose_name_plural': 'سياسات الضمان',
            },
        ),
        migrations.AddField(
            model_name='warranty',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty_management.warrantypolicy', verbose_name='السياسة'),
        ),
    ]
