# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('on_hold', 'معلقة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('progress', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('repeat_type', models.CharField(choices=[('none', 'بدون تكرار'), ('daily', 'يومياً'), ('weekly', 'أسبوعياً'), ('monthly', 'شهرياً'), ('yearly', 'سنوياً'), ('custom', 'مخصص')], default='none', max_length=10, verbose_name='نوع التكرار')),
                ('repeat_interval', models.IntegerField(default=1, verbose_name='فترة التكرار')),
                ('repeat_until', models.DateField(blank=True, null=True, verbose_name='تكرار حتى')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list, verbose_name='الوسوم')),
                ('estimated_hours', models.FloatField(blank=True, null=True, verbose_name='الساعات المقدرة')),
                ('actual_hours', models.FloatField(blank=True, null=True, verbose_name='الساعات الفعلية')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبتة')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-is_pinned', 'due_date', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='المهمة الرئيسية')),
            ],
            options={
                'verbose_name': 'مهمة فرعية',
                'verbose_name_plural': 'المهام الفرعية',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reminder_type', models.CharField(choices=[('task', 'مهمة'), ('event', 'حدث'), ('meeting', 'اجتماع'), ('deadline', 'موعد نهائي'), ('follow_up', 'متابعة'), ('custom', 'مخصص')], default='custom', max_length=20, verbose_name='نوع التذكير')),
                ('notification_channel', models.CharField(choices=[('app', 'التطبيق'), ('email', 'البريد الإلكتروني'), ('sms', 'رسالة نصية'), ('push', 'إشعار دفع'), ('all', 'الجميع')], default='app', max_length=10, verbose_name='قناة الإشعار')),
                ('remind_at', models.DateTimeField(verbose_name='وقت التذكير')),
                ('snoozed_until', models.DateTimeField(blank=True, null=True, verbose_name='مؤجل حتى')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='متكرر')),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, verbose_name='قاعدة التكرار')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='تم التجاهل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'تذكير',
                'verbose_name_plural': 'التذكيرات',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/', verbose_name='الملف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='المهمة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='fas fa-tasks', max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system', models.BooleanField(default=False, verbose_name='فئة نظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فئة مهام',
                'verbose_name_plural': 'فئات المهام',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='المهمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='المهمة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مهمة',
                'verbose_name_plural': 'سجل المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القائمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='fas fa-list', max_length=50, verbose_name='الأيقونة')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_task_lists', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_task_lists', to=settings.AUTH_USER_MODEL, verbose_name='مشترك مع')),
            ],
            options={
                'verbose_name': 'قائمة مهام',
                'verbose_name_plural': 'قوائم المهام',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasklist', verbose_name='القائمة'),
        ),
    ]
