# Generated by Django 5.2.5 on 2025-08-14 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_cheque_accounting__number_b628ad_idx_and_more'),
        ('crm', '0001_initial'),
        ('hr', '0004_hseinspection_weekendday_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='أُغلقت بواسطة'),
        ),
        migrations.CreateModel(
            name='CommissionAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='النسبة %')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الأساس')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ العمولة')),
                ('status', models.CharField(choices=[('accrued', 'مستحقة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='accrued', max_length=10, verbose_name='الحالة')),
                ('accrued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستحقاق')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='قيد محاسبي')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity', verbose_name='الفرصة')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.quotation', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'عمولة مستحقة',
                'verbose_name_plural': 'عمولات مستحقة',
                'ordering': ['-accrued_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السياسة')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة العمولة %')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سياسة عمولة',
                'verbose_name_plural': 'سياسات العمولات',
            },
        ),
    ]
