# Generated by Django 5.2.5 on 2025-08-17 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_opportunity_closed_by_commissionaccrual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='crm_customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mobile'], name='crm_customer_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='crm_customer_fname_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='crm_customer_lname_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='crm_customer_company_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='crm_customer_fullname_idx'),
        ),
    ]
