# Generated by Django 5.2.5 on 2025-08-22 02:15

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_crm_customer_phone_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='مبلغ خصم الصنف'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة خصم الصنف'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='مبلغ ضريبة الصنف'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة ضريبة الصنف'),
        ),
    ]
