# Generated by Django 5.2.5 on 2025-08-22 02:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_quotationitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة خصم الصنف'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة الصنف'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر الوحدة'),
        ),
    ]
