# Generated by Django 5.2.5 on 2025-12-09 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_activity_id_alter_activitytype_id_and_more'),
        ('hr', '0007_alter_employeeidcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity', verbose_name='الفرصة'),
        ),
        migrations.AlterField(
            model_name='commissionscheme',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='الموظف'),
        ),
    ]
