# Generated by Django 5.2.9 on 2026-02-13 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ العرض'),
        ),
    ]
