# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_quotation_quotation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعدة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('trigger', models.CharField(choices=[('opportunity_stage_change', 'تغيير مرحلة الفرصة'), ('no_activity_days', 'عدم نشاط لأيام'), ('quotation_sent', 'بعد إرسال عرض سعر'), ('quotation_expired', 'انتهاء عرض سعر'), ('ticket_no_response', 'تذكرة بدون رد'), ('customer_birthday', 'عيد ميلاد العميل'), ('contract_expiring', 'قرب انتهاء العقد'), ('no_purchase_days', 'عدم شراء لأيام')], max_length=50, verbose_name='المشغِّل')),
                ('days_after', models.PositiveIntegerField(default=3, help_text='عدد الأيام بعد الحدث', verbose_name='بعد (أيام)')),
                ('action', models.CharField(choices=[('create_activity', 'إنشاء نشاط'), ('send_notification', 'إرسال إشعار'), ('escalate', 'تصعيد للمدير'), ('send_email', 'إرسال بريد إلكتروني'), ('create_ticket', 'إنشاء تذكرة')], max_length=50, verbose_name='الإجراء')),
                ('template_message', models.TextField(blank=True, help_text='يمكنك استخدام {customer_name}, {company}, {amount}', verbose_name='نموذج الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات التنفيذ')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='المستخدم المسؤول عن تنفيذ الإجراء', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تعيين إلى')),
            ],
            options={
                'verbose_name': 'قاعدة متابعة',
                'verbose_name_plural': 'قواعد المتابعة',
                'ordering': ['trigger', 'days_after'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ')),
                ('result', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل'), ('skipped', 'تم تخطيه')], max_length=20, verbose_name='النتيجة')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_logs', to='crm.customer', verbose_name='العميل')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.followuprule', verbose_name='القاعدة')),
            ],
            options={
                'verbose_name': 'سجل متابعة',
                'verbose_name_plural': 'سجلات المتابعة',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic_score', models.IntegerField(default=0, help_text='حسب نوع الشركة والحجم والموقع', verbose_name='نقاط ديموغرافية')),
                ('behavior_score', models.IntegerField(default=0, help_text='حسب التفاعل مع الشركة', verbose_name='نقاط السلوك')),
                ('financial_score', models.IntegerField(default=0, help_text='حسب حجم الصفقات والمشتريات', verbose_name='نقاط مالية')),
                ('engagement_score', models.IntegerField(default=0, help_text='حسب سرعة الاستجابة والتواصل', verbose_name='نقاط التفاعل')),
                ('recency_score', models.IntegerField(default=0, help_text='حسب آخر تعامل', verbose_name='نقاط الحداثة')),
                ('manual_adjustment', models.IntegerField(default=0, help_text='تعديل يدوي من المدير (+/-)', verbose_name='تعديل يدوي')),
                ('grade', models.CharField(choices=[('A', 'A - عميل ذهبي'), ('B', 'B - عميل مهم'), ('C', 'C - عميل عادي'), ('D', 'D - يحتاج متابعة'), ('F', 'F - غير نشط')], default='C', max_length=1, verbose_name='التصنيف')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='آخر حساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score', to='crm.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تقييم عميل',
                'verbose_name_plural': 'تقييمات العملاء',
                'ordering': ['-financial_score', '-behavior_score'],
            },
        ),
        migrations.CreateModel(
            name='SupportSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الـ SLA')),
                ('priority', models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], max_length=20, unique=True, verbose_name='الأولوية')),
                ('first_response_hours', models.PositiveIntegerField(verbose_name='مهلة الرد الأول (ساعات)')),
                ('resolution_hours', models.PositiveIntegerField(verbose_name='مهلة الحل (ساعات)')),
                ('escalation_after_hours', models.PositiveIntegerField(verbose_name='تصعيد بعد (ساعات)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('escalate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تصعيد إلى')),
            ],
            options={
                'verbose_name': 'اتفاقية مستوى خدمة',
                'verbose_name_plural': 'اتفاقيات مستوى الخدمة',
                'ordering': ['first_response_hours'],
            },
        ),
    ]
