# Generated by Django 5.2.9 on 2026-01-04 16:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الباقة')),
                ('plan_type', models.CharField(choices=[('starter', 'باقة المبتدئين'), ('business', 'باقة الأعمال'), ('enterprise', 'باقة المؤسسات'), ('custom', 'باقة مخصصة')], max_length=20, verbose_name='نوع الباقة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('features', models.JSONField(default=dict, verbose_name='المميزات')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('quarterly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الربع سنوي')),
                ('semi_annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر النصف سنوي')),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر السنوي')),
                ('max_users', models.IntegerField(default=5, verbose_name='أقصى عدد مستخدمين')),
                ('max_products', models.IntegerField(default=1000, verbose_name='أقصى عدد منتجات')),
                ('max_invoices_per_month', models.IntegerField(default=100, verbose_name='أقصى فواتير شهرياً')),
                ('max_storage_gb', models.IntegerField(default=10, verbose_name='مساحة التخزين (GB)')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='الوصول للـ API')),
                ('has_mobile_app', models.BooleanField(default=False, verbose_name='تطبيق الموبايل')),
                ('has_advanced_reports', models.BooleanField(default=False, verbose_name='تقارير متقدمة')),
                ('has_ai_features', models.BooleanField(default=False, verbose_name='مميزات الذكاء الاصطناعي')),
                ('has_whatsapp_integration', models.BooleanField(default=False, verbose_name='تكامل واتساب')),
                ('has_ecommerce', models.BooleanField(default=False, verbose_name='متجر إلكتروني')),
                ('has_multi_branch', models.BooleanField(default=False, verbose_name='فروع متعددة')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='دعم فني أولوية')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الاشتراك')),
                ('billing_period', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], max_length=20, verbose_name='فترة الدفع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='انتهاء الفترة التجريبية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الخصم')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر النهائي')),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('suspended', 'موقوف'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='trial', max_length=20, verbose_name='الحالة')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='تجديد تلقائي')),
                ('current_users', models.IntegerField(default=1, verbose_name='المستخدمون الحاليون')),
                ('current_products', models.IntegerField(default=0, verbose_name='المنتجات الحالية')),
                ('current_invoices_this_month', models.IntegerField(default=0, verbose_name='الفواتير هذا الشهر')),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='المساحة المستخدمة (GB)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'اشتراك عميل',
                'verbose_name_plural': 'اشتراكات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('mada', 'مدى'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='رقم المعاملة')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.customersubscription')),
            ],
            options={
                'verbose_name': 'دفعة اشتراك',
                'verbose_name_plural': 'دفعات الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
