# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('doc_type', models.CharField(choices=[('document', 'مستند'), ('spreadsheet', 'جدول بيانات'), ('presentation', 'عرض تقديمي'), ('form', 'نموذج')], default='document', max_length=20, verbose_name='نوع المستند')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('content_json', models.JSONField(blank=True, default=dict, verbose_name='المحتوى JSON')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('is_template', models.BooleanField(default=False, verbose_name='قالب')),
                ('is_starred', models.BooleanField(default=False, verbose_name='مفضل')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_documents', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'تم الإنشاء'), ('edited', 'تم التعديل'), ('shared', 'تمت المشاركة'), ('commented', 'تم التعليق'), ('viewed', 'تم العرض'), ('restored', 'تمت الاستعادة')], max_length=20, verbose_name='نوع النشاط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='collaborative_docs.document', verbose_name='المستند')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'عرض فقط'), ('comment', 'تعليق'), ('edit', 'تعديل'), ('admin', 'مسؤول')], default='view', max_length=20, verbose_name='الصلاحية')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_collaborators', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborative_docs.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'متعاون',
                'verbose_name_plural': 'المتعاونون',
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(related_name='shared_documents', through='collaborative_docs.DocumentCollaborator', through_fields=('document', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='المتعاونون'),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('position_start', models.IntegerField(blank=True, null=True, verbose_name='بداية الموقع')),
                ('position_end', models.IntegerField(blank=True, null=True, verbose_name='نهاية الموقع')),
                ('selected_text', models.TextField(blank=True, verbose_name='النص المحدد')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='collaborative_docs.document', verbose_name='المستند')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaborative_docs.documentcomment', verbose_name='الرد على')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_shared', models.BooleanField(default=False, verbose_name='مشترك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='collaborative_docs.documentfolder', verbose_name='المجلد الأب')),
            ],
            options={
                'verbose_name': 'مجلد',
                'verbose_name_plural': 'المجلدات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='collaborative_docs.documentfolder', verbose_name='المجلد'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='رقم النسخة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('content_json', models.JSONField(default=dict, verbose_name='المحتوى JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='collaborative_docs.document', verbose_name='المستند')),
            ],
            options={
                'verbose_name': 'نسخة',
                'verbose_name_plural': 'النسخ',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
