# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('sequence', models.IntegerField(verbose_name='الترتيب')),
                ('conversion_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='احتمال التحويل %')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مرحلة البيع',
                'verbose_name_plural': 'مراحل البيع',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(verbose_name='تاريخ التنبؤ')),
                ('period', models.CharField(max_length=20, verbose_name='الفترة')),
                ('total_pipeline', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي خط الأنابيب')),
                ('weighted_pipeline', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='خط الأنابيب المرجح')),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإيرادات المتوقعة')),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='دقة التنبؤ %')),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيرادات الفعلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل التنبؤ',
                'verbose_name_plural': 'سجلات التنبؤات',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الفرصة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة المتوقعة')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('weighted_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة المرجحة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('qualified', 'معتمدة'), ('proposal_sent', 'تم إرسال عرض'), ('negotiation', 'قيد التفاوض'), ('won', 'فازت'), ('lost', 'خسرت'), ('on_hold', 'معلقة')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expected_close_date', models.DateField(verbose_name='تاريخ الإغلاق المتوقع')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق الفعلي')),
                ('attachments', models.FileField(blank=True, upload_to='opportunities/', verbose_name='الملفات')),
                ('is_at_risk', models.BooleanField(default=False, verbose_name='في خطر')),
                ('risk_reason', models.TextField(blank=True, verbose_name='سبب الخطر')),
                ('success_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='احتمال النجاح %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_opportunities', to='crm.contactperson')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_opportunities', to='crm.customer')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='inventory.product')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advanced_crm.salesstage')),
            ],
            options={
                'verbose_name': 'فرصة تجارية',
                'verbose_name_plural': 'الفرص التجارية',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'مكالمة'), ('email', 'بريد إلكتروني'), ('meeting', 'اجتماع'), ('visit', 'زيارة'), ('task', 'مهمة'), ('note', 'ملاحظة'), ('proposal', 'عرض'), ('contract', 'عقد')], max_length=20, verbose_name='نوع النشاط')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('activity_date', models.DateTimeField(verbose_name='تاريخ النشاط')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('outcome', models.CharField(blank=True, max_length=200, verbose_name='النتيجة')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='متابعة مطلوبة')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('attachments', models.FileField(blank=True, upload_to='activities/', verbose_name='الملفات')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contactperson')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='advanced_crm.opportunity')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات الأنشطة',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['opportunity'], name='advanced_cr_opportu_caed71_idx'), models.Index(fields=['activity_date'], name='advanced_cr_activit_85b86e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='advanced_cr_status_adf9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='advanced_cr_stage_i_57425b_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='advanced_cr_expecte_7deed2_idx'),
        ),
    ]
