# Generated by Django 5.2.5 on 2026-02-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_crm', '0002_update_currency_default_to_egp'),
        ('partners', '0017_add_is_active_to_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_opportunities', to='partners.customer'),
        ),
    ]
