# Generated by Django 5.2.9 on 2026-02-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('stock_out', 'نفاد مخزون متوقع'), ('capacity_overload', 'حمل زائد متوقع'), ('cash_flow', 'مشكلة تدفق نقدي متوقعة'), ('deadline_risk', 'خطر فوات موعد'), ('quality_trend', 'اتجاه جودة سلبي'), ('cost_overrun', 'تجاوز تكلفة متوقع')], max_length=50, verbose_name='نوع التحذير')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('predicted_date', models.DateField(null=True, verbose_name='التاريخ المتوقع')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مستوى الثقة')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='القيمة الحالية')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='قيمة الحد')),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='القيمة المتوقعة')),
                ('preventive_actions', models.JSONField(default=list, verbose_name='الإجراءات الوقائية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='تم التجاهل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تحذير استباقي',
                'verbose_name_plural': 'التحذيرات الاستباقية',
                'db_table': 'proactive_warnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sales', 'المبيعات'), ('inventory', 'المخزون'), ('production', 'الإنتاج'), ('financial', 'مالي'), ('quality', 'الجودة'), ('performance', 'الأداء'), ('security', 'الأمان')], max_length=50, verbose_name='الفئة')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], max_length=20, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('investigating', 'قيد التحقيق'), ('acknowledged', 'تم الاطلاع'), ('resolved', 'تم الحل'), ('false_positive', 'إنذار خاطئ')], default='new', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('anomaly_type', models.CharField(max_length=100, verbose_name='نوع الشذوذ')),
                ('detected_value', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='القيمة المكتشفة')),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='القيمة المتوقعة')),
                ('deviation_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الانحراف')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='الإجراءات الموصى بها')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='معرف السجل')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاكتشاف')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'تنبيه شذوذ',
                'verbose_name_plural': 'تنبيهات الشذوذ',
                'db_table': 'anomaly_alerts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['category', 'severity', 'status'], name='anomaly_ale_categor_5232dc_idx'), models.Index(fields=['detected_at'], name='anomaly_ale_detecte_614177_idx')],
            },
        ),
    ]
