# Generated by Django 5.2.5 on 2026-01-15 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('whatsapp_api_url', models.URLField(verbose_name='رابط WhatsApp API')),
                ('whatsapp_api_token', models.CharField(max_length=500, verbose_name='Token')),
                ('phone_number_id', models.CharField(max_length=100, verbose_name='معرّف رقم الهاتف')),
                ('n8n_webhook_url', models.URLField(blank=True, verbose_name='رابط n8n Webhook')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', max_length=50, verbose_name='مزود الذكاء الصناعي')),
                ('ai_api_key', models.CharField(blank=True, max_length=500, verbose_name='AI API Key')),
                ('ai_model', models.CharField(default='gpt-4', max_length=100, verbose_name='نموذج الذكاء الصناعي')),
                ('system_prompt', models.TextField(default='أنت مساعد مبيعات ذكي لشركة بيع منتجات.\nمهمتك:\n1. الترحيب بالعملاء بطريقة ودودة واحترافية\n2. فهم احتياجاتهم وتقديم المنتجات المناسبة\n3. الإجابة على الأسئلة بدقة\n4. تشجيع العميل على الشراء بطريقة لطيفة\n5. تسجيل اهتمامات العميل\n\nكن مهذباً، سريعاً في الرد، ومفيداً.', verbose_name='نص التعليمات للـ AI')),
                ('auto_create_customer', models.BooleanField(default=True, verbose_name='إنشاء عميل تلقائياً')),
                ('auto_create_opportunity', models.BooleanField(default=True, verbose_name='إنشاء فرصة بيع تلقائياً')),
                ('default_opportunity_stage', models.CharField(default='مبدئي', max_length=50, verbose_name='مرحلة الفرصة الافتراضية')),
                ('business_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل ساعات العمل')),
                ('business_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('business_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('outside_hours_message', models.TextField(blank=True, default='شكراً لتواصلك. نحن خارج أوقات العمل حالياً. سنرد عليك في أقرب وقت.', verbose_name='رسالة خارج أوقات العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات واتساب',
                'verbose_name_plural': 'إعدادات واتساب',
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, verbose_name='اسم المنتج')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='كود المنتج')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف المنتج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('specifications', models.JSONField(default=dict, verbose_name='المواصفات')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('keywords', models.JSONField(default=list, verbose_name='الكلمات المفتاحية')),
                ('common_questions', models.JSONField(default=list, verbose_name='الأسئلة الشائعة')),
                ('in_stock', models.BooleanField(default=True, verbose_name='متوفر')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='الكمية المتوفرة')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الفئة')),
                ('tags', models.JSONField(default=list, verbose_name='الوسوم')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='معدل الشعبية')),
                ('times_mentioned', models.IntegerField(default=0, verbose_name='مرات الذكر')),
                ('times_purchased', models.IntegerField(default=0, verbose_name='مرات الشراء')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'معلومات منتج للـ AI',
                'verbose_name_plural': 'قاعدة معرفة المنتجات',
                'ordering': ['-popularity_score', 'product_name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='whatsapp_ai_categor_0c1de8_idx'), models.Index(fields=['-popularity_score'], name='whatsapp_ai_popular_4b02bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('closed', 'مغلقة'), ('converted', 'تم التحويل لعميل')], default='active', max_length=20, verbose_name='الحالة')),
                ('interested_products', models.JSONField(blank=True, default=list, verbose_name='المنتجات المهتم بها')),
                ('requested_categories', models.JSONField(blank=True, default=list, verbose_name='الفئات المطلوبة')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='الميزانية المتوقعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('first_message_at', models.DateTimeField(auto_now_add=True, verbose_name='أول رسالة')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('messages_count', models.IntegerField(default=0, verbose_name='عدد الرسائل')),
                ('conversation_summary', models.TextField(blank=True, verbose_name='ملخص المحادثة')),
                ('ai_sentiment', models.CharField(blank=True, max_length=50, verbose_name='تحليل المشاعر')),
                ('conversion_probability', models.FloatField(default=0.0, verbose_name='احتمالية الشراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='crm.customer', verbose_name='عميل CRM')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='crm.opportunity', verbose_name='فرصة بيع')),
            ],
            options={
                'verbose_name': 'محادثة واتساب',
                'verbose_name_plural': 'محادثات واتساب',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'وارد من العميل'), ('outbound', 'صادر للعميل')], max_length=10, verbose_name='الاتجاه')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('voice', 'صوت'), ('video', 'فيديو')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('media_url', models.URLField(blank=True, verbose_name='رابط الوسائط')),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='معرّف الرسالة')),
                ('ai_intent', models.CharField(blank=True, max_length=100, verbose_name='النية المكتشفة')),
                ('ai_entities', models.JSONField(blank=True, default=dict, verbose_name='الكيانات المستخرجة')),
                ('delivered', models.BooleanField(default=False, verbose_name='تم التوصيل')),
                ('read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_ai.whatsappconversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['phone_number', 'status'], name='whatsapp_ai_phone_n_c29969_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='whatsapp_ai_status_912319_idx'),
        ),
    ]
