# Generated by Django 5.2.5 on 2026-01-15 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        ('whatsapp_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('platform', models.CharField(choices=[('whatsapp', 'واتساب'), ('facebook', 'فيسبوك ماسنجر'), ('instagram', 'انستجرام')], max_length=20, unique=True, verbose_name='المنصة')),
                ('page_id', models.CharField(blank=True, help_text='للفيسبوك والانستجرام', max_length=100, verbose_name='معرّف الصفحة')),
                ('page_access_token', models.CharField(max_length=500, verbose_name='Page Access Token')),
                ('app_secret', models.CharField(blank=True, help_text='للتحقق من الـ webhook', max_length=200, verbose_name='App Secret')),
                ('verify_token', models.CharField(blank=True, help_text='للتحقق من الـ webhook', max_length=200, verbose_name='Verify Token')),
                ('phone_number_id', models.CharField(blank=True, help_text='للواتساب فقط', max_length=100, verbose_name='معرّف رقم الهاتف')),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=100, verbose_name='معرّف حساب واتساب بيزنس')),
                ('instagram_account_id', models.CharField(blank=True, max_length=100, verbose_name='معرّف حساب الانستجرام')),
                ('n8n_webhook_url', models.URLField(blank=True, verbose_name='رابط n8n Webhook')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=50, verbose_name='مزود الذكاء الصناعي')),
                ('ai_api_key', models.CharField(blank=True, max_length=500, verbose_name='AI API Key')),
                ('ai_model', models.CharField(default='gpt-4', max_length=100, verbose_name='نموذج الذكاء الصناعي')),
                ('system_prompt', models.TextField(default='أنت مساعد مبيعات ذكي لشركة بيع منتجات.\nمهمتك:\n1. الترحيب بالعملاء بطريقة ودودة واحترافية\n2. فهم احتياجاتهم وتقديم المنتجات المناسبة\n3. الإجابة على الأسئلة بدقة\n4. تشجيع العميل على الشراء بطريقة لطيفة\n5. تسجيل اهتمامات العميل\n\nكن مهذباً، سريعاً في الرد، ومفيداً.', verbose_name='نص التعليمات للـ AI')),
                ('auto_create_customer', models.BooleanField(default=True, verbose_name='إنشاء عميل تلقائياً')),
                ('auto_create_opportunity', models.BooleanField(default=True, verbose_name='إنشاء فرصة بيع تلقائياً')),
                ('business_hours_enabled', models.BooleanField(default=False, verbose_name='تفعيل ساعات العمل')),
                ('business_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('business_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('outside_hours_message', models.TextField(blank=True, default='شكراً لتواصلك. نحن خارج أوقات العمل حالياً. سنرد عليك في أقرب وقت.', verbose_name='رسالة خارج أوقات العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات منصة سوشيال',
                'verbose_name_plural': 'إعدادات منصات السوشيال',
            },
        ),
        migrations.CreateModel(
            name='SocialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'واتساب'), ('facebook', 'فيسبوك'), ('instagram', 'انستجرام')], db_index=True, default='whatsapp', max_length=20, verbose_name='المنصة')),
                ('platform_user_id', models.CharField(db_index=True, max_length=200, verbose_name='معرّف المستخدم')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('profile_picture', models.URLField(blank=True, verbose_name='صورة البروفايل')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('closed', 'مغلقة'), ('converted', 'تم التحويل لعميل')], default='active', max_length=20, verbose_name='الحالة')),
                ('interested_products', models.JSONField(blank=True, default=list, verbose_name='المنتجات المهتم بها')),
                ('requested_categories', models.JSONField(blank=True, default=list, verbose_name='الفئات المطلوبة')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='الميزانية المتوقعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('first_message_at', models.DateTimeField(auto_now_add=True, verbose_name='أول رسالة')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('messages_count', models.IntegerField(default=0, verbose_name='عدد الرسائل')),
                ('conversation_summary', models.TextField(blank=True, verbose_name='ملخص المحادثة')),
                ('ai_sentiment', models.CharField(blank=True, max_length=50, verbose_name='تحليل المشاعر')),
                ('conversion_probability', models.FloatField(default=0.0, verbose_name='احتمالية الشراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_conversations', to='crm.customer', verbose_name='عميل CRM')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_conversations', to='crm.opportunity', verbose_name='فرصة بيع')),
            ],
            options={
                'verbose_name': 'محادثة سوشيال ميديا',
                'verbose_name_plural': 'محادثات سوشيال ميديا',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'وارد من العميل'), ('outbound', 'صادر للعميل')], max_length=10, verbose_name='الاتجاه')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('voice', 'صوت'), ('video', 'فيديو'), ('sticker', 'ستيكر'), ('story_mention', 'إشارة في ستوري'), ('story_reply', 'رد على ستوري')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('media_url', models.URLField(blank=True, verbose_name='رابط الوسائط')),
                ('platform_message_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='معرّف الرسالة')),
                ('ai_intent', models.CharField(blank=True, max_length=100, verbose_name='النية المكتشفة')),
                ('ai_entities', models.JSONField(blank=True, default=dict, verbose_name='الكيانات المستخرجة')),
                ('delivered', models.BooleanField(default=False, verbose_name='تم التوصيل')),
                ('read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_ai.socialconversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة سوشيال ميديا',
                'verbose_name_plural': 'رسائل سوشيال ميديا',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['platform', 'platform_user_id'], name='whatsapp_ai_platfor_50bf3d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='whatsapp_ai_status_5433e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialconversation',
            unique_together={('platform', 'platform_user_id')},
        ),
    ]
