# Generated by Django 5.2.5 on 2026-01-15 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0002_socialplatformconfig_socialconversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='اسم الفئة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الاستبعاد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستبعاد')),
                ('excluded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الاستبعاد بواسطة')),
            ],
            options={
                'verbose_name': 'فئة مستبعدة',
                'verbose_name_plural': 'الفئات المستبعدة',
                'ordering': ['category_name'],
            },
        ),
    ]
