# Generated by Django 5.2.5 on 2026-01-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ai', '0003_add_excluded_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productknowledgebase',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='العملة'),
        ),
    ]
