# Generated by Django 5.2.5 on 2026-01-15 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_businessactivity_contracttype_crmsettings_and_more'),
        ('inventory', '0035_rename_spp_prod_supp_active_idx_inventory_s_product_2d38ac_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, verbose_name='اسم الإعداد')),
                ('n8n_webhook_url', models.URLField(blank=True, verbose_name='رابط n8n Webhook')),
                ('n8n_api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح n8n API')),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=100, verbose_name='Phone Number ID')),
                ('whatsapp_token', models.CharField(blank=True, max_length=500, verbose_name='Access Token')),
                ('whatsapp_verify_token', models.CharField(blank=True, max_length=100, verbose_name='Verify Token')),
                ('welcome_message', models.TextField(default='مرحباً بك! كيف يمكننا مساعدتك؟', verbose_name='رسالة الترحيب')),
                ('product_inquiry_response', models.TextField(default='شكراً لاستفسارك. سنرسل لك قائمة المنتجات المتاحة.', verbose_name='رسالة الاستفسار عن المنتجات')),
                ('order_confirmation', models.TextField(default='تم استلام طلبك بنجاح!', verbose_name='رسالة تأكيد الطلب')),
                ('use_ai_responses', models.BooleanField(default=False, verbose_name='استخدام الرد الذكي')),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='نموذج AI')),
                ('ai_api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح OpenAI')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات واتساب',
                'verbose_name_plural': 'إعدادات واتساب',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('category', models.CharField(choices=[('welcome', 'ترحيب'), ('product', 'منتجات'), ('order', 'طلبات'), ('payment', 'دفع'), ('shipping', 'شحن'), ('support', 'دعم'), ('marketing', 'تسويق')], max_length=20, verbose_name='الفئة')),
                ('header', models.CharField(blank=True, max_length=60, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('footer', models.CharField(blank=True, max_length=60, verbose_name='التذييل')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='الأزرار')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='المتغيرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_description', models.TextField(blank=True, verbose_name='وصف واتساب')),
                ('whatsapp_image_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('keywords', models.TextField(blank=True, help_text='كلمات مفتاحية مفصولة بفاصلة', verbose_name='كلمات البحث')),
                ('is_available_on_whatsapp', models.BooleanField(default=True, verbose_name='متاح على واتساب')),
                ('quick_replies', models.JSONField(blank=True, default=list, verbose_name='ردود سريعة')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_catalog', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'كتالوج منتج',
                'verbose_name_plural': 'كتالوج المنتجات',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='رقم الهاتف')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('pending', 'قيد الانتظار'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_registered', models.BooleanField(default=False, verbose_name='تم التسجيل تلقائياً')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_integration_assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_integration_conversations', to='crm.customer', verbose_name='العميل في CRM')),
            ],
            options={
                'verbose_name': 'محادثة واتساب',
                'verbose_name_plural': 'محادثات واتساب',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp Message ID')),
                ('direction', models.CharField(choices=[('incoming', 'واردة'), ('outgoing', 'صادرة')], max_length=10, verbose_name='الاتجاه')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('audio', 'صوت'), ('video', 'فيديو'), ('location', 'موقع'), ('contact', 'جهة اتصال'), ('button', 'زر'), ('list', 'قائمة')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('media_url', models.URLField(blank=True, verbose_name='رابط الوسائط')),
                ('detected_intent', models.CharField(blank=True, max_length=50, verbose_name='النية المكتشفة')),
                ('confidence', models.FloatField(default=0, verbose_name='مستوى الثقة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_integration.whatsappconversation', verbose_name='المحادثة')),
                ('mentioned_products', models.ManyToManyField(blank=True, to='inventory.product', verbose_name='المنتجات المذكورة')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('trigger_text', models.CharField(max_length=255, verbose_name='نص التفعيل')),
                ('match_type', models.CharField(choices=[('exact', 'مطابقة تامة'), ('contains', 'يحتوي على'), ('starts_with', 'يبدأ بـ'), ('regex', 'تعبير منتظم')], default='contains', max_length=20, verbose_name='نوع المطابقة')),
                ('action', models.CharField(choices=[('reply', 'رد برسالة'), ('send_products', 'إرسال منتجات'), ('create_lead', 'إنشاء عميل محتمل'), ('assign_agent', 'تحويل لموظف'), ('webhook', 'تشغيل Webhook')], max_length=20, verbose_name='الإجراء')),
                ('response_text', models.TextField(blank=True, verbose_name='نص الرد')),
                ('webhook_url', models.URLField(blank=True, verbose_name='رابط Webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('response_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.whatsapptemplate', verbose_name='قالب الرد')),
            ],
            options={
                'verbose_name': 'قاعدة رد تلقائي',
                'verbose_name_plural': 'قواعد الرد التلقائي',
                'ordering': ['-priority'],
            },
        ),
    ]
