# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'مضيف'), ('co_host', 'مضيف مشارك'), ('participant', 'مشارك'), ('viewer', 'مشاهد')], default='participant', max_length=20, verbose_name='الدور')),
                ('is_connected', models.BooleanField(default=False, verbose_name='متصل')),
                ('is_muted', models.BooleanField(default=False, verbose_name='صامت')),
                ('is_video_on', models.BooleanField(default=True, verbose_name='الفيديو مفعل')),
                ('is_screen_sharing', models.BooleanField(default=False, verbose_name='يشارك الشاشة')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='انضم في')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='غادر في')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشارك فيديو',
                'verbose_name_plural': 'مشاركو الفيديو',
            },
        ),
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='المعرف الفريد')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الغرفة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('room_type', models.CharField(choices=[('instant', 'فوري'), ('scheduled', 'مجدول'), ('recurring', 'متكرر')], default='instant', max_length=20, verbose_name='نوع الغرفة')),
                ('max_participants', models.IntegerField(default=10, verbose_name='أقصى عدد مشاركين')),
                ('is_recording_enabled', models.BooleanField(default=False, verbose_name='تسجيل مفعل')),
                ('is_chat_enabled', models.BooleanField(default=True, verbose_name='الدردشة مفعلة')),
                ('is_screen_share_enabled', models.BooleanField(default=True, verbose_name='مشاركة الشاشة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الاجتماع')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='المدة (دقيقة)')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='كلمة المرور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_video_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المضيف')),
                ('participants', models.ManyToManyField(related_name='video_rooms', through='video_calls.VideoParticipant', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'غرفة فيديو',
                'verbose_name_plural': 'غرف الفيديو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video_calls/recordings/', verbose_name='ملف التسجيل')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='المدة (ثانية)')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='video_calls.videoroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
            },
        ),
        migrations.AddField(
            model_name='videoparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_calls.videoroom'),
        ),
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_messages', to='video_calls.videoroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'رسالة فيديو',
                'verbose_name_plural': 'رسائل الفيديو',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='videoparticipant',
            unique_together={('room', 'user')},
        ),
    ]
