# Generated by Django 5.2.5 on 2025-12-15 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشغل')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('logo', models.ImageField(blank=True, upload_to='eservices/operators/', verbose_name='الشعار')),
                ('prefixes', models.CharField(help_text='مفصولة بفاصلة مثل: 010,011,012', max_length=100, verbose_name='بادئات الأرقام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مشغل اتصالات',
                'verbose_name_plural': 'مشغلي الاتصالات',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفئة')),
                ('icon', models.CharField(default='bi-gear', max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فئة خدمة',
                'verbose_name_plural': 'فئات الخدمات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المزود')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المزود')),
                ('logo', models.ImageField(blank=True, upload_to='eservices/providers/', verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='نقطة API')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='سر API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مزود خدمة',
                'verbose_name_plural': 'مزودي الخدمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='عدد المعاملات')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المبالغ')),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الرسوم')),
                ('successful_count', models.PositiveIntegerField(default=0, verbose_name='الناجحة')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='الفاشلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقرير خدمات',
                'verbose_name_plural': 'تقارير الخدمات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RechargePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('bonus', models.CharField(blank=True, max_length=200, verbose_name='المميزات')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='صلاحية (أيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='eservices.mobileoperator', verbose_name='المشغل')),
            ],
            options={
                'verbose_name': 'باقة شحن',
                'verbose_name_plural': 'باقات الشحن',
                'ordering': ['operator', 'order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='EService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الخدمة')),
                ('service_type', models.CharField(choices=[('mobile_recharge', 'شحن رصيد'), ('bill_payment', 'دفع فواتير'), ('money_transfer', 'تحويل أموال'), ('government', 'خدمات حكومية'), ('subscription', 'اشتراكات'), ('booking', 'حجوزات'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الخدمة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-lightning', max_length=50, verbose_name='الأيقونة')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم الأساسية')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الرسوم %')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى')),
                ('requires_account', models.BooleanField(default=False, verbose_name='يتطلب حساب')),
                ('requires_verification', models.BooleanField(default=False, verbose_name='يتطلب تحقق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='eservices.servicecategory', verbose_name='الفئة')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='eservices.serviceprovider', verbose_name='المزود')),
            ],
            options={
                'verbose_name': 'خدمة إلكترونية',
                'verbose_name_plural': 'الخدمات الإلكترونية',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الفاتورة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('icon', models.CharField(default='bi-receipt', max_length=50, verbose_name='الأيقونة')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eservices.serviceprovider', verbose_name='المزود')),
            ],
            options={
                'verbose_name': 'نوع فاتورة',
                'verbose_name_plural': 'أنواع الفواتير',
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='رقم المعاملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتملة'), ('failed', 'فشلت'), ('refunded', 'مستردة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('service_number', models.CharField(max_length=50, verbose_name='رقم الخدمة')),
                ('service_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الخدمة')),
                ('provider_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع المزود')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة المزود')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='eservices.eservice', verbose_name='الخدمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'معاملة خدمة',
                'verbose_name_plural': 'معاملات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('wallet', 'محفظة'), ('bank', 'بنك'), ('mobile', 'رصيد جوال')], max_length=20, verbose_name='نوع التحويل')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='هاتف المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('receiver_account', models.CharField(blank=True, max_length=50, verbose_name='حساب المستلم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money_transfer', to='eservices.servicetransaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'التحويلات المالية',
            },
        ),
        migrations.CreateModel(
            name='MobileRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('pin_code', models.CharField(blank=True, max_length=50, verbose_name='كود الشحن')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eservices.mobileoperator', verbose_name='المشغل')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eservices.rechargepackage', verbose_name='الباقة')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recharge', to='eservices.servicetransaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'شحن رصيد',
                'verbose_name_plural': 'شحن الرصيد',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, verbose_name='رقم الفاتورة')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الفاتورة')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eservices.billtype', verbose_name='نوع الفاتورة')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment', to='eservices.servicetransaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'دفع فاتورة',
                'verbose_name_plural': 'دفع الفواتير',
            },
        ),
    ]
