# Generated by Django 5.2.11 on 2026-03-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المقدم')),
                ('number_of_installments', models.IntegerField(verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة القسط')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الفائدة %')),
                ('start_date', models.DateField(verbose_name='تاريخ أول قسط')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='sales.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='sales.salesinvoice', verbose_name='الفاتورة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'خطة أقساط',
                'verbose_name_plural': 'خطط الأقساط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('installment_number', models.IntegerField(verbose_name='رقم القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المدفوع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('paid', 'مدفوع'), ('partial', 'جزئي'), ('overdue', 'متأخر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='installments.installmentplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'ordering': ['installment_number'],
            },
        ),
    ]
