# Generated by Django 5.2.9 on 2026-01-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الويدجت')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('widget_type', models.CharField(choices=[('stats', 'إحصائيات'), ('chart', 'رسم بياني'), ('list', 'قائمة'), ('table', 'جدول'), ('calendar', 'تقويم'), ('quick_action', 'إجراء سريع'), ('notification', 'إشعارات'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع الويدجت')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-chart-bar', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='اللون')),
                ('default_size', models.CharField(choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير'), ('full', 'كامل العرض')], default='medium', max_length=10, verbose_name='الحجم الافتراضي')),
                ('min_width', models.IntegerField(default=1, verbose_name='الحد الأدنى للعرض')),
                ('min_height', models.IntegerField(default=1, verbose_name='الحد الأدنى للارتفاع')),
                ('data_source', models.CharField(blank=True, max_length=200, verbose_name='مصدر البيانات')),
                ('data_config', models.JSONField(default=dict, verbose_name='تكوين البيانات')),
                ('refresh_interval', models.IntegerField(default=60, verbose_name='فترة التحديث (ثواني)')),
                ('template_name', models.CharField(blank=True, max_length=200, verbose_name='اسم القالب')),
                ('required_permission', models.CharField(blank=True, max_length=100, verbose_name='الصلاحية المطلوبة')),
                ('allowed_roles', models.JSONField(default=list, verbose_name='الأدوار المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='ويدجت نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'ويدجت',
                'verbose_name_plural': 'الويدجتس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التخطيط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('columns', models.IntegerField(default=3, verbose_name='عدد الأعمدة')),
                ('layout_config', models.JSONField(default=dict, verbose_name='تكوين التخطيط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تخطيط لوحة التحكم',
                'verbose_name_plural': 'تخطيطات لوحة التحكم',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickActionWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإجراء')),
                ('icon', models.CharField(max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='اللون')),
                ('url', models.CharField(max_length=500, verbose_name='الرابط')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إجراء سريع',
                'verbose_name_plural': 'الإجراءات السريعة',
                'ordering': ['order', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0, verbose_name='الموقع X')),
                ('position_y', models.IntegerField(default=0, verbose_name='الموقع Y')),
                ('width', models.IntegerField(default=1, verbose_name='العرض')),
                ('height', models.IntegerField(default=1, verbose_name='الارتفاع')),
                ('title_override', models.CharField(blank=True, max_length=100, verbose_name='عنوان مخصص')),
                ('custom_config', models.JSONField(default=dict, verbose_name='إعدادات مخصصة')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي')),
                ('is_collapsed', models.BooleanField(default=False, verbose_name='مطوي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='custom_dashboard.dashboardlayout', verbose_name='التخطيط')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_instances', to='custom_dashboard.widget', verbose_name='الويدجت')),
            ],
            options={
                'verbose_name': 'ويدجت لوحة التحكم',
                'verbose_name_plural': 'ويدجتس لوحة التحكم',
                'ordering': ['order', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='WidgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='البيانات')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التخزين')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_data', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_data', to='custom_dashboard.widget', verbose_name='الويدجت')),
            ],
            options={
                'verbose_name': 'بيانات ويدجت',
                'verbose_name_plural': 'بيانات الويدجتس',
            },
        ),
    ]
