# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0027_rename_accounting__entry_t_abc123_idx_accounting__entry_t_bba407_idx_and_more'),
        ('sales', '0027_customerdiscountnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxpayer_id', models.CharField(max_length=50, verbose_name='رقم المكلف')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='اسم المكلف')),
                ('last_return_filed_date', models.DateField(verbose_name='تاريخ آخر إقرار')),
                ('next_return_due_date', models.DateField(verbose_name='تاريخ استحقاق الإقرار التالي')),
                ('tax_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الضريبي')),
                ('is_current', models.BooleanField(default=True, verbose_name='محدث')),
                ('compliance_status', models.CharField(choices=[('compliant', 'ممتثل'), ('non_compliant', 'غير ممتثل'), ('pending', 'قيد الانتظار')], max_length=50, verbose_name='حالة الامتثال')),
                ('last_audit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر تدقيق')),
                ('audit_findings', models.TextField(blank=True, verbose_name='نتائج التدقيق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'امتثال ضريبي',
                'verbose_name_plural': 'الامتثال الضريبي',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='معدل الضريبة %')),
                ('applicable_on', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('both', 'الاثنين')], max_length=50, verbose_name='تطبق على')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع ضريبة',
                'verbose_name_plural': 'أنواع الضرائب',
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('vat_return', 'إقرار ضريبة القيمة المضافة'), ('income_tax_return', 'إقرار ضريبة الدخل'), ('withholding_return', 'إقرار الضرائب المستقطعة'), ('annual_return', 'الإقرار السنوي')], max_length=50, verbose_name='نوع التقرير')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], max_length=20, verbose_name='نوع الفترة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_taxable_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي الدخل الخاضع')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الخصومات')),
                ('taxable_profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الربح الخاضع')),
                ('total_tax_liability', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي الالتزام الضريبي')),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الضريبة المدفوعة')),
                ('tax_payable', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الضريبة المستحقة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسلة'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة')], max_length=50, verbose_name='الحالة')),
                ('report_document', models.FileField(blank=True, upload_to='tax_reports/', verbose_name='وثيقة التقرير')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير ضريبي',
                'verbose_name_plural': 'التقارير الضريبية',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['report_type', 'period_end'], name='tax_system__report__39e8e4_idx'), models.Index(fields=['status'], name='tax_system__status_735045_idx')],
                'unique_together': {('report_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('income_tax', 'ضريبة الدخل'), ('corporate_tax', 'ضريبة الشركات'), ('withholding_tax', 'ضريبة الخصم'), ('stamp_duty', 'رسم الدمغة')], max_length=50, verbose_name='نوع الحساب')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الخاضع للضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='معدل الضريبة %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('calculation_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الحساب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم دفعها')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_calculations', to='sales.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_system.taxtype')),
            ],
            options={
                'verbose_name': 'حساب ضريبة',
                'verbose_name_plural': 'حسابات الضرائب',
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['tax_type'], name='tax_system__tax_typ_364421_idx'), models.Index(fields=['calculation_date'], name='tax_system__calcula_d54b8e_idx'), models.Index(fields=['is_paid'], name='tax_system__is_paid_c18280_idx')],
            },
        ),
    ]
