# Generated by Django 5.2.9 on 2026-02-18 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطابعة')),
                ('printer_type', models.CharField(choices=[('zebra', 'Zebra ZPL (باركود/ملصقات)'), ('thermal', 'XPrinter ESC/POS (إيصالات)'), ('a4', 'A4 ليزر/حبر (مستندات)'), ('card', 'طابعة بطاقات هوية')], max_length=20, verbose_name='نوع الطابعة')),
                ('document_type', models.CharField(choices=[('production_barcode', 'ملصق باركود إنتاج'), ('warranty_label', 'ملصق ضمان'), ('sales_invoice', 'فاتورة مبيعات (A4)'), ('sales_receipt', 'إيصال مبيعات (حراري)'), ('purchase_order', 'أمر شراء (A4)'), ('hr_id_card', 'بطاقة هوية موظف'), ('journal_entry', 'قيد محاسبي (A4)'), ('trial_balance', 'ميزان المراجعة (A4)'), ('product_barcode', 'باركود منتج'), ('generic_a4', 'مستند A4 عام'), ('generic_receipt', 'إيصال عام')], max_length=30, verbose_name='نوع المستند')),
                ('connection_type', models.CharField(choices=[('network', 'شبكة (IP:Port)'), ('cups', 'CUPS (Linux)'), ('usb', 'USB مباشر'), ('shared', 'طابعة مشاركة Windows'), ('agent', 'وكيل الطباعة WebSocket')], default='agent', max_length=20, verbose_name='نوع الاتصال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=9100, verbose_name='المنفذ')),
                ('cups_printer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم طابعة CUPS/OS')),
                ('shared_printer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم الطابعة المشتركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي لهذا النوع')),
                ('total_prints', models.PositiveIntegerField(default=0)),
                ('last_print_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'إعداد طابعة',
                'verbose_name_plural': 'إعدادات الطابعات',
                'ordering': ['document_type', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('production_barcode', 'ملصق باركود إنتاج'), ('warranty_label', 'ملصق ضمان'), ('sales_invoice', 'فاتورة مبيعات (A4)'), ('sales_receipt', 'إيصال مبيعات (حراري)'), ('purchase_order', 'أمر شراء (A4)'), ('hr_id_card', 'بطاقة هوية موظف'), ('journal_entry', 'قيد محاسبي (A4)'), ('trial_balance', 'ميزان المراجعة (A4)'), ('product_barcode', 'باركود منتج'), ('generic_a4', 'مستند A4 عام'), ('generic_receipt', 'إيصال عام')], max_length=30, verbose_name='نوع المستند')),
                ('zpl_command', models.TextField(blank=True, default='', verbose_name='أمر ZPL')),
                ('escpos_data', models.BinaryField(blank=True, default=b'', verbose_name='بيانات ESC/POS')),
                ('pdf_base64', models.TextField(blank=True, default='', verbose_name='PDF (base64)')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='محتوى HTML')),
                ('title', models.CharField(blank=True, default='', max_length=300, verbose_name='عنوان المهمة')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('sent', 'أُرسل للوكيل'), ('printing', 'جاري الطباعة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغى')], default='queued', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_app', models.CharField(blank=True, default='', max_length=50, verbose_name='التطبيق المصدر')),
                ('source_model', models.CharField(blank=True, default='', max_length=100, verbose_name='النموذج المصدر')),
                ('source_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف الكائن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='printing.printerconfiguration', verbose_name='الطابعة')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='طُلب بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة طباعة',
                'verbose_name_plural': 'مهام الطباعة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='printjob_status_created_idx'), models.Index(fields=['document_type', 'status'], name='printjob_doctype_status_idx')],
            },
        ),
    ]
