# Generated by Django 5.2.9 on 2026-02-18 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(help_text='اسم الجهاز (Hostname) — يُكتشف تلقائياً من الوكيل', max_length=200, unique=True, verbose_name='اسم الجهاز')),
                ('machine_ip', models.GenericIPAddressField(blank=True, help_text='عنوان IP المُرسل من الوكيل', null=True, verbose_name='عنوان IP')),
                ('agent_port', models.PositiveIntegerField(default=9876, verbose_name='منفذ الوكيل')),
                ('agent_version', models.CharField(blank=True, default='', max_length=20, verbose_name='إصدار الوكيل')),
                ('os_platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], default='windows', max_length=20, verbose_name='نظام التشغيل')),
                ('display_name', models.CharField(blank=True, help_text="اسم ودي مثل 'جهاز التغليف' أو 'كاشير المبيعات 1'", max_length=200, verbose_name='الاسم المعروض')),
                ('location', models.CharField(blank=True, help_text="الموقع الفعلي: 'خط التغليف' أو 'صالة العرض 1'", max_length=200, verbose_name='الموقع')),
                ('discovered_printers', models.JSONField(blank=True, default=list, help_text='قائمة الطابعات المُرسلة من الوكيل عند الاتصال', verbose_name='الطابعات المكتشفة')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='أول ظهور')),
                ('is_active', models.BooleanField(default=True, help_text='يمكن للمدير تعطيل محطة', verbose_name='مفعّل')),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='المستخدمون المرتبطون بهذه المحطة (للتوجيه التلقائي)', related_name='print_stations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المعيّنون')),
            ],
            options={
                'verbose_name': 'محطة طباعة',
                'verbose_name_plural': 'محطات الطباعة',
                'ordering': ['display_name', 'machine_name'],
            },
        ),
        migrations.CreateModel(
            name='StationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP العميل')),
                ('connected_at', models.DateTimeField(auto_now=True, verbose_name='وقت الاتصال')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='printing.printstation', verbose_name='المحطة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_session', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة محطة',
                'verbose_name_plural': 'جلسات المحطات',
            },
        ),
        migrations.CreateModel(
            name='PrinterMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('barcode', 'ملصق باركود (Zebra ZPL)'), ('production_barcode', 'باركود إنتاج'), ('warranty_label', 'ملصق ضمان'), ('sales_receipt', 'إيصال مبيعات (POS)'), ('kitchen_receipt', 'إيصال مطبخ'), ('sales_invoice', 'فاتورة مبيعات (A4)'), ('purchase_order', 'أمر شراء (A4)'), ('delivery_note', 'إذن تسليم (A4)'), ('hr_document', 'مستند موارد بشرية (A4)'), ('trial_balance', 'ميزان المراجعة (A4)'), ('general', 'مستند عام')], max_length=50, verbose_name='نوع المستند')),
                ('local_printer_name', models.CharField(blank=True, help_text='اسم الطابعة المحلية على المحطة (من discovered_printers). يُستخدم عند الطباعة عبر تعريف نظام التشغيل المحلي.', max_length=300, verbose_name='اسم الطابعة المحلية')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='عدد النسخ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('priority', models.PositiveIntegerField(default=0, help_text='الأعلى = تُجرّب أولاً عند وجود عدة تعيينات', verbose_name='الأولوية')),
                ('printer_config', models.ForeignKey(blank=True, help_text='طابعة شبكية من إعدادات الطابعات (Zebra TCP مثلاً)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_mappings', to='printing.printerconfiguration', verbose_name='إعداد الطابعة')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_mappings', to='printing.printstation', verbose_name='المحطة')),
            ],
            options={
                'verbose_name': 'تعيين طابعة',
                'verbose_name_plural': 'تعيينات الطابعات',
                'ordering': ['station', 'document_type', '-priority'],
                'unique_together': {('station', 'document_type', 'local_printer_name')},
            },
        ),
    ]
