# Generated by Django 5.2.9 on 2026-02-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printstation_stationsession_printermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('barcode_label', 'ملصق باركود'), ('warranty_label', 'ملصق ضمان'), ('pos_receipt', 'إيصال نقطة بيع'), ('sales_invoice', 'فاتورة مبيعات'), ('production_label', 'ملصق إنتاج'), ('shipping_label', 'ملصق شحن')], max_length=30, verbose_name='نوع القالب')),
                ('width', models.DecimalField(decimal_places=2, help_text='عرض الملصق/الإيصال', max_digits=7, verbose_name='العرض')),
                ('height', models.DecimalField(decimal_places=2, help_text='ارتفاع الملصق/الإيصال (0 = لفة مستمرة)', max_digits=7, verbose_name='الارتفاع')),
                ('unit', models.CharField(choices=[('mm', 'ملليمتر'), ('in', 'بوصة'), ('dots', 'نقاط (dots)')], default='mm', max_length=5, verbose_name='وحدة القياس')),
                ('dpi', models.PositiveIntegerField(default=203, verbose_name='دقة الطباعة (DPI)')),
                ('zpl_template', models.TextField(blank=True, help_text='قالب ZPL مع متغيرات مثل {product_name}, {sku}, {barcode}', verbose_name='قالب ZPL')),
                ('escpos_template', models.TextField(blank=True, help_text='قالب ESC/POS بتنسيق JSON للأوامر', verbose_name='قالب ESC/POS')),
                ('html_template', models.TextField(blank=True, help_text='قالب HTML للطباعة عبر المتصفح', verbose_name='قالب HTML')),
                ('margin_top', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش علوي')),
                ('margin_left', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش أيسر')),
                ('font_size', models.PositiveIntegerField(default=24, verbose_name='حجم الخط الافتراضي')),
                ('barcode_height', models.PositiveIntegerField(default=80, verbose_name='ارتفاع الباركود (نقاط)')),
                ('barcode_width', models.PositiveIntegerField(default=2, verbose_name='عرض خط الباركود (نقاط)')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب طباعة',
                'verbose_name_plural': 'قوالب الطباعة',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
