# Generated by Django 5.2.9 on 2026-01-05 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('work_type', models.CharField(choices=[('software', 'برمجية'), ('book', 'كتاب'), ('music', 'موسيقى'), ('film', 'فيلم'), ('other', 'أخرى')], max_length=100, verbose_name='نوع العمل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('author', models.CharField(max_length=200, verbose_name='المؤلف')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='الناشر')),
                ('work_file', models.FileField(blank=True, upload_to='copyrights/', verbose_name='ملف العمل')),
                ('creation_date', models.DateField(verbose_name='تاريخ الإنشاء')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('copyright_duration', models.IntegerField(verbose_name='مدة حق النشر (سنة)')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_licensed', models.BooleanField(default=False, verbose_name='مرخص')),
                ('license_agreement', models.FileField(blank=True, upload_to='copyrights/', verbose_name='اتفاق الترخيص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'عمل محمي بحق النشر',
                'verbose_name_plural': 'الأعمال المحمية بحق النشر',
            },
        ),
        migrations.CreateModel(
            name='IPLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الرخصة')),
                ('license_type', models.CharField(choices=[('patent_license', 'رخصة براءة'), ('trademark_license', 'رخصة علامة'), ('copyright_license', 'رخصة نشر'), ('technology_license', 'رخصة تقنية')], max_length=50, verbose_name='نوع الرخصة')),
                ('licensor', models.CharField(max_length=200, verbose_name='منح الرخصة')),
                ('licensee', models.CharField(max_length=200, verbose_name='متلقي الرخصة')),
                ('subject_matter', models.TextField(verbose_name='موضوع الرخصة')),
                ('territory', models.CharField(max_length=200, verbose_name='الإقليم')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصرية')),
                ('royalty_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='معدل الملكية %')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الدفع المسبق')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('license_agreement', models.FileField(upload_to='licenses/', verbose_name='اتفاق الرخصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'رخصة ملكية فكرية',
                'verbose_name_plural': 'رخص الملكية الفكرية',
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trademark_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العلامة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العلامة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('logo_image', models.ImageField(upload_to='trademarks/', verbose_name='صورة الشعار')),
                ('goods_and_services', models.TextField(verbose_name='السلع والخدمات')),
                ('nice_classification', models.CharField(max_length=100, verbose_name='تصنيف نيس')),
                ('owner', models.CharField(max_length=200, verbose_name='صاحب الحق')),
                ('owner_address', models.TextField(verbose_name='عنوان صاحب الحق')),
                ('registration_date', models.DateField(verbose_name='تاريخ التسجيل')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('registered', 'مسجلة'), ('pending', 'قيد التسجيل'), ('renewed', 'مجددة'), ('expired', 'منتهية')], max_length=20, verbose_name='الحالة')),
                ('protected_countries', models.TextField(verbose_name='الدول المحمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patent_number', models.CharField(max_length=100, unique=True, verbose_name='رقم البراءة')),
                ('application_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('patent_type', models.CharField(choices=[('invention', 'براءة اختراع'), ('design', 'براءة تصميم'), ('utility_model', 'نموذج منفعة'), ('trademark', 'علامة تجارية')], max_length=50, verbose_name='نوع البراءة')),
                ('technical_field', models.CharField(max_length=200, verbose_name='المجال التقني')),
                ('classification', models.CharField(blank=True, help_text='مثل: G06F, H04L', max_length=100, verbose_name='التصنيف')),
                ('inventors', models.TextField(verbose_name='المخترعون/الملكية الفكرية')),
                ('patent_owner', models.CharField(max_length=200, verbose_name='صاحب البراءة')),
                ('filing_date', models.DateField(verbose_name='تاريخ الإيداع')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('filed', 'مودعة'), ('pending', 'قيد الفحص'), ('approved', 'موافق عليها'), ('expired', 'منتهية'), ('rejected', 'مرفوضة'), ('abandoned', 'مهجورة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('specification_document', models.FileField(upload_to='patents/', verbose_name='وثيقة المواصفات')),
                ('drawings', models.FileField(blank=True, upload_to='patents/', verbose_name='الرسومات')),
                ('claims', models.TextField(blank=True, verbose_name='المطالبات')),
                ('protected_countries', models.TextField(help_text='قائمة بأسماء الدول مفصولة بفواصل', verbose_name='الدول المحمية')),
                ('registration_fee_paid', models.BooleanField(default=False, verbose_name='تم دفع رسم التسجيل')),
                ('annual_fees_paid', models.BooleanField(default=False, verbose_name='تم دفع الرسوم السنوية')),
                ('next_renewal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد التالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'براءة اختراع',
                'verbose_name_plural': 'براءات الاختراع',
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['status'], name='intellectua_status_fa8c60_idx'), models.Index(fields=['patent_type'], name='intellectua_patent__c1e87f_idx'), models.Index(fields=['expiry_date'], name='intellectua_expiry__572e69_idx')],
            },
        ),
    ]
