# Generated by Django 5.2.5 on 2025-12-15 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الشركة')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='سر API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شركة شحن',
                'verbose_name_plural': 'شركات الشحن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المنطقة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('cities', models.TextField(blank=True, help_text='أدخل المدن مفصولة بفاصلة', verbose_name='المدن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منطقة شحن',
                'verbose_name_plural': 'مناطق الشحن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التتبع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('picked_up', 'تم الاستلام'), ('in_transit', 'في الطريق'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('returned', 'مرتجع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='هاتف المرسل')),
                ('sender_address', models.TextField(verbose_name='عنوان المرسل')),
                ('sender_city', models.CharField(max_length=100, verbose_name='مدينة المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('receiver_address', models.TextField(verbose_name='عنوان المستلم')),
                ('receiver_city', models.CharField(max_length=100, verbose_name='مدينة المستلم')),
                ('description', models.TextField(verbose_name='وصف المحتويات')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن (كجم)')),
                ('pieces', models.PositiveIntegerField(default=1, verbose_name='عدد القطع')),
                ('dimensions', models.CharField(blank=True, help_text='الطول × العرض × الارتفاع', max_length=50, verbose_name='الأبعاد')),
                ('payment_type', models.CharField(choices=[('prepaid', 'مدفوع مسبقاً'), ('cod', 'الدفع عند الاستلام'), ('account', 'على الحساب')], default='prepaid', max_length=20, verbose_name='نوع الدفع')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشحن')),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ COD')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ التأمين')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='التوصيل المتوقع')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='التوصيل الفعلي')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المرجع')),
                ('order_id', models.CharField(blank=True, max_length=50, verbose_name='رقم الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingcompany', verbose_name='شركة الشحن')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.shippingzone', verbose_name='منطقة الشحن')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('picked_up', 'تم الاستلام'), ('in_transit', 'في الطريق'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('returned', 'مرتجع'), ('cancelled', 'ملغي')], max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipping.shipment', verbose_name='الشحنة')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
            ],
            options={
                'verbose_name': 'تتبع شحنة',
                'verbose_name_plural': 'تتبع الشحنات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('invoice_date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضريبة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='shipping.shippingcompany', verbose_name='شركة الشحن')),
            ],
            options={
                'verbose_name': 'فاتورة شحن',
                'verbose_name_plural': 'فواتير الشحن',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shippinginvoice', verbose_name='الفاتورة')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='shipping.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفواتير',
            },
        ),
        migrations.CreateModel(
            name='ShippingPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الاستلام')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('picked_up', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('pickup_address', models.TextField(verbose_name='عنوان الاستلام')),
                ('pickup_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('contact_name', models.CharField(max_length=100, verbose_name='اسم المسؤول')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='هاتف المسؤول')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ الاستلام المحدد')),
                ('scheduled_time_from', models.TimeField(verbose_name='من الساعة')),
                ('scheduled_time_to', models.TimeField(verbose_name='إلى الساعة')),
                ('pieces_count', models.PositiveIntegerField(verbose_name='عدد القطع المتوقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='shipping.shippingcompany', verbose_name='شركة الشحن')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'طلب استلام',
                'verbose_name_plural': 'طلبات الاستلام',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_from', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الوزن من (كجم)')),
                ('weight_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن إلى (كجم)')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('extra_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الكيلو الإضافي')),
                ('delivery_days', models.PositiveIntegerField(default=3, verbose_name='أيام التوصيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingcompany', verbose_name='شركة الشحن')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'تعريفة شحن',
                'verbose_name_plural': 'تعريفات الشحن',
                'ordering': ['company', 'zone', 'weight_from'],
            },
        ),
    ]
