# Generated by Django 5.2.5 on 2025-08-10 19:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fiscalyear_account_journalentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_post',
            field=models.BooleanField(default=True, help_text='إذا كان false، لا يمكن إنشاء قيود على هذا الحساب مباشرة', verbose_name='يقبل القيد'),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الحد الائتماني'),
        ),
        migrations.AddField(
            model_name='account',
            name='requires_cost_center',
            field=models.BooleanField(default=False, verbose_name='يتطلب مركز تكلفة'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='reference_document',
            field=models.CharField(blank=True, max_length=100, verbose_name='وثيقة مرجعية'),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المركز')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مركز التكلفة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدير المركز')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='المركز الرئيسي')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة الافتراضي'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.CreateModel(
            name='JournalEntryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('sale_cash', 'مبيعات نقدية'), ('sale_credit', 'مبيعات آجلة'), ('purchase_cash', 'مشتريات نقدية'), ('purchase_credit', 'مشتريات آجلة'), ('payment', 'دفع نقدي'), ('receipt', 'إيصال نقدي'), ('expense', 'مصروف'), ('salary', 'راتب'), ('depreciation', 'استهلاك'), ('custom', 'قالب مخصص')], max_length=20, verbose_name='نوع القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_apply', models.BooleanField(default=False, verbose_name='تطبيق تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب قيد محاسبي',
                'verbose_name_plural': 'قوالب القيود المحاسبية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='النوع')),
                ('amount_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية'), ('variable', 'متغير')], default='variable', max_length=20, verbose_name='نوع المبلغ')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ الثابت')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='النسبة المئوية')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='البيان الافتراضي')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='الحساب')),
                ('default_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة الافتراضي')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentrytemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'بند قالب القيد',
                'verbose_name_plural': 'بنود قوالب القيود',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي الموازنة')),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الموازنة المخصصة')),
                ('actual_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المصروفات الفعلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='السنة المالية')),
            ],
            options={
                'verbose_name': 'موازنة مركز تكلفة',
                'verbose_name_plural': 'موازنات مراكز التكلفة',
                'unique_together': {('cost_center', 'fiscal_year')},
            },
        ),
    ]
