# Generated by Django 5.2.5 on 2025-08-11 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_account_can_post_account_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز البنك')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='الشخص المسؤول')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='رمز Swift')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القرض')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ القرض')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='معدل الفائدة')),
                ('duration_months', models.PositiveIntegerField(verbose_name='مدة القرض بالشهور')),
                ('disbursement_date', models.DateField(verbose_name='تاريخ الصرف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر')], default='draft', max_length=20, verbose_name='الحالة')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد المستحق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bank', verbose_name='البنك')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounting.account', verbose_name='حساب القرض')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='جزء أصل الدين')),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='جزء الفوائد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.loan', verbose_name='القرض')),
            ],
            options={
                'verbose_name': 'دفعة قرض',
                'verbose_name_plural': 'دفعات القروض',
            },
        ),
    ]
