# Generated by Django 5.2.5 on 2025-08-13 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_cheque'),
        ('partners', '0002_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['number'], name='accounting__number_b628ad_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_14c1fd_idx'),
        ),
    ]
