# Generated by Django 5.2.5 on 2025-08-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cashflowaccountmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='ar_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب العملاء (الذمم)'),
        ),
    ]
