# Generated by Django 5.2.5 on 2025-08-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingsettings_ar_account'),
        ('showrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='showroom',
            field=models.ForeignKey(blank=True, help_text='ربط القيد بمعرض محدد لاحتساب أرباح/خسائر الفروع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='showrooms.showroom', verbose_name='المعرض'),
        ),
    ]
