# Generated by Django 5.2.5 on 2025-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_journalentry_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryitem',
            name='analytics',
            field=models.CharField(blank=True, max_length=200, verbose_name='تحليل مالي'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='analytics_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='تحليل مالي مكمل'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='analytics_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='تحليل مالي مكمل 1'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='master_account',
            field=models.CharField(blank=True, max_length=200, verbose_name='حساب أستاذ'),
        ),
    ]
