# Generated by Django 5.2.5 on 2025-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_journalentryitem_analytics_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['journal_entry', 'type'], name='accounting__journal_980a75_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['account', 'type'], name='accounting__account_524b4b_idx'),
        ),
    ]
