# Generated by Django 5.2.5 on 2025-09-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_journalentryitem_accounting__journal_980a75_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False, help_text='إذا كان True لا يقبل قيد مباشر (سيتم ضبط can_post تلقائياً)', verbose_name='حساب تجميعي'),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='account',
            name='path',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name='المسار'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_889d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__da6035_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_28dd04_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_account_parent_name'),
        ),
    ]
