# Generated by Django 5.2.5 on 2025-09-15 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_account_is_group_account_level_account_path_and_more'),
        ('purchases', '0010_merge_0009_conflict'),
        ('sales', '0016_invoice_bank_account_invoice_bank_name'),
        ('showrooms', '0005_rename_showroom_attendance_showroom_date_idx_showrooms_a_showroo_4c4c49_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_95b69a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='accounting__date_e3f521_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_5e6cde_idx'),
        ),
    ]
