# Generated by Django 5.2.5 on 2025-09-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_journalentry_accounting__is_post_95b69a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['cost_center'], name='accounting__cost_ce_34ac3d_idx'),
        ),
    ]
