# Generated by Django 5.2.5 on 2025-09-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_journalentryitem_accounting__cost_ce_34ac3d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='customer_advances_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account', verbose_name='حساب سلف العملاء / دفعات مقدمة'),
        ),
    ]
