# Generated by Django 5.2.5 on 2025-09-16 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_customer_advances_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('is_reconciled', models.BooleanField(db_index=True, default=False, verbose_name='مسوّى')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounting.account', verbose_name='حساب بنكي')),
            ],
            options={
                'verbose_name': 'حركة بنك',
                'verbose_name_plural': 'حركات البنك',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['account', 'is_reconciled'], name='accounting__account_08e4cf_idx'), models.Index(fields=['date'], name='accounting__date_60a468_idx')],
            },
        ),
    ]
