# Generated by Django 5.2.5 on 2025-09-16 06:36

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_banktransaction'),
        ('purchases', '0010_merge_0009_conflict'),
        ('sales', '0020_alter_invoicepayment_options_and_more'),
        ('showrooms', '0005_rename_showroom_attendance_showroom_date_idx_showrooms_a_showroo_4c4c49_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodYearClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإقفال')),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='صافي الربح/الخسارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('preview_data', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل الحركات وقت الإقفال')),
            ],
            options={
                'verbose_name': 'إقفال سنة مالية',
                'verbose_name_plural': 'إقفالات السنوات المالية',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-number'], 'permissions': [('view_journal_reports', 'Can view accounting analytical reports'), ('post_journal_entry', 'Can post journal entries'), ('unpost_journal_entry', 'Can unpost (reverse) journal entries'), ('create_journal_entry', 'Can create manual journal entries')], 'verbose_name': 'قيد محاسبي', 'verbose_name_plural': 'القيود المحاسبية'},
        ),
        migrations.AlterModelOptions(
            name='journalentryitem',
            options={'permissions': [('edit_posted_entry_items', 'Can edit items of posted journal (not recommended)')], 'verbose_name': 'بند قيد محاسبي', 'verbose_name_plural': 'بنود القيود المحاسبية'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='معدل الفائدة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الرصيد المستحق'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ القرض'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='interest_portion',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جزء الفوائد'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='principal_portion',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='جزء أصل الدين'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date', 'is_posted'], name='je_date_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['account', 'journal_entry'], name='jei_account_entry_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__lte', Decimal('100'))), name='loan_interest_rate_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('principal_portion'), '+', models.F('interest_portion')))), name='loanpayment_amount_equals_parts'),
        ),
        migrations.AddField(
            model_name='periodyearclose',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة'),
        ),
        migrations.AddField(
            model_name='periodyearclose',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_closures', to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='periodyearclose',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='قيد الإقفال'),
        ),
        migrations.AddConstraint(
            model_name='periodyearclose',
            constraint=models.UniqueConstraint(fields=('fiscal_year',), name='uniq_year_close_once'),
        ),
    ]
