# Generated by Django 5.2.5 on 2025-09-16 06:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_periodyearclose_alter_journalentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='كمية المحرك')),
                ('driver_rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='معدل التحميل')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ موزع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نتيجة توزيع',
                'verbose_name_plural': 'نتائج التوزيع',
            },
        ),
        migrations.CreateModel(
            name='CostAllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=10, verbose_name='الفترة')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_indirect_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='إجمالي غير مباشر')),
                ('total_allocated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='إجمالي موزع')),
                ('status', models.CharField(db_index=True, default='running', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'تشغيل توزيع تكاليف',
                'verbose_name_plural': 'تشغيلات توزيع التكاليف',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CostDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('driver_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المحرك')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='وحدة القياس')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محرك تكلفة',
                'verbose_name_plural': 'محركات التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجمع تكاليف',
                'verbose_name_plural': 'مجمعات التكاليف',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostPoolConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='كمية المحرك')),
                ('period', models.CharField(help_text='مثال: 2025-09 (شهر) أو 2025Q3', max_length=10, verbose_name='فترة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'استهلاك مجمع',
                'verbose_name_plural': 'استهلاكات المجمعات',
            },
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_c6090c_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['parent'], name='accounting__parent__4b7960_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['manager'], name='accounting__manager_572adc_idx'),
        ),
        migrations.AddField(
            model_name='costallocationresult',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.costcenter', verbose_name='مركز'),
        ),
        migrations.AddField(
            model_name='costallocationresult',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='قيد التوزيع'),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نُفذ بواسطة'),
        ),
        migrations.AddField(
            model_name='costallocationresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounting.costallocationrun', verbose_name='تشغيل'),
        ),
        migrations.AddField(
            model_name='costpool',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز خدمة (اختياري)'),
        ),
        migrations.AddField(
            model_name='costpool',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.costdriver', verbose_name='محرك التكلفة'),
        ),
        migrations.AddField(
            model_name='costallocationresult',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.costpool', verbose_name='مجمع'),
        ),
        migrations.AddField(
            model_name='costpoolconsumption',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter', verbose_name='مركز مستفيد'),
        ),
        migrations.AddField(
            model_name='costpoolconsumption',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='accounting.costpool', verbose_name='مجمع'),
        ),
        migrations.AddIndex(
            model_name='costallocationresult',
            index=models.Index(fields=['run', 'cost_center'], name='accounting__run_id_69ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='costallocationresult',
            index=models.Index(fields=['pool'], name='accounting__pool_id_fec831_idx'),
        ),
        migrations.AddIndex(
            model_name='costpoolconsumption',
            index=models.Index(fields=['pool', 'period'], name='accounting__pool_id_35e5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='costpoolconsumption',
            index=models.Index(fields=['cost_center', 'period'], name='accounting__cost_ce_f8bbc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='costpoolconsumption',
            constraint=models.UniqueConstraint(fields=('pool', 'cost_center', 'period'), name='uniq_pool_center_period'),
        ),
    ]
