# Generated by Django 5.2.5 on 2025-09-16 07:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_costallocationresult_costallocationrun_costdriver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpool',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب دائن (مصدر)'),
        ),
        migrations.AddField(
            model_name='costpool',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب مدين (تحميل)'),
        ),
        migrations.CreateModel(
            name='CostPoolSourceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='اترك 0 لاستخدام القيمة الكاملة للحساب', max_digits=7, verbose_name='نسبة اعتبارية %')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_accounts', to='accounting.costpool', verbose_name='مجمع')),
            ],
            options={
                'verbose_name': 'حساب مصدر مجمع',
                'verbose_name_plural': 'حسابات مصادر المجمعات',
                'indexes': [models.Index(fields=['pool', 'is_active'], name='accounting__pool_id_546a76_idx')],
                'constraints': [models.UniqueConstraint(fields=('pool', 'account'), name='uniq_pool_account_source')],
            },
        ),
    ]
