# Generated by Django 5.2.5 on 2025-12-08 04:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_account_id_alter_accountingsettings_id_and_more'),
        ('inventory', '0018_printerconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('costing_method', models.CharField(choices=[('standard', 'تكلفة معيارية'), ('actual', 'تكلفة فعلية'), ('average', 'متوسط متحرك')], default='standard', max_length=20, verbose_name='طريقة التكلفة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('archived', 'مؤرشفة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('direct_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة المواد المباشرة')),
                ('direct_labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة العمالة المباشرة')),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='التكاليف الصناعية غير المباشرة')),
                ('other_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكاليف أخرى')),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='إجمالي التكلفة')),
                ('target_profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='هامش الربح المستهدف %')),
                ('suggested_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='السعر المقترح')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_costings', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costings', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بطاقة تكلفة منتج',
                'verbose_name_plural': 'بطاقات تكاليف المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_cost', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='التكلفة القديمة')),
                ('new_cost', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='التكلفة الجديدة')),
                ('change_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب التغيير')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_history', to='inventory.product', verbose_name='المنتج')),
                ('costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.productcosting', verbose_name='بطاقة التكلفة')),
            ],
            options={
                'verbose_name': 'سجل تكلفة',
                'verbose_name_plural': 'سجل التكاليف',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CostComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('material', 'مادة خام'), ('labor', 'عمالة'), ('overhead', 'تكاليف صناعية غير مباشرة'), ('service', 'خدمة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المكون')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15, verbose_name='الكمية')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='إجمالي التكلفة')),
                ('allocation_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='نسبة التخصيص %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account', verbose_name='الحساب')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='الصنف')),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounting.productcosting', verbose_name='بطاقة التكلفة')),
            ],
            options={
                'verbose_name': 'مكون تكلفة',
                'verbose_name_plural': 'مكونات التكاليف',
                'ordering': ['sequence', 'component_type', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='productcosting',
            index=models.Index(fields=['product', 'status'], name='accounting__product_0d341f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcosting',
            index=models.Index(fields=['status', 'effective_from'], name='accounting__status_1d9c3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcosting',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_costing_version'),
        ),
        migrations.AddIndex(
            model_name='costinghistory',
            index=models.Index(fields=['product', 'changed_at'], name='accounting__product_f19b67_idx'),
        ),
        migrations.AddIndex(
            model_name='costcomponent',
            index=models.Index(fields=['costing', 'component_type'], name='accounting__costing_b1e7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='costcomponent',
            index=models.Index(fields=['item'], name='accounting__item_id_e89fd4_idx'),
        ),
    ]
