# Generated by Django 5.2.9 on 2026-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_financial_analysis_and_account_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountentry',
            new_name='accounting__entry_t_bba407_idx',
            old_name='accounting__entry_t_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='accountentry',
            new_name='accounting__ledger__30cdd7_idx',
            old_name='accounting__ledger__def456_idx',
        ),
        migrations.RenameIndex(
            model_name='accountentry',
            new_name='accounting__financi_59c2d2_idx',
            old_name='accounting__financi_ghi789_idx',
        ),
        migrations.RenameIndex(
            model_name='accountentry',
            new_name='accounting__financi_7a6a53_idx',
            old_name='accounting__financi_jkl012_idx',
        ),
    ]
