# Generated by Django 5.2.9 on 2026-01-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_accounting__entry_t_abc123_idx_accounting__entry_t_bba407_idx_and_more'),
        ('partners', '0011_product_unit_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='partners.supplier', verbose_name='صاحب التوريد'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='partners.supplier', verbose_name='صاحب التوريد'),
        ),
    ]
