# Generated by Django 5.2.9 on 2026-01-08 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_add_supplier_to_revenue_entries'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0011_product_unit_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='owner_content_type',
            field=models.ForeignKey(blank=True, help_text='نوع الكيان (عميل، مورد، سائق، إلخ)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع صاحب العملية'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='owner_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف صاحب العملية'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text="استخدم حقل 'صاحب العملية' الجديد بدلاً من هذا", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='partners.supplier', verbose_name='صاحب التوريد (قديم)'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['owner_content_type', 'owner_object_id'], name='accounting__owner_c_0bfd29_idx'),
        ),
    ]
