# Generated by Django 5.2.5 on 2026-01-09 10:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_add_generic_owner_to_accountentry'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0011_product_unit_warranty'),
        ('showrooms', '0011_showroompricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('account_type', models.CharField(choices=[('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('orange_cash', 'أورانج كاش'), ('etisalat_cash', 'اتصالات كاش'), ('we_pay', 'وي باي'), ('paypal', 'باي بال'), ('paymob', 'بايموب'), ('fawry', 'فوري'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الحساب')),
                ('phone_number', models.CharField(blank=True, help_text='رقم الهاتف المرتبط بالمحفظة/الحساب', max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('account_id', models.CharField(blank=True, help_text='رقم الحساب أو المعرف الفريد', max_length=100, verbose_name='معرف الحساب')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حساب إلكتروني',
                'verbose_name_plural': 'الحسابات الإلكترونية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخزينة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الخزينة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خزينة',
                'verbose_name_plural': 'الخزائن',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'بنك', 'verbose_name_plural': 'البنوك'},
        ),
        migrations.AddField(
            model_name='accountentry',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='accounting.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('treasury', 'خزينة'), ('bank', 'بنك'), ('electronic', 'حساب إلكتروني')], help_text='أين دخلت/خرجت الأموال', max_length=20, null=True, verbose_name='نوع الوجهة'),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الحالي'),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_2e6e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['code'], name='accounting__code_49111b_idx'),
        ),
        migrations.AddField(
            model_name='electronicaccount',
            name='linked_account',
            field=models.ForeignKey(blank=True, help_text='الحساب في دليل الحسابات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_accounts', to='accounting.account', verbose_name='الحساب المحاسبي المرتبط'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='electronic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='accounting.electronicaccount', verbose_name='الحساب الإلكتروني'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='accounting.account', verbose_name='الحساب المحاسبي المرتبط'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_treasuries', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='showrooms.showroom', verbose_name='المعرض/الفرع'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='accounting.treasury', verbose_name='الخزينة'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['destination_type'], name='accounting__destina_401df6_idx'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['treasury'], name='accounting__treasur_110324_idx'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['bank'], name='accounting__bank_id_c5b5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['electronic_account'], name='accounting__electro_07e211_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicaccount',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_b82aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicaccount',
            index=models.Index(fields=['account_type'], name='accounting__account_a11457_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicaccount',
            index=models.Index(fields=['code'], name='accounting__code_dc3c87_idx'),
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_b9afef_idx'),
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['code'], name='accounting__code_177654_idx'),
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['showroom'], name='accounting__showroo_35df7e_idx'),
        ),
    ]
