# Generated by Django 5.2.9 on 2026-01-09 12:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_electronicaccount_treasury_alter_bank_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0011_product_unit_warranty'),
        ('showrooms', '0011_showroompricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('treasury', 'خزينة'), ('bank', 'بنك'), ('electronic', 'حساب إلكتروني'), ('fawry', 'ماكينة فوري'), ('visa', 'ماكينة فيزا')], help_text='أين دخلت/خرجت الأموال', max_length=20, null=True, verbose_name='نوع الوجهة'),
        ),
        migrations.CreateModel(
            name='FawryMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الماكينة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الماكينة')),
                ('machine_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الماكينة')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف المربوط')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الحالي')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة العمولة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fawry_machines', to='accounting.account', verbose_name='الحساب المحاسبي المرتبط')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_fawry_machines', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fawry_machines', to='showrooms.showroom', verbose_name='المعرض/الفرع')),
            ],
            options={
                'verbose_name': 'ماكينة فوري',
                'verbose_name_plural': 'ماكينات الفوري',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accountentry',
            name='fawry_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='accounting.fawrymachine', verbose_name='ماكينة الفوري'),
        ),
        migrations.CreateModel(
            name='VisaMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الماكينة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الماكينة')),
                ('terminal_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الترمينال')),
                ('merchant_id', models.CharField(blank=True, max_length=50, verbose_name='رقم التاجر')),
                ('machine_type', models.CharField(choices=[('visa', 'فيزا'), ('mastercard', 'ماستركارد'), ('mada', 'مدى'), ('multi', 'متعدد البطاقات')], default='multi', max_length=20, verbose_name='نوع الماكينة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة العمولة %')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_machines', to='accounting.bank', verbose_name='البنك المربوط')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_machines', to='accounting.account', verbose_name='الحساب المحاسبي المرتبط')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_visa_machines', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_machines', to='showrooms.showroom', verbose_name='المعرض/الفرع')),
            ],
            options={
                'verbose_name': 'ماكينة فيزا',
                'verbose_name_plural': 'ماكينات الفيزا',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accountentry',
            name='visa_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='accounting.visamachine', verbose_name='ماكينة الفيزا'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['fawry_machine'], name='accounting__fawry_m_a29b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountentry',
            index=models.Index(fields=['visa_machine'], name='accounting__visa_ma_2d7ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='fawrymachine',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_17fd49_idx'),
        ),
        migrations.AddIndex(
            model_name='fawrymachine',
            index=models.Index(fields=['code'], name='accounting__code_996371_idx'),
        ),
        migrations.AddIndex(
            model_name='fawrymachine',
            index=models.Index(fields=['machine_id'], name='accounting__machine_2de5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='fawrymachine',
            index=models.Index(fields=['showroom'], name='accounting__showroo_1fd470_idx'),
        ),
        migrations.AddIndex(
            model_name='visamachine',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_13197c_idx'),
        ),
        migrations.AddIndex(
            model_name='visamachine',
            index=models.Index(fields=['code'], name='accounting__code_ad4cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='visamachine',
            index=models.Index(fields=['terminal_id'], name='accounting__termina_b7413d_idx'),
        ),
        migrations.AddIndex(
            model_name='visamachine',
            index=models.Index(fields=['showroom'], name='accounting__showroo_be1f53_idx'),
        ),
        migrations.AddIndex(
            model_name='visamachine',
            index=models.Index(fields=['bank'], name='accounting__bank_id_835155_idx'),
        ),
    ]
