# Generated by Django 5.2.9 on 2026-01-09 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_add_fawry_visa_machines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('date', models.DateField(verbose_name='تاريخ التحويل')),
                ('from_type', models.CharField(choices=[('treasury', 'خزينة'), ('bank', 'بنك'), ('electronic', 'حساب إلكتروني'), ('fawry', 'ماكينة فوري'), ('visa', 'ماكينة فيزا')], max_length=20, verbose_name='نوع المصدر')),
                ('to_type', models.CharField(choices=[('treasury', 'خزينة'), ('bank', 'بنك'), ('electronic', 'حساب إلكتروني'), ('fawry', 'ماكينة فوري'), ('visa', 'ماكينة فيزا')], max_length=20, verbose_name='نوع الوجهة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='رسوم التحويل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='completed', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, verbose_name='البيان/الوصف')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.bank', verbose_name='من بنك')),
                ('from_electronic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.electronicaccount', verbose_name='من حساب إلكتروني')),
                ('from_fawry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.fawrymachine', verbose_name='من ماكينة فوري')),
                ('from_treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.treasury', verbose_name='من خزينة')),
                ('from_visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.visamachine', verbose_name='من ماكينة فيزا')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.bank', verbose_name='إلى بنك')),
                ('to_electronic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.electronicaccount', verbose_name='إلى حساب إلكتروني')),
                ('to_fawry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.fawrymachine', verbose_name='إلى ماكينة فوري')),
                ('to_treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.treasury', verbose_name='إلى خزينة')),
                ('to_visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.visamachine', verbose_name='إلى ماكينة فيزا')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='accounting__date_6feb00_idx'), models.Index(fields=['from_type'], name='accounting__from_ty_fa745d_idx'), models.Index(fields=['to_type'], name='accounting__to_type_93fbc9_idx'), models.Index(fields=['status'], name='accounting__status_f759ba_idx'), models.Index(fields=['transfer_number'], name='accounting__transfe_666437_idx')],
            },
        ),
    ]
