# Generated by Django 5.2.9 on 2026-01-09 12:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_add_account_transfer'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0011_product_unit_warranty'),
        ('purchases', '0018_supplierdiscountnote'),
        ('sales', '0029_advanced_accounting_features'),
        ('showrooms', '0011_showroompricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingApprovalWorkflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف السجل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approval_level', models.IntegerField(default=1, verbose_name='مستوى الاعتماد')),
                ('total_levels', models.IntegerField(default=1, verbose_name='إجمالي المستويات')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سير عمل موافقة',
                'verbose_name_plural': 'سير عمل الموافقات',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountingAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('post', 'ترحيل'), ('unpost', 'إلغاء ترحيل'), ('approve', 'اعتماد'), ('reject', 'رفض')], max_length=20, verbose_name='نوع الإجراء')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف السجل')),
                ('object_repr', models.CharField(max_length=200, verbose_name='تمثيل السجل')),
                ('changes', models.JSONField(verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الأصل')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='تكلفة الشراء')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='قيمة الخردة')),
                ('useful_life_years', models.IntegerField(verbose_name='العمر الإنتاجي (سنوات)')),
                ('useful_life_months', models.IntegerField(default=0, verbose_name='العمر الإنتاجي (أشهر إضافية)')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'القسط الثابت'), ('declining_balance', 'القسط المتناقص'), ('units_of_production', 'وحدات الإنتاج'), ('sum_of_years', 'مجموع السنين')], default='straight_line', max_length=30, verbose_name='طريقة الإهلاك')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل الإهلاك %')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='مجمع الإهلاك')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة الدفترية')),
                ('last_depreciation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إهلاك')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('disposed', 'تم التصرف فيه'), ('fully_depreciated', 'تم إهلاكه بالكامل'), ('under_maintenance', 'تحت الصيانة')], default='active', max_length=30, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='المورد')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الضمان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_statement', models.FileField(help_text='ملف CSV أو Excel من البنك', upload_to='bank_statements/%Y/%m/', verbose_name='كشف الحساب البنكي')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الختامي')),
                ('status', models.CharField(choices=[('in_progress', 'جاري التسوية'), ('completed', 'مكتملة'), ('needs_review', 'تحتاج مراجعة'), ('approved', 'معتمدة')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('auto_matched_count', models.IntegerField(default=0, verbose_name='عدد المطابقات التلقائية')),
                ('manual_matched_count', models.IntegerField(default=0, verbose_name='عدد المطابقات اليدوية')),
                ('unmatched_items', models.JSONField(default=dict, verbose_name='البنود غير المطابقة')),
                ('matched_items', models.JSONField(default=dict, verbose_name='البنود المطابقة')),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='فرق التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تسوية بنكية',
                'verbose_name_plural': 'التسويات البنكية',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المدرج بالموازنة')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ الفعلي')),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='فرق المبلغ')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الفرق %')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بند موازنة',
                'verbose_name_plural': 'بنود الموازنات',
                'ordering': ['fiscal_year', 'month', 'account'],
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع التقرير')),
                ('filters', models.JSONField(default=dict, verbose_name='الفلاتر')),
                ('columns', models.JSONField(default=list, verbose_name='الأعمدة')),
                ('grouping', models.JSONField(default=list, verbose_name='التجميع')),
                ('sorting', models.JSONField(default=list, verbose_name='الترتيب')),
                ('is_public', models.BooleanField(default=False, verbose_name='تقرير عام')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='تفعيل الجدولة')),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, verbose_name='تكرار الجدولة')),
                ('schedule_recipients', models.JSONField(default=list, verbose_name='مستلمو التقرير')),
                ('execution_count', models.IntegerField(default=0, verbose_name='عدد مرات التشغيل')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تقرير مخصص',
                'verbose_name_plural': 'التقارير المخصصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField(verbose_name='تاريخ الإهلاك')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الإهلاك')),
                ('accumulated_depreciation_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مجمع الإهلاك قبل')),
                ('accumulated_depreciation_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مجمع الإهلاك بعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قيد إهلاك',
                'verbose_name_plural': 'قيود الإهلاك',
                'ordering': ['-depreciation_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='نوع الفترة')),
                ('period_number', models.IntegerField(verbose_name='رقم الفترة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'جاري الإقفال'), ('closed', 'مقفل'), ('reopened', 'أعيد فتحه')], default='open', max_length=20, verbose_name='الحالة')),
                ('checklist_completed', models.BooleanField(default=False, verbose_name='تم إكمال قائمة التحقق')),
                ('closing_entries_created', models.BooleanField(default=False, verbose_name='تم إنشاء قيود الإقفال')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إعادة الفتح')),
                ('reopen_reason', models.TextField(blank=True, verbose_name='سبب إعادة الفتح')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إقفال فترة',
                'verbose_name_plural': 'إقفالات الفترات',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableAging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ المدفوع')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد المتبقي')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='أيام التأخير')),
                ('aging_bucket', models.CharField(max_length=20, verbose_name='فئة العمر')),
                ('snapshot_date', models.DateField(auto_now_add=True, verbose_name='تاريخ اللقطة')),
            ],
            options={
                'verbose_name': 'عمر دين',
                'verbose_name_plural': 'أعمار الديون',
                'ordering': ['partner', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القيد المتكرر')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('biweekly', 'كل أسبوعين'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semiannually', 'نصف سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('next_execution', models.DateField(verbose_name='التنفيذ التالي')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('auto_post', models.BooleanField(default=False, help_text='إذا كان True، سيتم ترحيل القيد تلقائياً', verbose_name='ترحيل تلقائي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notify_before_days', models.IntegerField(default=3, verbose_name='التنبيه قبل (أيام)')),
                ('execution_count', models.IntegerField(default=0, verbose_name='عدد مرات التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قيد متكرر',
                'verbose_name_plural': 'القيود المتكررة',
                'ordering': ['next_execution'],
            },
        ),
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': 'شيك', 'verbose_name_plural': 'حافظة الشيكات'},
        ),
        migrations.AddField(
            model_name='cheque',
            name='alert_days_before',
            field=models.IntegerField(default=3, verbose_name='التنبيه قبل (أيام)'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='alert_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال تنبيه الاستحقاق'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bank', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounced_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإرتداد'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounced_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='رسوم الإرتداد'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounced_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإرتداد'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cleared_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحصيل'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإيداع'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='replacement_cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_cheques', to='accounting.cheque', verbose_name='الشيك البديل'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='مولد تلقائياً'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.journalentry', verbose_name='عكس قيد'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='اسم البنك'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/%Y/%m/', verbose_name='صورة الشيك'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الشيك'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('received', 'مستلم'), ('issued', 'صادر'), ('under_collection', 'قيد التحصيل'), ('deposited', 'مودع بالبنك'), ('cleared', 'محصل'), ('bounced', 'مرتجع'), ('cancelled', 'ملغى'), ('replaced', 'تم استبداله')], default='received', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'قيد يدوي'), ('sales', 'من المبيعات'), ('purchase', 'من المشتريات'), ('payment', 'دفعة'), ('receipt', 'إيصال'), ('adjustment', 'قيد تسوية'), ('salary', 'من الرواتب'), ('inventory', 'من المخزون'), ('pos', 'من نقاط البيع'), ('depreciation', 'قيد إهلاك'), ('closing', 'قيد إقفال')], default='manual', max_length=20, verbose_name='نوع القيد'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['cheque_type', 'status'], name='accounting__cheque__35864e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['auto_generated'], name='accounting__auto_ge_74d59e_idx'),
        ),
        migrations.AddField(
            model_name='accountingapprovalworkflow',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_approval_workflows', to='contenttypes.contenttype', verbose_name='نوع السجل'),
        ),
        migrations.AddField(
            model_name='accountingapprovalworkflow',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد الحالي'),
        ),
        migrations.AddField(
            model_name='accountingapprovalworkflow',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة'),
        ),
        migrations.AddField(
            model_name='accountingauditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_audit_logs', to='contenttypes.contenttype', verbose_name='نوع السجل'),
        ),
        migrations.AddField(
            model_name='accountingauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='asset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounting.account', verbose_name='حساب الأصل'),
        ),
        migrations.AddField(
            model_name='asset',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_assets', to='accounting.account', verbose_name='حساب مجمع الإهلاك'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_assets', to='accounting.account', verbose_name='حساب مصروف الإهلاك'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='customreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='accounting.asset', verbose_name='الأصل'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='periodclose',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_closed', to=settings.AUTH_USER_MODEL, verbose_name='أقفل بواسطة'),
        ),
        migrations.AddField(
            model_name='periodclose',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='periodclose',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_reopened', to=settings.AUTH_USER_MODEL, verbose_name='أعيد فتحه بواسطة'),
        ),
        migrations.AddField(
            model_name='receivableaging',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='الشريك/العميل'),
        ),
        migrations.AddField(
            model_name='recurringjournalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='recurringjournalentry',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.journalentrytemplate', verbose_name='قالب القيد'),
        ),
        migrations.AddIndex(
            model_name='accountingauditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='accounting__content_eecef3_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='accounting__user_id_fb12c4_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingauditlog',
            index=models.Index(fields=['action_type'], name='accounting__action__c2344b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='accounting__status_68dd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['purchase_date'], name='accounting__purchas_134dec_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['bank', 'period_start', 'period_end'], name='accounting__bank_id_37df7d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['status'], name='accounting__status_bef3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['fiscal_year', 'month'], name='accounting__fiscal__ad135a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['account'], name='accounting__account_265cf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('account', 'cost_center', 'fiscal_year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='periodclose',
            unique_together={('fiscal_year', 'period_type', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='receivableaging',
            index=models.Index(fields=['partner', 'aging_bucket'], name='accounting__partner_62a97e_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableaging',
            index=models.Index(fields=['snapshot_date'], name='accounting__snapsho_d7d6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournalentry',
            index=models.Index(fields=['is_active', 'next_execution'], name='accounting__is_acti_86f1be_idx'),
        ),
    ]
