# Generated by Django 5.2.9 on 2026-01-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_advanced_features_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_create_journal_entries',
            field=models.BooleanField(default=True, help_text='عند التفعيل، يتم إنشاء قيد محاسبي تلقائياً عند تسجيل إيراد أو مصروف', verbose_name='إنشاء قيود تلقائية للإيرادات والمصروفات'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_bank', to='accounting.account', verbose_name='حساب البنك الافتراضي'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_electronic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_electronic', to='accounting.account', verbose_name='حساب المحافظ الإلكترونية الافتراضي'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_treasury_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_treasury', to='accounting.account', verbose_name='حساب الخزينة الافتراضي'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='misc_expense_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الافتراضي للمصروفات غير المصنفة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_misc_expense', to='accounting.account', verbose_name='حساب المصروفات المتنوعة'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='misc_revenue_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الافتراضي للإيرادات غير المصنفة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_misc_revenue', to='accounting.account', verbose_name='حساب الإيرادات المتنوعة'),
        ),
    ]
