# Generated by Django 5.2.9 on 2026-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_add_auto_journal_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'قيد يدوي'), ('sales', 'من المبيعات'), ('purchase', 'من المشتريات'), ('payment', 'دفعة'), ('receipt', 'إيصال'), ('adjustment', 'قيد تسوية'), ('salary', 'من الرواتب'), ('inventory', 'من المخزون'), ('pos', 'من نقاط البيع'), ('depreciation', 'قيد إهلاك'), ('closing', 'قيد إقفال'), ('revenue', 'قيد إيراد'), ('expense', 'قيد مصروف')], default='manual', max_length=20, verbose_name='نوع القيد'),
        ),
    ]
