# Generated by Django 5.2.5 on 2026-02-09 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_alter_journalentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
