# Generated by Django 5.2.9 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_add_is_active_to_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهرية'), ('quarterly', 'ربع سنوية'), ('semi_annual', 'نصف سنوية'), ('annual', 'سنوية'), ('special', 'خاصة')], default='monthly', max_length=20, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوحة')),
                ('is_adjustment_period', models.BooleanField(default=False, help_text='هل هذه فترة تسوية نهاية سنة؟', verbose_name='فترة تسوية')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL, verbose_name='أُغلقت بواسطة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear', verbose_name='السنة المالية')),
            ],
            options={
                'verbose_name': 'فترة محاسبية',
                'verbose_name_plural': 'الفترات المحاسبية',
                'ordering': ['start_date'],
                'unique_together': {('fiscal_year', 'start_date')},
            },
        ),
    ]
