# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='productcosting',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='ساري من'),
        ),
    ]
