# Generated by Django 5.2.9 on 2026-01-06 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0025_add_ecommerce_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('stable', 'مستقر'), ('growing', 'نامي'), ('declining', 'متراجع'), ('seasonal', 'موسمي'), ('volatile', 'متقلب')], max_length=20, verbose_name='نوع النمط')),
                ('average_daily_demand', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='متوسط الطلب اليومي')),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الانحراف المعياري')),
                ('coefficient_of_variation', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='معامل التباين')),
                ('has_seasonality', models.BooleanField(default=False, verbose_name='له موسمية')),
                ('peak_months', models.JSONField(blank=True, default=list, verbose_name='أشهر الذروة')),
                ('low_months', models.JSONField(blank=True, default=list, verbose_name='أشهر الهدوء')),
                ('seasonality_index', models.JSONField(blank=True, default=dict, verbose_name='مؤشر الموسمية')),
                ('trend_direction', models.CharField(choices=[('up', 'تصاعدي'), ('down', 'تنازلي'), ('flat', 'ثابت')], default='flat', max_length=20, verbose_name='اتجاه الطلب')),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الاتجاه الشهري %')),
                ('analysis_start_date', models.DateField(verbose_name='بداية فترة التحليل')),
                ('analysis_end_date', models.DateField(verbose_name='نهاية فترة التحليل')),
                ('data_points_count', models.IntegerField(default=0, verbose_name='عدد نقاط البيانات')),
                ('recommended_reorder_point', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='نقطة إعادة الطلب الموصى بها')),
                ('recommended_safety_stock', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المخزون الاحتياطي الموصى به')),
                ('recommended_order_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='كمية الطلب الموصى بها')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_patterns', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'نمط طلب',
                'verbose_name_plural': 'أنماط الطلب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('period_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فترة تنبؤ',
                'verbose_name_plural': 'فترات التنبؤ',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_forecasts', models.IntegerField(default=0, verbose_name='إجمالي التنبؤات')),
                ('accurate_forecasts', models.IntegerField(default=0, verbose_name='التنبؤات الدقيقة')),
                ('overall_accuracy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدقة الإجمالية %')),
                ('mean_absolute_error', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='متوسط الخطأ المطلق (MAE)')),
                ('mean_squared_error', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='متوسط مربع الخطأ (MSE)')),
                ('root_mean_squared_error', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الجذر التربيعي لمتوسط مربع الخطأ (RMSE)')),
                ('mean_absolute_percentage_error', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='متوسط نسبة الخطأ المطلق (MAPE) %')),
                ('best_method', models.CharField(blank=True, max_length=50, verbose_name='أفضل طريقة')),
                ('worst_method', models.CharField(blank=True, max_length=50, verbose_name='أسوأ طريقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_metrics', to='sales_forecasting.forecastperiod', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'مقاييس دقة التنبؤ',
                'verbose_name_plural': 'مقاييس دقة التنبؤ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المتوقعة')),
                ('forecasted_revenue', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإيراد المتوقع')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مستوى الثقة %')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الكمية الفعلية')),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الإيراد الفعلي')),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='انحراف الكمية')),
                ('variance_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='انحراف الإيراد')),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الدقة %')),
                ('method', models.CharField(choices=[('moving_average', 'المتوسط المتحرك'), ('exponential_smoothing', 'التمهيد الأسي'), ('linear_regression', 'الانحدار الخطي'), ('seasonal', 'التحليل الموسمي'), ('ai_ml', 'الذكاء الاصطناعي'), ('manual', 'يدوي')], default='moving_average', max_length=50, verbose_name='طريقة التنبؤ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('historical_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات التاريخية')),
                ('seasonality_factors', models.JSONField(blank=True, default=dict, verbose_name='عوامل الموسمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_forecasts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecasts', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='sales_forecasting.forecastperiod', verbose_name='الفترة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تنبؤ بالمبيعات',
                'verbose_name_plural': 'التنبؤات بالمبيعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('stock_up', 'زيادة المخزون'), ('reduce_stock', 'تقليل المخزون'), ('maintain', 'الحفاظ على المستوى الحالي'), ('urgent_order', 'طلب عاجل'), ('slow_moving', 'بطيء الحركة - تقليل المخزون')], max_length=30, verbose_name='نوع التوصية')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], max_length=20, verbose_name='الأولوية')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المخزون الحالي')),
                ('current_reorder_point', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='نقطة إعادة الطلب الحالية')),
                ('recommended_stock_level', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مستوى المخزون الموصى به')),
                ('recommended_order_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='كمية الطلب الموصى بها')),
                ('estimated_stockout_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نفاذ المخزون المتوقع')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('implemented', 'تم التنفيذ')], default='pending', max_length=20, verbose_name='الحالة')),
                ('action_taken', models.TextField(blank=True, verbose_name='الإجراء المتخذ')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
                ('demand_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_forecasting.demandpattern', verbose_name='نمط الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_recommendations', to='inventory.product', verbose_name='المنتج')),
                ('forecast_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_forecasting.salesforecast', verbose_name='بيانات التنبؤ')),
            ],
            options={
                'verbose_name': 'توصية مخزون',
                'verbose_name_plural': 'توصيات المخزون',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandpattern',
            index=models.Index(fields=['product', 'is_active'], name='sales_forec_product_eb1680_idx'),
        ),
        migrations.AddIndex(
            model_name='demandpattern',
            index=models.Index(fields=['pattern_type'], name='sales_forec_pattern_177f00_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['period_type', 'start_date'], name='sales_forec_period__149698_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastperiod',
            index=models.Index(fields=['is_active'], name='sales_forec_is_acti_7d1cdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastaccuracymetrics',
            unique_together={('period', 'product')},
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['period', 'product'], name='sales_forec_period__72134b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['status'], name='sales_forec_status_7160b7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['method'], name='sales_forec_method_6ab319_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together={('period', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventoryrecommendation',
            index=models.Index(fields=['product', 'status'], name='sales_forec_product_169150_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecommendation',
            index=models.Index(fields=['priority', 'status'], name='sales_forec_priorit_df0db4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecommendation',
            index=models.Index(fields=['recommendation_type'], name='sales_forec_recomme_1e4499_idx'),
        ),
    ]
