# Generated by Django 5.2.11 on 2026-03-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('failed_login', 'محاولة دخول فاشلة'), ('permission_denied', 'رفض صلاحية'), ('price_change', 'تعديل سعر'), ('discount', 'خصم')], max_length=30, verbose_name='الإجراء')),
                ('module', models.CharField(max_length=100, verbose_name='القسم')),
                ('model_name', models.CharField(max_length=100, verbose_name='الجدول')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='رقم السجل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='القيمة القديمة')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='القيمة الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('level', models.CharField(choices=[('owner', 'إدارة عليا'), ('ceo', 'مدير عام'), ('cfo', 'مدير مالي'), ('account_manager', 'مدير حسابات'), ('accountant', 'محاسب'), ('branch_manager', 'مدير فرع'), ('salesperson', 'بائع'), ('cashier', 'كاشير'), ('storekeeper', 'أمين مخزن'), ('production_manager', 'مدير إنتاج'), ('production_supervisor', 'مشرف خط إنتاج'), ('custom', 'مخصص')], max_length=30, verbose_name='المستوى')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أقصى نسبة خصم %')),
                ('can_see_cost', models.BooleanField(default=False, verbose_name='يرى التكلفة')),
                ('can_see_profit', models.BooleanField(default=False, verbose_name='يرى الأرباح')),
                ('can_see_other_branches', models.BooleanField(default=False, verbose_name='يرى فروع أخرى')),
                ('can_delete', models.BooleanField(default=False, verbose_name='يستطيع الحذف')),
                ('can_modify_prices', models.BooleanField(default=False, verbose_name='يعدّل الأسعار')),
                ('can_approve_entries', models.BooleanField(default=False, verbose_name='يعتمد القيود')),
                ('can_create_users', models.BooleanField(default=False, verbose_name='ينشئ مستخدمين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'دور وظيفي',
                'verbose_name_plural': 'الأدوار الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('start_date', models.DateTimeField(verbose_name='بداية التفويض')),
                ('end_date', models.DateTimeField(verbose_name='نهاية التفويض')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='المفوَّض إليه')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='المفوِّض')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.role', verbose_name='الدور المفوَّض')),
            ],
            options={
                'verbose_name': 'تفويض',
                'verbose_name_plural': 'التفويضات',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('module', models.CharField(choices=[('accounts', 'المحاسبة'), ('inventory', 'المخزون'), ('production', 'الإنتاج'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('hr', 'الموارد البشرية'), ('reports', 'التقارير'), ('settings', 'الإعدادات')], max_length=20, verbose_name='القسم')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('create', 'إنشاء'), ('edit', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('export', 'تصدير')], max_length=20, verbose_name='الإجراء')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='مسموح')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authorization.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'unique_together': {('role', 'module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('is_primary', models.BooleanField(default=False, verbose_name='دور أساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='authorization.role', verbose_name='الدور')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور المستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
