# Generated by Django 5.2.11 on 2026-03-02 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('core', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_url', models.CharField(max_length=500, verbose_name='الـ URL')),
                ('attempted_module', models.CharField(max_length=50, verbose_name='القسم')),
                ('attempted_action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محاولة وصول غير مصرح',
                'verbose_name_plural': 'سجل الأمان',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='كود الصلاحية')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصلاحية')),
                ('module', models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('accounts', 'المحاسبة'), ('inventory', 'المخزون'), ('production', 'الإنتاج'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('hr', 'الموارد البشرية'), ('treasury', 'الخزينة والبنوك'), ('expenses', 'المصروفات'), ('crm', 'إدارة العملاء'), ('quotations', 'عروض الأسعار'), ('delivery', 'التوصيل'), ('warranty', 'الضمان'), ('reports', 'التقارير'), ('notifications', 'الإشعارات'), ('authorization', 'الصلاحيات'), ('settings', 'الإعدادات')], max_length=50, verbose_name='القسم')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('create', 'إنشاء'), ('edit', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('cancel', 'إلغاء'), ('post', 'ترحيل'), ('close', 'إقفال'), ('export', 'تصدير'), ('print', 'طباعة'), ('receive', 'استلام'), ('issue', 'صرف'), ('transfer', 'تحويل'), ('adjust', 'تسوية'), ('count', 'جرد'), ('start', 'بدء'), ('complete', 'إكمال'), ('collect', 'تحصيل'), ('pay', 'دفع'), ('payroll', 'رواتب'), ('update_progress', 'تحديث تقدم'), ('report_waste', 'تسجيل هالك'), ('quality_check', 'فحص جودة'), ('view_cost', 'رؤية التكلفة'), ('view_profit', 'رؤية الربح'), ('give_discount', 'منح خصم'), ('view_other_branches', 'رؤية فروع أخرى'), ('manage_users', 'إدارة المستخدمين'), ('audit_log', 'سجل المراجعة')], max_length=50, verbose_name='الإجراء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_sensitive', models.BooleanField(default=False, help_text='الصلاحيات الحساسة تحتاج اعتماد خاص', verbose_name='حساسة')),
            ],
            options={
                'verbose_name': 'صلاحية نظامية',
                'verbose_name_plural': 'الصلاحيات النظامية',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الدور')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('scope', models.CharField(choices=[('all', 'كل الفروع'), ('branch', 'فرعه فقط'), ('warehouse', 'مخزنه فقط'), ('production_line', 'خط إنتاجه فقط'), ('assigned', 'المسند إليه فقط')], default='branch', max_length=20, verbose_name='النطاق')),
                ('invoice_approval_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سقف اعتماد الفواتير')),
                ('expense_approval_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سقف اعتماد المصروفات')),
                ('return_approval_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سقف اعتماد المرتجعات')),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أقصى خصم %')),
                ('is_system', models.BooleanField(default=False, verbose_name='دور نظامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('can_be_granted_by', models.ManyToManyField(blank=True, related_name='can_grant', to='authorization.systemrole', verbose_name='يُمنح بواسطة')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authorization.systempermission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور نظامي',
                'verbose_name_plural': 'الأدوار النظامية',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='عيّنه')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionline', verbose_name='خط الإنتاج')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorization.systemrole', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'تعيين دور',
                'verbose_name_plural': 'تعيينات الأدوار',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
