# Generated by Django 5.2.11 on 2026-03-02 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_securityviolationlog_systempermission_systemrole_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('request_type', models.CharField(choices=[('invoice', 'فاتورة'), ('return', 'مرتجع'), ('expense', 'مصروف'), ('purchase', 'أمر شراء'), ('stock_adjustment', 'تسوية مخزون'), ('discount', 'خصم تجاوز الحد'), ('production', 'أمر إنتاج'), ('payroll', 'مسيّر رواتب')], max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('source_model', models.CharField(max_length=100, verbose_name='المصدر')),
                ('source_id', models.IntegerField(verbose_name='رقم المصدر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدِّل بواسطة')),
            ],
            options={
                'verbose_name': 'طلب اعتماد',
                'verbose_name_plural': 'طلبات الاعتماد',
                'ordering': ['-created_at'],
            },
        ),
    ]
