# Generated by Django 5.2.11 on 2026-03-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_sprint23_approval_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='المتصفح'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('failed_login', 'محاولة دخول فاشلة'), ('permission_denied', 'رفض صلاحية'), ('price_change', 'تعديل سعر'), ('discount', 'خصم')], db_index=True, max_length=30, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الجدول'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, max_length=100, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم السجل'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت'),
        ),
    ]
