# Generated by Django 5.2.5 on 2025-12-30 13:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_face_recognition', models.BooleanField(default=True, verbose_name='تفعيل التعرف على الوجه')),
                ('face_recognition_threshold', models.FloatField(default=0.6, help_text='الحد الأدنى للتطابق (0-1)', verbose_name='حد دقة التعرف')),
                ('enable_gps_validation', models.BooleanField(default=True, verbose_name='تفعيل التحقق من GPS')),
                ('enable_wifi_validation', models.BooleanField(default=True, verbose_name='تفعيل التحقق من WiFi')),
                ('enable_ip_validation', models.BooleanField(default=False, verbose_name='تفعيل التحقق من IP')),
                ('allow_manual_checkin', models.BooleanField(default=True, verbose_name='السماح بالتسجيل اليدوي')),
                ('manual_checkin_requires_approval', models.BooleanField(default=True, verbose_name='التسجيل اليدوي يحتاج موافقة')),
                ('require_photo_on_checkin', models.BooleanField(default=True, verbose_name='صورة إلزامية عند الحضور')),
                ('require_photo_on_checkout', models.BooleanField(default=False, verbose_name='صورة إلزامية عند الانصراف')),
                ('send_late_notifications', models.BooleanField(default=True, verbose_name='إرسال إشعارات التأخير')),
                ('send_absent_notifications', models.BooleanField(default=True, verbose_name='إرسال إشعارات الغياب')),
                ('default_work_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4, verbose_name='ساعات العمل الافتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'إعدادات الحضور',
                'verbose_name_plural': 'إعدادات الحضور',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الموقع')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('radius_meters', models.IntegerField(default=100, help_text='المسافة المسموح بها من الموقع', verbose_name='نطاق القبول (متر)')),
                ('allowed_wifi_networks', models.JSONField(blank=True, default=list, help_text='قائمة بأسماء شبكات WiFi (SSID) المسموح بها', verbose_name='شبكات WiFi المسموح بها')),
                ('allowed_ip_addresses', models.JSONField(blank=True, default=list, verbose_name='عناوين IP المسموح بها')),
                ('work_start_time', models.TimeField(default='08:00', verbose_name='وقت بداية العمل')),
                ('work_end_time', models.TimeField(default='17:00', verbose_name='وقت نهاية العمل')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='المدة المسموح بها للتأخير بدون عقوبة', verbose_name='فترة السماح (دقائق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موقع العمل',
                'verbose_name_plural': 'مواقع العمل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('missing', 'تسجيل حضور فائت'), ('correction', 'تصحيح وقت'), ('excuse', 'عذر'), ('leave', 'طلب إجازة')], max_length=20, verbose_name='نوع الطلب')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('requested_check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور المطلوب')),
                ('requested_check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف المطلوب')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attendance/requests/', verbose_name='مرفق')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'طلب تعديل حضور',
                'verbose_name_plural': 'طلبات تعديل الحضور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.BinaryField(blank=True, null=True, verbose_name='بيانات البصمة')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_data/', verbose_name='صورة الوجه')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('accuracy_score', models.FloatField(default=0.0, help_text='نسبة دقة التعرف على الوجه', verbose_name='دقة التعرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بيانات بصمة الوجه',
                'verbose_name_plural': 'بيانات بصمات الوجه',
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('report_type', models.CharField(choices=[('daily', 'تقرير يومي'), ('weekly', 'تقرير أسبوعي'), ('monthly', 'تقرير شهري'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات التقرير')),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='attendance/reports/', verbose_name='ملف التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('users', models.ManyToManyField(blank=True, related_name='attendance_reports', to=settings.AUTH_USER_MODEL, verbose_name='الموظفون')),
                ('locations', models.ManyToManyField(blank=True, related_name='attendance_reports', to='attendance.worklocation', verbose_name='المواقع')),
            ],
            options={
                'verbose_name': 'تقرير حضور',
                'verbose_name_plural': 'تقارير الحضور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('check_in_method', models.CharField(blank=True, choices=[('manual', 'تسجيل يدوي'), ('face', 'بصمة الوجه'), ('gps', 'موقع GPS'), ('wifi', 'شبكة WiFi'), ('qr', 'كود QR'), ('mobile', 'تطبيق الموبايل')], max_length=20, null=True, verbose_name='طريقة تسجيل الحضور')),
                ('check_out_method', models.CharField(blank=True, choices=[('manual', 'تسجيل يدوي'), ('face', 'بصمة الوجه'), ('gps', 'موقع GPS'), ('wifi', 'شبكة WiFi'), ('qr', 'كود QR'), ('mobile', 'تطبيق الموبايل')], max_length=20, null=True, verbose_name='طريقة تسجيل الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('leave', 'إجازة'), ('holiday', 'عطلة')], default='present', max_length=20, verbose_name='الحالة')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط عرض الحضور')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط طول الحضور')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط عرض الانصراف')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط طول الانصراف')),
                ('check_in_wifi_ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='شبكة WiFi عند الحضور')),
                ('check_out_wifi_ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='شبكة WiFi عند الانصراف')),
                ('check_in_device_info', models.JSONField(blank=True, default=dict, verbose_name='معلومات جهاز الحضور')),
                ('check_out_device_info', models.JSONField(blank=True, default=dict, verbose_name='معلومات جهاز الانصراف')),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance/checkin/', verbose_name='صورة الحضور')),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance/checkout/', verbose_name='صورة الانصراف')),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الحضور')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الانصراف')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='إجمالي الساعات')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات إضافية')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.worklocation', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_f0d554_idx'), models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'), models.Index(fields=['location', 'date'], name='attendance__locatio_d0e086_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
