# Generated by Django 5.2.5 on 2025-12-24 04:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0010_jobposition_salary_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الباقة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الباقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('includes', models.TextField(blank=True, help_text='ما تشمله الباقة', verbose_name='تشمل')),
                ('excludes', models.TextField(blank=True, help_text='ما لا تشمله الباقة', verbose_name='لا تشمل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الخصم')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5, verbose_name='المدة (ساعات)')),
                ('workers_count', models.PositiveIntegerField(default=1, verbose_name='عدد العمال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'باقة نظافة',
                'verbose_name_plural': 'باقات النظافة',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeServicesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_maintenance', models.BooleanField(default=True, verbose_name='تفعيل خدمة الصيانة')),
                ('enable_cleaning', models.BooleanField(default=True, verbose_name='تفعيل خدمة النظافة')),
                ('working_hours_start', models.TimeField(default='08:00', verbose_name='بداية العمل')),
                ('working_hours_end', models.TimeField(default='22:00', verbose_name='نهاية العمل')),
                ('emergency_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5, verbose_name='نسبة رسوم الطوارئ %')),
                ('urgent_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=5, verbose_name='نسبة رسوم العاجل %')),
                ('min_booking_hours_advance', models.PositiveIntegerField(default=2, verbose_name='الحد الأدنى للحجز (ساعات مسبقة)')),
                ('max_booking_days_advance', models.PositiveIntegerField(default=30, verbose_name='الحد الأقصى للحجز (أيام مسبقة)')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('confirmation_message', models.TextField(blank=True, default='شكراً لك! تم استلام طلبك وسيتم التواصل معك قريباً.', verbose_name='رسالة التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الخدمات المنزلية',
                'verbose_name_plural': 'إعدادات الخدمات المنزلية',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-wrench', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'فئة صيانة',
                'verbose_name_plural': 'فئات الصيانة',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنطقة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('extra_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='رسوم إضافية')),
            ],
            options={
                'verbose_name': 'منطقة خدمة',
                'verbose_name_plural': 'مناطق الخدمة',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الخدمة')),
                ('category', models.CharField(choices=[('maintenance', 'صيانة'), ('cleaning', 'نظافة'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-tools', max_length=50, verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_services/types/', verbose_name='الصورة')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السعر الأساسي')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السعر بالساعة')),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الحد الأدنى للسعر')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='المدة التقديرية (ساعات)')),
                ('requires_inspection', models.BooleanField(default=False, verbose_name='يتطلب معاينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع خدمة',
                'verbose_name_plural': 'أنواع الخدمات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('request_type', models.CharField(choices=[('maintenance', 'طلب صيانة'), ('cleaning', 'طلب نظافة')], max_length=20, verbose_name='نوع الطلب')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('building_type', models.CharField(blank=True, help_text='شقة، فيلا، مكتب، إلخ', max_length=100, verbose_name='نوع المبنى')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='وصف تفصيلي')),
                ('preferred_date', models.DateField(verbose_name='التاريخ المفضل')),
                ('preferred_time_from', models.TimeField(blank=True, null=True, verbose_name='من الساعة')),
                ('preferred_time_to', models.TimeField(blank=True, null=True, verbose_name='إلى الساعة')),
                ('urgency', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('emergency', 'طوارئ')], default='normal', max_length=20, verbose_name='درجة الاستعجال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('assigned', 'تم التعيين'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوع'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر التقديري')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر النهائي')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الخصم')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنتهاء')),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المدة الفعلية (ساعات)')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('worker_notes', models.TextField(blank=True, verbose_name='ملاحظات الفني')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='التقييم')),
                ('review', models.TextField(blank=True, verbose_name='ملاحظات التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='hr.employee', verbose_name='الفني المعين')),
                ('cleaning_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_services.cleaningpackage', verbose_name='باقة النظافة')),
                ('maintenance_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_services.maintenancecategory', verbose_name='فئة الصيانة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='home_services.servicetype', verbose_name='نوع الخدمة')),
            ],
            options={
                'verbose_name': 'طلب خدمة',
                'verbose_name_plural': 'طلبات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_services/requests/', verbose_name='الصورة')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home_services.servicerequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'صورة الطلب',
                'verbose_name_plural': 'صور الطلب',
            },
        ),
        migrations.CreateModel(
            name='ServiceWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='متوسط التقييم')),
                ('total_jobs', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأعمال')),
                ('completed_jobs', models.PositiveIntegerField(default=0, verbose_name='الأعمال المكتملة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_worker_profile', to='hr.employee', verbose_name='الموظف')),
                ('maintenance_categories', models.ManyToManyField(blank=True, related_name='workers', to='home_services.maintenancecategory', verbose_name='فئات الصيانة')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='workers', to='home_services.servicearea', verbose_name='مناطق الخدمة')),
                ('specializations', models.ManyToManyField(blank=True, related_name='workers', to='home_services.servicetype', verbose_name='التخصصات')),
            ],
            options={
                'verbose_name': 'فني خدمة',
                'verbose_name_plural': 'فنيو الخدمة',
            },
        ),
    ]
