# Generated by Django 5.2.5 on 2025-12-27 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservicessettings',
            name='working_hours_end',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='نهاية العمل'),
        ),
        migrations.AlterField(
            model_name='homeservicessettings',
            name='working_hours_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='بداية العمل'),
        ),
    ]
