# Generated by Django 5.2.9 on 2026-01-05 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(verbose_name='تاريخ التنبؤ')),
                ('period_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=20, verbose_name='نوع الفترة')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('inflows', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='التدفقات الداخلة')),
                ('outflows', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='التدفقات الخارجة')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الختامي')),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الدقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تنبؤ التدفق النقدي',
                'verbose_name_plural': 'تنبؤات التدفق النقدي',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='CashPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الموقف')),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رصيد البنك')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='النقد في الصندوق')),
                ('short_term_investments', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='استثمارات قصيرة الأجل')),
                ('short_term_liabilities', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='التزامات قصيرة الأجل')),
                ('total_liquidity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي السيولة')),
                ('net_position', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الموقف الصافي')),
                ('liquidity_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة السيولة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موقف السيولة',
                'verbose_name_plural': 'مواقف السيولة',
                'ordering': ['-position_date'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الهدف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('target_liquidity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هدف السيولة')),
                ('target_debt_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='هدف نسبة الدين')),
                ('target_roi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='هدف العائد')),
                ('actual_liquidity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='السيولة الفعلية')),
                ('actual_debt_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الدين الفعلية')),
                ('actual_roi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='العائد الفعلي')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد الإنجاز'), ('achieved', 'تحقق'), ('failed', 'فشل')], max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'هدف الشؤون المالية',
                'verbose_name_plural': 'أهداف الشؤون المالية',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الاستثمار')),
                ('investment_type', models.CharField(choices=[('stocks', 'الأسهم'), ('bonds', 'السندات'), ('funds', 'الصناديق'), ('real_estate', 'العقارات'), ('deposits', 'الودائع'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الاستثمار')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الأساسي')),
                ('investment_date', models.DateField(verbose_name='تاريخ الاستثمار')),
                ('maturity_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('expected_return_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='معدل العائد المتوقع')),
                ('expected_return_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ العائد المتوقع')),
                ('actual_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ العائد الفعلي')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('matured', 'استحقت'), ('liquidated', 'مصفاة'), ('on_hold', 'معلقة')], default='active', max_length=20, verbose_name='الحالة')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة الحالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'استثمار',
                'verbose_name_plural': 'الاستثمارات',
                'ordering': ['-investment_date'],
                'indexes': [models.Index(fields=['status'], name='treasury_ma_status_dd31fe_idx'), models.Index(fields=['maturity_date'], name='treasury_ma_maturit_af0615_idx')],
            },
        ),
    ]
