# Generated by Django 5.2.5 on 2025-08-14 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hseinspection_weekendday_complaint_and_more'),
        ('partners', '0002_partner'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المستحق')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('done', 'منجزة')], default='open', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='مسؤول المتابعة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='sales.invoice', verbose_name='فاتورة')),
            ],
            options={
                'verbose_name': 'مهمة تحصيل',
                'verbose_name_plural': 'مهام التحصيل',
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الزيارة')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('outcome', models.CharField(choices=[('won', 'إغلاق ناجح'), ('lost', 'لم يكتمل'), ('follow_up', 'متابعة مطلوبة'), ('demo', 'عرض توضيحي')], default='follow_up', max_length=20, verbose_name='النتيجة')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.customer', verbose_name='العميل')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='المندوب')),
            ],
            options={
                'verbose_name': 'زيارة ميدانية',
                'verbose_name_plural': 'زيارات ميدانية',
                'ordering': ['-visit_date', '-id'],
            },
        ),
    ]
