# Generated by Django 5.2.5 on 2025-08-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hseinspection_weekendday_complaint_and_more'),
        ('partners', '0004_customer_customer_key_idx'),
        ('sales', '0003_invoice_payment_method_invoice_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectiontask',
            index=models.Index(fields=['status'], name='collection_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontask',
            index=models.Index(fields=['due_date'], name='collection_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['visit_date'], name='fieldvisit_visit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['outcome'], name='fieldvisit_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['date'], name='salesreturn_date_idx'),
        ),
    ]
