# Generated by Django 5.2.5 on 2025-08-17 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_print_customerstatement_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': [('print_customerstatement', 'طباعة كشف حساب عميل')]},
        ),
        migrations.AlterModelOptions(
            name='invoicepayment',
            options={'ordering': ['-date', '-id'], 'permissions': [('lock_invoicepayment', 'قفل دفعة فاتورة'), ('print_invoicepayment', 'طباعة إيصال دفعة فاتورة')], 'verbose_name': 'دفعة فاتورة', 'verbose_name_plural': 'دفعات الفواتير'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='سبب الحذف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_invoices', to=settings.AUTH_USER_MODEL, verbose_name='محذوف بواسطة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
    ]
