# Generated by Django 5.2.5 on 2025-08-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingsettings_ar_account'),
        ('sales', '0013_invoice_tax_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
    ]
