# Generated by Django 5.2.5 on 2025-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoicepayment_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.CharField(blank=True, max_length=120, verbose_name='رقم / IBAN الحساب (للحوالة)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم البنك (للحوالة)'),
        ),
    ]
