# Generated by Django 5.2.5 on 2025-09-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_invoicepayment_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.invoice', verbose_name='الفاتورة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.invoicepayment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة',
                'verbose_name_plural': 'تخصيصات الدفعات',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['invoice'], name='alloc_invoice_idx'), models.Index(fields=['payment'], name='alloc_payment_idx')],
            },
        ),
    ]
