# Generated by Django 5.2.5 on 2025-09-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_invoicepaymentallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='تكون صحيحة إذا لم ترتبط الدفعة بفاتورة عند الترحيل', verbose_name='دفعة مقدمة'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_invoice_payments', to=settings.AUTH_USER_MODEL, verbose_name='رحّل بواسطة'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحلة'), ('cancelled', 'ملغاة')], default='draft', max_length=12, verbose_name='الحالة'),
        ),
    ]
