# Generated by Django 5.2.5 on 2025-09-16 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_accountingsettings_customer_advances_account'),
        ('sales', '0019_invoicepayment_is_advance_invoicepayment_posted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicepayment',
            options={'ordering': ['-date', '-id'], 'permissions': [('lock_invoicepayment', 'قفل دفعة فاتورة'), ('print_invoicepayment', 'طباعة إيصال دفعة فاتورة'), ('cancel_invoicepayment', 'إلغاء دفعة فاتورة')], 'verbose_name': 'دفعة فاتورة', 'verbose_name_plural': 'دفعات الفواتير'},
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='reverse_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_invoice_payments', to='accounting.journalentry', verbose_name='قيد الإلغاء'),
        ),
    ]
