# Generated by Django 5.2.5 on 2025-12-09 00:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printerconfiguration_and_more'),
        ('partners', '0008_alter_customer_id_alter_partner_id_alter_supplier_id'),
        ('production', '0004_workerproductionentry'),
        ('sales', '0021_alter_collectiontask_id_alter_fieldvisit_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الأمر')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('in_production', 'قيد التصنيع'), ('ready', 'جاهز للتسليم'), ('partially_delivered', 'تسليم جزئي'), ('delivered', 'تم التسليم'), ('invoiced', 'تم إصدار الفاتورة'), ('cancelled', 'ملغى')], default='draft', max_length=25, verbose_name='الحالة')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الخصم')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('delivery_address', models.TextField(blank=True, verbose_name='عنوان التسليم')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='ملاحظات التسليم')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='شروط الدفع')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الدفعة المقدمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='أكده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order', to='sales.invoice', verbose_name='الفاتورة')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='production.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'أمر بيع',
                'verbose_name_plural': 'أوامر البيع',
                'ordering': ['-date', '-id'],
                'permissions': [('can_confirm_sales_order', 'يمكنه تأكيد أمر البيع'), ('can_convert_to_invoice', 'يمكنه تحويل أمر البيع لفاتورة')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المحجوزة')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المُسلمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='الموقع/المستودع')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='أمر البيع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند أمر بيع',
                'verbose_name_plural': 'بنود أوامر البيع',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-date'], name='sales_sales_date_c0240d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_sales_status_480214_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_sales_custome_b24b56_idx'),
        ),
    ]
