# Generated by Django 5.2.5 on 2025-12-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_salesorder_salesorderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvisit',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='دقة الموقع (متر)'),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
    ]
