# Generated by Django 5.2.5 on 2025-12-15 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_supplierdocument'),
        ('payments', '0007_alter_paymenttransaction_installment'),
        ('sales', '0023_add_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'date'], name='invoice_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_deleted', 'date'], name='invoice_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_due_date_idx'),
        ),
    ]
