# Generated by Django 5.2.5 on 2025-12-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Order',
                'verbose_name_plural': 'Sale Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.invoice',),
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Order Item',
                'verbose_name_plural': 'Sale Order Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.invoiceitem',),
        ),
    ]
