# Generated by Django 5.2.5 on 2025-12-29 02:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_journalentry_created_by'),
        ('partners', '0011_product_unit_warranty'),
        ('sales', '0026_add_showroom_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscountNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الإشعار المدين')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الخصم')),
                ('is_percentage', models.BooleanField(default=False, help_text='إذا كان نعم، سيتم احتساب النسبة من الفاتورة المرتبطة', verbose_name='نسبة مئوية')),
                ('percentage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='النسبة من 0 إلى 100', max_digits=5, verbose_name='النسبة المئوية')),
                ('reason', models.CharField(choices=[('loyalty', 'خصم وفاء عميل'), ('trade', 'خصم تجاري خاص'), ('delay_compensation', 'تعويض تأخير'), ('early_payment', 'خصم سداد مبكر'), ('other', 'سبب آخر')], default='loyalty', max_length=30, verbose_name='سبب الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_customer_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_notes', to='partners.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_notes', to='sales.invoice', verbose_name='الفاتورة المرتبطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_discount_notes', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_customer_discount_notes', to=settings.AUTH_USER_MODEL, verbose_name='رحّله')),
            ],
            options={
                'verbose_name': 'إشعار خصم مسموح به',
                'verbose_name_plural': 'إشعارات الخصم المسموح بها',
                'ordering': ['-date', '-id'],
                'permissions': [('can_post_customer_discount', 'يمكنه ترحيل إشعار خصم العميل'), ('can_cancel_customer_discount', 'يمكنه إلغاء إشعار خصم العميل')],
                'indexes': [models.Index(fields=['-date'], name='sales_custo_date_42d1b5_idx'), models.Index(fields=['customer', '-date'], name='sales_custo_custome_083bc7_idx'), models.Index(fields=['status'], name='sales_custo_status_d4b7ff_idx')],
            },
        ),
    ]
