# Generated by Django 5.2.9 on 2026-01-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_customerdiscountnote'),
        ('sales', '0027_invoice_enhanced_features'),
    ]

    operations = [
    ]
