# Generated by Django 5.2.9 on 2026-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_merge_20260109_0205'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoiceautosave',
            new_name='sales_invoi_user_id_eabaf0_idx',
            old_name='sales_invoi_user_up_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceautosave',
            new_name='sales_invoi_expires_2aca56_idx',
            old_name='sales_invoi_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicehistory',
            new_name='sales_invoi_invoice_4d46ea_idx',
            old_name='sales_invoi_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicehistory',
            new_name='sales_invoi_user_id_c2ee11_idx',
            old_name='sales_invoi_user_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicetemplate',
            new_name='sales_invoi_custome_0ae9ea_idx',
            old_name='sales_invoi_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicetemplate',
            new_name='sales_invoi_created_b18841_idx',
            old_name='sales_invoi_created_idx',
        ),
        migrations.AlterField(
            model_name='customercreditlimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoiceautosave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
