# Generated by Django 5.2.9 on 2026-01-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_advanced_features_final'),
        ('sales', '0029_advanced_accounting_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='مرحّل محاسبياً'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
    ]
