# Generated by Django 5.2.9 on 2026-02-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_invoice_approved_at_invoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
