# Generated by Django 5.2.9 on 2026-02-14 05:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_invoicepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enable_extra_discount',
            field=models.BooleanField(default=False, verbose_name='تفعيل خصم إضافي'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enable_previous_balance',
            field=models.BooleanField(default=False, verbose_name='تفعيل رصيد سابق'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enable_shipping',
            field=models.BooleanField(default=False, verbose_name='تفعيل الشحن'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extra_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الخصم الإضافي'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_tax_invoice',
            field=models.BooleanField(default=False, verbose_name='فاتورة ضريبية'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد السابق'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='تكلفة الشحن'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
    ]
