# Generated by Django 5.2.9 on 2026-02-23 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_add_invoice_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الزيارة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الأمر'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
