# Generated by Django 5.2.11 on 2026-03-01 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('danger', 'خطر'), ('success', 'نجاح')], default='info', max_length=20, verbose_name='النوع')),
                ('category', models.CharField(choices=[('stock_low', 'مخزون منخفض'), ('stock_out', 'نفاد مخزون'), ('invoice_overdue', 'فاتورة متأخرة'), ('installment_due', 'قسط مستحق'), ('installment_overdue', 'قسط متأخر'), ('contract_expiring', 'عقد قارب على الانتهاء'), ('contract_expired', 'عقد منتهي'), ('quotation_expiring', 'عرض سعر قارب على الانتهاء'), ('quotation_follow_up', 'متابعة عرض سعر'), ('production_delayed', 'أمر إنتاج متأخر'), ('production_completed', 'أمر إنتاج مكتمل'), ('leave_request', 'طلب إجازة'), ('advance_request', 'طلب سلفة'), ('expense_pending', 'مصروف في انتظار الاعتماد'), ('check_due', 'شيك مستحق'), ('check_bounced', 'شيك مرتجع'), ('payroll_ready', 'مسيّر رواتب جاهز'), ('budget_exceeded', 'تجاوز ميزانية'), ('general', 'عام')], default='general', max_length=30, verbose_name='الفئة')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('source_model', models.CharField(blank=True, max_length=100, verbose_name='المصدر')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='رقم المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_alerts', models.BooleanField(default=True, verbose_name='تنبيهات المخزون')),
                ('invoice_alerts', models.BooleanField(default=True, verbose_name='تنبيهات الفواتير')),
                ('production_alerts', models.BooleanField(default=True, verbose_name='تنبيهات الإنتاج')),
                ('hr_alerts', models.BooleanField(default=True, verbose_name='تنبيهات الموارد البشرية')),
                ('financial_alerts', models.BooleanField(default=True, verbose_name='تنبيهات مالية')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='إشعارات بالإيميل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات إشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
    ]
