# Generated by Django 5.2.9 on 2026-01-05 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('customer_segmentation', 'تقسيم العملاء'), ('churn_risk', 'خطر فقدان العميل'), ('next_best_action', 'أفضل إجراء تالي'), ('lifetime_value', 'القيمة مدى الحياة'), ('anomaly', 'كشف الشذوذ')], max_length=50, verbose_name='نوع التحليل')),
                ('entity_type', models.CharField(max_length=100, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(max_length=100, verbose_name='رقم الكيان')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('segment', models.CharField(blank=True, max_length=100, verbose_name='القطاع')),
                ('recommendation', models.TextField(verbose_name='التوصية')),
                ('patterns', models.JSONField(default=dict, verbose_name='الأنماط')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التحليل')),
            ],
            options={
                'verbose_name': 'تحليل تنبؤي',
                'verbose_name_plural': 'التحليلات التنبؤية',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('layout', models.CharField(choices=[('grid', 'شبكة'), ('flex', 'مرن'), ('custom', 'مخصص')], max_length=50, verbose_name='التخطيط')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'غامق'), ('auto', 'تلقائي')], max_length=50, verbose_name='المظهر')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='تحديث تلقائي')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='فترة التحديث (ثوان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لوحة معلومات',
                'verbose_name_plural': 'لوحات المعلومات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_type', models.CharField(choices=[('revenue', 'الإيرادات'), ('demand', 'الطلب'), ('churn', 'معدل الفقدان'), ('inventory', 'المخزون'), ('customer_value', 'قيمة العميل')], max_length=50, verbose_name='نوع التنبؤ')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة المتنبأ بها')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مستوى الثقة %')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الحد الأدنى')),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الحد الأقصى')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='القيمة الفعلية')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدقة %')),
                ('model_used', models.CharField(max_length=100, verbose_name='النموذج المستخدم')),
                ('training_data_points', models.IntegerField(verbose_name='نقاط البيانات المستخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تنبؤ',
                'verbose_name_plural': 'التنبؤات',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['forecast_type'], name='business_in_forecas_6ab7d2_idx'), models.Index(fields=['period_end'], name='business_in_period__c3a56f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('report_type', models.CharField(choices=[('sales', 'المبيعات'), ('financial', 'مالي'), ('operational', 'تشغيلي'), ('customer', 'العملاء'), ('inventory', 'المخزون'), ('custom', 'مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('annual', 'سنوي'), ('on_demand', 'عند الطلب')], max_length=20, verbose_name='التكرار')),
                ('schedule', models.CharField(blank=True, help_text='مثل: 0 9 * * 1 (كل يوم اثنين الساعة 9 صباحاً)', max_length=100, verbose_name='الجدولة')),
                ('recipient_emails', models.TextField(blank=True, verbose_name='عناوين بريد إضافية')),
                ('last_report_file', models.FileField(blank=True, upload_to='reports/', verbose_name='آخر تقرير')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='آخر توليد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recipients', models.ManyToManyField(blank=True, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('widget_type', models.CharField(choices=[('kpi', 'مؤشر أداء رئيسي'), ('chart', 'رسم بياني'), ('table', 'جدول'), ('gauge', 'مقياس'), ('map', 'خريطة'), ('timeline', 'خط زمني'), ('heatmap', 'خريطة حرارية'), ('custom', 'مخصص')], max_length=50, verbose_name='نوع الأداة')),
                ('data_source', models.CharField(max_length=200, verbose_name='مصدر البيانات')),
                ('query', models.TextField(blank=True, verbose_name='الاستعلام')),
                ('position_x', models.IntegerField(verbose_name='موقع X')),
                ('position_y', models.IntegerField(verbose_name='موقع Y')),
                ('width', models.IntegerField(verbose_name='العرض')),
                ('height', models.IntegerField(verbose_name='الارتفاع')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('refresh_interval', models.IntegerField(blank=True, null=True, verbose_name='فترة التحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='business_intelligence.dashboard')),
            ],
            options={
                'verbose_name': 'أداة',
                'verbose_name_plural': 'الأدوات',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
